begin;
select plan(15);
select has_column('public','meeting_sessions','duration_seconds','session history stores duration');
select has_column('public','meeting_sessions','outcome_code','session history stores safe outcome');
select has_column('public','meeting_sessions','outcome_source','session history stores verified source');
select has_column('public','meeting_sessions','outcome_verified_at','session history stores verification time');
select has_function('public','get_meeting_history',array['uuid','text','integer'],'history RPC exists');
select has_function('public','get_meeting_attendance_history',array['uuid'],'attendance RPC exists');
select has_trigger('public','meeting_events','meeting_history_verified_outcome','verified webhook projection trigger exists');
select has_index('public','meeting_sessions','idx_meeting_sessions_history_time','history index exists');
select ok(has_function_privilege('authenticated','public.get_meeting_history(uuid,text,integer)','execute'),'authenticated users can call guarded history RPC');
select ok(has_function_privilege('authenticated','public.get_meeting_attendance_history(uuid)','execute'),'authenticated users can call guarded attendance RPC');
select ok(not has_function_privilege('anon','public.get_meeting_history(uuid,text,integer)','execute'),'anonymous users cannot call history RPC');
select ok(not has_function_privilege('anon','public.get_meeting_attendance_history(uuid)','execute'),'anonymous users cannot call attendance RPC');
select matches(pg_get_functiondef('public.get_meeting_history(uuid,text,integer)'::regprocedure),'recordingAvailable'',false','history never claims a recording');
select matches(pg_get_functiondef('public.get_meeting_history(uuid,text,integer)'::regprocedure),'transcriptRetained'',false','history never claims retained transcript text');
select matches(pg_get_functiondef('public.get_meeting_attendance_history(uuid)'::regprocedure),'can_view_all or attendance.user_id=auth.uid','attendance is all-for-manager or self-only');
select * from finish();
rollback;
