begin;
select plan(18);
select has_column('public','audit_log','actor_kind','audit distinguishes user and system actors');
select has_column('public','audit_log','meeting_event_id','audit links safe meeting event');
select has_column('public','audit_log','metadata','audit has bounded metadata');
select has_column('public','audit_log','retention_until','audit has retention floor');
select has_column('public','meeting_attendance','retention_until','attendance has retention floor');
select has_column('public','meeting_events','retention_until','meeting events have retention floor');
select has_column('public','meeting_waiting_entries','retention_until','waiting metadata has retention floor');
select has_trigger('public','meeting_events','meeting_events_append_only','meeting events are immutable');
select has_trigger('public','meeting_events','meeting_event_to_restricted_audit','meeting events mirror to restricted audit');
select has_trigger('public','meeting_caption_sessions','meeting_caption_lifecycle_audit','caption activation is audited');
select has_function('public','prevent_meeting_event_mutation',array[]::text[],'append-only guard exists');
select has_function('public','audit_meeting_event',array[]::text[],'audit mirror exists');
select has_function('public','audit_meeting_caption_lifecycle',array[]::text[],'caption audit projection exists');
select ok(not has_table_privilege('authenticated','public.meeting_events','update'),'clients cannot update meeting events');
select ok(not has_table_privilege('authenticated','public.meeting_events','delete'),'clients cannot delete meeting events');
select matches(pg_get_functiondef('public.audit_meeting_event()'::regprocedure),'meeting_admission','admit and deny transitions are audited');
select matches(pg_get_functiondef('public.audit_meeting_event()'::regprocedure),'meeting_media','screen share controls are audited');
select matches(pg_get_functiondef('public.audit_meeting_caption_lifecycle()'::regprocedure),'''retentionMode'',''ephemeral''','caption audit never stores transcript text');
select * from finish();
rollback;
