begin;
select plan(20);
select has_table('public','meeting_reaction_signals','server reaction table exists');
select has_column('public','meeting_reaction_signals','expires_at','reactions expire');
select has_index('public','meeting_reaction_signals','idx_meeting_reaction_signals_session_expiry','reaction subscription index exists');
select has_function('public','send_meeting_reaction',array['uuid','uuid','uuid','text'],'reaction RPC exists');
select has_function('public','enforce_meeting_waiting_abuse_guard',array[]::text[],'waiting guard exists');
select has_function('public','enforce_meeting_chat_abuse_guard',array[]::text[],'chat guard exists');
select has_function('public','enforce_meeting_privileged_abuse_guard',array[]::text[],'privileged guard exists');
select has_trigger('public','meeting_waiting_entries','meeting_waiting_insert_abuse_guard','waiting insert is rate limited');
select has_trigger('public','meeting_chat_message_links','meeting_chat_link_abuse_guard','meeting chat is rate limited');
select has_trigger('public','audit_log','meeting_privileged_action_abuse_guard','privileged actions are rate limited transactionally');
select ok(not has_table_privilege('authenticated','public.meeting_reaction_signals','insert'),'clients cannot forge reaction rows');
select ok(not has_table_privilege('authenticated','public.meeting_reaction_signals','update'),'clients cannot mutate reaction rows');
select ok(not has_table_privilege('authenticated','public.meeting_reaction_signals','delete'),'clients cannot delete reaction rows');
select ok(has_table_privilege('authenticated','public.meeting_reaction_signals','select'),'participants can receive RLS-filtered reactions');
select matches(pg_get_functiondef('public.send_meeting_reaction(uuid,uuid,uuid,text)'::regprocedure),'meeting_user_is_restricted','reaction checks bans and timeouts');
select matches(pg_get_functiondef('public.send_meeting_reaction(uuid,uuid,uuid,text)'::regprocedure),'meeting_reaction','reaction consumes dedicated budget');
select matches(pg_get_functiondef('public.consume_current_user_action_rate_limit(text)'::regprocedure),'meeting_waiting_request','waiting budget exists');
select matches(pg_get_functiondef('public.consume_current_user_action_rate_limit(text)'::regprocedure),'meeting_chat_send','meeting chat budget exists');
select matches(pg_get_functiondef('public.consume_current_user_action_rate_limit(text)'::regprocedure),'meeting_privileged_action','privileged budget exists');
select matches(pg_get_functiondef('public.consume_meeting_request_limit(text)'::regprocedure),'PICOM_MEETING_ABUSE','safe server abuse marker exists');
select * from finish();
rollback;
