[picom-verify]
exten => s,1,Answer()
 same => n,Wait(1)
 same => n,Playback(beep)
 same => n,SayDigits(${PICOM_VERIFY_CODE})
 same => n,Wait(1)
 same => n,SayDigits(${PICOM_VERIFY_CODE})
 same => n,Hangup()