// Generated by `npm run supabase:types` when Supabase CLI is available.
// This lightweight placeholder keeps the app type-safe before local Supabase is started.
// Do not add secrets or server-only fields here.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          avatar_url: string | null;
          status: string;
          status_text: string;
          bio: string | null;
          accent_color: string | null;
          onboarding_completed: boolean;
          onboarding_completed_at: string | null;
          is_bot: boolean;
          deletion_requested_at: string | null;
          accepted_terms_version: string | null;
          terms_accepted_at: string | null;
          accepted_privacy_version: string | null;
          privacy_accepted_at: string | null;
          dm_privacy: "everyone" | "friends" | "no_one";
          friend_request_privacy: "everyone" | "community_members" | "friends_of_friends" | "nobody";
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & Pick<Database["public"]["Tables"]["profiles"]["Row"], "id" | "username" | "display_name">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]>;
        Relationships: [];
      };
      communities: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string | null;
          icon_url: string | null;
          accent_color: string;
          visibility: "public" | "private";
          public_read_enabled: boolean;
          discovery_listed: boolean;
          discovery_join_policy: "open" | "request";
          category: "development" | "design" | "gaming" | "music" | "study" | "work" | null;
          discovery_content_flags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["communities"]["Row"]> & Pick<Database["public"]["Tables"]["communities"]["Row"], "owner_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["communities"]["Row"]>;
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          community_id: string;
          name: string;
          color: string;
          level: number;
          permissions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["roles"]["Row"]> & Pick<Database["public"]["Tables"]["roles"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["roles"]["Row"]>;
        Relationships: [];
      };
      community_members: {
        Row: {
          id: string;
          community_id: string;
          user_id: string;
          role_id: string | null;
          joined_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["community_members"]["Row"]> & Pick<Database["public"]["Tables"]["community_members"]["Row"], "community_id" | "user_id">;
        Update: Partial<Database["public"]["Tables"]["community_members"]["Row"]>;
        Relationships: [];
      };
      channel_categories: {
        Row: {
          id: string;
          community_id: string;
          name: string;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["channel_categories"]["Row"]> & Pick<Database["public"]["Tables"]["channel_categories"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["channel_categories"]["Row"]>;
        Relationships: [];
      };
      channels: {
        Row: {
          id: string;
          community_id: string;
          category_id: string | null;
          name: string;
          type: "text" | "voice" | "forum" | "announcement";
          topic: string | null;
          is_private: boolean;
          public_read_enabled: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["channels"]["Row"]> & Pick<Database["public"]["Tables"]["channels"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["channels"]["Row"]>;
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          community_id: string;
          channel_id: string;
          author_id: string;
          body: string;
          client_message_id: string | null;
          sequence: number | null;
          created_at: string;
          edited_at: string | null;
          deleted_at: string | null;
          thread_id: string | null;
          webhook_id: string | null;
          webhook_name: string | null;
          search_vector: unknown;
        };
        Insert: Partial<Database["public"]["Tables"]["messages"]["Row"]> & Pick<Database["public"]["Tables"]["messages"]["Row"], "community_id" | "channel_id" | "author_id">;
        Update: Partial<Database["public"]["Tables"]["messages"]["Row"]>;
        Relationships: [];
      };
      attachments: {
        Row: {
          id: string;
          message_id: string | null;
          uploader_id: string;
          storage_path: string;
          file_name: string;
          mime_type: string;
          size_bytes: number;
          attachment_type: "image";
          width: number | null;
          height: number | null;
          public_url: string | null;
          thumbnail_url: string | null;
          scan_status: "pending" | "clean" | "suspicious" | "failed" | "skipped_development";
          status: "pending" | "attached" | "failed";
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["attachments"]["Row"]> & Pick<Database["public"]["Tables"]["attachments"]["Row"], "uploader_id" | "storage_path" | "file_name" | "mime_type" | "size_bytes">;
        Update: Partial<Database["public"]["Tables"]["attachments"]["Row"]>;
        Relationships: [];
      };
      message_reactions: {
        Row: {
          id: string;
          message_id: string;
          user_id: string;
          emoji: string;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["message_reactions"]["Row"]> & Pick<Database["public"]["Tables"]["message_reactions"]["Row"], "message_id" | "user_id" | "emoji">;
        Update: Partial<Database["public"]["Tables"]["message_reactions"]["Row"]>;
        Relationships: [];
      };
      community_events: {
        Row: { id:string;community_id:string;channel_id:string|null;title:string;description:string;starts_at:string;ends_at:string|null;event_type:"meeting"|"voice"|"release"|"review"|"social";created_by:string;cancelled_at:string|null;created_at:string;updated_at:string };
        Insert: Partial<Database["public"]["Tables"]["community_events"]["Row"]> & Pick<Database["public"]["Tables"]["community_events"]["Row"],"community_id"|"title"|"starts_at"|"created_by">;
        Update: Partial<Database["public"]["Tables"]["community_events"]["Row"]>;Relationships:[];
      };
      community_event_rsvps: {
        Row: { id:string;event_id:string;user_id:string;status:"interested"|"going"|"not_going";created_at:string;updated_at:string };
        Insert: Partial<Database["public"]["Tables"]["community_event_rsvps"]["Row"]> & Pick<Database["public"]["Tables"]["community_event_rsvps"]["Row"],"event_id"|"user_id"|"status">;
        Update: Partial<Database["public"]["Tables"]["community_event_rsvps"]["Row"]>;Relationships:[];
      };
      community_event_reminders: {
        Row: { id:string;event_id:string;user_id:string;minutes_before:number;enabled:boolean;created_at:string;updated_at:string };
        Insert: Partial<Database["public"]["Tables"]["community_event_reminders"]["Row"]> & Pick<Database["public"]["Tables"]["community_event_reminders"]["Row"],"event_id"|"user_id">;
        Update: Partial<Database["public"]["Tables"]["community_event_reminders"]["Row"]>;Relationships:[];
      };
      saved_messages: {
        Row: { id: string; user_id: string; message_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["saved_messages"]["Row"]> & Pick<Database["public"]["Tables"]["saved_messages"]["Row"], "user_id" | "message_id">;
        Update: Partial<Database["public"]["Tables"]["saved_messages"]["Row"]>; Relationships: [];
      };
      blocked_users: {
        Row: { id: string; blocker_id: string; blocked_user_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["blocked_users"]["Row"]> & Pick<Database["public"]["Tables"]["blocked_users"]["Row"], "blocker_id" | "blocked_user_id">;
        Update: Partial<Database["public"]["Tables"]["blocked_users"]["Row"]>; Relationships: [];
      };
      user_follows: {
        Row: { id: string; follower_id: string; followed_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["user_follows"]["Row"]> & Pick<Database["public"]["Tables"]["user_follows"]["Row"], "follower_id" | "followed_id">;
        Update: Partial<Database["public"]["Tables"]["user_follows"]["Row"]>; Relationships: [];
      };
      message_mentions: {
        Row: { id: string; message_id: string; mentioned_user_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["message_mentions"]["Row"]> & Pick<Database["public"]["Tables"]["message_mentions"]["Row"], "message_id" | "mentioned_user_id">;
        Update: Partial<Database["public"]["Tables"]["message_mentions"]["Row"]>; Relationships: [];
      };
      voice_story_events: {
        Row: { id: string; author_id: string; community_id: string; channel_id: string; title: string; created_at: string; ended_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["voice_story_events"]["Row"]> & Pick<Database["public"]["Tables"]["voice_story_events"]["Row"], "author_id" | "community_id" | "channel_id" | "title">;
        Update: Partial<Database["public"]["Tables"]["voice_story_events"]["Row"]>; Relationships: [];
      };
      friend_requests: {
        Row: { id: string; sender_id: string; recipient_id: string; status: "pending" | "accepted" | "declined"; created_at: string; responded_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["friend_requests"]["Row"]> & Pick<Database["public"]["Tables"]["friend_requests"]["Row"], "sender_id" | "recipient_id">;
        Update: Partial<Database["public"]["Tables"]["friend_requests"]["Row"]>; Relationships: [];
      };
      friendships: {
        Row: { id: string; user_low_id: string; user_high_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["friendships"]["Row"]> & Pick<Database["public"]["Tables"]["friendships"]["Row"], "user_low_id" | "user_high_id">;
        Update: Partial<Database["public"]["Tables"]["friendships"]["Row"]>; Relationships: [];
      };
      direct_conversations: {
        Row: { id: string; type: "direct"; created_by: string; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["direct_conversations"]["Row"]> & Pick<Database["public"]["Tables"]["direct_conversations"]["Row"], "created_by">;
        Update: Partial<Database["public"]["Tables"]["direct_conversations"]["Row"]>;
        Relationships: [];
      };
      direct_conversation_members: {
        Row: { id: string; conversation_id: string; user_id: string; joined_at: string; last_read_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["direct_conversation_members"]["Row"]> & Pick<Database["public"]["Tables"]["direct_conversation_members"]["Row"], "conversation_id" | "user_id">;
        Update: Partial<Database["public"]["Tables"]["direct_conversation_members"]["Row"]>;
        Relationships: [];
      };
      direct_messages: {
        Row: { id: string; conversation_id: string; author_id: string; body: string; client_message_id: string | null; created_at: string; updated_at: string; edited_at: string | null; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["direct_messages"]["Row"]> & Pick<Database["public"]["Tables"]["direct_messages"]["Row"], "conversation_id" | "author_id" | "body">;
        Update: Partial<Database["public"]["Tables"]["direct_messages"]["Row"]>;
        Relationships: [];
      };
      direct_message_reactions: {
        Row: { id: string; message_id: string; user_id: string; emoji: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["direct_message_reactions"]["Row"]> & Pick<Database["public"]["Tables"]["direct_message_reactions"]["Row"], "message_id" | "user_id" | "emoji">;
        Update: Partial<Database["public"]["Tables"]["direct_message_reactions"]["Row"]>;
        Relationships: [];
      };
      direct_message_attachments: {
        Row: { id: string; message_id: string; uploader_id: string; storage_path: string; file_name: string; mime_type: string; size_bytes: number; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["direct_message_attachments"]["Row"]> & Pick<Database["public"]["Tables"]["direct_message_attachments"]["Row"], "message_id" | "uploader_id" | "storage_path" | "file_name" | "mime_type" | "size_bytes">;
        Update: Partial<Database["public"]["Tables"]["direct_message_attachments"]["Row"]>;
        Relationships: [];
      };
      read_states: {
        Row: {
          id: string;
          user_id: string;
          channel_id: string;
          last_read_message_id: string | null;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["read_states"]["Row"]> & Pick<Database["public"]["Tables"]["read_states"]["Row"], "user_id" | "channel_id">;
        Update: Partial<Database["public"]["Tables"]["read_states"]["Row"]>;
        Relationships: [];
      };
      community_invites: {
        Row: { id: string; community_id: string; code: string; created_by: string; max_uses: number | null; uses: number; expires_at: string | null; revoked_at: string | null; created_at: string; campaign_label: string | null; last_used_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["community_invites"]["Row"]> & Pick<Database["public"]["Tables"]["community_invites"]["Row"], "community_id" | "code" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_invites"]["Row"]>;
        Relationships: [];
      };
      community_voice_usage_daily: {
        Row: { community_id: string; usage_date: string; session_count: number; participant_minutes: number; peak_concurrent: number; updated_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      friend_request_notifications: {
        Row: { id: string; recipient_id: string; actor_id: string; request_id: string | null; event_type: "request_sent" | "request_accepted"; created_at: string; read_at: string | null };
        Insert: never; Update: Pick<Database["public"]["Tables"]["friend_request_notifications"]["Row"], "read_at">; Relationships: [];
      };
      app_admins: {
        Row: { user_id: string; granted_by: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      verification_badges: {
        Row:{id:string;subject_type:"user"|"community"|"role";subject_id:string;badge_kind:"profile_reviewed"|"community_official"|"role_managed";label:string;scope_note:string;granted_by:string;granted_at:string;revoked_at:string|null;revoked_by:string|null};Insert:never;Update:never;Relationships:[];
      };
      profile_privacy_settings:{Row:{user_id:string;profile_visibility:"everyone"|"shared_communities"|"friends";show_location:boolean;show_timezone:boolean;show_activity:boolean;show_media:boolean;location:string|null;timezone:string|null;updated_at:string};Insert:never;Update:never;Relationships:[]};
      data_export_requests: {
        Row: { id: string; user_id: string; status: "requested" | "processing" | "ready" | "failed"; format: "json"; requested_at: string; completed_at: string | null; expires_at: string | null; failure_code: string | null };
        Insert: Partial<Database["public"]["Tables"]["data_export_requests"]["Row"]> & Pick<Database["public"]["Tables"]["data_export_requests"]["Row"], "user_id">;
        Update: never;
        Relationships: [];
      };
      account_deletion_requests: {
        Row: { id: string; user_id: string; status: "requested" | "reviewing" | "canceled" | "completed"; requested_at: string; canceled_at: string | null; completed_at: string | null; anonymize_after: string | null; sessions_revoked_at: string | null; session_revocation_status: "pending" | "completed" | "failed"; finalization_status: "pending" | "profile_anonymized" | "auth_soft_delete_failed" | "completed" };
        Insert: Partial<Database["public"]["Tables"]["account_deletion_requests"]["Row"]> & Pick<Database["public"]["Tables"]["account_deletion_requests"]["Row"], "user_id">;
        Update: never;
        Relationships: [];
      };
      account_security_events: {
        Row: { id: string; user_id: string; event_type: "account_deletion_requested" | "account_deletion_canceled" | "account_sessions_revoked"; request_id: string | null; metadata: Record<string, unknown>; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      legal_policy_versions: {
        Row: { policy_key: "terms" | "privacy"; current_version: string; effective_at: string; requires_reaccept: boolean; updated_at: string };
        Insert: never; Update: never; Relationships: [];
      };
      legal_acceptance_events: {
        Row: { id: string; user_id: string; terms_version: string; privacy_version: string; accepted_at: string; source: "registration" | "reaccept" };
        Insert: never; Update: never; Relationships: [];
      };
      threads: {
        Row: { id: string; community_id: string; channel_id: string; parent_message_id: string; name: string; created_by: string; created_at: string; archived_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["threads"]["Row"]> & Pick<Database["public"]["Tables"]["threads"]["Row"], "community_id" | "channel_id" | "parent_message_id" | "name" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["threads"]["Row"]>;
        Relationships: [];
      };
      thread_read_states: {
        Row: { thread_id: string; user_id: string; last_read_at: string };
        Insert: Database["public"]["Tables"]["thread_read_states"]["Row"];
        Update: Partial<Database["public"]["Tables"]["thread_read_states"]["Row"]>;
        Relationships: [];
      };
      announcement_channel_followers: {
        Row: { channel_id: string; user_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["announcement_channel_followers"]["Row"]> & Pick<Database["public"]["Tables"]["announcement_channel_followers"]["Row"], "channel_id" | "user_id">;
        Update: never;
        Relationships: [];
      };
      forum_posts: {
        Row: { id: string; community_id: string; channel_id: string; parent_message_id: string; thread_id: string; title: string; body: string; author_id: string; tags: string[]; status: "open" | "resolved"; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["forum_posts"]["Row"]> & Pick<Database["public"]["Tables"]["forum_posts"]["Row"], "channel_id" | "title" | "author_id">;
        Update: Partial<Database["public"]["Tables"]["forum_posts"]["Row"]>;
        Relationships: [];
      };
      bots: {
        Row: { id: string; profile_id: string; owner_id: string; display_name: string; avatar_url: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      community_bots: {
        Row: { community_id: string; bot_id: string; role_id: string; installed_by: string; installed_at: string };
        Insert: Partial<Database["public"]["Tables"]["community_bots"]["Row"]> & Pick<Database["public"]["Tables"]["community_bots"]["Row"], "community_id" | "bot_id" | "role_id" | "installed_by">;
        Update: Partial<Database["public"]["Tables"]["community_bots"]["Row"]>;
        Relationships: [];
      };
      bot_credentials: {
        Row: { id: string; bot_id: string; token_prefix: string; token_hash: string; hash_algorithm: "sha256"; created_by: string; created_at: string; last_used_at: string | null; revoked_at: string | null };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      bot_action_rate_limits: {
        Row: { credential_id: string; action_key: "api_request" | "message_send" | "reaction_write" | "event_delivery" | "command_invoke"; window_started_at: string; request_count: number; denied_count: number; updated_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      reports: {
        Row: { id: string; community_id: string | null; reporter_id: string; target_type: "message" | "user" | "community"; target_id: string; reason: "spam" | "harassment" | "unsafe_content" | "impersonation" | "other"; description: string; status: "open" | "reviewed" | "dismissed" | "action_taken"; reviewed_by: string | null; reviewed_at: string | null; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["reports"]["Row"]> & Pick<Database["public"]["Tables"]["reports"]["Row"], "reporter_id" | "target_type" | "target_id" | "reason" | "description">;
        Update: Partial<Database["public"]["Tables"]["reports"]["Row"]>;
        Relationships: [];
      };
      moderation_action_records: {
        Row: { id: string; community_id: string; affected_user_id: string; actor_id: string | null; action_type: "ban" | "kick" | "timeout" | "message_delete" | "other"; target_id: string | null; reason_code: string; appealable: boolean; appealable_until: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      moderation_appeals: {
        Row: { id: string; community_id: string; affected_user_id: string; moderation_action_id: string; reason: string; status: "open" | "under_review" | "accepted" | "denied" | "closed"; decision_note: string | null; reviewed_by: string | null; reviewed_at: string | null; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["moderation_appeals"]["Row"]> & Pick<Database["public"]["Tables"]["moderation_appeals"]["Row"], "community_id" | "affected_user_id" | "moderation_action_id" | "reason">;
        Update: Pick<Partial<Database["public"]["Tables"]["moderation_appeals"]["Row"]>, "status" | "decision_note" | "reviewed_by" | "updated_at">;
        Relationships: [];
      };
      abuse_events: {
        Row: { id: number; event_type: string; severity: "info" | "warning" | "critical"; community_id: string | null; reason_code: string; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      audit_log: {
        Row: { id: string; community_id: string; actor_id: string; action_type: string; target_type: string; target_id: string | null; reason: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      webhooks: {
        Row: { id: string; community_id: string; channel_id: string; name: string; avatar_url: string | null; token_hash: string; created_by: string; revoked_at: string | null; created_at: string; updated_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      community_emojis: {
        Row: { id: string; community_id: string; name: string; image_url: string; storage_path: string | null; created_by: string; created_at: string; moderation_status: "active" | "disabled"; disabled_at: string | null; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["community_emojis"]["Row"]> & Pick<Database["public"]["Tables"]["community_emojis"]["Row"], "community_id" | "name" | "image_url" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_emojis"]["Row"]>;
        Relationships: [];
      };
      community_stickers: {
        Row: { id: string; pack_id: string | null; community_id: string; name: string; title: string; image_url: string; storage_path: string | null; created_by: string; created_at: string; moderation_status: "active" | "disabled"; disabled_at: string | null; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["community_stickers"]["Row"]> & Pick<Database["public"]["Tables"]["community_stickers"]["Row"], "community_id" | "name" | "image_url" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_stickers"]["Row"]>;
        Relationships: [];
      };
      community_sticker_packs: {
        Row: { id: string; community_id: string; name: string; description: string; created_by: string; created_at: string; moderation_status: "active" | "disabled"; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["community_sticker_packs"]["Row"]> & Pick<Database["public"]["Tables"]["community_sticker_packs"]["Row"], "community_id" | "name" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_sticker_packs"]["Row"]>;
        Relationships: [];
      };
      polls: {
        Row: { id: string; message_id: string; question: string; allow_multiple: boolean; closes_at: string | null; closed_at: string | null; closed_by: string | null; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["polls"]["Row"]> & Pick<Database["public"]["Tables"]["polls"]["Row"], "message_id" | "question">;
        Update: Partial<Database["public"]["Tables"]["polls"]["Row"]>;
        Relationships: [];
      };
      poll_options: {
        Row: { id: string; poll_id: string; text: string; position: number };
        Insert: Partial<Database["public"]["Tables"]["poll_options"]["Row"]> & Pick<Database["public"]["Tables"]["poll_options"]["Row"], "poll_id" | "text" | "position">;
        Update: Partial<Database["public"]["Tables"]["poll_options"]["Row"]>;
        Relationships: [];
      };
      poll_votes: {
        Row: { id: string; poll_id: string; option_id: string; user_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["poll_votes"]["Row"]> & Pick<Database["public"]["Tables"]["poll_votes"]["Row"], "poll_id" | "option_id" | "user_id">;
        Update: never;
        Relationships: [];
      };
    };
    Views: {
      message_attachments: {
        Row: Database["public"]["Tables"]["attachments"]["Row"];
        Relationships: [];
      };
      mention_feed_view: {
        Row: {
          message_id: string; community_id: string; channel_id: string; author_id: string; mentioned_user_ids: string[];
          body: string; title: string | null; created_at: string; source: "popular_feed" | "following";
          attachments: Json; reactions: Json; view_count: number; comment_count: number; commenter_ids: string[];
          popularity_score: number; is_saved: boolean;
        };
        Relationships: [];
      };
      followed_user_stories_view: {
        Row: {
          story_id: string; author_id: string; community_id: string | null; channel_id: string | null; message_id: string | null;
          story_type: string; title: string; subtitle: string | null; body: string | null; image_url: string | null;
          gradient_variant: string | null; created_at: string; duration_seconds: number; mentioned_user_ids: string[];
        };
        Relationships: [];
      };
    };
    Functions: {
      accept_current_legal_terms: { Args: Record<string, never>; Returns: Array<{ terms_version: string; privacy_version: string; accepted_at: string }> };
      request_current_user_account_deletion: { Args: { confirmation_username: string }; Returns: Array<{ request_id: string; requested_at: string; anonymize_after: string }> };
      cancel_current_user_account_deletion: { Args: Record<string, never>; Returns: Array<{ request_id: string; canceled_at: string }> };
      list_public_discovery_communities: {
        Args: { search_text?: string | null; category_filter?: string | null; result_limit?: number };
        Returns: Array<{ id: string; name: string; description: string | null; icon_url: string | null; accent_color: string; category: string | null; member_count: number; join_policy: "open" | "request" }>;
      };
      join_or_request_discovery_community: { Args: { target_community_id: string }; Returns: "joined" | "requested" | "already_member" };
      list_discovery_review_queue: {
        Args: { status_filter?: string | null; result_limit?: number };
        Returns: Array<{ community_id: string; community_name: string; description: string | null; icon_url: string | null; category: string | null; content_flags: string[]; review_status: "pending" | "approved" | "rejected" | "hidden" | "suspended"; report_count: number; submitted_at: string; reviewed_at: string | null }>;
      };
      review_discovery_listing: { Args: { target_community_id: string; next_status: string; review_reason?: string | null }; Returns: boolean };
      search_accessible_entities: {
        Args: { query_text: string; category_filter?: string | null; result_limit?: number };
        Returns: Array<{ result_type: "community" | "channel" | "member" | "message" | "mention" | "saved_message"; entity_id: string; label: string; detail: string; community_id: string | null; channel_id: string | null; message_id: string | null; user_id: string | null; created_at: string; rank: number }>;
      };
      users_are_blocked: { Args: { first_user_id: string; second_user_id: string }; Returns: boolean };
      respond_friend_request: { Args: { target_request_id: string; accept_request: boolean }; Returns: boolean };
      send_friend_request: { Args: { target_user_id: string }; Returns: string };
      cancel_friend_request: { Args: { target_request_id: string }; Returns: boolean };
      list_friend_relationship_state: { Args: Record<string, never>; Returns: Json };
      block_user: { Args: { target_user_id: string }; Returns: boolean };
      unblock_user: { Args: { target_user_id: string }; Returns: boolean };
      list_blocked_users: { Args: Record<string, never>; Returns: Array<{ user_id: string; display_name: string; username: string; blocked_at: string }> };
      remove_friend: { Args: { other_user_id: string }; Returns: boolean };
      create_direct_conversation: { Args: { other_user_id: string }; Returns: string };
      list_direct_conversations: { Args: { result_limit?: number }; Returns: Array<{ id: string; participant_user_id: string; participant_name: string; participant_username: string; participant_status: string; participant_status_text: string; last_message_preview: string; updated_at: string; unread_count: number }> };
      send_direct_message: { Args: { target_conversation_id: string; message_body: string; target_client_message_id: string }; Returns: Json };
      mark_direct_conversation_read: { Args: { target_conversation_id: string }; Returns: boolean };
      accept_community_invite: {
        Args: { invite_code: string };
        Returns: Array<{ id: string; community_id: string; user_id: string; role_id: string | null; joined_at: string }>;
      };
      create_community_invite: { Args: { target_community_id: string; target_max_uses?: number | null; target_expires_at?: string | null; target_campaign_label?: string | null }; Returns: Array<Database["public"]["Tables"]["community_invites"]["Row"]> };
      revoke_community_invite: { Args: { target_invite_id: string }; Returns: Array<Database["public"]["Tables"]["community_invites"]["Row"]> };
      list_community_invite_campaigns: { Args: { target_community_id: string }; Returns: Array<{ id: string; community_id: string; created_by: string; creator_name: string; campaign_label: string | null; max_uses: number | null; uses: number; expires_at: string | null; revoked_at: string | null; last_used_at: string | null; created_at: string }> };
      append_community_audit_log: {
        Args: { target_community_id: string; event_action_type: string; event_target_type: string; event_target_id: string | null; event_reason: string | null };
        Returns: string;
      };
      is_app_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      list_active_verification_badges:{Args:{target_subject_type:string;target_subject_id:string};Returns:Array<{id:string;subject_type:string;subject_id:string;badge_kind:string;label:string;scope_note:string;granted_at:string;revoked_at:null}>};
      list_recent_verification_badges:{Args:{result_limit?:number};Returns:Array<{id:string;subject_type:string;subject_id:string;badge_kind:string;label:string;scope_note:string;granted_at:string;revoked_at:string|null}>};
      grant_verification_badge:{Args:{target_subject_type:string;target_subject_id:string;target_badge_kind:string;target_label:string;target_scope_note:string;grant_reason:string};Returns:Array<{id:string;subject_type:string;subject_id:string;badge_kind:string;label:string;scope_note:string;granted_at:string;revoked_at:null}>};
      revoke_verification_badge:{Args:{target_badge_id:string;revoke_reason:string};Returns:boolean};
      get_own_profile_privacy:{Args:Record<string,never>;Returns:Array<{profile_visibility:"everyone"|"shared_communities"|"friends";show_location:boolean;show_timezone:boolean;show_activity:boolean;show_media:boolean}>};
      update_profile_privacy:{Args:{next_visibility:string;next_show_location:boolean;next_show_timezone:boolean;next_show_activity:boolean;next_show_media:boolean};Returns:boolean};
      get_profile_privacy_projection:{Args:{target_user_id:string};Returns:Array<{can_view_profile:boolean;show_location:boolean;show_timezone:boolean;show_activity:boolean;show_media:boolean;location:string|null;timezone:string|null}>};
      get_trust_safety_summary: {
        Args: Record<string, never>;
        Returns: Json;
      };
      get_admin_system_status_v2: { Args: Record<string, never>; Returns: Json };
      list_admin_operations_v2: { Args: { section_name: string; page_cursor_created_at?: string | null; page_cursor_id?: string | null; page_limit?: number }; Returns: Json };
      append_admin_operations_audit: { Args: { admin_action_type: string; admin_target_type: string; admin_target_id?: string | null }; Returns: number };
      can_manage_community_bots: { Args: { target_community_id: string }; Returns: boolean };
      issue_community_bot_credential: { Args: { target_community_id: string; target_bot_id: string }; Returns: Array<{ raw_token: string; token_prefix: string; created_at: string }> };
      revoke_community_bot_credential: { Args: { target_community_id: string; target_bot_id: string }; Returns: boolean };
      get_community_bot_credential_status: { Args: { target_community_id: string; target_bot_id: string }; Returns: Array<{ bot_id: string; token_prefix: string; created_at: string; revoked_at: string | null; rate_limit_per_minute: number }> };
      rotate_community_bot_credential: { Args: { target_community_id: string; target_bot_id: string }; Returns: Array<{ raw_token: string; token_prefix: string; created_at: string }> };
      create_channel_webhook: { Args: { target_community_id: string; target_channel_id: string; target_webhook_name: string; webhook_avatar_url: string | null }; Returns: Array<{ webhook_id: string; community_id: string; channel_id: string; webhook_name: string; avatar_url: string | null; created_by: string; revoked_at: string | null; created_at: string; updated_at: string; token_once: string }> };
      revoke_channel_webhook: { Args: { target_webhook_id: string }; Returns: Array<{ webhook_id: string; community_id: string; channel_id: string; webhook_name: string; avatar_url: string | null; created_by: string; revoked_at: string | null; created_at: string; updated_at: string }> };
      create_poll_atomic: { Args: { target_message_id: string; poll_question: string; option_texts: string[]; allow_multiple_choices: boolean; poll_closes_at: string | null }; Returns: Json };
      get_poll_state: { Args: { target_poll_id: string }; Returns: Json };
      toggle_poll_vote: { Args: { target_poll_id: string; target_option_id: string }; Returns: Json };
      close_poll: { Args: { target_poll_id: string }; Returns: Json };
      set_community_event_rsvp: { Args: { target_event_id: string; next_status: "interested" | "going" | "not_going" }; Returns: boolean };
      open_or_create_thread: { Args: { target_community_id: string; target_channel_id: string; target_parent_message_id: string; thread_name: string }; Returns: Json };
      send_thread_message: { Args: { target_thread_id: string; message_body: string; target_client_message_id: string }; Returns: Json };
      get_thread_summary: { Args: { target_thread_id: string }; Returns: Json };
      mark_thread_read: { Args: { target_thread_id: string }; Returns: boolean };
      create_forum_post: { Args: { target_community_id: string; target_channel_id: string; post_title: string; post_body: string; post_tags: string[] }; Returns: Json };
      list_accessible_saved_messages: { Args: { result_limit?: number }; Returns: Array<{ id: string; message_id: string; community_id: string; channel_id: string; author_id: string; preview: string; message_created_at: string; created_at: string }> };
      get_community_insights_v2: { Args: { target_community_id: string; window_days?: number }; Returns: Json };
      list_mention_feed: {
        Args: { cursor_created_at?: string | null; cursor_message_id?: string | null; result_limit?: number };
        Returns: Array<Database["public"]["Views"]["mention_feed_view"]["Row"]>;
      };
      list_followed_user_stories: {
        Args: { cursor_created_at?: string | null; cursor_story_id?: string | null; result_limit?: number };
        Returns: Array<Database["public"]["Views"]["followed_user_stories_view"]["Row"]>;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
