// Generated by `npm run supabase:types` when Supabase CLI is available.
// This lightweight placeholder keeps the app type-safe before local Supabase is started.
// Do not add secrets or server-only fields here.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          avatar_url: string | null;
          status: string;
          status_text: string;
          bio: string | null;
          accent_color: string | null;
          onboarding_completed: boolean;
          onboarding_completed_at: string | null;
          is_bot: boolean;
          deletion_requested_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & Pick<Database["public"]["Tables"]["profiles"]["Row"], "id" | "username" | "display_name">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]>;
        Relationships: [];
      };
      communities: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string | null;
          icon_url: string | null;
          accent_color: string;
          visibility: "public" | "private";
          public_read_enabled: boolean;
          discovery_listed: boolean;
          category: "development" | "design" | "gaming" | "music" | "study" | "work" | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["communities"]["Row"]> & Pick<Database["public"]["Tables"]["communities"]["Row"], "owner_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["communities"]["Row"]>;
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          community_id: string;
          name: string;
          color: string;
          level: number;
          permissions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["roles"]["Row"]> & Pick<Database["public"]["Tables"]["roles"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["roles"]["Row"]>;
        Relationships: [];
      };
      community_members: {
        Row: {
          id: string;
          community_id: string;
          user_id: string;
          role_id: string | null;
          joined_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["community_members"]["Row"]> & Pick<Database["public"]["Tables"]["community_members"]["Row"], "community_id" | "user_id">;
        Update: Partial<Database["public"]["Tables"]["community_members"]["Row"]>;
        Relationships: [];
      };
      channel_categories: {
        Row: {
          id: string;
          community_id: string;
          name: string;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["channel_categories"]["Row"]> & Pick<Database["public"]["Tables"]["channel_categories"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["channel_categories"]["Row"]>;
        Relationships: [];
      };
      channels: {
        Row: {
          id: string;
          community_id: string;
          category_id: string | null;
          name: string;
          type: "text" | "voice" | "forum" | "announcement";
          topic: string | null;
          is_private: boolean;
          public_read_enabled: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["channels"]["Row"]> & Pick<Database["public"]["Tables"]["channels"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["channels"]["Row"]>;
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          community_id: string;
          channel_id: string;
          author_id: string;
          body: string;
          client_message_id: string | null;
          sequence: number | null;
          created_at: string;
          edited_at: string | null;
          deleted_at: string | null;
          thread_id: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["messages"]["Row"]> & Pick<Database["public"]["Tables"]["messages"]["Row"], "community_id" | "channel_id" | "author_id">;
        Update: Partial<Database["public"]["Tables"]["messages"]["Row"]>;
        Relationships: [];
      };
      attachments: {
        Row: {
          id: string;
          message_id: string | null;
          uploader_id: string;
          storage_path: string;
          file_name: string;
          mime_type: string;
          size_bytes: number;
          attachment_type: "image";
          width: number | null;
          height: number | null;
          public_url: string | null;
          thumbnail_url: string | null;
          status: "pending" | "attached" | "failed";
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["attachments"]["Row"]> & Pick<Database["public"]["Tables"]["attachments"]["Row"], "uploader_id" | "storage_path" | "file_name" | "mime_type" | "size_bytes">;
        Update: Partial<Database["public"]["Tables"]["attachments"]["Row"]>;
        Relationships: [];
      };
      message_reactions: {
        Row: {
          id: string;
          message_id: string;
          user_id: string;
          emoji: string;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["message_reactions"]["Row"]> & Pick<Database["public"]["Tables"]["message_reactions"]["Row"], "message_id" | "user_id" | "emoji">;
        Update: Partial<Database["public"]["Tables"]["message_reactions"]["Row"]>;
        Relationships: [];
      };
      community_events: {
        Row: { id:string;community_id:string;channel_id:string|null;title:string;description:string;starts_at:string;ends_at:string|null;created_by:string;cancelled_at:string|null;created_at:string;updated_at:string };
        Insert: Partial<Database["public"]["Tables"]["community_events"]["Row"]> & Pick<Database["public"]["Tables"]["community_events"]["Row"],"community_id"|"title"|"starts_at"|"created_by">;
        Update: Partial<Database["public"]["Tables"]["community_events"]["Row"]>;Relationships:[];
      };
      saved_messages: {
        Row: { id: string; user_id: string; message_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["saved_messages"]["Row"]> & Pick<Database["public"]["Tables"]["saved_messages"]["Row"], "user_id" | "message_id">;
        Update: Partial<Database["public"]["Tables"]["saved_messages"]["Row"]>; Relationships: [];
      };
      blocked_users: {
        Row: { id: string; blocker_id: string; blocked_user_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["blocked_users"]["Row"]> & Pick<Database["public"]["Tables"]["blocked_users"]["Row"], "blocker_id" | "blocked_user_id">;
        Update: Partial<Database["public"]["Tables"]["blocked_users"]["Row"]>; Relationships: [];
      };
      user_follows: {
        Row: { id: string; follower_id: string; followed_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["user_follows"]["Row"]> & Pick<Database["public"]["Tables"]["user_follows"]["Row"], "follower_id" | "followed_id">;
        Update: Partial<Database["public"]["Tables"]["user_follows"]["Row"]>; Relationships: [];
      };
      friend_requests: {
        Row: { id: string; sender_id: string; recipient_id: string; status: "pending" | "accepted" | "declined"; created_at: string; responded_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["friend_requests"]["Row"]> & Pick<Database["public"]["Tables"]["friend_requests"]["Row"], "sender_id" | "recipient_id">;
        Update: Partial<Database["public"]["Tables"]["friend_requests"]["Row"]>; Relationships: [];
      };
      friendships: {
        Row: { id: string; user_low_id: string; user_high_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["friendships"]["Row"]> & Pick<Database["public"]["Tables"]["friendships"]["Row"], "user_low_id" | "user_high_id">;
        Update: Partial<Database["public"]["Tables"]["friendships"]["Row"]>; Relationships: [];
      };
      direct_conversations: {
        Row: { id: string; type: "direct"; created_by: string; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["direct_conversations"]["Row"]> & Pick<Database["public"]["Tables"]["direct_conversations"]["Row"], "created_by">;
        Update: Partial<Database["public"]["Tables"]["direct_conversations"]["Row"]>;
        Relationships: [];
      };
      direct_conversation_members: {
        Row: { id: string; conversation_id: string; user_id: string; joined_at: string; last_read_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["direct_conversation_members"]["Row"]> & Pick<Database["public"]["Tables"]["direct_conversation_members"]["Row"], "conversation_id" | "user_id">;
        Update: Partial<Database["public"]["Tables"]["direct_conversation_members"]["Row"]>;
        Relationships: [];
      };
      direct_messages: {
        Row: { id: string; conversation_id: string; author_id: string; body: string; client_message_id: string | null; created_at: string; updated_at: string; edited_at: string | null; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["direct_messages"]["Row"]> & Pick<Database["public"]["Tables"]["direct_messages"]["Row"], "conversation_id" | "author_id" | "body">;
        Update: Partial<Database["public"]["Tables"]["direct_messages"]["Row"]>;
        Relationships: [];
      };
      direct_message_reactions: {
        Row: { id: string; message_id: string; user_id: string; emoji: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["direct_message_reactions"]["Row"]> & Pick<Database["public"]["Tables"]["direct_message_reactions"]["Row"], "message_id" | "user_id" | "emoji">;
        Update: Partial<Database["public"]["Tables"]["direct_message_reactions"]["Row"]>;
        Relationships: [];
      };
      direct_message_attachments: {
        Row: { id: string; message_id: string; uploader_id: string; storage_path: string; file_name: string; mime_type: string; size_bytes: number; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["direct_message_attachments"]["Row"]> & Pick<Database["public"]["Tables"]["direct_message_attachments"]["Row"], "message_id" | "uploader_id" | "storage_path" | "file_name" | "mime_type" | "size_bytes">;
        Update: Partial<Database["public"]["Tables"]["direct_message_attachments"]["Row"]>;
        Relationships: [];
      };
      read_states: {
        Row: {
          id: string;
          user_id: string;
          channel_id: string;
          last_read_message_id: string | null;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["read_states"]["Row"]> & Pick<Database["public"]["Tables"]["read_states"]["Row"], "user_id" | "channel_id">;
        Update: Partial<Database["public"]["Tables"]["read_states"]["Row"]>;
        Relationships: [];
      };
      community_invites: {
        Row: { id: string; community_id: string; code: string; created_by: string; max_uses: number | null; uses: number; expires_at: string | null; revoked_at: string | null; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["community_invites"]["Row"]> & Pick<Database["public"]["Tables"]["community_invites"]["Row"], "community_id" | "code" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_invites"]["Row"]>;
        Relationships: [];
      };
      app_admins: {
        Row: { user_id: string; granted_by: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      data_export_requests: {
        Row: { id: string; user_id: string; status: "requested" | "processing" | "ready" | "failed"; requested_at: string; completed_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["data_export_requests"]["Row"]> & Pick<Database["public"]["Tables"]["data_export_requests"]["Row"], "user_id">;
        Update: never;
        Relationships: [];
      };
      account_deletion_requests: {
        Row: { id: string; user_id: string; status: "requested" | "reviewing" | "canceled" | "completed"; requested_at: string; canceled_at: string | null; completed_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["account_deletion_requests"]["Row"]> & Pick<Database["public"]["Tables"]["account_deletion_requests"]["Row"], "user_id">;
        Update: Partial<Database["public"]["Tables"]["account_deletion_requests"]["Row"]>;
        Relationships: [];
      };
      threads: {
        Row: { id: string; community_id: string; channel_id: string; parent_message_id: string; name: string; created_by: string; created_at: string; archived_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["threads"]["Row"]> & Pick<Database["public"]["Tables"]["threads"]["Row"], "community_id" | "channel_id" | "parent_message_id" | "name" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["threads"]["Row"]>;
        Relationships: [];
      };
      forum_posts: {
        Row: { id: string; channel_id: string; title: string; author_id: string; tags: string[]; status: "open" | "resolved"; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["forum_posts"]["Row"]> & Pick<Database["public"]["Tables"]["forum_posts"]["Row"], "channel_id" | "title" | "author_id">;
        Update: Partial<Database["public"]["Tables"]["forum_posts"]["Row"]>;
        Relationships: [];
      };
      bots: {
        Row: { id: string; profile_id: string; owner_id: string; display_name: string; avatar_url: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      community_bots: {
        Row: { community_id: string; bot_id: string; role_id: string; installed_by: string; installed_at: string };
        Insert: Partial<Database["public"]["Tables"]["community_bots"]["Row"]> & Pick<Database["public"]["Tables"]["community_bots"]["Row"], "community_id" | "bot_id" | "role_id" | "installed_by">;
        Update: Partial<Database["public"]["Tables"]["community_bots"]["Row"]>;
        Relationships: [];
      };
      reports: {
        Row: { id: string; community_id: string | null; reporter_id: string; target_type: "message" | "user" | "community"; target_id: string; reason: "spam" | "harassment" | "unsafe_content" | "impersonation" | "other"; description: string; status: "open" | "reviewed" | "dismissed" | "action_taken"; reviewed_by: string | null; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["reports"]["Row"]> & Pick<Database["public"]["Tables"]["reports"]["Row"], "reporter_id" | "target_type" | "target_id" | "reason" | "description">;
        Update: Partial<Database["public"]["Tables"]["reports"]["Row"]>;
        Relationships: [];
      };
      audit_log: {
        Row: { id: string; community_id: string; actor_id: string; action_type: string; target_type: string; target_id: string | null; reason: string | null; created_at: string };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      webhooks: {
        Row: { id: string; community_id: string; channel_id: string; name: string; avatar_url: string | null; token_hash: string; created_by: string; revoked_at: string | null; created_at: string; updated_at: string };
        Insert: Partial<Database["public"]["Tables"]["webhooks"]["Row"]> & Pick<Database["public"]["Tables"]["webhooks"]["Row"], "community_id" | "channel_id" | "name" | "token_hash" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["webhooks"]["Row"]>;
        Relationships: [];
      };
      community_emojis: {
        Row: { id: string; community_id: string; name: string; image_url: string; created_by: string; created_at: string; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["community_emojis"]["Row"]> & Pick<Database["public"]["Tables"]["community_emojis"]["Row"], "community_id" | "name" | "image_url" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_emojis"]["Row"]>;
        Relationships: [];
      };
      community_stickers: {
        Row: { id: string; community_id: string; name: string; image_url: string; created_by: string; created_at: string; deleted_at: string | null };
        Insert: Partial<Database["public"]["Tables"]["community_stickers"]["Row"]> & Pick<Database["public"]["Tables"]["community_stickers"]["Row"], "community_id" | "name" | "image_url" | "created_by">;
        Update: Partial<Database["public"]["Tables"]["community_stickers"]["Row"]>;
        Relationships: [];
      };
      polls: {
        Row: { id: string; message_id: string; question: string; allow_multiple: boolean; closes_at: string | null; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["polls"]["Row"]> & Pick<Database["public"]["Tables"]["polls"]["Row"], "message_id" | "question">;
        Update: Partial<Database["public"]["Tables"]["polls"]["Row"]>;
        Relationships: [];
      };
      poll_options: {
        Row: { id: string; poll_id: string; text: string; position: number };
        Insert: Partial<Database["public"]["Tables"]["poll_options"]["Row"]> & Pick<Database["public"]["Tables"]["poll_options"]["Row"], "poll_id" | "text" | "position">;
        Update: Partial<Database["public"]["Tables"]["poll_options"]["Row"]>;
        Relationships: [];
      };
      poll_votes: {
        Row: { id: string; poll_id: string; option_id: string; user_id: string; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["poll_votes"]["Row"]> & Pick<Database["public"]["Tables"]["poll_votes"]["Row"], "poll_id" | "option_id" | "user_id">;
        Update: never;
        Relationships: [];
      };
    };
    Views: {
      message_attachments: {
        Row: Database["public"]["Tables"]["attachments"]["Row"];
        Relationships: [];
      };
    };
    Functions: {
      users_are_blocked: { Args: { first_user_id: string; second_user_id: string }; Returns: boolean };
      respond_friend_request: { Args: { target_request_id: string; accept_request: boolean }; Returns: boolean };
      remove_friend: { Args: { other_user_id: string }; Returns: boolean };
      create_direct_conversation: { Args: { other_user_id: string }; Returns: string };
      accept_community_invite: {
        Args: { invite_code: string };
        Returns: Array<{ id: string; community_id: string; user_id: string; role_id: string | null; joined_at: string }>;
      };
      append_community_audit_log: {
        Args: { target_community_id: string; event_action_type: string; event_target_type: string; event_target_id: string | null; event_reason: string | null };
        Returns: string;
      };
      is_app_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
