// Generated by `npm run supabase:types` when Supabase CLI is available.
// This lightweight placeholder keeps the app type-safe before local Supabase is started.
// Do not add secrets or server-only fields here.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          avatar_url: string | null;
          status: string;
          status_text: string;
          bio: string | null;
          accent_color: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & Pick<Database["public"]["Tables"]["profiles"]["Row"], "id" | "username" | "display_name">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]>;
        Relationships: [];
      };
      communities: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string | null;
          icon_url: string | null;
          accent_color: string;
          visibility: "public" | "private";
          public_read_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["communities"]["Row"]> & Pick<Database["public"]["Tables"]["communities"]["Row"], "owner_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["communities"]["Row"]>;
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          community_id: string;
          name: string;
          color: string;
          level: number;
          permissions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["roles"]["Row"]> & Pick<Database["public"]["Tables"]["roles"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["roles"]["Row"]>;
        Relationships: [];
      };
      community_members: {
        Row: {
          id: string;
          community_id: string;
          user_id: string;
          role_id: string | null;
          joined_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["community_members"]["Row"]> & Pick<Database["public"]["Tables"]["community_members"]["Row"], "community_id" | "user_id">;
        Update: Partial<Database["public"]["Tables"]["community_members"]["Row"]>;
        Relationships: [];
      };
      channel_categories: {
        Row: {
          id: string;
          community_id: string;
          name: string;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["channel_categories"]["Row"]> & Pick<Database["public"]["Tables"]["channel_categories"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["channel_categories"]["Row"]>;
        Relationships: [];
      };
      channels: {
        Row: {
          id: string;
          community_id: string;
          category_id: string | null;
          name: string;
          type: "text" | "voice";
          topic: string | null;
          is_private: boolean;
          public_read_enabled: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["channels"]["Row"]> & Pick<Database["public"]["Tables"]["channels"]["Row"], "community_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["channels"]["Row"]>;
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          community_id: string;
          channel_id: string;
          author_id: string;
          body: string;
          client_message_id: string | null;
          sequence: number | null;
          created_at: string;
          edited_at: string | null;
          deleted_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["messages"]["Row"]> & Pick<Database["public"]["Tables"]["messages"]["Row"], "community_id" | "channel_id" | "author_id">;
        Update: Partial<Database["public"]["Tables"]["messages"]["Row"]>;
        Relationships: [];
      };
      attachments: {
        Row: {
          id: string;
          message_id: string | null;
          uploader_id: string;
          storage_path: string;
          file_name: string;
          mime_type: string;
          size_bytes: number;
          attachment_type: "image";
          width: number | null;
          height: number | null;
          public_url: string | null;
          thumbnail_url: string | null;
          status: "pending" | "attached" | "failed";
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["attachments"]["Row"]> & Pick<Database["public"]["Tables"]["attachments"]["Row"], "uploader_id" | "storage_path" | "file_name" | "mime_type" | "size_bytes">;
        Update: Partial<Database["public"]["Tables"]["attachments"]["Row"]>;
        Relationships: [];
      };
      message_reactions: {
        Row: {
          id: string;
          message_id: string;
          user_id: string;
          emoji: string;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["message_reactions"]["Row"]> & Pick<Database["public"]["Tables"]["message_reactions"]["Row"], "message_id" | "user_id" | "emoji">;
        Update: Partial<Database["public"]["Tables"]["message_reactions"]["Row"]>;
        Relationships: [];
      };
      read_states: {
        Row: {
          id: string;
          user_id: string;
          channel_id: string;
          last_read_message_id: string | null;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["read_states"]["Row"]> & Pick<Database["public"]["Tables"]["read_states"]["Row"], "user_id" | "channel_id">;
        Update: Partial<Database["public"]["Tables"]["read_states"]["Row"]>;
        Relationships: [];
      };
    };
    Views: {
      message_attachments: {
        Row: Database["public"]["Tables"]["attachments"]["Row"];
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
