import type { FeedItem,FeedMediaSummary } from "../../types/feed";
import { AppIcon } from "../AppIcon";

function duration(seconds:number|undefined){if(!seconds)return null;const hours=Math.floor(seconds/3600);const minutes=Math.floor((seconds%3600)/60);return hours?`${hours}h ${minutes}m`:`${minutes} min`;}
export function FeedMediaGrid({items,onPreview}:{items:readonly FeedMediaSummary[];onPreview?:(media:FeedMediaSummary)=>void}){if(!items.length)return null;return <div className={`feed-v1-media feed-v1-media--${Math.min(items.length,4)}`}>{items.slice(0,4).map(media=>media.type==="video"?<video key={media.id} src={media.url} poster={media.thumbnailUrl} controls preload="metadata" aria-label={media.fileName??"Feed video"}/>:<button type="button" key={media.id} onClick={onPreview?()=>onPreview(media):undefined} disabled={!onPreview}><img src={media.thumbnailUrl??media.url} alt={media.fileName??"Feed attachment"}/></button>)}</div>;}
export function FeedTextBody({item,onPreview}:{item:FeedItem;onPreview?:(media:FeedMediaSummary)=>void}){return <><p className="feed-v1-copy">{item.bodyPreview}</p><FeedMediaGrid items={item.media} onPreview={onPreview}/></>;}
export function FeedRadioBody({item,onPlay}:{item:FeedItem;onPlay?:()=>void}){const meta=item.sourceMetadata.type==="radio_session"?item.sourceMetadata:null;return <div className="feed-v1-audio"><div className="feed-v1-audio__cover">{meta?.coverUrl?<img src={meta.coverUrl} alt=""/>:<AppIcon name="voice" size="xl"/>}<span className={`feed-v1-audio__state is-${meta?.status??"conversation"}`}>{meta?.status??"Radio chat"}</span></div><div><span className="feed-v1-eyebrow">RADIO</span><h3>{item.title??(meta?.status==="live"?"Live now":"Radio conversation")}</h3><p>{item.bodyPreview}</p><div className="feed-v1-audio__meta">{meta?<span><AppIcon name="users" size="xs"/>{meta.listenerCount} listeners</span>:null}{meta?.durationSeconds?<span>{duration(meta.durationSeconds)}</span>:null}</div>{onPlay?<button type="button" className="feed-v1-primary" onClick={onPlay}><AppIcon name="play" size="sm"/>{meta?.status==="live"?"Listen":"Open Radio"}</button>:null}</div></div>;}
export function FeedPodcastBody({item,onPlay}:{item:FeedItem;onPlay?:()=>void}){const meta=item.sourceMetadata.type==="podcast_episode"?item.sourceMetadata:null;return <div className="feed-v1-audio"><div className="feed-v1-audio__cover">{meta?.coverUrl?<img src={meta.coverUrl} alt=""/>:<AppIcon name="headphones" size="xl"/>}<span className="feed-v1-audio__state">Podcast</span></div><div><span className="feed-v1-eyebrow">PODCAST</span><h3>{item.title??"Episode conversation"}</h3><p>{item.bodyPreview}</p><div className="feed-v1-audio__meta">{meta?.durationSeconds?<span>{duration(meta.durationSeconds)}</span>:null}<span><AppIcon name="headphones" size="xs"/>{item.engagement.uniqueExternalViewers} plays</span></div>{onPlay?<button type="button" className="feed-v1-primary" onClick={onPlay}><AppIcon name="play" size="sm"/>{meta?"Play":"Open Episode"}</button>:null}</div></div>;}

