import { mockUpcomingEvents } from "../data/mockEvents";
import type { UpcomingEvent, UpcomingEventType } from "../types/events";
import { dataSourceService } from "./dataSourceService";
import { getSupabaseClient } from "./supabase/supabaseClient";
let mockEvents:UpcomingEvent[]=[...mockUpcomingEvents];
export type CreateCommunityEventInput=Readonly<{communityId:string;channelId?:string;title:string;description:string;startsAt:string;endsAt?:string;type:UpcomingEventType}>;
function map(row:{id:string;community_id:string;channel_id:string|null;title:string;description:string;starts_at:string;ends_at:string|null;created_by:string;cancelled_at:string|null;created_at:string;updated_at:string}):UpcomingEvent{return{id:row.id,communityId:row.community_id,channelId:row.channel_id??undefined,title:row.title,description:row.description,startsAt:row.starts_at,endsAt:row.ends_at??undefined,createdBy:row.created_by,cancelledAt:row.cancelled_at??undefined,createdAt:row.created_at,updatedAt:row.updated_at,type:"meeting"}}
export const communityEventService={
 async listEvents(communityId?:string):Promise<UpcomingEvent[]>{if(dataSourceService.getStatus().isMock)return mockEvents.filter((event)=>!communityId||event.communityId===communityId);const client=getSupabaseClient();if(!client)return[];let query=client.from("community_events").select("id,community_id,channel_id,title,description,starts_at,ends_at,created_by,cancelled_at,created_at,updated_at").is("cancelled_at",null).order("starts_at");if(communityId)query=query.eq("community_id",communityId);const {data}=await query;return(data??[]).map(map)},
 async createEvent(input:CreateCommunityEventInput):Promise<UpcomingEvent|null>{if(!input.title.trim()||!input.startsAt)return null;if(dataSourceService.getStatus().isMock){const now=new Date().toISOString();const event:UpcomingEvent={id:`event-${Date.now()}`,communityId:input.communityId,channelId:input.channelId,title:input.title.trim(),description:input.description.trim(),startsAt:input.startsAt,endsAt:input.endsAt,type:input.type,attendeeCount:1,createdBy:"mock-current-user",createdAt:now,updatedAt:now};mockEvents=[event,...mockEvents];return event}const client=getSupabaseClient();if(!client)return null;const {data:user}=await client.auth.getUser();if(!user.user)return null;const {data}=await client.from("community_events").insert({community_id:input.communityId,channel_id:input.channelId??null,title:input.title.trim(),description:input.description.trim(),starts_at:input.startsAt,ends_at:input.endsAt??null,created_by:user.user.id}).select().single();return data?map(data):null},
 async cancelEvent(eventId:string):Promise<boolean>{if(dataSourceService.getStatus().isMock){const now=new Date().toISOString();mockEvents=mockEvents.map((event)=>event.id===eventId?{...event,cancelledAt:now,updatedAt:now}:event);return true}const client=getSupabaseClient();if(!client)return false;const now=new Date().toISOString();const {error}=await client.from("community_events").update({cancelled_at:now,updated_at:now}).eq("id",eventId);return !error}
};
