import type { CreatePollDraft, PollData } from "../types/polls";
import { dataSourceService } from "./dataSourceService";
import { getSupabaseClient } from "./supabase/supabaseClient";
type Result<T> = { ok: true; data: T } | { ok: false; message: string };
export const pollService = {
  async create(input: CreatePollDraft & { messageId: string }): Promise<Result<PollData>> {
    const question = input.question.trim().slice(0, 240); const options = input.options.map((item) => item.trim().slice(0, 100)).filter(Boolean).slice(0, 10); if (!question || options.length < 2) return { ok: false, message: "A poll needs a question and at least two options." }; const createdAt = new Date().toISOString();
    if (dataSourceService.getStatus().isMock) { const id = `poll-${crypto.randomUUID()}`; return { ok: true, data: { id, messageId: input.messageId, question, allowMultiple: input.allowMultiple, closesAt: input.closesAt, createdAt, options: options.map((text, position) => ({ id: `${id}-option-${position}`, text, position, voteCount: 0 })) } }; }
    const client = getSupabaseClient(); if (!client) return { ok: false, message: "Poll creation is unavailable." }; const { data: poll, error } = await client.from("polls").insert({ message_id: input.messageId, question, allow_multiple: input.allowMultiple, closes_at: input.closesAt ?? null }).select("id,message_id,question,allow_multiple,closes_at,created_at").single(); if (error || !poll) return { ok: false, message: "Picom could not create this poll." }; const rows = options.map((text, position) => ({ poll_id: poll.id, text, position })); const { data: optionRows, error: optionError } = await client.from("poll_options").insert(rows).select("id,poll_id,text,position"); if (optionError || !optionRows) return { ok: false, message: "Picom could not create poll options." }; return { ok: true, data: { id: poll.id, messageId: poll.message_id, question: poll.question, allowMultiple: poll.allow_multiple, closesAt: poll.closes_at ?? undefined, createdAt: poll.created_at, options: optionRows.map((item) => ({ id: item.id, text: item.text, position: item.position, voteCount: 0 })) } };
  },
  async toggleVote(poll: PollData, optionId: string, userId: string): Promise<Result<PollData>> {
    const option = poll.options.find((item) => item.id === optionId); if (!option) return { ok: false, message: "Poll option not found." }; if (poll.closesAt && Date.parse(poll.closesAt) <= Date.now()) return { ok: false, message: "This poll is closed." };
    const nextOptions = poll.options.map((item) => { if (item.id === optionId) return { ...item, votedByCurrentUser: !item.votedByCurrentUser, voteCount: Math.max(0, item.voteCount + (item.votedByCurrentUser ? -1 : 1)) }; if (!poll.allowMultiple && item.votedByCurrentUser) return { ...item, votedByCurrentUser: false, voteCount: Math.max(0, item.voteCount - 1) }; return item; });
    if (dataSourceService.getStatus().isMock) return { ok: true, data: { ...poll, options: nextOptions } };
    const client = getSupabaseClient(); if (!client) return { ok: false, message: "Voting is unavailable." }; if (!poll.allowMultiple) await client.from("poll_votes").delete().eq("poll_id", poll.id).eq("user_id", userId); const wasVoted = Boolean(option.votedByCurrentUser); const result = wasVoted ? await client.from("poll_votes").delete().eq("poll_id", poll.id).eq("option_id", optionId).eq("user_id", userId) : await client.from("poll_votes").insert({ poll_id: poll.id, option_id: optionId, user_id: userId }); if (result.error) return { ok: false, message: "Picom could not update your vote." }; return { ok: true, data: { ...poll, options: nextOptions } };
  },
};
