import { currentUserId } from "../data/mockCommunities";
import type { VerificationBadge, VerificationBadgeKind, VerificationSubjectType } from "../types/verification";
import { dataSourceService } from "./dataSourceService";
import { getSupabaseClient } from "./supabase/supabaseClient";

type Result<T> = Promise<{ ok: true; data: T } | { ok: false; message: string }>;
const STORAGE_KEY="picom.verificationBadges.mock.v1";
const seed:VerificationBadge={id:"mock-profile-reviewed",subjectType:"user",subjectId:currentUserId,kind:"profile_reviewed",label:"Profile reviewed",scopeNote:"Picom staff reviewed profile ownership signals. This is not a legal identity or trust guarantee.",grantedAt:"2026-07-10T09:00:00.000Z",revokedAt:null};
function readMock():VerificationBadge[]{try{const raw=window.localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw) as VerificationBadge[]:[seed];}catch{return [seed];}}
function writeMock(items:VerificationBadge[]):void{try{window.localStorage.setItem(STORAGE_KEY,JSON.stringify(items));}catch{/* restricted fallback */}}
function mapRow(row:{id:string;subject_type:string;subject_id:string;badge_kind:string;label:string;scope_note:string;granted_at:string;revoked_at?:string|null}):VerificationBadge{return{id:row.id,subjectType:row.subject_type as VerificationSubjectType,subjectId:row.subject_id,kind:row.badge_kind as VerificationBadgeKind,label:row.label,scopeNote:row.scope_note,grantedAt:row.granted_at,revokedAt:row.revoked_at??null};}

export const profileVerificationService={
  async listForSubject(subjectType:VerificationSubjectType,subjectId:string):Result<VerificationBadge[]>{if(dataSourceService.getStatus().isMock)return{ok:true,data:readMock().filter((item)=>item.subjectType===subjectType&&item.subjectId===subjectId&&!item.revokedAt)};const client=getSupabaseClient();if(!client)return{ok:false,message:"Verification markers are unavailable."};const{data,error}=await client.rpc("list_active_verification_badges",{target_subject_type:subjectType,target_subject_id:subjectId});return error?{ok:false,message:"Picom could not load verification markers."}:{ok:true,data:(data??[]).map(mapRow)};},
  async listAdminRecent():Result<VerificationBadge[]>{if(dataSourceService.getStatus().isMock)return{ok:true,data:readMock()};const client=getSupabaseClient();if(!client)return{ok:false,message:"Verification administration is unavailable."};const{data,error}=await client.rpc("list_recent_verification_badges",{result_limit:100});return error?{ok:false,message:"Picom could not load verification administration."}:{ok:true,data:(data??[]).map(mapRow)};},
  async grant(input:{subjectType:VerificationSubjectType;subjectId:string;kind:VerificationBadgeKind;label:string;scopeNote:string;reason:string}):Result<VerificationBadge>{if(dataSourceService.getStatus().isMock){const badge:VerificationBadge={id:crypto.randomUUID(),subjectType:input.subjectType,subjectId:input.subjectId,kind:input.kind,label:input.label.trim(),scopeNote:input.scopeNote.trim(),grantedAt:new Date().toISOString(),revokedAt:null};writeMock([...readMock().filter((item)=>!(item.subjectType===input.subjectType&&item.subjectId===input.subjectId&&item.kind===input.kind&&!item.revokedAt)),badge]);return{ok:true,data:badge};}const client=getSupabaseClient();if(!client)return{ok:false,message:"Verification administration is unavailable."};const{data,error}=await client.rpc("grant_verification_badge",{target_subject_type:input.subjectType,target_subject_id:input.subjectId,target_badge_kind:input.kind,target_label:input.label,target_scope_note:input.scopeNote,grant_reason:input.reason});const row=data?.[0];return error||!row?{ok:false,message:"Picom could not grant this marker."}:{ok:true,data:mapRow(row)};},
  async revoke(badgeId:string,reason:string):Result<boolean>{if(dataSourceService.getStatus().isMock){writeMock(readMock().map((item)=>item.id===badgeId?{...item,revokedAt:new Date().toISOString()}:item));return{ok:true,data:true};}const client=getSupabaseClient();if(!client)return{ok:false,message:"Verification administration is unavailable."};const{data,error}=await client.rpc("revoke_verification_badge",{target_badge_id:badgeId,revoke_reason:reason});return error?{ok:false,message:"Picom could not revoke this marker."}:{ok:true,data};},
};
