import type { ThreadMessage, ThreadRecord } from "../types/threads";
import { dataSourceService } from "./dataSourceService";
import { getSupabaseClient } from "./supabase/supabaseClient";
type Result<T> = { ok: true; data: T } | { ok: false; message: string };
type LocalStore = { threads: ThreadRecord[]; messages: ThreadMessage[] };
const STORAGE_KEY = "picom.threads.v1";
function readLocal(): LocalStore { try { const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "{}") as Partial<LocalStore>; return { threads: Array.isArray(parsed.threads) ? parsed.threads : [], messages: Array.isArray(parsed.messages) ? parsed.messages : [] }; } catch { return { threads: [], messages: [] }; } }
function writeLocal(store: LocalStore): void { try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); } catch { /* restricted fallback */ } }
export const threadService = {
  async openOrCreate(input: { communityId: string; channelId: string; parentMessageId: string; name: string; createdBy: string; canCreate: boolean }): Promise<Result<ThreadRecord>> {
    if (dataSourceService.getStatus().isMock) { const store = readLocal(); const existing = store.threads.find((item) => item.parentMessageId === input.parentMessageId); if (existing) return { ok: true, data: existing }; if (!input.canCreate) return { ok: false, message: "You can view existing threads but cannot start one in this channel." }; const thread: ThreadRecord = { id: `thread-${crypto.randomUUID()}`, communityId: input.communityId, channelId: input.channelId, parentMessageId: input.parentMessageId, name: input.name.trim().slice(0, 100) || "Message thread", createdBy: input.createdBy, createdAt: new Date().toISOString() }; writeLocal({ ...store, threads: [...store.threads, thread] }); return { ok: true, data: thread }; }
    const client = getSupabaseClient(); if (!client) return { ok: false, message: "Threads are unavailable." }; const { data: existing } = await client.from("threads").select("id,community_id,channel_id,parent_message_id,name,created_by,created_at,archived_at").eq("parent_message_id", input.parentMessageId).maybeSingle(); if (existing) return { ok: true, data: { id: existing.id, communityId: existing.community_id, channelId: existing.channel_id, parentMessageId: existing.parent_message_id, name: existing.name, createdBy: existing.created_by, createdAt: existing.created_at, archivedAt: existing.archived_at ?? undefined } }; if (!input.canCreate) return { ok: false, message: "You do not have permission to start a thread." }; const { data, error } = await client.from("threads").insert({ community_id: input.communityId, channel_id: input.channelId, parent_message_id: input.parentMessageId, name: input.name.trim().slice(0, 100) || "Message thread", created_by: input.createdBy }).select("id,community_id,channel_id,parent_message_id,name,created_by,created_at,archived_at").single(); return error || !data ? { ok: false, message: "Picom could not start this thread." } : { ok: true, data: { id: data.id, communityId: data.community_id, channelId: data.channel_id, parentMessageId: data.parent_message_id, name: data.name, createdBy: data.created_by, createdAt: data.created_at, archivedAt: data.archived_at ?? undefined } };
  },
  async listMessages(threadId: string): Promise<Result<ThreadMessage[]>> { if (dataSourceService.getStatus().isMock) return { ok: true, data: readLocal().messages.filter((item) => item.threadId === threadId) }; const client = getSupabaseClient(); if (!client) return { ok: false, message: "Thread messages are unavailable." }; const { data, error } = await client.from("messages").select("id,thread_id,author_id,body,created_at").eq("thread_id", threadId).order("created_at"); return error ? { ok: false, message: "Picom could not load thread messages." } : { ok: true, data: (data ?? []).map((item) => ({ id: item.id, threadId: item.thread_id ?? threadId, authorId: item.author_id, body: item.body, createdAt: item.created_at })) }; },
  async sendMessage(input: { thread: ThreadRecord; authorId: string; body: string; canSend: boolean }): Promise<Result<ThreadMessage>> { const body = input.body.trim().slice(0, 4000); if (!input.canSend) return { ok: false, message: "You do not have permission to reply in this thread." }; if (!body) return { ok: false, message: "Thread reply cannot be empty." }; if (dataSourceService.getStatus().isMock) { const store = readLocal(); const message: ThreadMessage = { id: `thread-message-${crypto.randomUUID()}`, threadId: input.thread.id, authorId: input.authorId, body, createdAt: new Date().toISOString() }; writeLocal({ ...store, messages: [...store.messages, message] }); return { ok: true, data: message }; } const client = getSupabaseClient(); if (!client) return { ok: false, message: "Thread replies are unavailable." }; const { data, error } = await client.from("messages").insert({ community_id: input.thread.communityId, channel_id: input.thread.channelId, thread_id: input.thread.id, author_id: input.authorId, body }).select("id,thread_id,author_id,body,created_at").single(); return error || !data ? { ok: false, message: "Picom could not send this thread reply." } : { ok: true, data: { id: data.id, threadId: data.thread_id ?? input.thread.id, authorId: data.author_id, body: data.body, createdAt: data.created_at } };
  },
};
