import { currentUserId } from "../data/mockCommunities";
import { dataSourceService } from "./dataSourceService";
import { getSupabaseClient } from "./supabase/supabaseClient";
import { registerRuntimeVerification, verificationVariantFromKind } from "../utils/verificationHelpers";
import type { VerificationBadgeKind } from "../types/verification";

export type VerificationRequestStatus = "pending" | "approved" | "rejected" | "revoked";
export type VerificationRequestTarget = "profile" | "community";
export type VerificationRequestRecord = Readonly<{ id: string; targetType: VerificationRequestTarget; targetId: string; targetName: string; type: VerificationBadgeKind; status: VerificationRequestStatus; category: string; reason?: string; officialLinks: readonly string[]; supportingText?: string; requestedAt: string; reviewedAt?: string; decisionReason?: string }>;
export type VerificationRequestInput = Readonly<{ category: string; reason: string; officialLinks: readonly string[]; supportingText?: string }>;
type Result<T> = Promise<{ ok: true; data: T } | { ok: false; message: string }>;
type RpcResult = { data: unknown; error: { message: string } | null };
const STORAGE_KEY = "picom.verificationRequests.mock.v1";

function readMock(): VerificationRequestRecord[] { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) as VerificationRequestRecord[] : []; } catch { return []; } }
function writeMock(records: VerificationRequestRecord[]): void { if (typeof window === "undefined") return; try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(records)); } catch { /* restricted fallback */ } }
function asRecord(value: unknown): VerificationRequestRecord | null { if (!value || typeof value !== "object") return null; const row = value as Record<string, unknown>; if (typeof row.id !== "string" || (row.targetType !== "profile" && row.targetType !== "community") || typeof row.targetId !== "string" || typeof row.type !== "string" || typeof row.status !== "string") return null; return { id: row.id, targetType: row.targetType, targetId: row.targetId, targetName: typeof row.targetName === "string" ? row.targetName : "Verification request", type: row.type as VerificationBadgeKind, status: row.status as VerificationRequestStatus, category: typeof row.category === "string" ? row.category : "other", reason: typeof row.reason === "string" ? row.reason : undefined, officialLinks: Array.isArray(row.officialLinks) ? row.officialLinks.filter((link): link is string => typeof link === "string") : [], supportingText: typeof row.supportingText === "string" ? row.supportingText : undefined, requestedAt: typeof row.requestedAt === "string" ? row.requestedAt : new Date().toISOString(), reviewedAt: typeof row.reviewedAt === "string" ? row.reviewedAt : undefined, decisionReason: typeof row.decisionReason === "string" ? row.decisionReason : undefined }; }
function syncBadge(record: VerificationRequestRecord): void { const variant = verificationVariantFromKind(record.type); if (!variant) return; if (record.status === "approved") registerRuntimeVerification(record.targetType, record.targetId, variant); else if (record.status === "revoked") registerRuntimeVerification(record.targetType, record.targetId, null); }
async function rpc(name: string, args: Record<string, unknown>): Promise<RpcResult> { const client = getSupabaseClient(); if (!client) return { data: null, error: { message: "Verification service is unavailable." } }; const call = client.rpc as unknown as (rpcName: string, rpcArgs: Record<string, unknown>) => Promise<RpcResult>; return call(name, args); }
function validate(input: VerificationRequestInput): string | null { if (input.reason.trim().length < 20) return "Explain the verification request in at least 20 characters."; if (input.supportingText && input.supportingText.length > 2000) return "Supporting text is too long."; if (input.officialLinks.length > 5 || input.officialLinks.some((link) => !/^https:\/\/\S+$/i.test(link))) return "Use up to five HTTPS official links."; return null; }

export const verificationRequestService = {
  async getOwnProfileRequests(): Result<VerificationRequestRecord[]> { if (dataSourceService.getStatus().isMock) { const records = readMock().filter((item) => item.targetType === "profile" && item.targetId === currentUserId); records.forEach(syncBadge); return { ok: true, data: records }; } const result = await rpc("get_own_profile_verification_requests", {}); if (result.error) return { ok: false, message: "Verification status could not be loaded." }; const records = (Array.isArray(result.data) ? result.data : []).map(asRecord).filter((item): item is VerificationRequestRecord => Boolean(item)); records.forEach(syncBadge); return { ok: true, data: records }; },
  async getCommunityRequests(communityId: string): Result<VerificationRequestRecord[]> { if (dataSourceService.getStatus().isMock) { const records = readMock().filter((item) => item.targetType === "community" && item.targetId === communityId); records.forEach(syncBadge); return { ok: true, data: records }; } const result = await rpc("get_community_verification_requests", { target_community_id: communityId }); if (result.error) return { ok: false, message: "Community verification status could not be loaded." }; const records = (Array.isArray(result.data) ? result.data : []).map(asRecord).filter((item): item is VerificationRequestRecord => Boolean(item)); records.forEach(syncBadge); return { ok: true, data: records }; },
  async requestProfile(input: VerificationRequestInput): Result<VerificationRequestRecord> { const invalid = validate(input); if (invalid) return { ok: false, message: invalid }; if (dataSourceService.getStatus().isMock) { const existing = readMock(); if (existing.some((item) => item.targetType === "profile" && item.targetId === currentUserId && ["pending", "approved"].includes(item.status))) return { ok: false, message: "An active profile verification request already exists." }; const record: VerificationRequestRecord = { id: crypto.randomUUID(), targetType: "profile", targetId: currentUserId, targetName: "Your profile", type: input.category === "creator" ? "creator_verified" : "verified_user", status: "pending", category: input.category, reason: input.reason.trim(), officialLinks: input.officialLinks, supportingText: input.supportingText?.trim(), requestedAt: new Date().toISOString() }; writeMock([record, ...existing]); return { ok: true, data: record }; } const result = await rpc("request_profile_verification", { request_type: input.category === "creator" ? "creator_verified" : "verified_user", request_category: input.category, request_reason: input.reason, request_links: input.officialLinks, request_supporting_text: input.supportingText ?? null }); const record = asRecord(result.data); return result.error || !record ? { ok: false, message: "Profile verification request could not be submitted." } : { ok: true, data: record }; },
  async requestCommunity(communityId: string, communityName: string, input: VerificationRequestInput): Result<VerificationRequestRecord> { const invalid = validate(input); if (invalid) return { ok: false, message: invalid }; if (dataSourceService.getStatus().isMock) { const existing = readMock(); if (existing.some((item) => item.targetType === "community" && item.targetId === communityId && ["pending", "approved"].includes(item.status))) return { ok: false, message: "An active community verification request already exists." }; const record: VerificationRequestRecord = { id: crypto.randomUUID(), targetType: "community", targetId: communityId, targetName: communityName, type: "official_community", status: "pending", category: input.category, reason: input.reason.trim(), officialLinks: input.officialLinks, supportingText: input.supportingText?.trim(), requestedAt: new Date().toISOString() }; writeMock([record, ...existing]); return { ok: true, data: record }; } const result = await rpc("request_community_verification", { target_community_id: communityId, request_category: input.category, request_reason: input.reason, request_links: input.officialLinks, request_supporting_text: input.supportingText ?? null }); const record = asRecord(result.data); return result.error || !record ? { ok: false, message: "Community verification request could not be submitted." } : { ok: true, data: record }; },
  async listReviewQueue(): Result<VerificationRequestRecord[]> { if (dataSourceService.getStatus().isMock) return { ok: true, data: readMock() }; const result = await rpc("list_verification_review_requests", { request_status: null }); if (result.error) return { ok: false, message: "Verification review queue is unavailable." }; return { ok: true, data: (Array.isArray(result.data) ? result.data : []).map(asRecord).filter((item): item is VerificationRequestRecord => Boolean(item)) }; },
  async review(request: VerificationRequestRecord, nextStatus: "approved" | "rejected" | "revoked", reason: string): Result<VerificationRequestRecord> { if (reason.trim().length < 10) return { ok: false, message: "A review reason of at least 10 characters is required." }; if (dataSourceService.getStatus().isMock) { let updated: VerificationRequestRecord | null = null; const records = readMock().map((item) => item.id === request.id ? (updated = { ...item, status: nextStatus, reviewedAt: new Date().toISOString(), decisionReason: reason.trim() }) : item); if (!updated) return { ok: false, message: "Verification request was not found." }; writeMock(records); syncBadge(updated); return { ok: true, data: updated }; } const result = await rpc("review_verification_request", { target_type: request.targetType, target_request_id: request.id, next_status: nextStatus, review_reason: reason }); const record = asRecord(result.data); if (result.error || !record) return { ok: false, message: "Verification review could not be completed." }; syncBadge(record); return { ok: true, data: record }; },
};
