import { useEffect, useMemo, useState } from "react";
import type { MouseEvent } from "react";
import { useAudioPlayer } from "../../hooks/useAudioPlayer";
import { podcastService } from "../../services/audio/podcastService";
import { dateTimeService } from "../../services/dateTimeService";
import type { AudioPlayableItem, PodcastEpisode } from "../../types/audio";
import type { Member } from "../../types/community";
import type { ReportModalTarget } from "../ReportModal";
import { AppIcon } from "../AppIcon";
import { MemberAvatar } from "../MemberAvatar";
import { AudioMiniPlayer } from "./AudioMiniPlayer";
import { formatAudioTime } from "./AudioProgressBar";

type PodcastEpisodeDetailProps = { episode: PodcastEpisode; communityName: string; author?: Member; relatedEpisodes: PodcastEpisode[]; getCommentAuthorLabel: (authorId: string) => string; onClose: () => void; onOpenCommunity: () => void; onOpenAuthor?: (event: MouseEvent<HTMLButtonElement>, author: Member) => void; onSelectEpisode: (episode: PodcastEpisode) => void; onReport?: (target: ReportModalTarget) => void };
type ListenerState = "loading" | "unplayed" | "in_progress" | "listened";
const reactionChoices = ["👍", "🔥", "💡", "👏"] as const;

function playableEpisode(episode: PodcastEpisode, communityName: string): AudioPlayableItem { return { id: episode.id, type: "podcast_episode", title: episode.title, contextLabel: `${communityName} / Podcast`, coverUrl: episode.coverUrl, audioUrl: episode.audioUrl, durationSeconds: episode.durationSeconds, communityId: episode.communityId }; }

export function PodcastEpisodeHeader({ episode, communityName, author, listenerState, busy, onToggleSaved, onToggleListened, onOpenCommunity, onOpenAuthor, onClose, onNotice, onReport }: { episode: PodcastEpisode; communityName: string; author?: Member; listenerState: ListenerState; busy: boolean; onToggleSaved: () => void; onToggleListened: () => void; onOpenCommunity: () => void; onOpenAuthor?: (event: MouseEvent<HTMLButtonElement>, author: Member) => void; onClose: () => void; onNotice: (message: string) => void; onReport?: () => void }) {
  return <header className="podcast-episode-header"><div className="podcast-episode-cover" aria-hidden="true">{episode.coverUrl ? <img src={episode.coverUrl} alt="" /> : <AppIcon name="headphones" size="xl" />}</div><div className="podcast-episode-title"><span className="podcast-episode-kind">PODCAST EPISODE</span><h1>{episode.title}</h1><button type="button" className="podcast-author-link" disabled={!author || !onOpenAuthor} onClick={(event) => author && onOpenAuthor?.(event, author)}>{author ? <MemberAvatar member={author} size={30} /> : null}<span><strong>{author?.displayName ?? "Picom creator"}</strong><small>{communityName}</small></span></button><div className="podcast-episode-meta"><span>{formatAudioTime(episode.durationSeconds)}</span><span>{dateTimeService.formatCompactDateTime(episode.publishedAt)}</span><span>{episode.listenerCount} listeners</span><span className={`podcast-listener-state ${listenerState}`}>{listenerState === "loading" ? "Checking progress" : listenerState === "listened" ? "Listened" : listenerState === "in_progress" ? "In progress" : "Not played"}</span></div><div className="podcast-episode-header-actions"><button type="button" className={`secondary-button compact ${episode.isSavedByCurrentUser ? "active" : ""}`} disabled={busy || episode.status !== "published"} onClick={onToggleSaved}><AppIcon name="pin" size="sm" />{episode.isSavedByCurrentUser ? "Saved" : "Save"}</button><button type="button" className={`secondary-button compact ${listenerState === "listened" ? "active" : ""}`} disabled={busy || listenerState === "loading" || episode.status !== "published"} onClick={onToggleListened}><AppIcon name={listenerState === "listened" ? "close" : "play"} size="sm" />{listenerState === "listened" ? "Mark unplayed" : "Mark listened"}</button><button type="button" className="secondary-button compact" onClick={() => onNotice("Sharing remains limited to authorized Podcast community routing.")}><AppIcon name="more" size="sm" />Share</button><button type="button" className="secondary-button compact" onClick={onOpenCommunity}><AppIcon name="hash" size="sm" />Open community</button>{onReport ? <button type="button" className="secondary-button compact" onClick={onReport}><AppIcon name="bell" size="sm" />Report</button> : null}</div></div><button type="button" className="icon-button podcast-detail-close" aria-label="Close podcast detail" onClick={onClose}><AppIcon name="close" size="md" /></button></header>;
}

export function PodcastEpisodePlayer({ episode, communityName }: { episode: PodcastEpisode; communityName: string }) { const [playerVisible, setPlayerVisible] = useState(true); const item = useMemo(() => playableEpisode(episode, communityName), [communityName, episode]); return <section className="podcast-episode-player" aria-label="Podcast episode player">{playerVisible ? <AudioMiniPlayer item={item} onClose={() => setPlayerVisible(false)} /> : <button type="button" className="primary-button" onClick={() => setPlayerVisible(true)}><AppIcon name="play" size="sm" />Open player</button>}<small>Playback starts only after you press Play.</small></section>; }

export function PodcastEpisodeDescription({ episode, busy, onToggleReaction }: { episode: PodcastEpisode; busy: boolean; onToggleReaction: (emoji: string, active: boolean) => void }) {
  const reactions = new Map(episode.reactionSummary.map((reaction) => [reaction.emoji, reaction]));
  const emojis = [...new Set([...reactionChoices, ...episode.reactionSummary.map((reaction) => reaction.emoji)])];
  return <section className="podcast-detail-section podcast-episode-description"><header><span>ABOUT THIS EPISODE</span><h2>Episode notes</h2></header><p>{episode.description}</p><div>{episode.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><footer className="podcast-reaction-actions" aria-label="Podcast reactions">{emojis.map((emoji) => { const reaction = reactions.get(emoji); const active = reaction?.reactedByCurrentUser === true; return <button type="button" key={emoji} className={active ? "active" : ""} aria-pressed={active} aria-label={`${active ? "Remove" : "Add"} ${emoji} reaction`} disabled={busy || episode.status !== "published"} onClick={() => onToggleReaction(emoji, active)}><span aria-hidden="true">{emoji}</span>{reaction?.count ? <strong>{reaction.count}</strong> : null}</button>; })}</footer></section>;
}

export function PodcastEpisodeCommentsPreview({ episode, getAuthorLabel, onNotice, onReport }: { episode: PodcastEpisode; getAuthorLabel: (authorId: string) => string; onNotice: (message: string) => void; onReport?: (commentId: string, label: string) => void }) {
  const [draft, setDraft] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [editBody, setEditBody] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { setDraft(""); setEditingId(null); setEditBody(""); }, [episode.id]);
  const create = async () => { if (!draft.trim() || busy) return; setBusy(true); const result = await podcastService.commentOnPodcastEpisode(episode.id, draft); setBusy(false); if (!result.ok) { onNotice(result.error.message); return; } setDraft(""); onNotice("Comment added."); };
  const saveEdit = async () => { if (!editingId || !editBody.trim() || busy) return; setBusy(true); const result = await podcastService.editPodcastComment(episode.id, editingId, editBody); setBusy(false); if (!result.ok) { onNotice(result.error.message); return; } setEditingId(null); setEditBody(""); onNotice("Comment updated."); };
  const remove = async (commentId: string) => { if (busy || !window.confirm("Delete your Podcast comment?")) return; setBusy(true); const result = await podcastService.deletePodcastComment(episode.id, commentId); setBusy(false); onNotice(result.ok ? "Comment deleted." : result.error.message); };
  return <section className="podcast-detail-section podcast-comments-preview"><header><span>COMMUNITY REPLIES</span><h2>{episode.commentCount} comments</h2></header>{episode.status === "published" ? <form className="podcast-comment-form" onSubmit={(event) => { event.preventDefault(); void create(); }}><label htmlFor={`podcast-comment-${episode.id}`}>Add a comment</label><div><textarea id={`podcast-comment-${episode.id}`} value={draft} maxLength={4000} rows={2} disabled={busy} placeholder="Share a relevant response with this Podcast community" onChange={(event) => setDraft(event.target.value)} /><button type="submit" className="primary-button" disabled={busy || !draft.trim()}><AppIcon name="send" size="sm" />Post</button></div><small>{draft.length}/4000</small></form> : <p className="podcast-interaction-locked">Archived episodes are read-only.</p>}{episode.commentPreview.length ? <div>{episode.commentPreview.map((comment) => <blockquote key={comment.id}>{editingId === comment.id ? <div className="podcast-comment-editor"><label htmlFor={`podcast-edit-${comment.id}`}>Edit comment</label><textarea id={`podcast-edit-${comment.id}`} rows={2} maxLength={4000} value={editBody} disabled={busy} onChange={(event) => setEditBody(event.target.value)} /><span><button type="button" disabled={busy || !editBody.trim()} onClick={() => void saveEdit()}><AppIcon name="edit" size="xs" />Save</button><button type="button" disabled={busy} onClick={() => { setEditingId(null); setEditBody(""); }}>Cancel</button></span></div> : <><strong>{getAuthorLabel(comment.authorId)}</strong><p>{comment.body}</p><footer><small>{dateTimeService.formatCompactDateTime(comment.createdAt)}{comment.updatedAt && comment.updatedAt !== comment.createdAt ? " · edited" : ""}</small><span>{comment.isOwn ? <><button type="button" disabled={busy || episode.status !== "published"} aria-label="Edit your Podcast comment" onClick={() => { setEditingId(comment.id); setEditBody(comment.body); }}><AppIcon name="edit" size="xs" />Edit</button><button type="button" disabled={busy} aria-label="Delete your Podcast comment" onClick={() => void remove(comment.id)}><AppIcon name="trash" size="xs" />Delete</button></> : null}{!comment.isOwn && onReport ? <button type="button" disabled={busy} aria-label="Report Podcast comment" onClick={() => onReport(comment.id, `${getAuthorLabel(comment.authorId)}: ${comment.body.slice(0, 90)}`)}><AppIcon name="bell" size="xs" />Report</button> : null}</span></footer></>}</blockquote>)}</div> : <div className="podcast-detail-empty">No comments are visible yet.</div>}{episode.commentCount > episode.commentPreview.length ? <small>{episode.commentCount - episode.commentPreview.length} additional comments remain in the authorized community thread.</small> : null}</section>;
}

export function PodcastRelatedEpisodes({ episodes, onSelectEpisode }: { episodes: PodcastEpisode[]; onSelectEpisode: (episode: PodcastEpisode) => void }) { return <section className="podcast-detail-section podcast-related-episodes"><header><span>KEEP LISTENING</span><h2>Related episodes</h2></header>{episodes.length ? <div>{episodes.slice(0, 4).map((episode) => <button type="button" key={episode.id} onClick={() => onSelectEpisode(episode)}><span className="podcast-related-cover">{episode.coverUrl ? <img src={episode.coverUrl} alt="" /> : <AppIcon name="headphones" size="sm" />}</span><span><strong>{episode.title}</strong><small>{formatAudioTime(episode.durationSeconds)} · {episode.listenerCount} listeners</small></span><AppIcon name="chevronRight" size="sm" /></button>)}</div> : <div className="podcast-detail-empty">No related episodes are available.</div>}</section>; }

export function PodcastEpisodeDetail({ episode, communityName, author, relatedEpisodes, getCommentAuthorLabel, onClose, onOpenCommunity, onOpenAuthor, onSelectEpisode, onReport }: PodcastEpisodeDetailProps) {
  const player = useAudioPlayer(); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [listenerState, setListenerState] = useState<ListenerState>("loading");
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [onClose]);
  useEffect(() => { let active = true; setNotice(null); setListenerState("loading"); void podcastService.getPlaybackProgress(episode.id).then((result) => { if (!active) return; if (!result.ok) { setListenerState("unplayed"); setNotice(result.error); return; } setListenerState(result.data?.completedAt ? "listened" : result.data && result.data.positionSeconds > 0 ? "in_progress" : "unplayed"); }); return () => { active = false; }; }, [episode.id]);
  useEffect(() => { if (player.item?.id !== episode.id || player.item.type !== "podcast_episode") return; if (player.status === "ended") setListenerState("listened"); else if (player.currentTime > 0) setListenerState("in_progress"); }, [episode.id, player.currentTime, player.item, player.status]);
  const toggleSaved = async () => { setBusy(true); const result = episode.isSavedByCurrentUser ? await podcastService.unsavePodcastEpisode(episode.id) : await podcastService.savePodcastEpisode(episode.id); setBusy(false); setNotice(result.ok ? episode.isSavedByCurrentUser ? "Episode removed from saved audio." : "Episode saved." : result.error.message); };
  const toggleReaction = async (emoji: string, active: boolean) => { setBusy(true); const result = active ? await podcastService.removePodcastReaction(episode.id, emoji) : await podcastService.reactToPodcastEpisode(episode.id, emoji); setBusy(false); setNotice(result.ok ? active ? "Reaction removed." : "Reaction added." : result.error.message); };
  const toggleListened = async () => { setBusy(true); const wasListened = listenerState === "listened"; const result = wasListened ? await podcastService.markPodcastEpisodeUnlistened(episode.id) : await podcastService.markPodcastEpisodeListened(episode.id, episode.durationSeconds); setBusy(false); if (!result.ok) { setNotice(result.error); return; } setListenerState(wasListened ? "unplayed" : "listened"); setNotice(wasListened ? "Episode marked unplayed." : "Episode marked listened."); };
  return <main className="podcast-episode-detail"><PodcastEpisodeHeader episode={episode} communityName={communityName} author={author} listenerState={listenerState} busy={busy} onToggleSaved={() => void toggleSaved()} onToggleListened={() => void toggleListened()} onOpenCommunity={onOpenCommunity} onOpenAuthor={onOpenAuthor} onClose={onClose} onNotice={setNotice} onReport={onReport ? () => onReport({ targetType: "podcast_episode", targetId: episode.id, communityId: episode.communityId, label: episode.title }) : undefined} /><div className="podcast-detail-scroll">{notice ? <div className="podcast-detail-notice" role="status">{notice}</div> : null}<PodcastEpisodePlayer episode={episode} communityName={communityName} /><div className="podcast-detail-grid"><div className="podcast-detail-primary"><PodcastEpisodeDescription episode={episode} busy={busy} onToggleReaction={(emoji, active) => void toggleReaction(emoji, active)} /><PodcastEpisodeCommentsPreview episode={episode} getAuthorLabel={getCommentAuthorLabel} onNotice={setNotice} onReport={onReport ? (commentId, label) => onReport({ targetType: "podcast_comment", targetId: commentId, communityId: episode.communityId, label }) : undefined} /></div><PodcastRelatedEpisodes episodes={relatedEpisodes.filter((candidate) => candidate.id !== episode.id && candidate.status === "published")} onSelectEpisode={onSelectEpisode} /></div></div></main>;
}
