import { useEffect, useState } from "react";
import type { AudioPlayableItem, PodcastEpisode, RadioSession } from "../../types/audio";
import type { Community } from "../../types/community";
import { dateTimeService } from "../../services/dateTimeService";
import { AppIcon } from "../AppIcon";
import { AudioMiniPlayer } from "./AudioMiniPlayer";
import { formatAudioTime } from "./AudioProgressBar";
import { PodcastEpisodeDetail } from "./PodcastEpisodeDetail";
import { radioService } from "../../services/audio/radioService";
import { podcastService } from "../../services/audio/podcastService";
import { communityNavigationService } from "../../services/community/communityNavigationService";

function communityName(communities: Community[], communityId: string) { return communities.find((community) => community.id === communityId)?.name ?? "Visible community"; }
function radioPlayable(session: RadioSession, communities: Community[]): AudioPlayableItem { return { id: session.id, type: session.status === "live" ? "radio_live" : session.status === "ended" ? "radio_ended" : "radio_scheduled", title: session.title, contextLabel: `${communityName(communities, session.communityId)} / Community radio`, coverUrl: session.coverUrl, audioUrl: session.streamUrl, durationSeconds: 3600, communityId: session.communityId, isLive: session.status === "live" }; }
function podcastPlayable(episode: PodcastEpisode, communities: Community[]): AudioPlayableItem { return { id: episode.id, type: "podcast_episode", title: episode.title, contextLabel: `${communityName(communities, episode.communityId)} / Podcast`, coverUrl: episode.coverUrl, audioUrl: episode.audioUrl, durationSeconds: episode.durationSeconds, communityId: episode.communityId }; }

type ProfileAudioSectionsProps = { hostedRadio: RadioSession[]; podcastEpisodes: PodcastEpisode[]; savedRadio: RadioSession[]; savedPodcasts: PodcastEpisode[]; communities: Community[]; isCurrentUser: boolean; onOpenCommunity?: (communityId: string) => void };

export function ProfileAudioSections({ hostedRadio, podcastEpisodes, savedRadio, savedPodcasts, communities, isCurrentUser, onOpenCommunity }: ProfileAudioSectionsProps) {
  const [selectedAudio, setSelectedAudio] = useState<AudioPlayableItem | null>(null);
  const [selectedPodcastEpisode, setSelectedPodcastEpisode] = useState<PodcastEpisode | null>(null);
  const [savedIds, setSavedIds] = useState<Set<string>>(() => new Set([...savedRadio.map((item) => item.id), ...savedPodcasts.map((item) => item.id)]));
  useEffect(() => { setSavedIds(new Set([...savedRadio.map((item) => item.id), ...savedPodcasts.map((item) => item.id)])); }, [savedPodcasts, savedRadio]);
  const toggleSaved = async (item: RadioSession | PodcastEpisode) => {
    const wasSaved = savedIds.has(item.id);
    setSavedIds((current) => { const next = new Set(current); if (wasSaved) next.delete(item.id); else next.add(item.id); return next; });
    const result = "durationSeconds" in item ? await (wasSaved ? podcastService.unsavePodcastEpisode(item.id) : podcastService.savePodcastEpisode(item.id)) : await (wasSaved ? radioService.unsaveRadio(item.id) : radioService.saveRadio(item.id));
    if (!result.ok) setSavedIds((current) => { const next = new Set(current); if (wasSaved) next.add(item.id); else next.delete(item.id); return next; });
  };
  const openRadio = (session: RadioSession) => { communityNavigationService.rememberRadioSession(session.communityId, session.id); onOpenCommunity?.(session.communityId); };
  const openPodcast = (episode: PodcastEpisode) => { setSelectedPodcastEpisode(episode); setSelectedAudio(podcastPlayable(episode, communities)); };
  const selectedPodcastCommunity = selectedPodcastEpisode ? communities.find((community) => community.id === selectedPodcastEpisode.communityId) : undefined;

  return <div className="profile-audio-sections">
    {selectedAudio ? <AudioMiniPlayer item={selectedAudio} onClose={() => setSelectedAudio(null)} /> : null}
    {selectedPodcastEpisode ? <div className="podcast-detail-modal-backdrop" role="presentation" onMouseDown={() => setSelectedPodcastEpisode(null)}><div className="podcast-detail-modal" role="dialog" aria-modal="true" aria-label={`${selectedPodcastEpisode.title} podcast detail`} onMouseDown={(event) => event.stopPropagation()}><PodcastEpisodeDetail episode={selectedPodcastEpisode} communityName={selectedPodcastCommunity?.name ?? "Picom community"} author={selectedPodcastCommunity?.members.find((member) => member.userId === selectedPodcastEpisode.authorUserId)} relatedEpisodes={podcastEpisodes.filter((episode) => episode.communityId === selectedPodcastEpisode.communityId)} getCommentAuthorLabel={(authorId) => selectedPodcastCommunity?.members.find((member) => member.userId === authorId)?.displayName ?? "Community member"} onClose={() => setSelectedPodcastEpisode(null)} onOpenCommunity={() => { const communityId = selectedPodcastEpisode.communityId; setSelectedPodcastEpisode(null); onOpenCommunity?.(communityId); }} onSelectEpisode={openPodcast} /></div></div> : null}

    <section className="profile-section"><div className="profile-section-header"><div><p className="eyebrow">Hosted radio</p><h2>Community sessions</h2></div><span>{hostedRadio.length} visible</span></div>{hostedRadio.length ? <div className="profile-audio-card-grid">{hostedRadio.map((session) => <article className="profile-radio-card" key={session.id}><div className="profile-audio-cover">{session.coverUrl ? <img src={session.coverUrl} alt="" aria-hidden="true" /> : <AppIcon name="voice" size="xl" />}<span className={session.status}>{session.status}</span></div><div><h3>{session.title}</h3><button type="button" onClick={() => onOpenCommunity?.(session.communityId)}>{communityName(communities, session.communityId)}</button><small>{dateTimeService.formatCompactDateTime(session.startsAt)} / {session.listenerCount} listeners</small><footer>{session.status === "live" ? <button type="button" className="primary" onClick={() => setSelectedAudio(radioPlayable(session, communities))}><AppIcon name="play" size="sm" />Listen</button> : null}<button type="button" onClick={() => openRadio(session)}>Open in Radio</button><button type="button" className={savedIds.has(session.id) ? "active" : ""} onClick={() => { void toggleSaved(session); }}><AppIcon name="pin" size="sm" />{savedIds.has(session.id) ? "Saved" : "Save"}</button></footer></div></article>)}</div> : <div className="profile-empty-panel">No visible radio sessions hosted by this member.</div>}</section>

    <section className="profile-section"><div className="profile-section-header"><div><p className="eyebrow">Podcasts</p><h2>Published episodes</h2></div><span>{podcastEpisodes.length} visible</span></div>{podcastEpisodes.length ? <div className="profile-podcast-list">{podcastEpisodes.map((episode) => <article key={episode.id}><div className="profile-podcast-cover">{episode.coverUrl ? <img src={episode.coverUrl} alt="" aria-hidden="true" /> : <AppIcon name="headphones" size="lg" />}</div><div><h3>{episode.title}</h3><button type="button" onClick={() => onOpenCommunity?.(episode.communityId)}>{communityName(communities, episode.communityId)}</button><small>{formatAudioTime(episode.durationSeconds)} / {dateTimeService.formatCompactDateTime(episode.publishedAt)} / {episode.listenerCount} listeners</small><span>{episode.reactionSummary.slice(0, 3).map((reaction) => `${reaction.emoji} ${reaction.count}`).join("  ")}</span></div><div className="profile-podcast-actions"><button type="button" className="primary" aria-label={`Open ${episode.title}`} onClick={() => openPodcast(episode)}><AppIcon name="play" size="sm" /></button><button type="button" className={savedIds.has(episode.id) ? "active" : ""} aria-label={savedIds.has(episode.id) ? `Unsave ${episode.title}` : `Save ${episode.title}`} onClick={() => { void toggleSaved(episode); }}><AppIcon name="pin" size="sm" /></button></div></article>)}</div> : <div className="profile-empty-panel">No published podcast episodes are visible for this member.</div>}</section>

    {isCurrentUser ? <section className="profile-section"><div className="profile-section-header"><div><p className="eyebrow">Saved audio</p><h2>Your listening shelf</h2></div><span>{savedIds.size} saved</span></div><div className="profile-saved-audio">{[...savedRadio, ...savedPodcasts].filter((item) => savedIds.has(item.id)).slice(0, 6).map((item) => <button type="button" key={item.id} onClick={() => { if ("durationSeconds" in item) openPodcast(item); else openRadio(item); }}><AppIcon name={"durationSeconds" in item ? "headphones" : "voice"} size="sm" /><span><strong>{item.title}</strong><small>{communityName(communities, item.communityId)}</small></span><AppIcon name="chevronRight" size="xs" /></button>)}{![...savedRadio, ...savedPodcasts].some((item) => savedIds.has(item.id)) ? <div className="profile-empty-panel">Save a radio session or podcast to see it here.</div> : null}</div></section> : null}
    <small className="profile-audio-privacy-note">Audio activity and media are limited to communities visible to you and enforced by Supabase RLS in connected mode.</small>
  </div>;
}
