bind 127.0.0.1 -::1
protected-mode yes
port __REDIS_PORT__
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
loglevel notice
logfile ""
databases 1
requirepass __REDIS_PASSWORD__
appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
save 900 1
save 300 10
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dir /data
maxmemory-policy noeviction
