export type NotificationCategory =
  | "system"
  | "message"
  | "mention"
  | "reply"
  | "reaction"
  | "direct_message"
  | "community_announcement"
  | "friend_request"
  | "friend_acceptance"
  | "friend_online"
  | "followed_user_live"
  | "followed_publisher_live"
  | "radio_live"
  | "radio_reminder"
  | "podcast_release"
  | "event_reminder"
  | "incoming_call";
