import type { RealtimeChannel } from "@supabase/supabase-js";
import type { MeetingRole } from "../../types/meeting";
import { MEETING_REACTION_KINDS,type AuthenticatedMeetingReaction,type MeetingHandQueueEntry,type MeetingHandQueueSnapshot,type MeetingHandSignalAction,type MeetingReactionSignal,type MeetingStageRequestStatus } from "../../types/meetingSignals";
import { dataSourceService } from "../dataSourceService";
import { loggingService } from "../loggingService";
import { createRealtimeEventDeduper,mapRealtimeSubscriptionStatus,type RealtimeConnectionStatus } from "../supabase/realtimeService";
import { getSupabaseClient,getSupabaseClientStatus } from "../supabase/supabaseClient";
import { voiceService,type VoiceDataPacket } from "../voiceService";

export const MEETING_SIGNAL_TOPIC="picom.meeting.signal.v1";
const REACTION_TTL_MS=5_000,WINDOW_MS=2_000,OUTBOUND_LIMIT=5,INBOUND_LIMIT=8,MAX_PAYLOAD_BYTES=1_024;
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
type Result<T>=Readonly<{ok:true;data:T}|{ok:false;error:Readonly<{code:string;message:string;retryAfterMs?:number}>}>;
type HandSubscriber=Readonly<{onSnapshot:(snapshot:MeetingHandQueueSnapshot)=>void;onStatus:(status:RealtimeConnectionStatus)=>void;onError?:(message:string)=>void}>;
const reactionListeners=new Set<(event:AuthenticatedMeetingReaction)=>void>(),seenEvents=new Map<string,number>(),inboundWindows=new Map<string,number[]>(),mockQueues=new Map<string,MeetingHandQueueSnapshot>();
let activeContext:{roomId:string;sessionId:string}|null=null,transportCleanup:(()=>void)|null=null,outboundWindow:number[]=[],lastAbuseLogAt=0;
const record=(value:unknown):Record<string,unknown>|null=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:null;
const text=(value:unknown)=>typeof value==="string"?value:"";const nullableText=(value:unknown)=>typeof value==="string"?value:null;const numeric=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:0;
const queueKey=(roomId:string,sessionId:string)=>`${roomId}:${sessionId}`;
const fail=<T>(code:string,message:string,retryAfterMs?:number):Result<T>=>({ok:false,error:{code,message,...(retryAfterMs?{retryAfterMs}:{})}});
const trimWindow=(values:number[],now:number)=>values.filter((value)=>now-value<WINDOW_MS);

function parseReaction(packet:VoiceDataPacket,context:{roomId:string;sessionId:string}):AuthenticatedMeetingReaction|null{
  if(packet.topic!==MEETING_SIGNAL_TOPIC||packet.payload.byteLength>MAX_PAYLOAD_BYTES)return null;
  let value:unknown;try{value=JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(packet.payload))}catch{return null}const row=record(value);if(!row)return null;
  const allowed=new Set(["schemaVersion","eventId","roomId","sessionId","kind","sentAt","expiresAt"]);if(Object.keys(row).some((key)=>!allowed.has(key)))return null;
  const kind=text(row.kind) as MeetingReactionSignal["kind"],sentAt=text(row.sentAt),expiresAt=text(row.expiresAt),eventId=text(row.eventId),now=Date.now(),sent=Date.parse(sentAt),expires=Date.parse(expiresAt);
  if(row.schemaVersion!==1||!uuid.test(eventId)||text(row.roomId)!==context.roomId||text(row.sessionId)!==context.sessionId||!MEETING_REACTION_KINDS.includes(kind)||!Number.isFinite(sent)||!Number.isFinite(expires)||Math.abs(now-sent)>10_000||expires<=now||expires-sent>REACTION_TTL_MS+500)return null;
  const prior=seenEvents.get(eventId);if(prior&&prior>now)return null;seenEvents.set(eventId,expires);for(const [id,expiry]of seenEvents)if(expiry<=now)seenEvents.delete(id);while(seenEvents.size>1_000)seenEvents.delete(seenEvents.keys().next().value as string);
  const senderWindow=trimWindow(inboundWindows.get(packet.senderIdentity)??[],now);if(senderWindow.length>=INBOUND_LIMIT){inboundWindows.set(packet.senderIdentity,senderWindow);if(now-lastAbuseLogAt>10_000){lastAbuseLogAt=now;loggingService.logWarn("Meeting reaction burst dropped",{reason:"receiver_rate_limit"},"meeting-signal")}return null}senderWindow.push(now);inboundWindows.set(packet.senderIdentity,senderWindow);
  return{schemaVersion:1,eventId,roomId:context.roomId,sessionId:context.sessionId,kind,sentAt,expiresAt,senderIdentity:packet.senderIdentity,receivedAt:packet.receivedAt,isLocal:false};
}

function emitReaction(event:AuthenticatedMeetingReaction){reactionListeners.forEach((listener)=>listener(event))}
function mapEntry(value:unknown):MeetingHandQueueEntry|null{const row=record(value);if(!row)return null;const meetingRole=text(row.meetingRole) as MeetingRole,stage=text(row.stageRequestStatus) as MeetingStageRequestStatus,participantId=text(row.participantId),displayName=text(row.displayName);if(!participantId||!displayName||!["host","cohost","speaker","participant","viewer","guest"].includes(meetingRole)||!["none","requested","approved","denied","cancelled"].includes(stage))return null;return{participantId,userId:nullableText(row.userId),displayName,meetingRole,handRaised:row.handRaised===true,handRaisedAt:nullableText(row.handRaisedAt),handSequence:numeric(row.handSequence),acknowledgedByUserId:nullableText(row.acknowledgedByUserId),acknowledgedAt:nullableText(row.acknowledgedAt),stageRequestStatus:stage,stageRequestedAt:nullableText(row.stageRequestedAt),stageResolvedAt:nullableText(row.stageResolvedAt),stageResolvedByUserId:nullableText(row.stageResolvedByUserId),serverVersion:numeric(row.serverVersion),updatedAt:text(row.updatedAt)}}
export function mapMeetingHandQueue(value:unknown):MeetingHandQueueSnapshot|null{const row=record(value);if(!row||row.schemaVersion!==1||!Array.isArray(row.entries))return null;const entries=row.entries.map(mapEntry).filter((entry):entry is MeetingHandQueueEntry=>Boolean(entry));if(entries.length!==row.entries.length)return null;const roomId=text(row.roomId),sessionId=text(row.sessionId);return roomId&&sessionId?{schemaVersion:1,roomId,sessionId,sessionSequence:numeric(row.sessionSequence),generatedAt:text(row.generatedAt)||new Date().toISOString(),entries}:null}

async function loadHandQueue(roomId:string,sessionId:string):Promise<Result<MeetingHandQueueSnapshot>>{if(dataSourceService.getStatus().isMock)return{ok:true,data:mockQueues.get(queueKey(roomId,sessionId))??{schemaVersion:1,roomId,sessionId,sessionSequence:0,generatedAt:new Date().toISOString(),entries:[]}};const client=getSupabaseClient();if(!client)return fail("DATA_SOURCE_NOT_CONFIGURED","Supabase is not configured.");const{data,error}=await client.rpc("get_meeting_hand_queue",{target_room_id:roomId,target_session_id:sessionId});const mapped=mapMeetingHandQueue(data);return error||!mapped?fail("MEETING_HAND_QUEUE_FAILED","Picom could not load the hand queue."):{ok:true,data:mapped}}

export const meetingSignalService={
  start(context:{roomId:string;sessionId:string}):()=>void{transportCleanup?.();activeContext=context;outboundWindow=[];inboundWindows.clear();const generation=context;const stop=voiceService.subscribeDataPackets((packet)=>{if(activeContext!==generation)return;const event=parseReaction(packet,generation);if(event)emitReaction(event)});transportCleanup=stop;return()=>{if(activeContext===generation){activeContext=null;transportCleanup=null}stop()}},
  stop():void{transportCleanup?.();transportCleanup=null;activeContext=null;outboundWindow=[];inboundWindows.clear()},
  subscribeReactions(listener:(event:AuthenticatedMeetingReaction)=>void):()=>void{reactionListeners.add(listener);return()=>reactionListeners.delete(listener)},
  async sendReaction(kind:MeetingReactionSignal["kind"]):Promise<Result<AuthenticatedMeetingReaction>>{const context=activeContext;if(!context||!MEETING_REACTION_KINDS.includes(kind))return fail("MEETING_REACTION_INVALID","Choose a supported reaction while connected to a meeting.");const now=Date.now();outboundWindow=trimWindow(outboundWindow,now);if(outboundWindow.length>=OUTBOUND_LIMIT)return fail("MEETING_REACTION_RATE_LIMITED","Slow down before sending another reaction.",Math.max(1,WINDOW_MS-(now-outboundWindow[0])));outboundWindow.push(now);const senderIdentity=dataSourceService.getStatus().isMock?"mock-local-participant":voiceService.getLocalParticipantIdentity();if(!senderIdentity)return fail("MEETING_REACTION_NOT_CONNECTED","Join the meeting before sending a reaction.");const signal:MeetingReactionSignal={schemaVersion:1,eventId:crypto.randomUUID(),roomId:context.roomId,sessionId:context.sessionId,kind,sentAt:new Date(now).toISOString(),expiresAt:new Date(now+REACTION_TTL_MS).toISOString()};const payload=new TextEncoder().encode(JSON.stringify(signal));if(!dataSourceService.getStatus().isMock){const sent=await voiceService.publishDataPacket(MEETING_SIGNAL_TOPIC,payload,false);if(!sent.ok)return fail(sent.error.code,sent.error.message)}const event:AuthenticatedMeetingReaction={...signal,senderIdentity,receivedAt:new Date().toISOString(),isLocal:true};seenEvents.set(signal.eventId,now+REACTION_TTL_MS);emitReaction(event);return{ok:true,data:event}},
  publishMockRemote(signal:MeetingReactionSignal,senderIdentity="mock-remote-participant"):void{const context=activeContext;if(!context)return;const event=parseReaction({topic:MEETING_SIGNAL_TOPIC,payload:new TextEncoder().encode(JSON.stringify(signal)),senderIdentity,receivedAt:new Date().toISOString()},context);if(event)emitReaction(event)},
  seedMockHandQueue(snapshot:MeetingHandQueueSnapshot):void{mockQueues.set(queueKey(snapshot.roomId,snapshot.sessionId),snapshot)},
  loadHandQueue,
  async applyHandAction(participantId:string,action:MeetingHandSignalAction):Promise<Result<MeetingHandQueueEntry>>{if(dataSourceService.getStatus().isMock){for(const[key,snapshot]of mockQueues){const current=snapshot.entries.find((entry)=>entry.participantId===participantId);if(!current)continue;const now=new Date().toISOString(),next:MeetingHandQueueEntry={...current,handRaised:action==="raise"||action==="request_stage"?true:action==="lower"?false:current.handRaised,handRaisedAt:action==="raise"||action==="request_stage"?(current.handRaisedAt??now):action==="lower"?null:current.handRaisedAt,handSequence:action==="lower"?0:current.handSequence||snapshot.entries.length+1,acknowledgedByUserId:action==="acknowledge"||action==="approve_stage"||action==="deny_stage"?"mock-host":current.acknowledgedByUserId,acknowledgedAt:action==="acknowledge"||action==="approve_stage"||action==="deny_stage"?now:current.acknowledgedAt,stageRequestStatus:action==="request_stage"?"requested":action==="approve_stage"?"approved":action==="deny_stage"?"denied":action==="cancel_stage"?"cancelled":current.stageRequestStatus,serverVersion:current.serverVersion+1,updatedAt:now};mockQueues.set(key,{...snapshot,generatedAt:now,entries:snapshot.entries.map((entry)=>entry.participantId===participantId?next:entry)});return{ok:true,data:next}}return fail("MEETING_HAND_PARTICIPANT_MISSING","The participant is not active.")}const client=getSupabaseClient();if(!client)return fail("DATA_SOURCE_NOT_CONFIGURED","Supabase is not configured.");const{data,error}=await client.rpc("update_meeting_hand_signal",{target_participant_id:participantId,target_action:action});const entry=mapEntry(data);return error||!entry?fail(error?.message.includes("RATE_LIMITED")?"MEETING_SIGNAL_RATE_LIMITED":"MEETING_HAND_ACTION_FAILED",error?.message.includes("RATE_LIMITED")?"Slow down before changing the hand state again.":"Picom could not update the hand state."):{ok:true,data:entry}},
  subscribeHandQueue(roomId:string,sessionId:string,subscriber:HandSubscriber):()=>void{if(dataSourceService.getStatus().isMock){subscriber.onStatus("connected");void loadHandQueue(roomId,sessionId).then((result)=>{if(result.ok)subscriber.onSnapshot(result.data)});return()=>undefined}const status=getSupabaseClientStatus(),client=getSupabaseClient();if(!status.configured||!client){subscriber.onStatus("disconnected");subscriber.onError?.(status.reason??"Meeting hand Realtime is unavailable.");return()=>undefined}let channel:RealtimeChannel|null=null,retryTimer:ReturnType<typeof setTimeout>|null=null,refreshTimer:ReturnType<typeof setTimeout>|null=null,attempt=0,generation=0;let canceled=false;const deduper=createRealtimeEventDeduper(500);const refresh=async(local:number)=>{const result=await loadHandQueue(roomId,sessionId);if(canceled||local!==generation)return;if(result.ok)subscriber.onSnapshot(result.data);else subscriber.onError?.(result.error.message)};const connect=()=>{if(canceled)return;const local=++generation;let connected=false;subscriber.onStatus(attempt?"reconnecting":"connecting");channel=client.channel(`meeting-hand:${sessionId}:${local}`).on("postgres_changes",{event:"*",schema:"public",table:"meeting_participant_runtime_state",filter:`session_id=eq.${sessionId}`},(payload)=>{const row=record(payload.new)??record(payload.old);const id=`${payload.eventType}:${text(row?.participant_id)}:${payload.commit_timestamp??text(row?.updated_at)}`;if(!deduper.shouldProcess(id))return;if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{refreshTimer=null;void refresh(local)},40)}).subscribe((value)=>{if(canceled||local!==generation)return;const mapped=mapRealtimeSubscriptionStatus(value,connected);if(!mapped)return;if(mapped==="connected"){connected=true;attempt=0;subscriber.onStatus("connected");void refresh(local);return}subscriber.onStatus(mapped);if((value==="CHANNEL_ERROR"||value==="TIMED_OUT"||value==="CLOSED")&&!retryTimer){attempt+=1;const stale=channel;channel=null;if(stale)void client.removeChannel(stale);retryTimer=setTimeout(()=>{retryTimer=null;connect()},Math.min(10_000,750*2**Math.min(attempt,4)))}})};connect();return()=>{canceled=true;generation+=1;if(retryTimer)clearTimeout(retryTimer);if(refreshTimer)clearTimeout(refreshTimer);if(channel)void client.removeChannel(channel);channel=null;deduper.clear()}},
};
