import { getApiCompatibilityRequestHeaders } from "../../config/apiCompatibility";
import { dataSourceService } from "../dataSourceService";
import { getSupabaseClient } from "../supabase/supabaseClient";
import { voiceService, type VoiceTranscriptionSegment } from "../voiceService";
import type { MeetingCaptionConsentDecision, MeetingCaptionFontSize, MeetingCaptionLanguage, MeetingCaptionSnapshot, MeetingCaptionStatus } from "../../types/meetingCaptions";
import { meetingDiagnosticsRegistry } from "../meetingDiagnosticsRegistry";

const POLICY_VERSION="2026-07-11";
const statusValues=new Set<MeetingCaptionStatus>(["idle","awaiting_consent","starting","active","stopping","stopped","failed","unavailable"]);
const languageValues=new Set<MeetingCaptionLanguage>(["en","tr","de","es","fr"]);
const listeners=new Set<()=>void>();
let activationGeneration=0;
let realtimeCleanup:(()=>void)|null=null;
let transcriptionCleanup:(()=>void)|null=null;

function storedFontSize():MeetingCaptionFontSize{try{const value=localStorage.getItem("picom.meeting.captionFontSize");return value==="small"||value==="large"?value:"medium"}catch{return"medium"}}
function storedDisplay():boolean{try{return localStorage.getItem("picom.meeting.captionsVisible")!=="false"}catch{return true}}
let snapshot:MeetingCaptionSnapshot={roomId:null,sessionId:null,configured:false,provider:"deepgram_livekit_agent",model:"nova-3",status:"unavailable",language:"en",retentionMode:"ephemeral",policyVersion:POLICY_VERSION,canStart:false,consentDecision:null,consentRequired:false,pendingConsentCount:0,displayEnabled:storedDisplay(),fontSize:storedFontSize(),segments:[],operation:"idle",error:null};

function emit(patch:Partial<MeetingCaptionSnapshot>):void{snapshot={...snapshot,...patch};listeners.forEach((listener)=>listener())}
function normalizeState(value:unknown):Partial<MeetingCaptionSnapshot>{if(!value||typeof value!=="object"||Array.isArray(value))return{};const row=value as Record<string,unknown>;const status=statusValues.has(row.status as MeetingCaptionStatus)?row.status as MeetingCaptionStatus:"unavailable";const language=languageValues.has(row.language as MeetingCaptionLanguage)?row.language as MeetingCaptionLanguage:"en";const decision:MeetingCaptionConsentDecision=row.consentDecision==="accepted"||row.consentDecision==="declined"?row.consentDecision:null;return{configured:row.configured===true,status,language,canStart:row.canStart===true||snapshot.canStart,consentDecision:decision,consentRequired:row.consentRequired===true,pendingConsentCount:Number.isFinite(Number(row.pendingConsentCount))?Math.max(0,Number(row.pendingConsentCount)):0,error:typeof row.errorCode==="string"&&row.errorCode?"Live captions stopped because the transcription provider reported an error.":null}}
async function invoke(action:"status"|"request"|"consent"|"stop",extra:Record<string,unknown>={}):Promise<{ok:true;data:unknown}|{ok:false;message:string}>{if(!snapshot.roomId||!snapshot.sessionId)return{ok:false,message:"No active meeting is available for captions."};const client=getSupabaseClient();if(!client)return{ok:false,message:"Live captions require a configured Picom service."};const result=await client.functions.invoke("meeting-captions",{headers:getApiCompatibilityRequestHeaders(),body:{action,roomId:snapshot.roomId,sessionId:snapshot.sessionId,...extra}});if(result.error)return{ok:false,message:action==="status"?"Live caption status is unavailable.":"The live caption request could not be completed."};return{ok:true,data:result.data}}
function acceptSegment(segment:VoiceTranscriptionSegment):void{if(snapshot.status!=="active"||!snapshot.roomId)return;const current=[...snapshot.segments];const index=current.findIndex((item)=>item.id===segment.id);if(index>=0)current[index]=segment;else current.push(segment);emit({segments:current.slice(-200)})}
async function refresh(generation=activationGeneration):Promise<boolean>{if(dataSourceService.getStatus().isMock){if(generation===activationGeneration)emit({configured:false,status:"unavailable",operation:"idle",error:"Live captions are unavailable in mock mode; Picom never displays simulated transcript text."});return false}emit({operation:"refreshing"});const result=await invoke("status");if(generation!==activationGeneration)return false;if(!result.ok){meetingDiagnosticsRegistry.recordCaptionFailure("CAPTION_STATUS_UNAVAILABLE");emit({configured:false,status:"unavailable",operation:"idle",error:result.message});return false}const normalized=normalizeState(result.data);if(normalized.status==="failed")meetingDiagnosticsRegistry.recordCaptionFailure("CAPTION_PROVIDER_FAILED");emit({...normalized,operation:"idle"});return true}
function subscribeRealtime(roomId:string,sessionId:string,generation:number):void{const client=getSupabaseClient();if(!client)return;const channel=client.channel(`meeting-captions:${sessionId}`).on("postgres_changes",{event:"*",schema:"public",table:"meeting_caption_sessions",filter:`session_id=eq.${sessionId}`},()=>{if(generation===activationGeneration)void refresh(generation)}).subscribe();realtimeCleanup=()=>{void client.removeChannel(channel)};void roomId}

export const meetingCaptionService={
  getSnapshot:():MeetingCaptionSnapshot=>snapshot,
  subscribe(listener:()=>void):()=>void{listeners.add(listener);return()=>listeners.delete(listener)},
  activate(input:{roomId:string;sessionId:string;canStart:boolean}):()=>void{const generation=++activationGeneration;realtimeCleanup?.();transcriptionCleanup?.();realtimeCleanup=null;transcriptionCleanup=voiceService.subscribeTranscriptions(acceptSegment);emit({roomId:input.roomId,sessionId:input.sessionId,canStart:input.canStart,status:"idle",configured:false,consentDecision:null,consentRequired:false,pendingConsentCount:0,segments:[],error:null});subscribeRealtime(input.roomId,input.sessionId,generation);void refresh(generation);return()=>{if(generation!==activationGeneration)return;activationGeneration+=1;realtimeCleanup?.();transcriptionCleanup?.();realtimeCleanup=null;transcriptionCleanup=null;emit({roomId:null,sessionId:null,configured:false,status:"unavailable",canStart:false,consentDecision:null,consentRequired:false,pendingConsentCount:0,segments:[],operation:"idle",error:null})}},
  async requestCaptions(language:MeetingCaptionLanguage):Promise<boolean>{emit({operation:"requesting",error:null});const result=await invoke("request",{language,policyVersion:POLICY_VERSION});if(!result.ok){meetingDiagnosticsRegistry.recordCaptionFailure("CAPTION_REQUEST_FAILED");emit({operation:"idle",error:result.message});return false}emit({...normalizeState(result.data),operation:"idle"});return true},
  async recordConsent(decision:Exclude<MeetingCaptionConsentDecision,null>):Promise<boolean>{emit({operation:"consenting",error:null});const result=await invoke("consent",{decision,policyVersion:POLICY_VERSION});if(!result.ok){meetingDiagnosticsRegistry.recordCaptionFailure("CAPTION_CONSENT_FAILED");emit({operation:"idle",error:result.message});return false}emit({...normalizeState(result.data),operation:"idle"});return true},
  async stopCaptions():Promise<boolean>{emit({operation:"stopping",error:null});const result=await invoke("stop",{policyVersion:POLICY_VERSION});if(!result.ok){meetingDiagnosticsRegistry.recordCaptionFailure("CAPTION_STOP_FAILED");emit({operation:"idle",error:result.message});return false}emit({...normalizeState(result.data),segments:[],operation:"idle"});return true},
  setDisplayEnabled(enabled:boolean):void{try{localStorage.setItem("picom.meeting.captionsVisible",String(enabled))}catch{ /* In-memory preference remains available. */ }emit({displayEnabled:enabled})},
  setFontSize(fontSize:MeetingCaptionFontSize):void{try{localStorage.setItem("picom.meeting.captionFontSize",fontSize)}catch{ /* In-memory preference remains available. */ }emit({fontSize})},
  refresh,
};
