import { currentUserId } from "../../data/mockCommunities";
import type { MeetingAttendanceFinalState, MeetingAttendanceItem, MeetingAttendancePage, MeetingAttendanceSummary, MeetingHistoryItem, MeetingHistoryPage, MeetingHistoryScope, MeetingHistoryStatus } from "../../types/meetingHistory";
import type { MeetingRole } from "../../types/meeting";
import { dataSourceService } from "../dataSourceService";
import { deepLinkService } from "../deepLinkService";
import { getSupabaseClient } from "../supabase/supabaseClient";
import { meetingChatContextService } from "./meetingChatContextService";

type HistoryResult<T>=Readonly<{ok:true;data:T}|{ok:false;error:{code:string;message:string}}>;
const roles=new Set<MeetingRole>(["host","cohost","speaker","participant","viewer","guest"]);
const statuses=new Set<MeetingHistoryStatus>(["upcoming","live","ended","failed"]);
const finalStates=new Set<MeetingAttendanceFinalState>(["left","removed","disconnected","ended"]);
const safeSegment=/^[a-zA-Z0-9_-]{1,128}$/;
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const text=(row:Record<string,unknown>,key:string):string=>typeof row[key]==="string"?row[key] as string:"";
const nullableText=(row:Record<string,unknown>,key:string):string|null=>typeof row[key]==="string"?row[key] as string:null;
const number=(row:Record<string,unknown>,key:string):number=>Number.isFinite(Number(row[key]))?Math.max(0,Number(row[key])):0;
const fail=<T>(code:string,message:string):HistoryResult<T>=>({ok:false,error:{code,message}});

function attendanceSummary(value:unknown):MeetingAttendanceSummary|null{const row=record(value),role=text(row,"role") as MeetingRole,finalState=text(row,"finalState") as MeetingAttendanceFinalState,joinedAt=text(row,"joinedAt");if(!roles.has(role)||!finalStates.has(finalState)||!joinedAt)return null;return{role,joinedAt,leftAt:nullableText(row,"leftAt"),durationSeconds:row.durationSeconds===null?null:number(row,"durationSeconds"),reconnectCount:number(row,"reconnectCount"),finalState}}
function mapItem(value:unknown):MeetingHistoryItem|null{const row=record(value),status=text(row,"status") as MeetingHistoryStatus,mode=text(row,"mode") as MeetingHistoryItem["mode"],roomId=text(row,"roomId"),communityId=text(row,"communityId"),title=text(row,"title"),hostUserId=text(row,"hostUserId"),outcome=text(row,"outcomeCode");if(!roomId||!communityId||!title||!hostUserId||!statuses.has(status)||!["voice","meeting","stage"].includes(mode))return null;return{roomId,sessionId:nullableText(row,"sessionId"),communityId,channelId:nullableText(row,"channelId"),title:title.slice(0,120),mode,status,scheduledFor:nullableText(row,"scheduledFor"),startedAt:nullableText(row,"startedAt"),endedAt:nullableText(row,"endedAt"),durationSeconds:row.durationSeconds===null||row.durationSeconds===undefined?null:number(row,"durationSeconds"),hostUserId,hostName:(text(row,"hostName")||"Picom host").slice(0,120),attendanceCount:number(row,"attendanceCount"),myAttendance:attendanceSummary(row.myAttendance),outcomeCode:["provider_ended","host_ended","failed","cancelled","unknown"].includes(outcome)?outcome as MeetingHistoryItem["outcomeCode"]:null,outcomeVerified:row.outcomeVerified===true,outcomeVerifiedAt:nullableText(row,"outcomeVerifiedAt"),hasDurableChat:row.hasDurableChat===true,captionsUsed:row.captionsUsed===true,transcriptRetained:false,recordingAvailable:false}}
function mapPage(value:unknown,scope:MeetingHistoryScope):MeetingHistoryPage|null{const row=record(value);const items=Array.isArray(row.items)?row.items.map(mapItem).filter((item):item is MeetingHistoryItem=>Boolean(item)):[];const upcoming=Array.isArray(row.upcoming)?row.upcoming.map(mapItem).filter((item):item is MeetingHistoryItem=>Boolean(item)):[];return{items,upcoming,scope,canViewAttendance:row.canViewAttendance===true,transcriptRetention:"ephemeral_none"}}
function mapAttendance(value:unknown,sessionId:string):MeetingAttendancePage|null{const row=record(value),items=Array.isArray(row.items)?row.items.flatMap((value)=>{const source=record(value),summary=attendanceSummary(source);return summary?[{...summary,userId:nullableText(source,"userId"),displayName:(text(source,"displayName")||"Guest participant").slice(0,120),avatarUrl:nullableText(source,"avatarUrl")}]:[]}):[];return{sessionId:text(row,"sessionId")||sessionId,canViewAll:row.canViewAll===true,items}}
function mockPage(communityId:string,scope:MeetingHistoryScope):MeetingHistoryPage{const now=Date.now();const own:MeetingAttendanceSummary={role:"participant",joinedAt:new Date(now-7_000_000).toISOString(),leftAt:new Date(now-3_400_000).toISOString(),durationSeconds:3600,reconnectCount:1,finalState:"ended"};const items:MeetingHistoryItem[]=[{roomId:"mock-history-room-1",sessionId:"mock-history-session-1",communityId,channelId:"mock-history-chat",title:"Product workspace review",mode:"meeting",status:"ended",scheduledFor:new Date(now-7_200_000).toISOString(),startedAt:own.joinedAt,endedAt:own.leftAt,durationSeconds:3600,hostUserId:"user-mira",hostName:"Mira Chen",attendanceCount:8,myAttendance:own,outcomeCode:"provider_ended",outcomeVerified:true,outcomeVerifiedAt:own.leftAt,hasDurableChat:true,captionsUsed:true,transcriptRetained:false,recordingAvailable:false},{roomId:"mock-history-room-2",sessionId:"mock-history-session-2",communityId,channelId:"mock-history-chat",title:"Community planning",mode:"voice",status:"ended",scheduledFor:new Date(now-172_800_000).toISOString(),startedAt:new Date(now-172_700_000).toISOString(),endedAt:new Date(now-170_900_000).toISOString(),durationSeconds:1800,hostUserId:currentUserId,hostName:"You",attendanceCount:5,myAttendance:{...own,role:"host",durationSeconds:1800,reconnectCount:0},outcomeCode:"host_ended",outcomeVerified:false,outcomeVerifiedAt:null,hasDurableChat:true,captionsUsed:false,transcriptRetained:false,recordingAvailable:false}];const upcoming:MeetingHistoryItem[]=[{roomId:"mock-upcoming-room",sessionId:null,communityId,channelId:"mock-history-chat",title:"Weekly community sync",mode:"meeting",status:"upcoming",scheduledFor:new Date(now+3_600_000).toISOString(),startedAt:null,endedAt:null,durationSeconds:null,hostUserId:"user-mira",hostName:"Mira Chen",attendanceCount:0,myAttendance:null,outcomeCode:null,outcomeVerified:false,outcomeVerifiedAt:null,hasDurableChat:true,captionsUsed:false,transcriptRetained:false,recordingAvailable:false}];return{items:scope==="mine"?items.filter((item)=>item.myAttendance):items,upcoming,scope,canViewAttendance:scope==="community",transcriptRetention:"ephemeral_none"}}

export const meetingHistoryService={
  async list(communityId:string,scope:MeetingHistoryScope="community",limit=20):Promise<HistoryResult<MeetingHistoryPage>>{if(!communityId.trim())return fail("MEETING_HISTORY_CONTEXT_INVALID","Choose a community before opening meeting history.");if(dataSourceService.getStatus().isMock)return{ok:true,data:mockPage(communityId,scope)};const client=getSupabaseClient();if(!client)return fail("DATA_SOURCE_NOT_CONFIGURED","Meeting history is unavailable until Picom reconnects.");const result=await client.rpc("get_meeting_history",{target_community_id:communityId,target_scope:scope,result_limit:Math.min(Math.max(limit,1),50)});const page=mapPage(result.data,scope);return result.error||!page?fail("MEETING_HISTORY_LOAD_FAILED","Picom could not load permission-safe meeting history."):{ok:true,data:page}},
  async attendance(sessionId:string):Promise<HistoryResult<MeetingAttendancePage>>{if(!sessionId)return fail("MEETING_ATTENDANCE_CONTEXT_INVALID","Choose a completed meeting session.");if(dataSourceService.getStatus().isMock){const base=mockPage("mock-community","community").items[0]?.myAttendance;return{ok:true,data:{sessionId,canViewAll:true,items:base?[{...base,userId:currentUserId,displayName:"You",avatarUrl:null},{...base,userId:"user-mira",displayName:"Mira Chen",avatarUrl:null,role:"host"}]:[]}}}const client=getSupabaseClient();if(!client)return fail("DATA_SOURCE_NOT_CONFIGURED","Attendance is unavailable until Picom reconnects.");const result=await client.rpc("get_meeting_attendance_history",{target_session_id:sessionId});const page=mapAttendance(result.data,sessionId);return result.error||!page?fail("MEETING_ATTENDANCE_LOAD_FAILED","You do not have permission to view this attendance list."):{ok:true,data:page}},
  async open(item:MeetingHistoryItem):Promise<HistoryResult<boolean>>{if(!safeSegment.test(item.communityId)||!safeSegment.test(item.roomId)||(item.sessionId&&!safeSegment.test(item.sessionId)))return fail("MEETING_HISTORY_LINK_INVALID","This meeting history link is invalid.");if((item.status==="ended"||item.status==="failed")&&item.hasDurableChat&&item.sessionId){if(dataSourceService.getStatus().isMock){meetingChatContextService.seedMock({roomId:item.roomId,sessionId:item.sessionId,communityId:item.communityId,channelId:item.channelId??"mock-history-chat",threadId:null,contextKind:"linked_channel",title:`${item.title} chat`,preserveAfterMeeting:true,guestAccessExpiresAt:null,canRead:true,canWrite:false,isGuest:false})}const context=await meetingChatContextService.resolve(item.roomId,item.sessionId);if(!context.ok)return fail(context.error.code,context.error.message);return meetingChatContextService.openDeepLink({communityId:context.data.communityId,channelId:context.data.channelId,roomId:item.roomId,sessionId:item.sessionId})}if(item.status==="ended"||item.status==="failed")return fail("MEETING_HISTORY_CHAT_UNAVAILABLE","This ended session has no accessible durable chat.");const channel=item.channelId&&safeSegment.test(item.channelId)?`/channel/${encodeURIComponent(item.channelId)}`:"";const session=item.sessionId?`/session/${encodeURIComponent(item.sessionId)}`:"";const link=`picom://meeting/${encodeURIComponent(item.communityId)}${channel}/room/${encodeURIComponent(item.roomId)}${session}`;const opened=deepLinkService.handleDeepLink(link);return opened.ok?{ok:true,data:true}:fail("MEETING_HISTORY_LINK_FAILED","Picom could not open this meeting.")},
};
