import { useState } from "react";
import { meetingChatContextService } from "../../services/meeting/meetingChatContextService";
import { meetingPreJoinService } from "../../services/meeting/meetingPreJoinService";
import type { MeetingClientSnapshot } from "../../types/meetingClient";
import { AppIcon } from "../AppIcon";
import { MeetingInviteExperience } from "./MeetingInviteExperience";
import type { NoiseShieldMode } from "../../types/noiseShield";
import { MeetingHistoryPanel } from "./MeetingHistoryPanel";

const noiseShieldLabels: Record<NoiseShieldMode,string>={off:"Off",standard:"Standard",enhanced:"Enhanced","voice-focus":"Voice Focus"};

export function MeetingInfoPanel({snapshot}:{snapshot:MeetingClientSnapshot}){const[copyStatus,setCopyStatus]=useState("");const roomInfo=meetingPreJoinService.getSnapshot().roomInfo;const participants=snapshot.participantIds.map((id)=>snapshot.participantsById[id]).filter(Boolean);const host=participants.find((item)=>item.role==="host")?.displayName??roomInfo?.hostName??"Host unavailable";const capabilities=Object.entries(snapshot.capabilities).filter(([,enabled])=>enabled).map(([key])=>key.replace(/^can/,"").replace(/([A-Z])/g," $1").trim());const copy=async()=>{if(!snapshot.context)return;const result=await meetingChatContextService.copyDeepLink({communityId:snapshot.context.communityId,channelId:snapshot.context.channelId,roomId:snapshot.context.roomId,sessionId:snapshot.context.sessionId});setCopyStatus(result.ok?"Meeting link copied.":result.error.message)};return <section className="meeting-info-panel" aria-label="Meeting information"><dl><div><dt>Room</dt><dd>{snapshot.context?.roomTitle??"Meeting"}</dd></div><div><dt>Community</dt><dd>{snapshot.context?.communityName??"Picom"}</dd></div><div><dt>Host</dt><dd>{host}</dd></div><div><dt>Schedule</dt><dd>{snapshot.phase==="connected"||snapshot.phase==="reconnecting"?"Live now":"Not live"}</dd></div><div><dt>Join policy</dt><dd>{roomInfo?.joinPolicy?.replace(/_/g," ")??"Membership policy"}</dd></div><div><dt>Status</dt><dd>{snapshot.phase}</dd></div><div><dt>Your role</dt><dd>{snapshot.role??"Not assigned"}</dd></div><div><dt>Noise Shield requested</dt><dd>{noiseShieldLabels[snapshot.noiseShield.requestedMode]}</dd></div><div><dt>Noise Shield applied</dt><dd>{noiseShieldLabels[snapshot.noiseShield.appliedMode]} ({snapshot.noiseShield.provider.replace(/_/g," ")})</dd></div>{snapshot.noiseShield.fallbackReason?<div><dt>Noise Shield fallback</dt><dd>{snapshot.noiseShield.fallbackReason}</dd></div>:null}</dl><section><h3>Enabled capabilities<span>{capabilities.length}</span></h3><div className="meeting-info-capabilities">{capabilities.map((item)=><span key={item}>{item}</span>)}</div></section><button type="button" className="meeting-copy-link" onClick={()=>void copy()}><AppIcon name="reply" size="sm"/>Copy meeting link</button>{copyStatus?<p role="status">{copyStatus}</p>:null}<MeetingInviteExperience snapshot={snapshot} hostName={host}/>{snapshot.context?<MeetingHistoryPanel communityId={snapshot.context.communityId} scope="mine" compact canViewAttendance={snapshot.capabilities.canViewAttendance}/>:null}</section>}
