import { useCallback, useEffect, useRef, useState, useSyncExternalStore, type KeyboardEvent as ReactKeyboardEvent, type MouseEventHandler } from "react";
import { useDialogFocusTrap } from "../../hooks/useDialogFocusTrap";
import { meetingControlService, type MeetingControlDevices, type MeetingControlResult, type MeetingShareSources } from "../../services/meeting/meetingControlService";
import type { MeetingReactionKind } from "../../types/meeting";
import type { MeetingClientSnapshot } from "../../types/meetingClient";
import { AppIcon, type IconName } from "../AppIcon";
import { meetingHostControlService } from "../../services/meeting/meetingHostControlService";
import { MEETING_REACTION_OPTIONS } from "../../services/meeting/meetingReactionCatalog";
import "./MeetingControlDock.css";

type Menu = "microphone"|"camera"|"share"|"noise"|"reactions"|"more"|null;

const noiseShieldLabels={off:"Off",standard:"Standard",enhanced:"Enhanced","voice-focus":"Voice Focus"} as const;

function ControlButton({icon,label,active=false,off=false,disabled=false,busy=false,shortcut,controlAction,onClick}:{icon:IconName;label:string;active?:boolean;off?:boolean;disabled?:boolean;busy?:boolean;shortcut?:string;controlAction?:string;onClick:MouseEventHandler<HTMLButtonElement>}){return <button type="button" className={`${active?"is-active ":""}${off?"is-off ":""}${busy?"is-loading":""}`.trim()} disabled={disabled||busy} aria-label={label} aria-pressed={active} aria-keyshortcuts={shortcut} data-meeting-shortcut-action={controlAction} onClick={onClick}><AppIcon name={icon} size="md" /><span>{busy?"Working":label}</span></button>}

function MeetingControlConfirmDialog({action,busy,onClose,onConfirm}:{action:"end"|"mute-all"|"cancel";busy:boolean;onClose:()=>void;onConfirm:()=>void}){
  const dialogRef=useDialogFocusTrap<HTMLDivElement>(onClose);
  const title=action==="end"?"End this meeting for everyone?":action==="cancel"?"Cancel this scheduled meeting?":"Mute all lower-role participants?";
  const body=action==="end"?"All participants will be marked as left and new meeting tokens will be denied for this session.":action==="cancel"?"The linked event, active invites, and waiting requests will be cancelled. This cannot be undone.":"Only lower-ranked participants are affected. Picom cannot and will not remotely unmute them; each person must unmute themselves.";
  return <div className="meeting-control-confirm" role="presentation" onMouseDown={onClose}><div ref={dialogRef} tabIndex={-1} role="alertdialog" aria-modal="true" aria-labelledby="meeting-destructive-title" aria-describedby="meeting-destructive-description" onMouseDown={(event)=>event.stopPropagation()}><AppIcon name={action==="mute-all"?"microphone":"close"} size="lg" /><strong id="meeting-destructive-title">{title}</strong><p id="meeting-destructive-description">{body}</p><footer><button type="button" data-dialog-initial-focus onClick={onClose}>Go back</button><button type="button" className="danger" disabled={busy} onClick={onConfirm}>Confirm {action==="mute-all"?"mute":"action"}</button></footer></div></div>;
}

export function MeetingControlDock({snapshot,focusMode,onCycleLayout,onToggleDock,onToggleFocus,onLeave}:{snapshot:MeetingClientSnapshot;focusMode:boolean;onCycleLayout:()=>void;onToggleDock:()=>void;onToggleFocus:()=>void;onLeave:()=>void}) {
  const root=useRef<HTMLElement>(null);const menuTrigger=useRef<HTMLButtonElement|null>(null);const[menu,setMenu]=useState<Menu>(null);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");const[devices,setDevices]=useState<MeetingControlDevices>(()=>meetingControlService.getDevices());const[shares,setShares]=useState<MeetingShareSources|null>(null);const[confirmAction,setConfirmAction]=useState<"end"|"mute-all"|"cancel"|null>(null);const[reactionCooldownMs,setReactionCooldownMs]=useState(0);const hostState=useSyncExternalStore(meetingHostControlService.subscribe,meetingHostControlService.getSnapshot,meetingHostControlService.getSnapshot);const roomLocked=hostState.locked;
  const connected=snapshot.phase==="connected"||snapshot.phase==="reconnecting";const local=snapshot.participantIds.map((id)=>snapshot.participantsById[id]).find((participant)=>participant?.isLocal);const stageAudience=snapshot.context?.roomMode==="stage"&&local&&!(["host","cohost","speaker"] as const).includes(local.role as "host"|"cohost"|"speaker"),stageRequest=stageAudience?snapshot.stageQueue?.find((entry)=>entry.participantId===local.id):undefined,handRaised=stageAudience?stageRequest?.stageRequestStatus==="requested":local?.handRaised??snapshot.handRaised;
  useEffect(()=>meetingControlService.subscribeDevices(setDevices),[]);useEffect(()=>{void meetingControlService.refreshDevices().then(setDevices)},[]);
  useEffect(()=>{if(menu!=="share"&&shares){void meetingControlService.cancelShareSelection(shares.requestId);setShares(null)}},[menu,shares]);
  useEffect(()=>{if(reactionCooldownMs<=0)return;const timer=window.setTimeout(()=>setReactionCooldownMs((value)=>Math.max(0,value-100)),100);return()=>window.clearTimeout(timer)},[reactionCooldownMs]);
  const closeMenu=useCallback((restore=false)=>{setMenu(null);if(restore)window.requestAnimationFrame(()=>menuTrigger.current?.isConnected&&menuTrigger.current.focus())},[]);
  const closeConfirm=useCallback(()=>setConfirmAction(null),[]);
  useEffect(()=>{const pointer=(event:PointerEvent)=>{if(root.current&&!root.current.contains(event.target as Node))closeMenu(false)};const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&menu)closeMenu(true)};document.addEventListener("pointerdown",pointer);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",pointer);document.removeEventListener("keydown",key)}},[closeMenu,menu]);
  useEffect(()=>{if(!menu)return;window.requestAnimationFrame(()=>root.current?.querySelector<HTMLButtonElement>(".meeting-control-menu button:not(:disabled)")?.focus())},[menu]);
  const run=async(key:string,operation:()=>Promise<MeetingControlResult<unknown>>|MeetingControlResult<unknown>)=>{setBusy(key);setError("");const result=await operation();if(!result.ok)setError(result.error.message);setBusy(null);return result.ok};
  const sendReaction=async(kind:MeetingReactionKind)=>{if(reactionCooldownMs>0)return;setBusy("reaction");setError("");const result=await meetingControlService.sendReaction(kind);setBusy(null);if(!result.ok){setError(result.error.message);setReactionCooldownMs(result.error.retryAfterMs??700);return}setReactionCooldownMs(400);closeMenu(true)};
  const openShare=async(trigger:HTMLButtonElement)=>{menuTrigger.current=trigger;if(snapshot.localMedia.screenSharing){await run("share",()=>meetingControlService.stopScreenShare());return}setBusy("share");setError("");const result=await meetingControlService.listShareSources();setBusy(null);if(!result.ok){setError(result.error.message);return}setShares(result.data);setMenu("share")};
  const chooseShare=async(sourceId:string)=>{if(!shares)return;const requestId=shares.requestId;setShares(null);closeMenu(true);await run("share",()=>meetingControlService.startScreenShare(requestId,sourceId))};
  const toggleMenu=(next:Exclude<Menu,null>,trigger:HTMLButtonElement)=>{menuTrigger.current=trigger;if(menu===next){closeMenu(true);return}setMenu(next)};
  const navigateMenu=(event:ReactKeyboardEvent<HTMLElement>)=>{const menuElement=(event.target as HTMLElement).closest<HTMLElement>(".meeting-control-menu");if(!menuElement||!["ArrowDown","ArrowUp","Home","End"].includes(event.key))return;const buttons=Array.from(menuElement.querySelectorAll<HTMLButtonElement>("button:not(:disabled)"));if(!buttons.length)return;event.preventDefault();const current=buttons.indexOf(document.activeElement as HTMLButtonElement);const index=event.key==="Home"?0:event.key==="End"?buttons.length-1:event.key==="ArrowDown"?(current+1+buttons.length)%buttons.length:(current-1+buttons.length)%buttons.length;buttons[index]?.focus()};
  return <footer id="meeting-control-dock" tabIndex={-1} ref={root} className="meeting-control-dock meeting-control-dock-v2" aria-label="Meeting controls" onKeyDown={navigateMenu}>
    {error?<p className="meeting-control-dock-v2__error" role="alert">{error}<button type="button" aria-label="Dismiss control error" onClick={()=>setError("")}><AppIcon name="close" size="xs" /></button></p>:null}
    <div className="meeting-control-dock__cluster meeting-control-dock-v2__devices">
      <span className="meeting-control-split"><ControlButton icon="microphone" label={snapshot.localMedia.muted?"Unmute":"Mute"} shortcut="M" controlAction="microphone" off={snapshot.localMedia.muted} disabled={!connected||!snapshot.capabilities.canPublishAudio} busy={busy==="microphone"} onClick={()=>void run("microphone",()=>meetingControlService.setMuted(!snapshot.localMedia.muted))}/><button type="button" className="meeting-control-split__menu" aria-label="Choose microphone" aria-expanded={menu==="microphone"} onClick={(event)=>toggleMenu("microphone",event.currentTarget)}><AppIcon name="chevronDown" size="xs" /></button></span>
      <span className="meeting-control-split"><ControlButton icon="image" label={snapshot.localMedia.cameraEnabled?"Camera off":"Camera on"} shortcut="V" controlAction="camera" active={snapshot.localMedia.cameraEnabled} disabled={!connected||!snapshot.capabilities.canPublishVideo} busy={busy==="camera"} onClick={()=>void run("camera",()=>meetingControlService.setCameraEnabled(!snapshot.localMedia.cameraEnabled))}/><button type="button" className="meeting-control-split__menu" aria-label="Choose camera" aria-expanded={menu==="camera"} onClick={(event)=>toggleMenu("camera",event.currentTarget)}><AppIcon name="chevronDown" size="xs" /></button></span>
      {menu==="microphone"?<div className="meeting-control-menu is-device" role="menu" aria-label="Microphones">{devices.microphones.length?devices.microphones.map((device)=><button type="button" role="menuitemradio" aria-checked={device.deviceId===devices.selectedMicrophoneId} key={device.deviceId} onClick={()=>{closeMenu(true);void run("microphone-device",()=>meetingControlService.selectMicrophone(device.deviceId))}}>{device.label}<small>{device.deviceId===devices.selectedMicrophoneId?"Active":""}</small></button>):<p>No microphone is available.</p>}</div>:null}
      {menu==="camera"?<div className="meeting-control-menu is-device is-camera" role="menu" aria-label="Cameras">{devices.cameras.length?devices.cameras.map((device)=><button type="button" role="menuitemradio" aria-checked={device.deviceId===devices.selectedCameraId} key={device.deviceId} onClick={()=>{closeMenu(true);void run("camera-device",()=>meetingControlService.selectCamera(device.deviceId))}}>{device.label}<small>{device.deviceId===devices.selectedCameraId?"Active":""}</small></button>):<p>No camera is available.</p>}</div>:null}
    </div>
    <div className="meeting-control-dock__cluster meeting-control-dock__cluster--center">
      <ControlButton icon="maximize" label={snapshot.localMedia.screenSharing?"Stop share":"Share"} shortcut="S" controlAction="screen-share" active={snapshot.localMedia.screenSharing} disabled={!connected||!snapshot.capabilities.canShareScreen} busy={busy==="share"} onClick={(event)=>void openShare(event.currentTarget)}/>
      <ControlButton icon="lock" label={`Noise Shield: ${noiseShieldLabels[snapshot.noiseShield.appliedMode]}`} active={snapshot.noiseShield.appliedMode!=="off"} disabled={!connected||!snapshot.capabilities.canPublishAudio} busy={busy==="noise"} onClick={(event)=>toggleMenu("noise",event.currentTarget)}/>
      <ControlButton icon="smile" label={reactionCooldownMs>0?`Reactions ready in ${(reactionCooldownMs/1000).toFixed(1)} seconds`:"Reactions"} disabled={!connected||!snapshot.capabilities.canReact||reactionCooldownMs>0} busy={busy==="reaction"} onClick={(event)=>toggleMenu("reactions",event.currentTarget)}/>
      <ControlButton icon="users" label={stageAudience?(handRaised?"Cancel request":"Request to speak"):(handRaised?"Lower hand":"Raise hand")} shortcut="H" controlAction="hand" active={Boolean(handRaised)} disabled={!connected||!snapshot.capabilities.canRaiseHand} busy={busy==="hand"} onClick={()=>void run("hand",()=>meetingControlService.toggleHand())}/>
      <ControlButton icon="more" label="More" onClick={(event)=>toggleMenu("more",event.currentTarget)}/>
      {menu==="share"&&shares?<div className="meeting-control-menu is-share" role="menu" aria-label="Share a screen or window">{shares.sources.map((source)=><button type="button" role="menuitem" key={source.id} onClick={()=>void chooseShare(source.id)}>{source.thumbnailDataUrl?<img src={source.thumbnailDataUrl} alt="" />:<AppIcon name="maximize" size="sm" />}<span>{source.name}</span><small>{source.type}</small></button>)}</div>:null}
      {menu==="noise"?<div className="meeting-control-menu is-device is-noise" role="menu" aria-label="Noise Shield mode">{snapshot.noiseShield.availableModes.map((mode)=><button type="button" role="menuitemradio" aria-checked={snapshot.noiseShield.requestedMode===mode} key={mode} onClick={()=>{closeMenu(true);void run("noise",()=>meetingControlService.setNoiseShieldMode(mode))}}>{noiseShieldLabels[mode]}<small>{snapshot.noiseShield.appliedMode===mode?"Applied":snapshot.noiseShield.requestedMode===mode?"Requested":""}</small></button>)}{snapshot.noiseShield.fallbackReason?<p role="status">{snapshot.noiseShield.fallbackReason}</p>:null}</div>:null}
      {menu==="reactions"?<div className="meeting-control-menu is-reactions" role="menu" aria-label="Meeting reactions">{MEETING_REACTION_OPTIONS.map((reaction)=><button type="button" role="menuitem" aria-label={reaction.label} disabled={busy==="reaction"||reactionCooldownMs>0} key={reaction.kind} onClick={()=>void sendReaction(reaction.kind)}><span aria-hidden="true">{reaction.emoji}</span><small>{reaction.label}</small></button>)}{reactionCooldownMs>0?<p className="meeting-reaction-cooldown" role="status">Ready in {(reactionCooldownMs/1000).toFixed(1)}s</p>:null}</div>:null}
      {menu==="more"?<div className="meeting-control-menu is-more" role="menu" aria-label="More meeting controls"><button type="button" role="menuitemcheckbox" aria-checked={snapshot.localMedia.deafened} onClick={()=>{setMenu(null);const result=meetingControlService.setDeafened(!snapshot.localMedia.deafened);if(!result.ok)setError(result.error.message)}}><AppIcon name="headphones" size="sm" />{snapshot.localMedia.deafened?"Restore meeting audio":"Deafen meeting audio"}</button><button type="button" role="menuitem" onClick={()=>{setMenu(null);onCycleLayout()}}><AppIcon name="maximize" size="sm" />Change layout ({snapshot.layout})</button><button type="button" role="menuitem" onClick={()=>{setMenu(null);onToggleDock()}}><AppIcon name="users" size="sm" />{snapshot.rightDock==="none"?"Open people panel":"Close meeting panel"}</button><button type="button" role="menuitem" onClick={()=>{setMenu(null);onToggleFocus()}}><AppIcon name="eye" size="sm" />{focusMode?"Exit focus mode":"Enter focus mode"}</button>{snapshot.capabilities.canLockRoom?<button type="button" role="menuitem" onClick={()=>{setMenu(null);void run("lock-room",()=>meetingControlService.setRoomLocked(!roomLocked))}}><AppIcon name="lock" size="sm" />{roomLocked?"Unlock room":"Lock room"}</button>:null}{snapshot.capabilities.canManageParticipants?<button type="button" role="menuitem" onClick={()=>{setMenu(null);setConfirmAction("mute-all")}}><AppIcon name="microphone" size="sm" />Mute all lower roles</button>:null}{snapshot.role==="host"&&hostState.roomStatus==="scheduled"?<button type="button" className="danger" role="menuitem" onClick={()=>{setMenu(null);setConfirmAction("cancel")}}><AppIcon name="trash" size="sm" />Cancel scheduled meeting</button>:null}{snapshot.capabilities.canEndRoom?<button type="button" className="danger" role="menuitem" onClick={()=>{setMenu(null);setConfirmAction("end")}}><AppIcon name="close" size="sm" />End for everyone</button>:null}</div>:null}
    </div>
    <div className="meeting-control-dock__cluster meeting-control-dock__cluster--end"><ControlButton icon="close" label="Leave" shortcut="Control+Shift+L" controlAction="leave" onClick={onLeave}/></div>
    {confirmAction?<MeetingControlConfirmDialog action={confirmAction} busy={busy!==null} onClose={closeConfirm} onConfirm={()=>void run(confirmAction,()=>confirmAction==="end"?meetingControlService.endForEveryone():confirmAction==="cancel"?meetingControlService.cancelScheduledRoom("Cancelled by host from meeting controls"):meetingControlService.muteAll(snapshot)).then((done)=>{if(done)closeConfirm()})}/>:null}
  </footer>;
}
