import { useEffect, useRef, useState } from "react";
import { meetingChatContextService } from "../../services/meeting/meetingChatContextService";
import type { MessageSummary } from "../../services/messageService";
import type { MeetingChatContext } from "../../types/meetingChat";
import type { MeetingClientParticipant, MeetingClientSnapshot } from "../../types/meetingClient";
import { AppIcon } from "../AppIcon";
import { VerifiedAvatarFrame } from "../VerifiedAvatarFrame";
import { VerifiedBadge } from "../VerifiedBadge";

function ChatMessage({message,participant}:{message:MessageSummary;participant?:MeetingClientParticipant}){const name=participant?.displayName??"Meeting participant";return <article className="meeting-chat-message"><VerifiedAvatarFrame userId={participant?.userId} label={name} avatarUrl={participant?.avatarUrl} avatarSeed={participant?.identity??message.authorId} verification={participant?.verification} size="compact" avatarSize={30}/><span><span><strong>{name}</strong><VerifiedBadge verification={participant?.verification} size="xs"/><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></span><p>{message.deletedAt?"Message deleted":message.body}</p>{message.editedAt?<small>Edited</small>:null}</span></article>}

export function MeetingChatPanel({snapshot}:{snapshot:MeetingClientSnapshot}){const[context,setContext]=useState<MeetingChatContext|null>(null);const[messages,setMessages]=useState<readonly MessageSummary[]>([]);const[body,setBody]=useState("");const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[error,setError]=useState("");const bottom=useRef<HTMLDivElement>(null);const participants=snapshot.participantIds.map((id)=>snapshot.participantsById[id]).filter(Boolean);
  const load=async(target:MeetingChatContext)=>{const result=await meetingChatContextService.listMessages(target,{limit:60});if(result.ok){setMessages(result.data.items);const last=result.data.items[result.data.items.length-1]?.id??null;void meetingChatContextService.markRead(target,last)}else setError(result.error.message);setLoading(false)};
  useEffect(()=>{let cleanup:()=>void=()=>undefined;let timer:ReturnType<typeof setInterval>|null=null;let cancelled=false;setLoading(true);setError("");if(!snapshot.context){setLoading(false);return}void meetingChatContextService.resolveForMeeting(snapshot.context).then((result)=>{if(cancelled)return;if(!result.ok){setError(result.error.message);setLoading(false);return}setContext(result.data);void load(result.data);cleanup=meetingChatContextService.subscribeMessages(result.data,()=>void load(result.data));timer=setInterval(()=>void load(result.data),5000)});return()=>{cancelled=true;cleanup();if(timer)clearInterval(timer)}},[snapshot.context?.roomId,snapshot.context?.sessionId]);
  useEffect(()=>{bottom.current?.scrollIntoView({block:"end"})},[messages.length]);
  const send=async()=>{if(!context||!body.trim()||sending)return;setSending(true);setError("");const text=body.trim();const result=await meetingChatContextService.sendMessage({context,body:text,clientMessageId:crypto.randomUUID()});if(result.ok){setMessages((current)=>current.some((item)=>item.id===result.data.id)?current:[...current,result.data]);setBody("");void meetingChatContextService.markRead(context,result.data.id)}else setError(result.error.message);setSending(false)};
  return <section className="meeting-chat-panel" aria-label="Meeting chat">{error?<p className="meeting-dock-error" role="alert">{error}</p>:null}<div className="meeting-chat-list" aria-live="polite">{loading?<div className="meeting-dock-empty"><strong>Loading meeting chat</strong></div>:messages.length?messages.map((message)=><ChatMessage key={message.id} message={message} participant={participants.find((item)=>item.userId===message.authorId)}/>):<div className="meeting-dock-empty"><AppIcon name="inbox" size="lg"/><strong>No meeting messages yet</strong><span>Start the durable linked conversation.</span></div>}<div ref={bottom}/></div><footer><textarea rows={2} value={body} disabled={!context?.canWrite||sending||!snapshot.capabilities.canSendChat} placeholder={context?.canWrite?"Message meeting chat":"Meeting chat is read only"} aria-label="Meeting chat message" onChange={(event)=>setBody(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send()}}}/><button type="button" disabled={!body.trim()||sending||!context?.canWrite||!snapshot.capabilities.canSendChat} aria-label="Send meeting chat message" onClick={()=>void send()}><AppIcon name="send" size="sm"/></button></footer></section>;
}
