import { useEffect, useState } from "react";
import { meetingHistoryService } from "../../services/meeting/meetingHistoryService";
import type { MeetingAttendanceItem, MeetingHistoryItem, MeetingHistoryPage, MeetingHistoryScope } from "../../types/meetingHistory";
import { AppIcon } from "../AppIcon";
import "./MeetingHistoryPanel.css";

const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"Time pending";
const formatDuration=(seconds:number|null)=>seconds===null?"Duration pending":seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60?`${seconds%60}s`:""}`.trim();

export function MeetingHistoryPanel({communityId,scope="community",compact=false,canViewAttendance=false}:{communityId:string;scope?:MeetingHistoryScope;compact?:boolean;canViewAttendance?:boolean}){
  const[page,setPage]=useState<MeetingHistoryPage|null>(null),[error,setError]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[attendance,setAttendance]=useState<Record<string,readonly MeetingAttendanceItem[]>>({}),[attendanceLoading,setAttendanceLoading]=useState<string|null>(null);
  useEffect(()=>{let active=true;setLoading(true);setError("");void meetingHistoryService.list(communityId,scope,compact?3:20).then((result)=>{if(!active)return;if(result.ok)setPage(result.data);else setError(result.error.message);setLoading(false)});return()=>{active=false}},[communityId,scope,compact]);
  const open=async(item:MeetingHistoryItem)=>{const result=await meetingHistoryService.open(item);setStatus(result.ok?(item.status==="ended"||item.status==="failed"?"Opening durable meeting chat...":"Opening meeting..."):result.error.message)};
  const loadAttendance=async(item:MeetingHistoryItem)=>{if(!item.sessionId)return;setAttendanceLoading(item.sessionId);const result=await meetingHistoryService.attendance(item.sessionId);if(result.ok)setAttendance((current)=>({...current,[item.sessionId!]:result.data.items}));else setStatus(result.error.message);setAttendanceLoading(null)};
  const items=page?[...page.upcoming,...page.items].slice(0,compact?3:40):[];
  return <section className={`meeting-history-panel${compact?" is-compact":""}`} aria-label={scope==="mine"?"Your recent meeting sessions":"Community meeting history"}><header><div><small>{scope==="mine"?"Your sessions":"Meeting history"}</small><h3>{scope==="mine"?"Recent participation":"Recent and upcoming sessions"}</h3></div><span><AppIcon name="voice" size="sm"/>{items.length}</span></header>
    {loading?<p className="meeting-history-state" role="status">Loading verified session history...</p>:error?<p className="meeting-history-state is-error" role="alert">{error}</p>:items.length===0?<p className="meeting-history-state">No visible meeting sessions yet.</p>:<div className="meeting-history-list">{items.map((item)=>{const rows=item.sessionId?attendance[item.sessionId]:undefined;const canInspect=Boolean(item.sessionId)&&(scope==="mine"||canViewAttendance||page?.canViewAttendance);return <article key={`${item.roomId}:${item.sessionId??"upcoming"}`} className={`meeting-history-item is-${item.status}`}><div className="meeting-history-item__main"><span className="meeting-history-mode"><AppIcon name="voice" size="sm"/></span><div><div className="meeting-history-title"><strong>{item.title}</strong><span>{item.status}</span>{item.outcomeVerified?<em title="Verified LiveKit webhook outcome">Verified outcome</em>:null}</div><p>{item.hostName} · {formatDate(item.scheduledFor??item.startedAt??item.endedAt)}</p><small>{item.status==="upcoming"?"Scheduled":`${formatDuration(item.durationSeconds)} · ${item.attendanceCount} attendee${item.attendanceCount===1?"":"s"}`}</small></div></div><div className="meeting-history-item__actions">{(item.status==="upcoming"||item.status==="live"||item.hasDurableChat)?<button type="button" onClick={()=>void open(item)}><AppIcon name="reply" size="xs"/>{item.status==="ended"||item.status==="failed"?"Open chat":"Open meeting"}</button>:null}{canInspect?<button type="button" className="secondary" disabled={attendanceLoading===item.sessionId} onClick={()=>void loadAttendance(item)}><AppIcon name="users" size="xs"/>{scope==="mine"&&!page?.canViewAttendance?"My attendance":"Attendance"}</button>:null}</div>{item.captionsUsed?<p className="meeting-history-retention">Captions were ephemeral. No transcript was retained.</p>:null}{rows?<div className="meeting-attendance-list">{rows.map((row,index)=><div key={`${row.userId??"guest"}:${index}`}><span aria-hidden="true">{row.displayName.slice(0,1).toUpperCase()}</span><p><strong>{row.displayName}</strong><small>{row.role} · {formatDuration(row.durationSeconds)} · {row.reconnectCount} reconnect{row.reconnectCount===1?"":"s"}</small></p><em>{row.finalState}</em></div>)}</div>:null}</article>})}</div>}
    <footer><span>No recordings or retained transcript text.</span>{status?<strong role="status">{status}</strong>:null}</footer>
  </section>;
}
