import { useEffect, useRef, useSyncExternalStore } from "react";
import { meetingPreJoinService } from "../../services/meeting/meetingPreJoinService";
import { AppIcon } from "../AppIcon";
import "./MeetingPreJoin.css";

function CameraPreview({stream}:{stream:MediaStream|null}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current)ref.current.srcObject=stream;return()=>{if(ref.current)ref.current.srcObject=null}},[stream]);return <div className="meeting-prejoin-preview">{stream?<video ref={ref} autoPlay muted playsInline aria-label="Camera preview" />:<div><span><AppIcon name="eye" size="xl" /></span><strong>Camera preview is off</strong><p>Picom will request camera access only when you choose Preview camera.</p></div>}</div>}

export function MeetingPreJoin({onCancel}:{onCancel?:()=>void}){
  const state=useSyncExternalStore(meetingPreJoinService.subscribe,meetingPreJoinService.getSnapshot,meetingPreJoinService.getSnapshot);
  const info=state.roomInfo;
  const policy=info?.waitingRoomEnabled||info?.joinPolicy==="approval_required"?"The host must admit you before media connects.":info?.joinPolicy==="invite_only"?"A valid invitation is required for this meeting.":info?.joinPolicy==="members"?"Community membership is required.":"This meeting allows eligible users to join directly.";
  return <section className="meeting-prejoin" aria-labelledby="meeting-prejoin-title">
    <div className="meeting-prejoin__media"><CameraPreview stream={state.cameraPreviewStream}/><div className="meeting-prejoin__preview-actions"><button type="button" disabled={state.busy||state.cameraPermission==="unsupported"} onClick={()=>state.cameraPreviewActive?meetingPreJoinService.stopCameraPreview():void meetingPreJoinService.startCameraPreview()}><AppIcon name="eye" size="sm" />{state.cameraPreviewActive?"Stop preview":"Preview camera"}</button></div></div>
    <div className="meeting-prejoin__setup">
      <header><small>{info?.communityName??"Picom community"}</small><h2 id="meeting-prejoin-title">{info?.roomTitle??"Prepare to join"}</h2><p>{info?`Hosted by ${info.hostName}`:"Review your devices before joining."}</p></header>
      <div className="meeting-prejoin__policy"><AppIcon name={info?.waitingRoomEnabled?"users":"lock"} size="sm" /><span><strong>{info?.joinPolicy?.replace(/_/g," ")??"Meeting policy"}</strong><small>{policy}</small></span></div>
      <div className="meeting-prejoin__fields">
        <label><span>Microphone</span><select aria-label="PreJoin microphone" value={state.selectedMicrophoneId} disabled={!state.microphones.length||state.busy} onChange={(event)=>void meetingPreJoinService.selectMicrophone(event.target.value)}>{!state.microphones.length?<option value="default">No microphone available</option>:state.microphones.map((device)=><option key={device.deviceId} value={device.deviceId}>{device.label}</option>)}</select></label>
        <label><span>Camera</span><select aria-label="PreJoin camera" value={state.selectedCameraId} disabled={!state.cameras.length||state.busy} onChange={(event)=>void meetingPreJoinService.selectCamera(event.target.value)}>{!state.cameras.length?<option value="default">No camera available</option>:state.cameras.map((device)=><option key={device.deviceId} value={device.deviceId}>{device.label}</option>)}</select></label>
        <label><span>Speaker</span><select aria-label="PreJoin speaker" value={state.selectedSpeakerId} disabled={!state.speakers.length||state.busy} onChange={(event)=>meetingPreJoinService.selectSpeaker(event.target.value)}>{!state.speakers.length?<option value="default">System default output</option>:state.speakers.map((device)=><option key={device.deviceId} value={device.deviceId}>{device.label}</option>)}</select></label>
      </div>
      <div className="meeting-prejoin__tests"><button type="button" disabled={state.busy} onClick={()=>state.microphonePermission==="granted"?(state.microphoneTestActive?meetingPreJoinService.stopMicrophoneTest():void meetingPreJoinService.testMicrophone()):void meetingPreJoinService.requestMicrophoneAccess()}><AppIcon name="microphone" size="sm" />{state.microphonePermission!=="granted"?"Allow microphone":state.microphoneTestActive?"Stop microphone test":"Test microphone"}</button><button type="button" disabled={state.speakerTestActive||state.busy} onClick={()=>void meetingPreJoinService.testSpeaker()}><AppIcon name="headphones" size="sm" />{state.speakerTestActive?"Playing test...":"Test speaker"}</button>{state.microphoneTestActive?<meter min={0} max={1} value={state.microphoneLevel} aria-label="Microphone level"/>:null}</div>
      <div className="meeting-prejoin__toggles"><label><span><strong>Join muted</strong><small>Keep your microphone off when media connects.</small></span><input type="checkbox" checked={state.joinMuted} onChange={(event)=>meetingPreJoinService.setJoinMuted(event.target.checked)}/></label><label><span><strong>Join with camera off</strong><small>Camera publishing remains disabled until you enable it.</small></span><input type="checkbox" checked={state.joinCameraOff} onChange={(event)=>meetingPreJoinService.setJoinCameraOff(event.target.checked)}/></label><label><span><strong>Noise Shield</strong><small>Use supported echo cancellation, noise suppression, and automatic gain control.</small></span><input type="checkbox" checked={state.noiseShieldMode==="standard"} onChange={(event)=>meetingPreJoinService.setNoiseShield(event.target.checked)}/></label></div>
      {state.error?<p className="meeting-prejoin__error" role="alert">{state.error.message}</p>:null}
      <footer><button type="button" className="secondary" onClick={()=>{meetingPreJoinService.dispose();onCancel?.()}}>Cancel</button><button type="button" className="primary" disabled={state.busy||!state.request} onClick={()=>void meetingPreJoinService.submit()}>{state.busy?"Preparing...":info?.waitingRoomEnabled?"Request to join":"Join meeting"}</button></footer>
    </div>
  </section>;
}
