import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import { meetingControlService, type MeetingControlDevices, type MeetingControlResult, type MeetingShareSources } from "../../services/meeting/meetingControlService";
import type { MeetingReactionKind } from "../../types/meeting";
import type { MeetingClientSnapshot } from "../../types/meetingClient";
import { AppIcon, type IconName } from "../AppIcon";
import { meetingHostControlService } from "../../services/meeting/meetingHostControlService";
import "./MeetingControlDock.css";

type Menu = "microphone"|"camera"|"share"|"reactions"|"more"|null;
const reactions: readonly Readonly<{kind:MeetingReactionKind;emoji:string;label:string}>[]=[{kind:"thumbs_up",emoji:"👍",label:"Thumbs up"},{kind:"heart",emoji:"❤️",label:"Heart"},{kind:"celebrate",emoji:"🎉",label:"Celebrate"},{kind:"laugh",emoji:"😄",label:"Laugh"},{kind:"surprised",emoji:"😮",label:"Surprised"},{kind:"clap",emoji:"👏",label:"Clap"}];

function ControlButton({icon,label,active=false,off=false,disabled=false,busy=false,onClick}:{icon:IconName;label:string;active?:boolean;off?:boolean;disabled?:boolean;busy?:boolean;onClick:()=>void}){return <button type="button" className={`${active?"is-active ":""}${off?"is-off ":""}${busy?"is-loading":""}`.trim()} disabled={disabled||busy} aria-label={label} aria-pressed={active} onClick={onClick}><AppIcon name={icon} size="md" /><span>{busy?"Working":label}</span></button>}

export function MeetingControlDock({snapshot,focusMode,onCycleLayout,onToggleDock,onToggleFocus,onLeave}:{snapshot:MeetingClientSnapshot;focusMode:boolean;onCycleLayout:()=>void;onToggleDock:()=>void;onToggleFocus:()=>void;onLeave:()=>void}) {
  const root=useRef<HTMLElement>(null);const[menu,setMenu]=useState<Menu>(null);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");const[devices,setDevices]=useState<MeetingControlDevices>(()=>meetingControlService.getDevices());const[shares,setShares]=useState<MeetingShareSources|null>(null);const[confirmAction,setConfirmAction]=useState<"end"|"mute-all"|"cancel"|null>(null);const hostState=useSyncExternalStore(meetingHostControlService.subscribe,meetingHostControlService.getSnapshot,meetingHostControlService.getSnapshot);const roomLocked=hostState.locked;
  const connected=snapshot.phase==="connected"||snapshot.phase==="reconnecting";const local=snapshot.participantIds.map((id)=>snapshot.participantsById[id]).find((participant)=>participant?.isLocal);const handRaised=local?.handRaised??snapshot.handRaised;
  useEffect(()=>meetingControlService.subscribeDevices(setDevices),[]);useEffect(()=>{void meetingControlService.refreshDevices().then(setDevices)},[]);
  useEffect(()=>{const pointer=(event:PointerEvent)=>{if(root.current&&!root.current.contains(event.target as Node))setMenu(null)};const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setMenu(null);setConfirmAction(null)}};document.addEventListener("pointerdown",pointer);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",pointer);document.removeEventListener("keydown",key)}},[]);
  const run=async(key:string,operation:()=>Promise<MeetingControlResult<unknown>>|MeetingControlResult<unknown>)=>{setBusy(key);setError("");const result=await operation();if(!result.ok)setError(result.error.message);setBusy(null);return result.ok};
  const openShare=async()=>{if(snapshot.localMedia.screenSharing){await run("share",()=>meetingControlService.stopScreenShare());return}setBusy("share");setError("");const result=await meetingControlService.listShareSources();setBusy(null);if(!result.ok){setError(result.error.message);return}setShares(result.data);setMenu("share")};
  const chooseShare=async(sourceId:string)=>{if(!shares)return;setMenu(null);await run("share",()=>meetingControlService.startScreenShare(shares.requestId,sourceId))};
  const toggleMenu=(next:Exclude<Menu,null>)=>setMenu((current)=>current===next?null:next);
  return <footer ref={root} className="meeting-control-dock meeting-control-dock-v2" aria-label="Meeting controls">
    {error?<p className="meeting-control-dock-v2__error" role="alert">{error}<button type="button" aria-label="Dismiss control error" onClick={()=>setError("")}><AppIcon name="close" size="xs" /></button></p>:null}
    <div className="meeting-control-dock__cluster meeting-control-dock-v2__devices">
      <span className="meeting-control-split"><ControlButton icon="microphone" label={snapshot.localMedia.muted?"Unmute":"Mute"} off={snapshot.localMedia.muted} disabled={!connected||!snapshot.capabilities.canPublishAudio} busy={busy==="microphone"} onClick={()=>void run("microphone",()=>meetingControlService.setMuted(!snapshot.localMedia.muted))}/><button type="button" className="meeting-control-split__menu" aria-label="Choose microphone" aria-expanded={menu==="microphone"} onClick={()=>toggleMenu("microphone")}><AppIcon name="chevronDown" size="xs" /></button></span>
      <span className="meeting-control-split"><ControlButton icon="image" label={snapshot.localMedia.cameraEnabled?"Camera off":"Camera on"} active={snapshot.localMedia.cameraEnabled} disabled={!connected||!snapshot.capabilities.canPublishVideo} busy={busy==="camera"} onClick={()=>void run("camera",()=>meetingControlService.setCameraEnabled(!snapshot.localMedia.cameraEnabled))}/><button type="button" className="meeting-control-split__menu" aria-label="Choose camera" aria-expanded={menu==="camera"} onClick={()=>toggleMenu("camera")}><AppIcon name="chevronDown" size="xs" /></button></span>
      {menu==="microphone"?<div className="meeting-control-menu is-device" role="menu" aria-label="Microphones">{devices.microphones.length?devices.microphones.map((device)=><button type="button" role="menuitemradio" aria-checked={device.deviceId===devices.selectedMicrophoneId} key={device.deviceId} onClick={()=>{setMenu(null);void run("microphone-device",()=>meetingControlService.selectMicrophone(device.deviceId))}}>{device.label}<small>{device.deviceId===devices.selectedMicrophoneId?"Active":""}</small></button>):<p>No microphone is available.</p>}</div>:null}
      {menu==="camera"?<div className="meeting-control-menu is-device is-camera" role="menu" aria-label="Cameras">{devices.cameras.length?devices.cameras.map((device)=><button type="button" role="menuitemradio" aria-checked={device.deviceId===devices.selectedCameraId} key={device.deviceId} onClick={()=>{setMenu(null);void run("camera-device",()=>meetingControlService.selectCamera(device.deviceId))}}>{device.label}<small>{device.deviceId===devices.selectedCameraId?"Active":""}</small></button>):<p>No camera is available.</p>}</div>:null}
    </div>
    <div className="meeting-control-dock__cluster meeting-control-dock__cluster--center">
      <ControlButton icon="maximize" label={snapshot.localMedia.screenSharing?"Stop share":"Share"} active={snapshot.localMedia.screenSharing} disabled={!connected||!snapshot.capabilities.canShareScreen} busy={busy==="share"} onClick={()=>void openShare()}/>
      <ControlButton icon="lock" label="Noise Shield" active={snapshot.noiseShield.status==="applied"} disabled={!connected||!snapshot.capabilities.canPublishAudio} busy={busy==="noise"} onClick={()=>void run("noise",()=>meetingControlService.setNoiseShield(snapshot.noiseShield.status!=="applied"))}/>
      <ControlButton icon="smile" label="Reactions" disabled={!connected||!snapshot.capabilities.canReact} onClick={()=>toggleMenu("reactions")}/>
      <ControlButton icon="users" label={handRaised?"Lower hand":"Raise hand"} active={handRaised} disabled={!connected||!snapshot.capabilities.canRaiseHand} busy={busy==="hand"} onClick={()=>void run("hand",()=>meetingControlService.toggleHand())}/>
      <ControlButton icon="more" label="More" onClick={()=>toggleMenu("more")}/>
      {menu==="share"&&shares?<div className="meeting-control-menu is-share" role="menu" aria-label="Share a screen or window">{shares.sources.map((source)=><button type="button" role="menuitem" key={source.id} onClick={()=>void chooseShare(source.id)}><AppIcon name="maximize" size="sm" /><span>{source.name}</span><small>{source.type}</small></button>)}</div>:null}
      {menu==="reactions"?<div className="meeting-control-menu is-reactions" role="menu" aria-label="Meeting reactions">{reactions.map((reaction)=><button type="button" role="menuitem" aria-label={reaction.label} key={reaction.kind} onClick={()=>{setMenu(null);void run("reaction",()=>meetingControlService.sendReaction(reaction.kind))}}><span aria-hidden="true">{reaction.emoji}</span><small>{reaction.label}</small></button>)}</div>:null}
      {menu==="more"?<div className="meeting-control-menu is-more" role="menu" aria-label="More meeting controls"><button type="button" role="menuitemcheckbox" aria-checked={snapshot.localMedia.deafened} onClick={()=>{setMenu(null);const result=meetingControlService.setDeafened(!snapshot.localMedia.deafened);if(!result.ok)setError(result.error.message)}}><AppIcon name="headphones" size="sm" />{snapshot.localMedia.deafened?"Restore meeting audio":"Deafen meeting audio"}</button><button type="button" role="menuitem" onClick={()=>{setMenu(null);onCycleLayout()}}><AppIcon name="maximize" size="sm" />Change layout ({snapshot.layout})</button><button type="button" role="menuitem" onClick={()=>{setMenu(null);onToggleDock()}}><AppIcon name="users" size="sm" />{snapshot.rightDock==="none"?"Open people panel":"Close meeting panel"}</button><button type="button" role="menuitem" onClick={()=>{setMenu(null);onToggleFocus()}}><AppIcon name="eye" size="sm" />{focusMode?"Exit focus mode":"Enter focus mode"}</button>{snapshot.capabilities.canLockRoom?<button type="button" role="menuitem" onClick={()=>{setMenu(null);void run("lock-room",()=>meetingControlService.setRoomLocked(!roomLocked))}}><AppIcon name="lock" size="sm" />{roomLocked?"Unlock room":"Lock room"}</button>:null}{snapshot.capabilities.canManageParticipants?<button type="button" role="menuitem" onClick={()=>{setMenu(null);setConfirmAction("mute-all")}}><AppIcon name="microphone" size="sm" />Mute all lower roles</button>:null}{snapshot.role==="host"&&hostState.roomStatus==="scheduled"?<button type="button" className="danger" role="menuitem" onClick={()=>{setMenu(null);setConfirmAction("cancel")}}><AppIcon name="trash" size="sm" />Cancel scheduled meeting</button>:null}{snapshot.capabilities.canEndRoom?<button type="button" className="danger" role="menuitem" onClick={()=>{setMenu(null);setConfirmAction("end")}}><AppIcon name="close" size="sm" />End for everyone</button>:null}</div>:null}
    </div>
    <div className="meeting-control-dock__cluster meeting-control-dock__cluster--end"><ControlButton icon="close" label="Leave" onClick={onLeave}/></div>
    {confirmAction?<div className="meeting-control-confirm" role="presentation" onMouseDown={()=>setConfirmAction(null)}><div role="alertdialog" aria-modal="true" aria-labelledby="meeting-destructive-title" onMouseDown={(event)=>event.stopPropagation()}><AppIcon name={confirmAction==="mute-all"?"microphone":"close"} size="lg" /><strong id="meeting-destructive-title">{confirmAction==="end"?"End this meeting for everyone?":confirmAction==="cancel"?"Cancel this scheduled meeting?":"Mute all lower-role participants?"}</strong><p>{confirmAction==="end"?"All participants will be marked as left and new meeting tokens will be denied for this session.":confirmAction==="cancel"?"The linked event, active invites, and waiting requests will be cancelled. This cannot be undone.":"Only lower-ranked participants are affected. Picom cannot and will not remotely unmute them; each person must unmute themselves."}</p><footer><button type="button" onClick={()=>setConfirmAction(null)}>Go back</button><button type="button" className="danger" disabled={busy!==null} onClick={()=>void run(confirmAction,()=>confirmAction==="end"?meetingControlService.endForEveryone():confirmAction==="cancel"?meetingControlService.cancelScheduledRoom("Cancelled by host from meeting controls"):meetingControlService.muteAll(snapshot)).then((done)=>{if(done)setConfirmAction(null)})}>Confirm {confirmAction==="mute-all"?"mute":"action"}</button></footer></div></div>:null}
  </footer>;
}
