begin;
select plan(15);
select has_table('public','community_permission_definitions','canonical permission registry exists');
select has_table('public','community_role_permissions','normalized role grants exist');
select has_table('public','community_permission_overrides','scoped permission overrides exist');
select has_column('public','roles','system_key','built-in role identity is explicit');
select has_column('public','roles','is_default','default member role is explicit');
select has_column('public','roles','permissions_version','permission projection is versioned');
select ok(to_regprocedure('public.effective_community_permission(uuid,text,text,uuid)') is not null,'effective evaluator exists');
select ok(to_regprocedure('public.set_community_role_permission(uuid,uuid,text,boolean,text)') is not null,'hierarchy-safe grant RPC exists');
select ok(to_regprocedure('public.set_community_permission_override(uuid,uuid,text,uuid,text,text,text)') is not null,'scope override RPC exists');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='roles_community_system_key_unique'),'one built-in role key per community');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='community_role_permissions_lookup'),'role grant lookup is indexed');
select ok(exists(select 1 from pg_trigger where tgname='community_member_role_integrity' and not tgisinternal),'self-join and owner assignment trigger exists');
select ok(exists(select 1 from pg_trigger where tgname='community_role_invariants' and not tgisinternal),'owner role mutation trigger exists');
select ok((select relrowsecurity from pg_class where oid='public.community_role_permissions'::regclass),'role grants enforce RLS');
select ok((select relrowsecurity from pg_class where oid='public.community_permission_overrides'::regclass),'overrides enforce RLS');
select * from finish();
rollback;
