begin;
select plan(16);
select has_function('public','rebuild_feed_engagement_rollup',array['uuid'],'single-item rollup repair exists');
select has_function('public','reconcile_feed_sources_v1',array['text','uuid','integer'],'bounded source reconciliation exists');
select has_function('public','reconcile_feed_rollups_v1',array['uuid','integer'],'bounded rollup reconciliation exists');
select ok(not has_function_privilege('authenticated','public.rebuild_feed_engagement_rollup(uuid)','EXECUTE'),'renderer cannot rebuild canonical scores');
select ok(not has_function_privilege('authenticated','public.reconcile_feed_sources_v1(text,uuid,integer)','EXECUTE'),'renderer cannot run source backfill');
select ok(not has_function_privilege('authenticated','public.reconcile_feed_rollups_v1(uuid,integer)','EXECUTE'),'renderer cannot run rollup repair');
select ok(pg_get_functiondef('public.feed_actor_is_eligible(uuid,uuid,uuid)'::regprocedure) like '%target_actor_id <> target_author_id%','self actions are excluded by actor eligibility');
select ok(pg_get_functiondef('public.rebuild_feed_engagement_rollup(uuid)'::regprocedure) like '%group by event.actor_id%','reaction/save/view actors are unique');
select ok(pg_get_functiondef('public.rebuild_feed_engagement_rollup(uuid)'::regprocedure) like '%least(10%','reaction/save caps are server side');
select ok(pg_get_functiondef('public.rebuild_feed_engagement_rollup(uuid)'::regprocedure) like '%least(3::numeric%','view cap is server side');
select ok(pg_get_functiondef('public.rebuild_feed_engagement_rollup(uuid)'::regprocedure) like '%external_supporter_count%','supporter union is persisted');
select ok(exists(select 1 from pg_trigger where tgname='feed_messages_sync' and not tgisinternal),'message source trigger exists');
select ok(exists(select 1 from pg_trigger where tgname='feed_attachments_sync' and not tgisinternal),'attachment reclassification trigger exists');
select ok(exists(select 1 from pg_trigger where tgname='feed_message_reactions_rollup' and not tgisinternal),'message reaction trigger exists');
select ok(exists(select 1 from pg_trigger where tgname='feed_podcast_comments_sync' and not tgisinternal),'podcast comment trigger exists');
select ok(exists(select 1 from pg_trigger where tgname='feed_impressions_rollup' and not tgisinternal),'unique opened-view trigger exists');
select * from finish();
rollback;
