begin;
select plan(17);
select has_function('public','get_feed_page',array['text','integer','numeric','timestamp with time zone','uuid','timestamp with time zone','text[]','boolean','boolean','integer','uuid'],'Feed V1 RPC exists');
select ok(has_function_privilege('authenticated','public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)','EXECUTE'),'authenticated can call Feed RPC');
select ok(not has_function_privilege('anon','public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)','EXECUTE'),'anonymous cannot call Feed RPC');
select ok(not has_function_privilege('authenticated','public.feed_item_has_friend_support(uuid,uuid)','EXECUTE'),'friend support helper is internal');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%visible_items as materialized%','access candidates are materialized before scoring');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%public.can_view_feed_item(item.id)%','source visibility is enforced');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%signal.raw_score>=4%','normal threshold is exact');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%signal.external_supporter_count>=1%','external support is required');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%signal.direct_mention or%','direct mention guarantee bypasses popularity only');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%power(2::numeric%/48%','48-hour freshness is query time');
select ok(pg_get_functiondef('public.feed_users_are_friends(uuid,uuid)'::regprocedure) like '%public.friendships%','Friends mode uses accepted friendships');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) not like '%user_follows%','Feed V1 has no follow dependency');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%candidate.author_position<=2%','author diversity cap exists');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%candidate.community_position<=4%','community diversity cap exists');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%candidate.consecutive_community_position<=2%','consecutive diversity cap exists');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) not like '%offset%','pagination is keyset only');
select ok(pg_get_functiondef('public.get_feed_page(text,integer,numeric,timestamptz,uuid,timestamptz,text[],boolean,boolean,integer,uuid)'::regprocedure) like '%candidate.id<cursor_feed_item_id%','stable ID tie-breaker exists');
select * from finish();
rollback;
