import { useEffect, useState } from "react";
import { adminOperationsService, type AdminOperationsAccess } from "../services/adminOperationsService";
import type { AdminOperationsListItem, AdminOperationsListSection, AdminSystemStatusV2 } from "../types/adminOperations";
import { dateTimeService } from "../services/dateTimeService";
import { AppIcon } from "./AppIcon";

export function AdminSystemStatusV2({ access }: { access: AdminOperationsAccess }) {
  const [status, setStatus] = useState<AdminSystemStatusV2 | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = async (audit = false) => { setLoading(true); setError(null); const result = await adminOperationsService.getSystemStatusV2(access); if (result.ok) setStatus(result.data); else setError(result.message); setLoading(false); if (audit) await adminOperationsService.recordAction(access, "admin_snapshot_refreshed"); };
  useEffect(() => { void load(); }, [access]);
  return <section className="admin-ops-v2-section"><header><div><strong>Backend aggregate status</strong><span>App-admin RPC; no private configuration is returned.</span></div><button type="button" disabled={loading} onClick={() => void load(true)}><AppIcon name="settings" size="sm" />Refresh</button></header>{error ? <div className="auth-error" role="alert">{error}</div> : status ? <div className="admin-ops-metrics"><article><span>Database</span><strong>{status.database}</strong></article><article><span>Users</span><strong>{status.users}</strong></article><article><span>Communities</span><strong>{status.communities}</strong></article><article><span>Open reports</span><strong>{status.openReports}</strong></article><article><span>Abuse events / 24h</span><strong>{status.abuseEvents24h}</strong></article><article><span>Admin audit / 24h</span><strong>{status.adminAuditEvents24h}</strong></article></div> : <div className="admin-ops-detail"><strong>Loading restricted status</strong><p>Only safe aggregate counters are requested.</p></div>}{status ? <small>Checked {dateTimeService.formatFullTimestamp(status.checkedAt)} · {status.source}</small> : null}</section>;
}

export function AdminOperationsPagedList({ access, section }: { access: AdminOperationsAccess; section: AdminOperationsListSection }) {
  const [items, setItems] = useState<readonly AdminOperationsListItem[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [hasMore, setHasMore] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async (nextCursor: string | null, append: boolean) => { setLoading(true); setError(null); const result = await adminOperationsService.listSection(section, access, nextCursor); if (result.ok) { setItems((current) => append ? [...current, ...result.data.items] : result.data.items); setCursor(result.data.nextCursor); setHasMore(result.data.hasMore); } else setError(result.message); setLoading(false); };
  useEffect(() => { setItems([]); setCursor(null); void load(null, false); }, [access, section]);
  return <section className="admin-ops-v2-section"><header><div><strong>{section.replace("_", " ")}</strong><span>Bounded metadata only; sensitive content is excluded.</span></div><em>25 per page</em></header>{error ? <div className="auth-error" role="alert">{error}</div> : null}<div className="admin-ops-paged-list">{items.map((item) => <article key={`${item.section}-${item.id}`}><div><strong>{item.label}</strong><span>{item.detail}</span></div><div><em>{item.status}</em><time>{dateTimeService.formatFullTimestamp(item.createdAt)}</time></div></article>)}{!loading && !items.length ? <div className="admin-ops-detail"><strong>No records</strong><p>This restricted list has no safe records to show.</p></div> : null}</div>{hasMore ? <button className="admin-ops-load-more" type="button" disabled={loading || !cursor} onClick={() => void load(cursor, true)}>{loading ? "Loading..." : "Load more"}</button> : items.length ? <small>End of restricted results.</small> : null}</section>;
}
