import { useEffect, useMemo, useState } from "react";
import type { AuditActionType, AuditLogRecord } from "../types/auditLog";
import { auditLogService } from "../services/auditLogService";
import { clipboardService } from "../services/clipboardService";
import { dateTimeService } from "../services/dateTimeService";
import { AppIcon } from "./AppIcon";

const actions: Array<{ value: "all" | AuditActionType; label: string }> = [{ value: "all", label: "All actions" }, { value: "community_update", label: "Community updates" }, { value: "channel_create", label: "Channel created" }, { value: "channel_update", label: "Channel updated" }, { value: "channel_delete", label: "Channel deleted" }, { value: "role_change", label: "Role changes" }, { value: "member_change", label: "Member changes" }, { value: "moderation_action", label: "Moderation actions" }, { value: "invite_create", label: "Invite created" }, { value: "invite_revoke", label: "Invite revoked" }];

export function CommunityAuditLogSection({ communityId, canView }: { communityId: string; canView: boolean }) {
  const [records, setRecords] = useState<AuditLogRecord[]>([]); const [actor, setActor] = useState(""); const [action, setAction] = useState<"all" | AuditActionType>("all"); const [range, setRange] = useState("all"); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { let active = true; void auditLogService.list(communityId, canView).then((result) => { if (!active) return; if (result.ok) setRecords(result.data); else setNotice(result.message); }); return () => { active = false; }; }, [canView, communityId]);
  const filtered = useMemo(() => { const cutoff = range === "7" ? Date.now() - 7 * 86400000 : range === "30" ? Date.now() - 30 * 86400000 : 0; return records.filter((record) => (!actor.trim() || record.actorId.toLowerCase().includes(actor.trim().toLowerCase())) && (action === "all" || record.actionType === action) && (!cutoff || Date.parse(record.createdAt) >= cutoff)); }, [action, actor, range, records]);
  const copy = async () => { const result = await clipboardService.copyText(auditLogService.exportJson(filtered)); setNotice(result.ok ? "Filtered audit JSON copied." : result.reason); };
  const download = () => { const blob = new Blob([auditLogService.exportJson(filtered)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `picom-audit-${communityId}.json`; anchor.click(); URL.revokeObjectURL(url); setNotice("Filtered audit JSON exported."); };
  return <section className="community-admin-section audit-log-section"><header><p className="eyebrow">Append-only history</p><h3>Audit log</h3><span>Administrative events only. Tokens, passwords, and message content are excluded.</span></header><div className="audit-log-toolbar"><label><span>Actor</span><input value={actor} onChange={(event) => setActor(event.target.value)} placeholder="Filter actor ID" /></label><label><span>Action</span><select value={action} onChange={(event) => setAction(event.target.value as typeof action)}>{actions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label><span>Date range</span><select value={range} onChange={(event) => setRange(event.target.value)}><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></label><div className="audit-export-actions"><button type="button" onClick={() => void copy()}><AppIcon name="paperclip" size="sm" />Copy JSON</button><button type="button" onClick={download}><AppIcon name="send" size="sm" />Export JSON</button></div></div>{notice ? <p className="audit-log-notice" role="status">{notice}</p> : null}{filtered.length ? <div className="audit-log-list">{filtered.map((record) => <article key={record.id}><div><strong>{record.actionType.replace(/_/g, " ")}</strong><span>{dateTimeService.formatFullTimestamp(record.createdAt)}</span></div><dl><div><dt>Actor</dt><dd>{record.actorId}</dd></div><div><dt>Target</dt><dd>{record.targetType}{record.targetId ? ` · ${record.targetId}` : ""}</dd></div><div><dt>Reason</dt><dd>{record.reason ?? "No reason provided"}</dd></div></dl></article>)}</div> : <div className="community-admin-empty"><AppIcon name="inbox" size="lg" /><strong>No matching audit events</strong><span>Adjust filters or perform an audited administrative action.</span></div>}</section>;
}
