import { useState, type FormEvent } from "react";
import type { Community } from "../types/community";
import type { CreateCommunityEventInput } from "../services/communityEventService";
import type { UpcomingEvent } from "../types/events";
import { dateTimeService } from "../services/dateTimeService";
import { AppIcon } from "./AppIcon";

export function CreateEventModal({community,onClose,onCreate}:{community:Community;onClose:()=>void;onCreate:(input:CreateCommunityEventInput)=>void}){const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [startsAt,setStartsAt]=useState("");const [endsAt,setEndsAt]=useState("");const submit=(event:FormEvent)=>{event.preventDefault();if(!title.trim()||!startsAt)return;onCreate({communityId:community.id,title,description,startsAt:new Date(startsAt).toISOString(),endsAt:endsAt?new Date(endsAt).toISOString():undefined,type:"meeting"});onClose()};return <div className="modal-backdrop" onMouseDown={onClose}><form className="community-event-modal" onSubmit={submit} onMouseDown={(event)=>event.stopPropagation()}><button type="button" className="icon-button modal-close" aria-label="Close" onClick={onClose}><AppIcon name="close" size="sm" /></button><span className="eyebrow">Community event</span><h2>Create Event</h2><label>Title<input value={title} maxLength={120} onChange={(event)=>setTitle(event.target.value)} /></label><label>Description<textarea value={description} maxLength={2000} rows={4} onChange={(event)=>setDescription(event.target.value)} /></label><div className="event-time-grid"><label>Starts<input type="datetime-local" value={startsAt} onChange={(event)=>setStartsAt(event.target.value)} /></label><label>Ends optional<input type="datetime-local" value={endsAt} onChange={(event)=>setEndsAt(event.target.value)} /></label></div><button className="primary-button" disabled={!title.trim()||!startsAt}>Create event</button></form></div>}
export function CommunityEventsAdminSection({community,events,onCreate,onCancel}:{community:Community;events:UpcomingEvent[];onCreate:(input:CreateCommunityEventInput)=>void;onCancel:(eventId:string)=>void}){const [creating,setCreating]=useState(false);const [rsvp,setRsvp]=useState<Record<string,string>>({});const visible=events.filter((event)=>event.communityId===community.id&&!event.cancelledAt).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));return <section className="community-admin-section"><header><p className="eyebrow">Schedule</p><h3>Events</h3><span>Create and manage upcoming community sessions.</span></header><button className="community-event-create" onClick={()=>setCreating(true)}><AppIcon name="plus" size="sm" /> Create Event</button><div className="community-event-list">{visible.length?visible.map((event)=><article key={event.id}><div><strong>{event.title}</strong><span>{dateTimeService.formatEventRange(event.startsAt,event.endsAt)}</span><small>{event.description||"Community event"}</small></div><select aria-label={`RSVP for ${event.title}`} value={rsvp[event.id]??"interested"} onChange={(change)=>setRsvp((current)=>({...current,[event.id]:change.target.value}))}><option value="interested">Interested</option><option value="going">Going</option><option value="not-going">Not going</option></select><button onClick={()=>onCancel(event.id)}>Cancel event</button></article>):<div className="community-admin-empty"><strong>No upcoming events</strong><span>Create the first event for this community.</span></div>}</div>{creating?<CreateEventModal community={community} onClose={()=>setCreating(false)} onCreate={onCreate}/>:null}</section>}
