import { useEffect, useState } from "react";
import type { CommunityStickerPack } from "../types/stickers";
import { stickerPackService } from "../services/stickerPackService";
import { AppIcon } from "./AppIcon";

export function CommunityStickersAdminSection({ communityId, currentUserId, canManage }: { communityId: string; currentUserId: string; canManage: boolean }) {
  const [packs, setPacks] = useState<CommunityStickerPack[]>([]);
  const [packName, setPackName] = useState(""); const [description, setDescription] = useState("");
  const [selectedPackId, setSelectedPackId] = useState(""); const [stickerName, setStickerName] = useState(""); const [title, setTitle] = useState(""); const [file, setFile] = useState<File | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { let active = true; void stickerPackService.list(communityId).then((result) => { if (!active) return; if (result.ok) { setPacks(result.data); setSelectedPackId((current) => current || result.data[0]?.id || ""); } else setNotice(result.message); }); return () => { active = false; }; }, [communityId]);
  const createPack = async () => { const result = await stickerPackService.createPack({ communityId, name: packName, description, ownerId: currentUserId, canManage }); if (result.ok) { setPacks((current) => [...current, result.data]); setSelectedPackId(result.data.id); setPackName(""); setDescription(""); setNotice("Sticker pack created."); } else setNotice(result.message); };
  const upload = async () => { if (!file || !selectedPackId) return; const result = await stickerPackService.addSticker({ communityId, packId: selectedPackId, name: stickerName, title, file, createdBy: currentUserId, canManage }); if (result.ok) { setPacks((current) => current.map((pack) => pack.id === selectedPackId ? { ...pack, stickers: [...pack.stickers, result.data] } : pack)); setStickerName(""); setTitle(""); setFile(null); setNotice("Sticker uploaded safely."); } else setNotice(result.message); };
  const togglePack = async (pack: CommunityStickerPack) => { const enabled = pack.moderationStatus !== "active"; const result = await stickerPackService.setPackEnabled({ communityId, packId: pack.id, enabled, canManage }); if (result.ok) { setPacks((current) => current.map((item) => item.id === pack.id ? { ...item, moderationStatus: enabled ? "active" : "disabled" } : item)); setNotice(enabled ? "Sticker pack enabled." : "Sticker pack disabled."); } else setNotice(result.message); };
  return <section className="community-admin-section emoji-admin-section"><header><p className="eyebrow">Community expression</p><h3>Sticker packs</h3><span>Community-owned packs only. Marketplace publishing is not available.</span></header>
    <div className="emoji-upload-form"><label><span>Pack name</span><input value={packName} onChange={(event) => setPackName(event.target.value)} placeholder="team_moments" /></label><label><span>Description</span><input value={description} maxLength={240} onChange={(event) => setDescription(event.target.value)} placeholder="Original team artwork" /></label><button type="button" disabled={!canManage || !packName.trim()} onClick={() => void createPack()}><AppIcon name="plus" size="sm" />Create pack</button></div>
    <div className="emoji-upload-form"><label><span>Pack</span><select value={selectedPackId} onChange={(event) => setSelectedPackId(event.target.value)}><option value="">Select pack</option>{packs.map((pack) => <option key={pack.id} value={pack.id}>{pack.name}</option>)}</select></label><label><span>Sticker name / title</span><input value={stickerName} onChange={(event) => setStickerName(event.target.value)} placeholder="ship_it" /><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ship it" /></label><label><span>Image</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><button type="button" disabled={!canManage || !selectedPackId || !stickerName.trim() || !title.trim() || !file} onClick={() => void upload()}><AppIcon name="image" size="sm" />Upload sticker</button></div>
    {notice ? <p className="emoji-admin-notice" role="status">{notice}</p> : null}
    <div className="emoji-admin-grid">{packs.map((pack) => <article key={pack.id}><AppIcon name="image" size="lg" /><div><strong>{pack.name}</strong><span>{pack.stickers.length} stickers · owned by community manager</span></div><button type="button" className="secondary-action" disabled={!canManage} onClick={() => void togglePack(pack)}>{pack.moderationStatus === "active" ? "Disable" : "Enable"}</button></article>)}</div>
  </section>;
}
