import { useEffect, useState } from "react";
import type { Community } from "../types/community";
import type { WebhookRecord } from "../types/webhooks";
import { clipboardService } from "../services/clipboardService";
import { webhookService } from "../services/webhookService";
import { AppIcon } from "./AppIcon";

export function CommunityWebhooksAdminSection({ community, currentUserId, canManage }: { community: Community; currentUserId: string; canManage: boolean }) {
  const channels = community.categories.flatMap((category) => category.channels).filter((channel) => channel.type === "text"); const [items, setItems] = useState<WebhookRecord[]>([]); const [name, setName] = useState(""); const [channelId, setChannelId] = useState(channels[0]?.id ?? ""); const [urlOnce, setUrlOnce] = useState<string | null>(null); const [pendingRevoke, setPendingRevoke] = useState<WebhookRecord | null>(null); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { let active = true; void webhookService.list(community.id).then((result) => { if (!active) return; if (result.ok) setItems(result.data); else setNotice(result.message); }); return () => { active = false; }; }, [community.id]);
  const create = async () => { const result = await webhookService.create({ communityId: community.id, channelId, name, createdBy: currentUserId, canManage }); if (!result.ok) { setNotice(result.message); return; } setItems((current) => [result.data.webhook, ...current]); setUrlOnce(result.data.urlOnce); setName(""); setNotice("Webhook created. Copy the URL now; Picom will not show its token again."); };
  const copy = async () => { if (!urlOnce) return; const result = await clipboardService.copyText(urlOnce); setNotice(result.ok ? "One-time webhook URL copied." : result.reason); };
  const revoke = async () => { if (!pendingRevoke) return; const result = await webhookService.revoke(pendingRevoke, canManage); if (result.ok) { setItems((current) => current.map((item) => item.id === result.data.id ? result.data : item)); setPendingRevoke(null); setNotice("Webhook revoked."); } else setNotice(result.message); };
  return <section className="community-admin-section webhooks-admin-section"><header><p className="eyebrow">Channel integrations</p><h3>Webhooks</h3><span>Outgoing credentials are never displayed again. Incoming delivery remains disabled until server validation and rate limiting are production-ready.</span></header><div className="webhook-create-form"><label><span>Name</span><input value={name} maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="Release Updates" /></label><label><span>Channel</span><select value={channelId} onChange={(event) => setChannelId(event.target.value)}>{channels.map((channel) => <option key={channel.id} value={channel.id}>#{channel.name}</option>)}</select></label><button type="button" disabled={!canManage || !name.trim() || !channelId} onClick={() => void create()}><AppIcon name="plus" size="sm" />Create webhook</button></div>{urlOnce ? <div className="webhook-secret-once"><div><strong>Copy this URL now</strong><span>{urlOnce}</span><small>The raw token exists only in this one-time result.</small></div><button type="button" onClick={() => void copy()}><AppIcon name="paperclip" size="sm" />Copy URL</button><button type="button" className="secondary-action" onClick={() => setUrlOnce(null)}>Dismiss</button></div> : null}{notice ? <p className="webhook-admin-notice" role="status">{notice}</p> : null}<div className="webhook-list">{items.map((webhook) => <article key={webhook.id}><div><strong>{webhook.name}{webhook.revokedAt ? <span>Revoked</span> : null}</strong><small>#{channels.find((channel) => channel.id === webhook.channelId)?.name ?? webhook.channelId}</small></div><button className="danger-action" type="button" disabled={!canManage || Boolean(webhook.revokedAt)} onClick={() => setPendingRevoke(webhook)}><AppIcon name="trash" size="sm" />Revoke</button></article>)}</div>{pendingRevoke ? <div className="webhook-revoke-confirm" role="alertdialog"><div><strong>Revoke {pendingRevoke.name}?</strong><span>Existing URLs will stop working permanently.</span></div><button className="secondary-action" type="button" onClick={() => setPendingRevoke(null)}>Cancel</button><button className="danger-action" type="button" onClick={() => void revoke()}>Confirm revoke</button></div> : null}</section>;
}
