import { useState } from "react";
import { botService } from "../services/botService";
import type { BotProfile } from "../types/bots";
import { AppIcon } from "./AppIcon";

export function CommunityBotsAdminSection({ communityId, ownerId, canManage }: { communityId: string; ownerId: string; canManage: boolean }) {
  const [bots, setBots] = useState(() => botService.listInstalledBots(communityId, ownerId)); const [pendingRemoval, setPendingRemoval] = useState<BotProfile | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const add = () => { const result = botService.addBotPlaceholder(communityId, ownerId, canManage); if (result.ok) { setBots((items) => [...items, result.data]); setNotice("Mock bot installed with the Member role."); } else setNotice(result.message); };
  const remove = () => { if (!pendingRemoval) return; const result = botService.removeBot(communityId, pendingRemoval.id, canManage); if (result.ok) { setBots((items) => items.filter((bot) => bot.id !== pendingRemoval.id)); setNotice("Bot removed from this community."); setPendingRemoval(null); } else setNotice(result.message); };
  return <section className="community-admin-section bots-admin-section"><header><p className="eyebrow">Automation identities</p><h3>Bots</h3><span>Role-based bot identities only. No marketplace, executable plugin runtime, public API, or raw token display.</span></header><div className="bots-admin-toolbar"><div><strong>{bots.length} installed</strong><span>Bot permissions follow their assigned community role.</span></div><button type="button" disabled={!canManage} onClick={add}><AppIcon name="plus" size="sm" />Add bot placeholder</button></div>{notice ? <p className="bots-admin-notice" role="status">{notice}</p> : null}<div className="bots-admin-list">{bots.map((bot) => <article key={bot.id}><span className="bots-avatar"><AppIcon name="user" size="md" /></span><div><strong>{bot.displayName}<span className="bot-badge">BOT</span></strong><span>Role: {bot.roleId} · Owner: {bot.ownerId}</span></div><button className="danger-action" type="button" disabled={!canManage} onClick={() => setPendingRemoval(bot)}><AppIcon name="trash" size="sm" />Remove</button></article>)}</div>{pendingRemoval ? <div className="bot-remove-confirm" role="alertdialog" aria-label="Confirm bot removal"><div><strong>Remove {pendingRemoval.displayName}?</strong><span>This removes the community installation only.</span></div><button className="secondary-action" type="button" onClick={() => setPendingRemoval(null)}>Cancel</button><button className="danger-action" type="button" onClick={remove}>Confirm remove</button></div> : null}</section>;
}
