import { useEffect, useState, type FormEvent } from "react";
import type { Community } from "../types/community";
import type { CreateCommunityEventInput, UpdateCommunityEventInput } from "../services/communityEventService";
import { communityEventService } from "../services/communityEventService";
import { eventReminderService } from "../services/eventReminderService";
import type { EventRsvpStatus, UpcomingEvent } from "../types/events";
import { dateTimeService } from "../services/dateTimeService";
import { AppIcon } from "./AppIcon";

function toLocalDateTime(value?: string): string { if (!value) return ""; const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }

export function EventEditorModal({ community, initial, onClose, onSave }: { community: Community; initial?: UpcomingEvent; onClose: () => void; onSave: (input: CreateCommunityEventInput | UpdateCommunityEventInput) => void | Promise<void> }) {
  const [title, setTitle] = useState(initial?.title ?? ""); const [description, setDescription] = useState(initial?.description ?? ""); const [startsAt, setStartsAt] = useState(toLocalDateTime(initial?.startsAt)); const [endsAt, setEndsAt] = useState(toLocalDateTime(initial?.endsAt));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !startsAt) return; const input = { ...(initial ? {} : { communityId: community.id }), channelId: initial?.channelId, title, description, startsAt: new Date(startsAt).toISOString(), endsAt: endsAt ? new Date(endsAt).toISOString() : undefined, type: initial?.type ?? "meeting" as const }; await onSave(input); onClose(); };
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="community-event-modal" onSubmit={(event) => void submit(event)} onMouseDown={(event) => event.stopPropagation()}><button type="button" className="icon-button modal-close" aria-label="Close" onClick={onClose}><AppIcon name="close" size="sm" /></button><span className="eyebrow">Community event</span><h2>{initial ? "Edit Event" : "Create Event"}</h2><label>Title<input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} /></label><label>Description<textarea value={description} maxLength={2000} rows={4} onChange={(event) => setDescription(event.target.value)} /></label><div className="event-time-grid"><label>Starts<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><label>Ends optional<input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></label></div><button className="primary-button" disabled={!title.trim() || !startsAt}>{initial ? "Save changes" : "Create event"}</button></form></div>;
}

export function CommunityEventsAdminSection({ community, currentUserId, events, onCreate, onUpdate, onCancel }: { community: Community; currentUserId: string; events: UpcomingEvent[]; onCreate: (input: CreateCommunityEventInput) => void | Promise<void>; onUpdate: (eventId: string, input: UpdateCommunityEventInput) => void | Promise<void>; onCancel: (eventId: string) => void }) {
  const [editing, setEditing] = useState<UpcomingEvent | "new" | null>(null); const [rsvp, setRsvp] = useState<Record<string, EventRsvpStatus>>({}); const [reminders, setReminders] = useState<Record<string, boolean>>({});
  useEffect(() => { setRsvp(Object.fromEntries(events.flatMap((event) => event.currentUserRsvp ? [[event.id, event.currentUserRsvp]] : []))); setReminders(Object.fromEntries(events.map((event) => [event.id, eventReminderService.isEnabled(event.id)]))); }, [events]);
  const visible = events.filter((event) => event.communityId === community.id && !event.cancelledAt).sort((a, b) => a.startsAt.localeCompare(b.startsAt));
  const updateRsvp = async (event: UpcomingEvent, status: EventRsvpStatus) => { if (await communityEventService.setRsvp(event.id, currentUserId, status)) { setRsvp((current) => ({ ...current, [event.id]: status })); if (status === "not_going" && reminders[event.id]) { await eventReminderService.set(event, false, status); setReminders((current) => ({ ...current, [event.id]: false })); } } };
  const toggleReminder = async (event: UpcomingEvent) => { const enabled = !reminders[event.id]; if (await eventReminderService.set(event, enabled, rsvp[event.id])) setReminders((current) => ({ ...current, [event.id]: enabled })); };
  return <section className="community-admin-section"><header><p className="eyebrow">Schedule</p><h3>Events</h3><span>Create, edit, RSVP, and schedule preference-aware desktop reminders.</span></header><button className="community-event-create" onClick={() => setEditing("new")}><AppIcon name="plus" size="sm" /> Create Event</button><div className="community-event-list">{visible.length ? visible.map((event) => <article key={event.id}><div><strong>{event.title}</strong><span>{dateTimeService.formatEventRange(event.startsAt, event.endsAt)}</span><small>{event.description || "Community event"}</small></div><select aria-label={`RSVP for ${event.title}`} value={rsvp[event.id] ?? "interested"} onChange={(change) => void updateRsvp(event, change.target.value as EventRsvpStatus)}><option value="interested">Interested</option><option value="going">Going</option><option value="not_going">Not going</option></select><button type="button" disabled={rsvp[event.id] !== "going" && rsvp[event.id] !== "interested"} onClick={() => void toggleReminder(event)}>{reminders[event.id] ? "Reminder on" : "Remind me"}</button><button type="button" onClick={() => setEditing(event)}>Edit</button><button type="button" className="danger-action" onClick={() => { eventReminderService.cancel(event.id); onCancel(event.id); }}>Cancel event</button></article>) : <div className="community-admin-empty"><strong>No upcoming events</strong><span>Create the first event for this community.</span></div>}</div>{editing ? <EventEditorModal community={community} initial={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onSave={(input) => editing === "new" ? onCreate(input as CreateCommunityEventInput) : onUpdate(editing.id, input as UpdateCommunityEventInput)} /> : null}</section>;
}
