import { useEffect, useMemo, useState } from "react";
import type { Community } from "../types/community";
import type { CommunityAccess } from "../types/communityAccess";
import type { CommunityInsightsSnapshot } from "../types/communityInsights";
import { communityInsightsService } from "../services/communityInsightsService";
import { AppIcon } from "./AppIcon";

export function CommunityInsightsView({ community, access }: { community: Community; access: CommunityAccess }) {
  const [snapshot, setSnapshot] = useState<CommunityInsightsSnapshot | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); setError(null); void communityInsightsService.getSnapshot(community, access).then((result) => { if (!active) return; if (result.ok) setSnapshot(result.data); else setError(result.message); setLoading(false); }); return () => { active = false; }; }, [access, community]);
  const peakMessages = useMemo(() => Math.max(1, ...(snapshot?.messagesByChannel.map((item) => item.messageCount) ?? [])), [snapshot]);
  if (loading) return <section className="community-insights-view" aria-busy="true"><div className="community-admin-empty"><AppIcon name="inbox" size="lg" /><strong>Loading aggregate insights</strong><span>No message content or member-level activity is requested.</span></div></section>;
  if (error || !snapshot) return <section className="community-insights-view"><div className="auth-error" role="alert">{error ?? "Community insights are unavailable."}</div></section>;
  const metrics = [["Members", snapshot.memberCount], ["Active members", snapshot.activeMembers], ["Messages", snapshot.messagesTotal], ["Active channels", snapshot.activeChannels], ["Voice sessions", snapshot.voiceSessions], ["Open reports", snapshot.openReports]] as const;
  return <section className="community-admin-section community-insights-view"><header><p className="eyebrow">Aggregate community health</p><h3>Insights</h3><span>Last {snapshot.windowDays} days. Counts only; no message content or individual member profiles.</span></header><div className="community-insights-metrics">{metrics.map(([label, value]) => <article key={label}><strong>{value.toLocaleString()}</strong><span>{label}</span></article>)}</div><div className="community-insights-grid"><article className="community-insights-card"><header><div><strong>Messages by channel</strong><span>Visible channels only</span></div><AppIcon name="hash" size="md" /></header>{snapshot.messagesByChannel.length ? <div className="community-insights-bars">{snapshot.messagesByChannel.slice(0, 8).map((item) => <div key={item.channelId}><div><span>#{item.channelName}</span><strong>{item.messageCount}</strong></div><i><b style={{ width: `${Math.max(4, (item.messageCount / peakMessages) * 100)}%` }} /></i></div>)}</div> : <div className="community-insights-empty">No message activity in this period.</div>}</article><article className="community-insights-card"><header><div><strong>Voice usage</strong><span>Anonymous daily totals</span></div><AppIcon name="microphone" size="md" /></header><dl><div><dt>Participant minutes</dt><dd>{snapshot.voiceParticipantMinutes.toLocaleString()}</dd></div><div><dt>Peak concurrent</dt><dd>{snapshot.voicePeakConcurrent}</dd></div><div><dt>Sessions</dt><dd>{snapshot.voiceSessions}</dd></div></dl></article><article className="community-insights-card"><header><div><strong>Membership and safety</strong><span>Operational aggregates</span></div><AppIcon name="users" size="md" /></header><dl><div><dt>New members</dt><dd>{snapshot.newMembers}</dd></div><div><dt>Total reports</dt><dd>{snapshot.reportsTotal}</dd></div><div><dt>Open reports</dt><dd>{snapshot.openReports}</dd></div></dl></article></div><footer><AppIcon name="lock" size="sm" /><span>Generated {new Date(snapshot.generatedAt).toLocaleString()} from {snapshot.source === "mock" ? "local mock aggregates" : "permission-checked Supabase aggregates"}.</span></footer></section>;
}
