import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Channel, Community, Member, Message } from "../types/community";
import type { ForumPost } from "../types/forum";
import type { ThreadRecord } from "../types/threads";
import { forumService } from "../services/forumService";
import { dateTimeService } from "../services/dateTimeService";
import { AppIcon } from "./AppIcon";
import { ThreadPanel } from "./ThreadPanel";

const tags = ["Design", "Help", "Showcase", "Feedback", "Resolved"];

function CreateForumPostModal({ onClose, onCreate }: { onClose: () => void; onCreate: (title: string, body: string, tags: string[]) => void | Promise<void> }) {
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [selectedTags, setSelectedTags] = useState<string[]>([]); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !body.trim()) return; setBusy(true); await onCreate(title, body, selectedTags); setBusy(false); onClose(); };
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="community-event-modal" onSubmit={(event) => void submit(event)} onMouseDown={(event) => event.stopPropagation()}><button type="button" className="icon-button modal-close" aria-label="Close forum post creator" onClick={onClose}><AppIcon name="close" size="sm" /></button><span className="eyebrow">Forum discussion</span><h2>Create post</h2><label>Title<input maxLength={180} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Message<textarea rows={6} maxLength={4000} value={body} onChange={(event) => setBody(event.target.value)} /></label><div className="forum-tools"><div>{tags.filter((tag) => tag !== "Resolved").map((tag) => <button key={tag} type="button" className={selectedTags.includes(tag) ? "active" : ""} onClick={() => setSelectedTags((current) => current.includes(tag) ? current.filter((item) => item !== tag) : [...current, tag])}>{tag}</button>)}</div></div><button className="primary-button" disabled={busy || !title.trim() || !body.trim()}>{busy ? "Creating..." : "Create post"}</button></form></div>;
}

export function ForumChannelView({ community, channel, currentMember, canCreate, onNotice }: { community: Community; channel: Channel; currentMember?: Member; canCreate: boolean; onNotice: (message: string, tone?: "info" | "error" | "success") => void }) {
  const [posts, setPosts] = useState<ForumPost[]>([]); const [query, setQuery] = useState(""); const [activeTag, setActiveTag] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [activePost, setActivePost] = useState<ForumPost | null>(null);
  useEffect(() => { let active = true; const timeout = globalThis.setTimeout(() => { void forumService.listPosts({ communityId: community.id, channelId: channel.id, query }).then((result) => { if (!active) return; if (result.ok) setPosts(result.data); else onNotice(result.message, "error"); }); }, 180); return () => { active = false; globalThis.clearTimeout(timeout); }; }, [channel.id, community.id, onNotice, query]);
  const visible = useMemo(() => posts.filter((post) => !activeTag || post.tags.includes(activeTag)), [activeTag, posts]);
  const create = async (title: string, body: string, selectedTags: string[]) => { if (!currentMember) return; const result = await forumService.createPost({ communityId: community.id, channelId: channel.id, title, body, tags: selectedTags, authorId: currentMember.userId }, canCreate); if (result.ok) { setPosts((items) => [result.data, ...items]); onNotice("Forum post created.", "success"); } else onNotice(result.message, "error"); };
  const threadForPost = (post: ForumPost): ThreadRecord => ({ id: post.threadId, communityId: post.communityId, channelId: post.channelId, parentMessageId: post.parentMessageId, name: post.title, createdBy: post.authorId, createdAt: post.createdAt, summary: { replyCount: post.replyCount, unreadCount: 0, lastReplyAt: post.lastActivityAt } });
  const parentForPost = (post: ForumPost): Message => ({ id: post.parentMessageId, channelId: post.channelId, authorId: post.authorId, body: post.body, createdAt: post.createdAt, threadId: post.threadId });
  return <section className="forum-channel-view"><header><div><p className="eyebrow">Forum channel</p><h2>Explore {channel.name}</h2><span>Focused posts keep longer discussions organized.</span></div><button type="button" disabled={!canCreate} onClick={() => setCreating(true)}><AppIcon name="plus" size="sm" />Create post</button></header><div className="forum-tools"><label><AppIcon name="search" size="sm" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search visible posts" /></label><div>{tags.map((tag) => <button key={tag} type="button" className={activeTag === tag ? "active" : ""} onClick={() => setActiveTag((current) => current === tag ? null : tag)}>{tag}</button>)}</div></div><div className="forum-post-list">{visible.map((post) => { const author = community.members.find((member) => member.userId === post.authorId); return <article key={post.id}><span className={`forum-status ${post.status}`}><AppIcon name={post.status === "resolved" ? "lock" : "inbox"} size="sm" /></span><div><strong>{post.title}</strong><span>{author?.displayName ?? "Community member"} · {post.replyCount} replies · {dateTimeService.formatMessageTime(post.lastActivityAt)}</span><div>{post.tags.map((tag) => <em key={tag}>{tag}</em>)}</div></div><button type="button" aria-label={`Open ${post.title}`} onClick={() => setActivePost(post)}><AppIcon name="chevronRight" size="sm" /></button></article>; })}{!visible.length ? <div className="community-admin-empty"><AppIcon name="search" size="lg" /><strong>No posts found</strong><span>Adjust the search or selected tag.</span></div> : null}</div>{creating ? <CreateForumPostModal onClose={() => setCreating(false)} onCreate={create} /> : null}{activePost && currentMember ? <ThreadPanel thread={threadForPost(activePost)} parentMessage={parentForPost(activePost)} members={community.members} currentUser={currentMember} canSend={canCreate && activePost.status === "open"} onClose={() => setActivePost(null)} onNotice={onNotice} /> : null}</section>;
}
