import { useEffect, useState } from "react";
import type { Member, Message } from "../types/community";
import type { ThreadMessage, ThreadRecord } from "../types/threads";
import { dateTimeService } from "../services/dateTimeService";
import { threadService } from "../services/threadService";
import { AppIcon } from "./AppIcon";
import { MemberAvatar } from "./MemberAvatar";

export function ThreadPanel({ thread, parentMessage, members, currentUser, canSend, onClose, onNotice }: { thread: ThreadRecord; parentMessage: Message; members: Member[]; currentUser: Member; canSend: boolean; onClose: () => void; onNotice: (message: string, tone?: "info" | "error" | "success") => void }) { const [messages, setMessages] = useState<ThreadMessage[]>([]); const [body, setBody] = useState(""); const [sending, setSending] = useState(false); useEffect(() => { let active = true; void threadService.listMessages(thread.id).then((result) => { if (!active) return; if (result.ok) setMessages(result.data); else onNotice(result.message, "error"); }); return () => { active = false; }; }, [onNotice, thread.id]); useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]); const send = async () => { if (!body.trim() || sending) return; setSending(true); const result = await threadService.sendMessage({ thread, authorId: currentUser.userId, body, canSend }); if (result.ok) { setMessages((items) => [...items, result.data]); setBody(""); } else onNotice(result.message, "error"); setSending(false); }; const parentAuthor = members.find((member) => member.userId === parentMessage.authorId); return <aside className="thread-panel" aria-label={`Thread: ${thread.name}`}><header><div><p className="eyebrow">Thread</p><h2>{thread.name}</h2><span>{messages.length} replies</span></div><button className="icon-button" aria-label="Close thread" onClick={onClose}><AppIcon name="close" size="lg" /></button></header><div className="thread-parent"><strong>{parentAuthor?.displayName ?? "Unknown member"}</strong><p>{parentMessage.deletedAt ? "Original message was deleted." : parentMessage.body}</p></div><div className="thread-message-list">{messages.map((message) => { const author = members.find((member) => member.userId === message.authorId) ?? currentUser; return <article key={message.id}><MemberAvatar member={author} size={32} /><div><header><strong>{author.displayName}</strong><time>{dateTimeService.formatMessageTime(message.createdAt)}</time></header><p>{message.body}</p></div></article>; })}{!messages.length ? <div className="thread-empty"><AppIcon name="reply" size="lg" /><strong>No replies yet</strong><span>Start a focused side discussion.</span></div> : null}</div><footer><textarea value={body} rows={2} disabled={!canSend} placeholder={canSend ? "Reply in thread" : "Read-only thread"} onChange={(event) => setBody(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} /><button className="send-button" disabled={!canSend || !body.trim() || sending} onClick={() => void send()}><AppIcon name="send" size="sm" />Send</button></footer></aside>; }
