import { useEffect, useState } from "react";
import type { Community } from "../types/community";
import { verificationRequestService, type VerificationRequestInput, type VerificationRequestRecord } from "../services/verificationRequestService";
import { AppIcon } from "./AppIcon";
import { VerifiedBadge } from "./VerifiedBadge";
import { verificationVariantFromKind } from "../utils/verificationHelpers";

function RequestPanel({ target, community }: { target: "profile" | "community"; community?: Community }) {
  const [requests, setRequests] = useState<VerificationRequestRecord[]>([]); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const [reason, setReason] = useState(""); const [category, setCategory] = useState(target === "profile" ? "individual" : "community"); const [links, setLinks] = useState(""); const [supportingText, setSupportingText] = useState("");
  const load = async () => { setLoading(true); const result = target === "profile" ? await verificationRequestService.getOwnProfileRequests() : await verificationRequestService.getCommunityRequests(community?.id ?? ""); if (result.ok) setRequests(result.data); else setNotice(result.message); setLoading(false); };
  useEffect(() => { void load(); }, [target, community?.id]);
  const latest = [...requests].sort((left, right) => right.requestedAt.localeCompare(left.requestedAt))[0]; const active = latest && ["pending", "approved"].includes(latest.status);
  const submit = async () => { const input: VerificationRequestInput = { category, reason, officialLinks: links.split(/[\n,]/).map((link) => link.trim()).filter(Boolean), supportingText }; setSubmitting(true); setNotice(null); const result = target === "profile" ? await verificationRequestService.requestProfile(input) : await verificationRequestService.requestCommunity(community?.id ?? "", community?.name ?? "Community", input); setSubmitting(false); if (!result.ok) { setNotice(result.message); return; } setRequests((current) => [result.data, ...current]); setReason(""); setLinks(""); setSupportingText(""); setNotice("Verification request submitted for Picom review."); };
  return <section className="verification-request-panel"><header><div><p className="eyebrow">Picom verification</p><h3>{target === "profile" ? "Profile verification" : "Official community verification"}</h3></div>{latest?.status === "approved" ? <VerifiedBadge variant={verificationVariantFromKind(latest.type)} /> : null}</header><p>Verification is free and review-based. Do not submit identity documents, payment data, passwords, or private credentials.</p>{loading ? <div className="verification-request-empty">Loading verification status...</div> : latest ? <div className={`verification-request-summary ${latest.status}`}><span>Current status</span><strong>{latest.status}</strong><small>Requested {new Date(latest.requestedAt).toLocaleDateString()}</small>{latest.decisionReason && ["rejected", "revoked"].includes(latest.status) ? <p><b>Review result:</b> {latest.decisionReason}</p> : null}</div> : <div className="verification-request-empty">No verification request yet.</div>}{!active ? <div className="verification-request-form"><label><span>Category</span><select value={category} onChange={(event) => setCategory(event.target.value)}>{target === "profile" ? <><option value="individual">Individual</option><option value="creator">Creator</option><option value="organization">Organization representative</option><option value="other">Other</option></> : <><option value="community">Community</option><option value="organization">Organization</option><option value="creator">Creator community</option><option value="other">Other</option></>}</select></label><label><span>Reason</span><textarea rows={3} maxLength={1000} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain why this account or community should be verified." /></label><label><span>Official links (optional)</span><textarea rows={2} value={links} onChange={(event) => setLinks(event.target.value)} placeholder="One HTTPS link per line, maximum five" /></label><label><span>Supporting text (optional)</span><textarea rows={3} maxLength={2000} value={supportingText} onChange={(event) => setSupportingText(event.target.value)} placeholder="Public context only. No document upload." /></label><button type="button" disabled={submitting || reason.trim().length < 20} onClick={() => void submit()}><AppIcon name="send" size="sm" />{submitting ? "Submitting..." : "Request verification"}</button></div> : null}{notice ? <p className="verification-request-notice" role="status">{notice}</p> : null}</section>;
}

export function ProfileVerificationRequestCard() { return <RequestPanel target="profile" />; }
export function CommunityVerificationRequestCard({ community }: { community: Community }) { return <RequestPanel target="community" community={community} />; }

export function VerificationAdminReviewQueue() {
  const [requests, setRequests] = useState<VerificationRequestRecord[]>([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<string | null>(null); const [reasons, setReasons] = useState<Record<string, string>>({}); const [busyId, setBusyId] = useState<string | null>(null);
  const load = async () => { setLoading(true); const result = await verificationRequestService.listReviewQueue(); if (result.ok) setRequests(result.data); else setNotice(result.message); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const review = async (request: VerificationRequestRecord, nextStatus: "approved" | "rejected" | "revoked") => { setBusyId(request.id); const result = await verificationRequestService.review(request, nextStatus, reasons[request.id] ?? ""); setBusyId(null); if (!result.ok) { setNotice(result.message); return; } setRequests((current) => current.map((item) => item.id === request.id ? result.data : item)); setReasons((current) => ({ ...current, [request.id]: "" })); setNotice(`Verification ${nextStatus}. Audit log recorded.`); };
  return <section className="verification-admin-queue"><header><div><p className="eyebrow">Restricted review</p><h3>Verification Requests</h3></div><button type="button" onClick={() => void load()}><AppIcon name="search" size="sm" />Refresh</button></header><p>Request reasons and supporting text are private reviewer context. No identity-document upload is supported.</p>{notice ? <p className="verification-request-notice" role="status">{notice}</p> : null}{loading ? <div className="verification-request-empty">Loading protected review queue...</div> : requests.length ? <div className="verification-review-list">{requests.map((request) => <article key={request.id}><header><div><strong>{request.targetName}</strong><span>{request.targetType} / {request.type} / {request.status}</span></div>{request.status === "approved" ? <VerifiedBadge variant={verificationVariantFromKind(request.type)} /> : null}</header><p>{request.reason ?? "No requester reason available."}</p>{request.supportingText ? <small>{request.supportingText}</small> : null}{request.officialLinks.length ? <div className="verification-review-links">{request.officialLinks.map((link) => <span key={link}>{link}</span>)}</div> : null}<textarea value={reasons[request.id] ?? ""} maxLength={1000} onChange={(event) => setReasons((current) => ({ ...current, [request.id]: event.target.value }))} placeholder="Private decision reason (minimum 10 characters)" rows={2} /><div className="verification-review-actions">{request.status === "pending" ? <><button disabled={busyId === request.id} onClick={() => void review(request, "approved")}>Approve</button><button className="danger" disabled={busyId === request.id} onClick={() => void review(request, "rejected")}>Reject</button></> : request.status === "approved" ? <button className="danger" disabled={busyId === request.id} onClick={() => void review(request, "revoked")}>Revoke</button> : null}</div></article>)}</div> : <div className="verification-request-empty">No verification requests.</div>}</section>;
}
