/** Settings modal sections — EN catalog extension merged into settingsI18n.en */
export const settingsModalEn = {
  "privacy.description":
    "Central desktop controls for blocking, privacy, data requests, and safety guidance. Supabase/RLS remains the source of truth for production enforcement.",
  "privacy.jumpAria": "Privacy sections",
  "privacy.jump.reach": "Who can reach you",
  "privacy.jump.visibility": "Profile visibility",
  "privacy.jump.blocking": "Blocking & mutes",
  "privacy.jump.data": "Data & guidance",
  "privacy.reach.title": "Who can reach you",
  "privacy.friendRequests.label": "Who can send friend requests",
  "privacy.friendRequests.hint": "Controls incoming friend requests while preserving existing community access.",
  "privacy.option.everyone": "Everyone",
  "privacy.option.communityMembers": "Community members",
  "privacy.option.friendsOfFriends": "Friends of friends",
  "privacy.option.nobody": "Nobody",
  "privacy.dm.label": "Who can start a direct message",
  "privacy.dm.hint": "Existing blocked relationships remain inaccessible regardless of this preference.",
  "privacy.option.friendsOnly": "Friends only",
  "privacy.option.noOne": "No one",
  "privacy.onlineStatus.label": "Show online status",
  "privacy.onlineStatus.hint": "Hide your online status and status text from other profile viewers.",
  "privacy.readReceipts.label": "Read receipts",
  "privacy.readReceipts.hint":
    "Controls whether eligible conversations may publish read receipts; detailed reader lists remain disabled.",
  "privacy.visibility.title": "Profile visibility",
  "privacy.profileAudience.label": "Profile audience",
  "privacy.profileAudience.hint":
    "Private-channel activity is always filtered by channel access, regardless of this choice.",
  "privacy.option.sharedCommunities": "Shared communities",
  "privacy.showLocation.label": "Show location",
  "privacy.showLocation.hint": "Hide your location from profile viewers.",
  "privacy.showTimezone.label": "Show timezone",
  "privacy.showTimezone.hint": "Hide your timezone from profile viewers.",
  "privacy.showActivity.label": "Show recent activity",
  "privacy.showActivity.hint":
    "Only friends or shared-community members can see activity, and only from channels they may access.",
  "privacy.showMedia.label": "Show shared media",
  "privacy.showMedia.hint": "Only friends or shared-community members can see eligible media.",
  "privacy.showCommunities.label": "Show communities and roles",
  "privacy.showCommunities.hint": "Hide community and role summaries from your public profile.",
  "privacy.showFriends.label": "Show friends",
  "privacy.showFriends.hint": "Allow trusted profile viewers to see friendship context when supported.",
  "privacy.showFollows.label": "Show follower counts",
  "privacy.showFollows.hint": "Control follower and following statistics on your profile.",
  "privacy.showAudio.label": "Show Radio and Podcast sections",
  "privacy.showAudio.hint": "Hide audio activity from your profile without removing public community audio.",
  "privacy.overview.title": "Overview",
  "privacy.safetySummary.aria": "Safety summary",
  "privacy.safetySummary.title": "Safety summary",
  "privacy.safetySummary.hint":
    "Privacy choices are enforced locally and synchronized to Supabase when connected; passwords, tokens, and message content are never stored here.",
  "privacy.publicVisibility.aria": "Public and visitor profile behavior",
  "privacy.publicVisibility.title": "Public and visitor visibility",
  "privacy.publicVisibility.hint":
    "Visitors never receive private-channel activity or media. Each section above can be hidden independently, and server-side profile projection remains authoritative.",
  "privacy.visibilityStrong.public": "Safe profile basics are public",
  "privacy.visibilityStrong.sharedCommunities": "Shared communities only",
  "privacy.visibilityStrong.friendsOnly": "Friends only",
  "privacy.metrics.aria": "Privacy metrics",
  "privacy.metrics.blockedUsers": "Blocked users",
  "privacy.metrics.blockedHint": "Community messages are collapsed and direct messages are disabled for blocked users.",
  "privacy.metrics.onlineStatus": "Online status",
  "privacy.metrics.onlineHint": "Profile visibility is synchronized when Supabase profile privacy is available.",
  "privacy.metrics.readReceipts": "Read receipts",
  "privacy.metrics.readReceiptsHint":
    "Read receipts remain opt-in and should not expose detailed reads in large communities.",
  "privacy.metrics.accountData": "Account data",
  "privacy.exportReady": "Export ready",
  "privacy.exportProcessing": "Export processing",
  "privacy.exportNotRequested": "Export not requested",
  "privacy.deletionPending": "Deletion request recorded; sign in again to cancel during the review period.",
  "privacy.noDeletionRequest": "No deletion request active.",
  "privacy.blocking.title": "Blocking & mutes",
  "privacy.blockedList.aria": "Blocked users list",
  "privacy.blockedUsers.title": "Blocked users",
  "privacy.blockedManageLocally": "Manage locally",
  "privacy.noBlockedUsers": "No blocked users",
  "privacy.blockedListHint": "Blocked users are enforced locally and synchronized through Supabase RLS when connected.",
  "privacy.blockedSuffix": "blocked {when}",
  "privacy.blockListClear.title": "Your block list is clear",
  "privacy.blockListClear.hint": "Use member/profile actions to block someone locally.",
  "privacy.muteAll.label": "Mute all notifications",
  "privacy.muteAll.hint":
    "Suppress desktop alerts while keeping the inbox available. This does not hide moderation-required content.",
  "privacy.mutedScopes.aria": "Muted communities and channels",
  "privacy.mutedScopes.title": "Muted scopes",
  "privacy.mutedScopesManage": "Manage notification and feed mutes",
  "privacy.noMutedScopesSummary": "No muted communities or channels",
  "privacy.mutedScopesHint":
    "Muted scopes suppress native notifications and normal Mention Feed items. Community chat and moderator queues stay accessible.",
  "privacy.unavailableCommunity": "Unavailable community",
  "privacy.communityMute": "Community mute",
  "privacy.channelMuteSuffix": "{community} · channel mute",
  "privacy.unavailableChannel": "unavailable-channel",
  "privacy.noMutedScopes.title": "No muted scopes",
  "privacy.noMutedScopes.hint": "Mute communities or channels from their context menus.",
  "privacy.data.title": "Data & guidance",
  "privacy.analytics.label": "Share anonymous usage diagnostics",
  "privacy.analytics.hint":
    "Off by default. Records feature counts and app health locally; never message content, passwords, tokens, channel names, or attachment contents.",
  "privacy.retention.aria": "Content deletion and retention information",
  "privacy.retention.title": "Content deletion and retention",
  "privacy.retention.strong": "Deletion hides content; retention periods are not yet enforced",
  "privacy.retention.body1":
    "Deleted messages appear as placeholders and their content, reactions, and attachments are hidden. Picom does not currently run an automatic production purge. Limited tombstones, moderation records, immutable audit events, and backups follow separate review and retention paths. Deleted accounts use a “Deleted User” fallback where historical context must remain.",
  "privacy.retention.body2":
    "Final retention periods and legal copy are pending privacy/legal approval. Clearing desktop cache does not delete server data; use Account data controls for export or deletion requests.",
  "privacy.safetyTips.aria": "Safety tips",
  "privacy.safetyTips.title": "Safety tips",
  "privacy.safetyTips.strong": "Stay in control",
  "privacy.safetyTips.hint":
    "Do not share passwords, tokens, recovery codes, or private invite links. Report suspicious behavior from message/member context actions.",
  "privacy.actions.aria": "Privacy data actions",
  "privacy.requestExport": "Request data export",
  "privacy.exportInAccountCenter": "Export runs in Account Center…",
  "privacy.accountDeletion": "Account deletion",
  "privacy.reportProblem": "Report a problem",
  "privacy.resetSafety": "Reset safety settings",
  "common.visible": "Visible",
  "common.hidden": "Hidden",
  "common.checking": "Checking…",
  "common.hide": "Hide",
  "profile.description":
    "Edit avatar, cover, username, bio, and presence here. Changes save through Supabase when you are signed in.",
  "profile.loading": "Loading your live profile from Supabase…",
  "profile.photos.title": "Photos",
  "profile.photos.intro": "Upload or remove your profile and cover photos.",
  "profile.public.title": "Public profile",
  "profile.public.intro": "Public profile fields shown across Picom.",
  "profile.displayName": "Display name",
  "profile.preferredLanguage": "Preferred language",
  "profile.tagsHint": "Up to 12 comma-separated tags.",
  "profile.presence.title": "Presence",
  "profile.presence.intro": "Status shown while you use Picom on desktop.",
  "profile.statusMessage": "Status message",
  "profile.discardChanges": "Discard changes",
  "profile.openPrivacy": "Privacy & safety",
  "profile.openOnWeb": "Open on web",
  "profile.identity.title": "Identity",
  "profile.username": "Username",
  "profile.usernameHint": "3–32 characters: lowercase letters, numbers, dots, underscores, or hyphens.",
  "profile.bio": "Bio",
  "profile.location": "Location",
  "profile.timezone": "Timezone",
  "profile.tags": "Tags",
  "profile.presenceField": "Presence",
  "profile.saveProfile": "Save profile",
  "profile.saving": "Saving...",
  "profile.loadingProfile": "Loading profile...",
  "profile.autoActivityHint": "Automatic activity status is writing this field while enabled.",
  "profile.saveStatusHint": "Optional. Saved with Save profile.",
  "profile.placeholder.username": "username",
  "profile.placeholder.displayName": "Display name",
  "profile.placeholder.bio": "Write a short profile bio",
  "profile.placeholder.location": "City or region",
  "profile.placeholder.timezone": "Europe/Berlin",
  "profile.placeholder.preferredLanguage": "English",
  "profile.placeholder.tags": "Design, Community, Music",
  "profile.placeholder.statusMessage": "Optional status shown with your presence",
  "notifications.description":
    "Choose which Picom activity can reach your inbox and desktop. Native delivery remains behind the safe preload bridge.",
  "notifications.jump.runtime": "Desktop delivery",
  "notifications.jump.categories": "Categories",
  "notifications.jump.quiet": "Quiet Hours",
  "notifications.jump.muted": "Muted scopes",
  "notifications.runtime.title": "Runtime & delivery",
  "notifications.runtime.aria": "Notification runtime status",
  "notifications.runtimeSupport": "Runtime support",
  "notifications.permissionLine": "Permission: {permission}. Account preferences synchronize when Supabase mode is available.",
  "notifications.sendTest": "Send test notification",
  "notifications.masterHint": "Master preference for notification inbox, unread routing, and desktop alerts.",
  "notifications.nativeHint": "Show approved alerts outside Picom when the desktop runtime and permission allow it.",
  "notifications.soundHint": "Play the operating-system notification sound when an alert is not silenced by Quiet Hours.",
  "notifications.dndHint": "Pause desktop interruptions while preserving the notification inbox and unread state.",
  "notifications.categories.aria": "Notification categories",
  "notifications.categories.title": "Categories",
  "notifications.categories.strong": "Choose what notifies you",
  "notifications.categories.hint": "Disabled categories do not create native alerts or inbox entries.",
  "notifications.mentionsOnly.label": "Mentions only",
  "notifications.mentionsOnly.hint": "Suppress normal-message desktop alerts while preserving mentions and system notices.",
  "notifications.digest.label": "Message digest preview",
  "notifications.digest.hint": "{mode} groups lower-priority messages in the inbox instead of interrupting you.",
  "notifications.digest.off": "Off",
  "notifications.digest.hourly": "Hourly grouping",
  "notifications.digest.daily": "Daily grouping",
  "notifications.quiet.title": "Quiet Hours",
  "notifications.quiet.aria": "Quiet Hours notification setting",
  "notifications.schedule": "Schedule",
  "notifications.quietDisabled": "Disabled",
  "notifications.quietTimezoneHint":
    "Uses your system timezone. Notification inbox can still record suppressed notifications later.",
  "notifications.enableQuiet.label": "Enable Quiet Hours",
  "notifications.enableQuiet.hint": "Silence notification interruptions during scheduled hours.",
  "notifications.startTime": "Start time",
  "notifications.endTime": "End time",
  "notifications.startTimeHint": "Local desktop time when Quiet Hours begin.",
  "notifications.endTimeHint": "Local desktop time when Quiet Hours end.",
  "notifications.applyTo.label": "Apply to",
  "notifications.applyTo.hint": "Choose whether Quiet Hours suppress all notifications, normal messages, or sounds only.",
  "notifications.applyTo.all": "All notifications",
  "notifications.applyTo.normalOnly": "Normal messages only",
  "notifications.applyTo.soundsOnly": "Sounds only",
  "notifications.allowMentionsQuiet.label": "Allow mentions during Quiet Hours",
  "notifications.allowMentionsQuiet.hint": "Mentions can still notify when this preference is enabled.",
  "notifications.allowMentionsMuted.label": "Allow mentions from muted communities and channels",
  "notifications.allowMentionsMuted.hint": "When disabled, muted scopes suppress mentions as well as normal activity.",
  "notifications.muted.title": "Muted scopes",
  "notifications.muted.aria": "Muted communities and channels",
  "notifications.mutedSummary.active": "Muted communities and channels",
  "notifications.mutedSummary.none": "No muted communities or channels",
  "notifications.mutedHint": "Muted scopes suppress normal activity. Mentions follow your muted-scope override above.",
  "notifications.channelMute": "channel mute",
  "voice.section.description":
    "Manage permission-gated voice devices, LiveKit capture processing, screen-share guidance, and Radio/Podcast playback defaults.",
  "voice.jump.aria": "Voice settings sections",
  "voice.jump.live": "Live session",
  "voice.jump.microphone": "Microphone",
  "voice.jump.output": "Output",
  "voice.jump.noise": "Noise Shield",
  "voice.live.title": "Live session",
  "voice.live.aria": "Voice session status",
  "voice.live.connection": "Connection",
  "voice.live.microphone": "Microphone",
  "voice.live.incoming": "Incoming audio",
  "voice.live.screenShare": "Screen share",
  "voice.live.roomPrefix": "Room: {room}",
  "voice.live.joinHint": "Join a voice channel to activate controls.",
  "voice.live.muted": "Muted",
  "voice.live.unmuted": "Unmuted",
  "voice.live.deafened": "Deafened",
  "voice.live.listening": "Listening",
  "voice.live.sharing": "Sharing",
  "voice.live.notSharing": "Not sharing",
  "voice.live.shortcutMic": "Shortcut: Ctrl + Shift + M while connected.",
  "voice.live.shortcutDeafen": "Shortcut: Ctrl + Shift + D while connected.",
  "voice.live.sourceHint": "Source selection is available from an active voice room.",
  "voice.live.unmuteMic": "Unmute microphone",
  "voice.live.muteMic": "Mute microphone",
  "voice.live.undeafen": "Undeafen",
  "voice.live.deafen": "Deafen",
  "voice.live.hintDisconnected": "Mute and deafen unlock when you join a voice channel.",
  "companion.description":
    "Control Companion Mode startup, bubble/dock behavior, and always-on-top overlays without leaving the main app.",
  "companion.loading.aria": "Companion preferences loading",
  "companion.loading.title": "Companion",
  "companion.loading.hint": "Companion preferences sync through the desktop shell when available.",
  "companion.startup.title": "Startup",
  "companion.startup.aria": "Companion startup mode",
  "companion.openAs": "Open Picom as",
  "companion.modeCompanion": "Companion Mode",
  "companion.modeMain": "Main window",
  "companion.startupHint": "Companion startup keeps the main window hidden and opens the always-available shell.",
  "companion.mainMode": "Main mode",
  "companion.companionMode": "Companion",
  "companion.behavior.title": "Behavior",
  "companion.alwaysOnTop.label": "Always on top",
  "companion.alwaysOnTop.hint": "Keep Companion windows above other apps.",
  "companion.smartCollapse.label": "Smart collapse",
  "companion.smartCollapse.hint": "Collapse to the logo bubble when unread is clear.",
  "companion.dockAutoHide.label": "Dock auto-hide",
  "companion.dockAutoHide.hint": "Hide the edge dock until you move near it.",
  "companion.gamingAutoDetect.label": "Gaming auto-detect",
  "companion.gamingAutoDetect.hint": "Show the gaming overlay when fullscreen play is detected.",
  "companion.notifications.label": "Companion notifications",
  "companion.notifications.hint": "Show toast replies and unread previews in Companion surfaces.",
  "companion.closeToTray.label": "Close to tray",
  "companion.closeToTray.hint": "Minimize Companion to the tray instead of exiting.",
  "companion.compactDensity.label": "Compact density",
  "companion.compactDensity.hint": "Tighter rows in Companion lists and chat.",
  "companion.appearance.title": "Appearance",
  "companion.windowOpacity.aria": "Companion window opacity",
  "companion.windowOpacity": "Window opacity",
  "companion.dockEdge.aria": "Companion dock edge",
  "companion.dockEdge": "Dock edge",
  "companion.theme.aria": "Companion theme",
  "companion.theme": "Companion theme",
  "companion.shortcuts.title": "Shortcuts",
  "companion.shortcuts.aria": "Companion shortcuts",
  "companion.shortcut.open": "Open Companion",
  "companion.shortcut.openHint": "Switch to Companion Mode from the desktop shell.",
  "companion.shortcut.quickReply": "Quick reply",
  "companion.shortcut.quickReplyHint": "Answer from a Companion notification toast.",
  "companion.shortcut.muteMic": "Mute microphone",
  "companion.shortcut.muteMicHint": "Toggle mute while a Companion voice call is connected.",
  "companion.openCompanion": "Open Companion",
  "companion.openGaming": "Open gaming mode",
  "diagnostics.shell.description":
    "Review redacted runtime health, export support payloads, and inspect local logs without exposing secrets.",
  "diagnostics.shell.jump.aria": "Diagnostics sections",
  "diagnostics.shell.jump.support": "Support",
  "diagnostics.shell.jump.snapshot": "Snapshot",
  "diagnostics.shell.jump.logs": "Logs",
  "advanced.description":
    "Tray, window controls, file handling and clipboard are routed through safe services.",
  "advanced.jump.aria": "Advanced sections",
  "advanced.jump.runtime": "Runtime",
  "advanced.jump.recovery": "Recovery",
  "advanced.jump.updates": "Updates",
  "advanced.jump.startup": "Startup",
  "advanced.jump.cache": "Cache",
  "advanced.runtime.title": "Runtime & build",
  "advanced.devPortal.aria": "Developer Portal restricted beta",
  "advanced.devPortal.title": "Developer Portal",
  "advanced.devPortal.strong": "Restricted beta",
  "advanced.devPortal.hint":
    "Review safe bot/webhook metadata and developer guidance. No raw keys, application registration, or public publishing.",
  "advanced.devPortal.open": "Open Developer Portal",
  "advanced.about.aria": "About Picom build metadata",
  "advanced.about.title": "About Picom",
  "advanced.about.betaLocal": "Beta · Local development",
  "advanced.about.betaPreview": "Beta · Frontend preview",
  "advanced.about.localHint": "Local desktop preview build. Packaged release metadata is injected at CI/build time.",
  "advanced.about.packagedHint": "Desktop build metadata for this Picom package.",
  "advanced.about.channelLine": "Channel {channel} · scope {scope} · {identifier}.",
  "advanced.about.build": "Build",
  "advanced.about.commit": "Commit",
  "advanced.about.runtime": "Runtime",
  "advanced.about.apiCompat": "API compatibility",
  "advanced.about.localUnstamped": "Local / unstamped",
  "advanced.about.localWorkspace": "Local workspace",
  "advanced.about.electronDesktop": "Electron desktop",
  "advanced.about.browserPreview": "Browser preview",
  "advanced.about.mvpPlaceholder": "Desktop MVP (placeholder)",
  "advanced.runtimeGrid.aria": "Advanced runtime summary",
  "advanced.card.release": "Release",
  "advanced.card.dataSource": "Data source",
  "advanced.card.localData": "Local data",
  "advanced.card.recoveryBackups": "Recovery backups",
  "advanced.card.localDataHint": "Bounded non-sensitive local migration backups; auth storage is excluded.",
  "advanced.card.migrationReview": "Last migration needs Safe Mode review",
  "advanced.card.migrationPending": "Migration manifest will be created at startup",
  "advanced.card.migratedAt": "Migrated {when}",
  "advanced.recovery.title": "Recovery & desktop shell",
  "advanced.safeMode.aria": "Safe Mode recovery",
  "advanced.safeMode.title": "Safe Mode",
  "advanced.safeMode.active": "Active: {reason}",
  "advanced.safeMode.available": "Available for troubleshooting",
  "advanced.safeMode.hint":
    "Safe Mode pauses optional services without clearing your authentication session or server data.",
  "advanced.restartSafeMode": "Restart in Safe Mode",
  "advanced.resetLayout": "Reset layout",
  "advanced.resetLocalSettings": "Reset local settings",
  "advanced.nativeMenu.aria": "Native app menu foundation",
  "advanced.nativeMenu.title": "Native app menu",
  "advanced.nativeMenu.strong": "Hidden chrome, safe actions",
  "advanced.nativeMenu.hint":
    "The operating-system menu remains hidden for the custom Picom titlebar. Desktop menu actions route through menuService instead of direct Electron calls.",
  "advanced.resetFirstLaunch": "Reset first-launch setup",
  "advanced.resetFirstLaunch.aria": "Reset first launch setup for development testing",
  "advanced.systemStatus.aria": "System status controls",
  "advanced.systemStatus.title": "System status",
  "advanced.systemStatus.panelOpenOperational": "Panel open · operational",
  "advanced.systemStatus.panelOpenDegraded": "Panel open · degraded",
  "advanced.systemStatus.panelOpenMaintenance": "Panel open · maintenance",
  "advanced.systemStatus.inApp": "In-app health check",
  "advanced.systemStatus.hint": "Shows live backend, voice, realtime, and network status without leaving Settings.",
  "advanced.refreshSystemStatus": "Refresh system status",
  "advanced.openSystemStatus": "Open system status",
  "advanced.liveStatus.aria": "Live system status",
  "advanced.status.allOperational": "All systems operational",
  "advanced.status.degraded": "Some services degraded",
  "advanced.status.maintenance": "Under maintenance",
  "advanced.status.row.app": "App",
  "advanced.status.row.backend": "Backend",
  "advanced.status.row.voice": "Voice (LiveKit)",
  "advanced.status.row.realtime": "Realtime",
  "advanced.status.row.network": "Network",
  "advanced.status.row.lastChecked": "Last checked",
  "advanced.status.configured": "Configured",
  "advanced.status.notConfigured": "Not configured",
  "advanced.status.mockData": "Mock data",
  "advanced.status.online": "Online",
  "advanced.status.offline": "Offline",
  "advanced.updates.title": "Updates & diagnostics",
  "advanced.desktopUpdates.aria": "Desktop update recovery status",
  "advanced.desktopUpdates.title": "Desktop updates",
  "advanced.desktopUpdates.hint": "Version {version} on {channel}. Full update controls live in the Update settings section.",
  "advanced.openUpdateSettings": "Open Update settings",
  "advanced.supportDiagnostics.aria": "Support diagnostics export",
  "advanced.supportDiagnostics.title": "Support diagnostics",
  "advanced.supportDiagnostics.strong": "Redacted snapshot ready",
  "advanced.supportDiagnostics.hint":
    "Review app/platform, data source, realtime, voice, recent errors, and redacted logs before sharing.",
  "advanced.openDiagnostics": "Open diagnostics",
  "advanced.crashReports.label": "Enable diagnostic reports",
  "advanced.crashReports.hint":
    "Off by default. Stores a bounded redacted local crash envelope; no provider or DSN is configured.",
  "advanced.statusPage.aria": "System status page",
  "advanced.statusPage.title": "System status page",
  "advanced.startup.title": "Startup & behavior",
  "advanced.launchStartup.aria": "Launch on startup",
  "advanced.launchStartup.title": "Launch on startup",
  "advanced.launchStartup.hint":
    "Mode: {mode}. Windows/macOS registration is available only in packaged builds; Linux remains unsupported safely.",
  "advanced.launchPicom.label": "Launch Picom on startup",
  "advanced.launchPicom.hint": "Registers Picom only after you enable it. Disabled by default.",
  "advanced.startMinimized.label": "Start minimized to tray",
  "advanced.startMinimized.hint":
    "Applied when launch-on-startup and native tray support are available; stored per device.",
  "advanced.closeToTray.label": "Close to tray",
  "advanced.closeToTray.hint":
    "When supported, the close button hides Picom. Use Quit from the tray menu to exit completely.",
  "advanced.appLock.aria": "App lock status",
  "advanced.appLock.title": "App lock",
  "advanced.appLock.hint":
    "Quick lock hides chat content without storing a password locally. Account authentication remains managed by Supabase.",
  "advanced.openKeyboardShortcuts": "Open Keyboard Shortcuts",
  "advanced.inactivityLock.label": "Automatic inactivity lock",
  "advanced.inactivityLock.hint": "Not available in Full MVP. Use Ctrl + Shift + L to lock Picom immediately.",
  "advanced.cache.title": "Cache & support",
  "advanced.cache.aria": "Cache management",
  "advanced.cache.titleCard": "Cache management",
  "advanced.cache.loading": "Loading cache summary",
  "advanced.cache.imageEntries": "{used}/{max} image cache entries",
  "advanced.cache.storageEstimate": "Storage estimate: {used}{quota}. Auth sessions and drafts are preserved.",
  "advanced.cache.ofQuota": " of {quota}",
  "advanced.cache.grid.aria": "Cache summary cards",
  "advanced.cache.images": "Images",
  "advanced.cache.imagesHint": "Metadata-only cache entries. Browser image bytes remain Chromium-managed.",
  "advanced.cache.logs": "Logs",
  "advanced.cache.logsHint": "Recent redacted in-memory log entries.",
  "advanced.cache.messages": "Messages",
  "advanced.cache.messagesHint":
    "Picom does not persist a separate message cache; server messages and local drafts are untouched.",
  "advanced.cache.offline": "Offline data",
  "advanced.cache.offlineHint": "Pending messages stay in memory and are preserved by cache clearing.",
  "advanced.cache.queued": "{count} queued",
  "advanced.cache.memoryOnly": "memory only",
  "advanced.refreshCacheSummary": "Refresh cache summary",
  "advanced.clearImageCache": "Clear image cache",
  "advanced.clearLogs": "Clear logs",
  "advanced.clearAllCache": "Clear all non-essential cache",
  "advanced.confirm.clearImage":
    "Clear Picom's in-memory image metadata cache? Images will load again when needed.",
  "advanced.confirm.clearLogs": "Clear recent redacted logs from this Picom session?",
  "advanced.confirm.clearAll":
    "Clear all non-essential image metadata and redacted logs? Auth sessions, drafts, queued messages, and server data are preserved.",
  "advanced.betaSupport.aria": "Beta feedback and redacted logs",
  "advanced.betaSupport.title": "Beta support",
  "advanced.betaSupport.strong": "Feedback and redacted exports",
  "advanced.betaSupport.hint":
    "User-facing feedback stays separate from redacted developer diagnostics. Prepared reports remain local until you explicitly copy/export them or open the support portal.",
  "advanced.feedback.issueType": "Issue type",
  "advanced.feedback.issueTypeHint": "Used only in the local export payload.",
  "advanced.feedback.issue.bug": "Bug",
  "advanced.feedback.issue.crash": "Crash",
  "advanced.feedback.issue.login": "Login",
  "advanced.feedback.issue.message": "Message",
  "advanced.feedback.issue.upload": "Upload",
  "advanced.feedback.issue.voice": "Voice",
  "advanced.feedback.issue.packaging": "Packaging",
  "advanced.feedback.issue.other": "Other",
  "advanced.feedback.titlePlaceholder": "Short feedback title",
  "advanced.feedback.descPlaceholder": "Describe what happened. Do not include passwords, tokens, or secrets.",
  "advanced.feedback.titleAria": "Feedback title",
  "advanced.feedback.descAria": "Feedback description",
  "advanced.feedback.issueTypeAria": "Feedback issue type",
  "advanced.feedback.includeDiagnostics": "Include diagnostics",
  "advanced.feedback.includeDiagnosticsHint": "Includes app mode, release channel, runtime, and non-sensitive state.",
  "advanced.feedback.includeLogs": "Include recent redacted logs",
  "advanced.feedback.includeLogsHint": "Logs are redacted by loggingService before export.",
  "advanced.copyFeedbackReport": "Copy feedback report",
  "advanced.exportDiagnosticsJson": "Export diagnostics JSON",
  "advanced.openDiagnosticsFeedback": "Open Diagnostics feedback",
} as const;

export type SettingsModalEnKey = keyof typeof settingsModalEn;
