#!/usr/bin/env pwsh
# Deploy LiveKit Ingress beside the existing Picom LiveKit stack on picom-update-server.
# Does not print API keys/secrets. Fail-closed if keys cannot be read from livekit.yaml.
# Does not restart picom-livekit unless ingress.rtmp_base_url must be added to livekit.yaml.

[CmdletBinding()]
param(
  [string]$Server = "picom-update-server",
  [string]$SshUser = "root",
  [int]$SshPort = 22,
  [string]$RemoteDirectory = "/home/picom/.config/picom/livekit",
  [string]$SshHostAlias = "picom-update-server",
  [string]$IngressImage = "livekit/ingress:v1.4.2",
  [string]$RtmpBaseUrl = "rtmp://ingest.picom.gg/live",
  [string]$WhipBaseUrl = "https://ingest.picom.gg/whip",
  [switch]$UseSudo
)

$ErrorActionPreference = "Stop"

if ($Server -notmatch '^[A-Za-z0-9.-]+$') { throw "Server must be a hostname or IPv4 address." }
if ($SshUser -notmatch '^[A-Za-z_][A-Za-z0-9_-]{0,31}$') { throw "SSH user contains unsupported characters." }
if ($RemoteDirectory -notmatch '^/[A-Za-z0-9._/-]+$') { throw "Remote directory is invalid." }
if ($SshPort -lt 1 -or $SshPort -gt 65535) { throw "SSH port is invalid." }
if ($IngressImage -notmatch '^livekit/ingress:v[0-9]+\.[0-9]+\.[0-9]+$') { throw "Ingress image pin is invalid." }
if ($RtmpBaseUrl -notmatch '^rtmps?://') { throw "RtmpBaseUrl must be an rtmp(s) URL." }

if (-not (Get-Command ssh -ErrorAction SilentlyContinue)) {
  throw "ssh is unavailable. Install the Windows OpenSSH Client."
}

$target = if ($PSBoundParameters.ContainsKey('SshUser') -or $SshUser -ne 'root') {
  # Prefer SSH host alias (picom-update-server) which already carries User/IdentityFile.
  if ($Server -eq 'picom-update-server' -or $Server -eq $SshHostAlias) { 'picom-update-server' } else { "${SshUser}@${Server}" }
} else {
  'picom-update-server'
}
$privilege = if ($UseSudo) { "sudo " } else { "" }
$stamp = [DateTimeOffset]::UtcNow.ToString("yyyyMMddTHHmmssZ")

# Single remote script. Secrets stay on the server and are never printed.
$remote = @"
set -euo pipefail
DIR='$RemoteDirectory'
IMAGE='$IngressImage'
RTMP_BASE='$RtmpBaseUrl'
WHIP_BASE='$WhipBaseUrl'
STAMP='$stamp'
cd "`$DIR"

if [ ! -f docker-compose.yaml ] || [ ! -f livekit.yaml ]; then
  echo "FAIL: required LiveKit files missing in `$DIR" >&2
  exit 2
fi

export DIR IMAGE RTMP_BASE WHIP_BASE STAMP
${privilege}python3 - <<'PY'
import os, re, stat, subprocess, sys
from pathlib import Path

dir_path = Path(os.environ["DIR"])
image = os.environ["IMAGE"]
rtmp_base = os.environ["RTMP_BASE"]
whip_base = os.environ["WHIP_BASE"]
stamp = os.environ["STAMP"]

compose = dir_path / "docker-compose.yaml"
livekit = dir_path / "livekit.yaml"
ingress_cfg = dir_path / "ingress.yaml"

text = livekit.read_text(encoding="utf-8")
# Parse first key under keys: without printing values.
api_key = api_secret = None
in_keys = False
for raw in text.splitlines():
    line = raw.rstrip()
    if re.match(r"^keys:\s*$", line):
        in_keys = True
        continue
    if in_keys:
        if re.match(r"^\S", line):
            break
        m = re.match(r"^\s+([A-Za-z0-9_-]+)\s*:\s*(.+?)\s*$", line)
        if m:
            api_key, api_secret = m.group(1), m.group(2).strip().strip("\"'")
            break

if not api_key or not api_secret or len(api_key) < 8 or len(api_secret) < 16:
    print("FAIL: could not read LiveKit API key/secret from livekit.yaml", file=sys.stderr)
    sys.exit(3)

# Backups (never print file contents)
subprocess.check_call(["cp", "-a", str(compose), str(dir_path / f"docker-compose.yaml.bak-{stamp}")])
subprocess.check_call(["cp", "-a", str(livekit), str(dir_path / f"livekit.yaml.bak-{stamp}")])

ingress_body = (
    "# Generated by deploy-livekit-ingress.ps1 — do not commit.\n"
    "# Compatible with LiveKit server v1.13.x; image pinned by deploy script.\n"
    f"api_key: {api_key}\n"
    f"api_secret: {api_secret}\n"
    "ws_url: ws://127.0.0.1:7880\n"
    "redis:\n"
    "  address: 127.0.0.1:6379\n"
    "rtmp_port: 1935\n"
    "whip_port: 8085\n"
    "http_relay_port: 9090\n"
    "logging:\n"
    "  level: info\n"
)
ingress_cfg.write_text(ingress_body, encoding="utf-8")
os.chmod(ingress_cfg, stat.S_IRUSR | stat.S_IWUSR)

need_livekit_restart = False
livekit_text = livekit.read_text(encoding="utf-8")
if "rtmp_base_url" not in livekit_text:
    need_livekit_restart = True
    if re.search(r"^ingress:\s*$", livekit_text, flags=re.M) is None:
        livekit.write_text(
            livekit_text.rstrip()
            + "\n\ningress:\n"
            + f"  rtmp_base_url: '{rtmp_base}'\n"
            + f"  whip_base_url: '{whip_base}'\n",
            encoding="utf-8",
        )
    print("INFO: added ingress base URLs to livekit.yaml (picom-livekit restart required)")

compose_text = compose.read_text(encoding="utf-8")
redis_service = None
for candidate in ("picom-livekit-redis", "redis", "livekit-redis"):
    if re.search(rf"^\s+{re.escape(candidate)}:\s*$", compose_text, flags=re.M):
        redis_service = candidate
        break

depends = f"\n    depends_on:\n      - {redis_service}\n" if redis_service else "\n"
service = f"""
  picom-livekit-ingress:
    image: {image}
    container_name: picom-livekit-ingress
    restart: unless-stopped
    network_mode: host
    environment:
      INGRESS_CONFIG_FILE: /etc/ingress.yaml
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml:ro{depends}"""
if "picom-livekit-ingress:" not in compose_text:
    if "services:" not in compose_text:
        print("FAIL: compose missing services:", file=sys.stderr)
        sys.exit(4)
    lines = compose_text.splitlines(True)
    out = []
    inserted = False
    in_services = False
    for line in lines:
        if line.startswith("services:"):
            in_services = True
            out.append(line)
            continue
        if in_services and not inserted and line and not line[0].isspace() and not line.startswith("#"):
            out.append(service if service.endswith("\n") else service + "\n")
            inserted = True
            in_services = False
        out.append(line)
    if in_services and not inserted:
        out.append(service if service.endswith("\n") else service + "\n")
        inserted = True
    if not inserted:
        print("FAIL: could not insert ingress service", file=sys.stderr)
        sys.exit(4)
    compose.write_text("".join(out), encoding="utf-8")
    print("INFO: added picom-livekit-ingress service to compose")
else:
    print("INFO: compose already contains picom-livekit-ingress")

subprocess.check_call(["docker", "compose", "-f", "docker-compose.yaml", "config", "--quiet"], cwd=dir_path)
subprocess.check_call(["docker", "compose", "-f", "docker-compose.yaml", "pull", "picom-livekit-ingress"], cwd=dir_path)

if need_livekit_restart:
    print("INFO: restarting picom-livekit to load ingress base URLs")
    subprocess.check_call(["docker", "compose", "-f", "docker-compose.yaml", "up", "-d", "picom-livekit"], cwd=dir_path)

subprocess.check_call(["docker", "compose", "-f", "docker-compose.yaml", "up", "-d", "picom-livekit-ingress"], cwd=dir_path)
subprocess.check_call(
    ["docker", "compose", "-f", "docker-compose.yaml", "ps", "picom-livekit", "picom-livekit-redis", "picom-livekit-ingress"],
    cwd=dir_path,
)

ss = subprocess.run(["bash", "-lc", "ss -lnt | awk '{print $4}' | grep -Eq '(:|\\.)1935$'"], check=False)
if ss.returncode == 0:
    print("OK: TCP 1935 is listening")
else:
    print("WARN: TCP 1935 not detected yet; container may still be starting", file=sys.stderr)

print(f"LiveKit Ingress deploy finished (image {image}).")
# Clear locals; do not print credentials.
api_key = api_secret = None
PY
"@

function Invoke-Native([string]$Command, [string[]]$Arguments) {
  & $Command @Arguments
  if ($LASTEXITCODE -ne 0) { throw "$Command failed with exit code $LASTEXITCODE." }
}

Write-Host "Deploying LiveKit Ingress to ${target}:${RemoteDirectory} (secrets will not be printed)."
Invoke-Native "ssh" @("-p", "$SshPort", "-o", "BatchMode=yes", $target, $remote)
Write-Host "Done. Run: node scripts/livekit-ingress-preflight.mjs"
