/** Turkish strings — part C (provider → windows). */
export default {
  "provider.connected": "Bağlı",
  "provider.epicPending": "Kurulum bekleniyor",
  "provider.googlePaused": "ÜRÜN KARARIYLA DURAKLATILDI",
  "provider.manageCenter": "Hesap Merkezi’nden yönetin.",
  "provider.notConnected": "Bağlı değil",
  "provider.steamBackend": "Steam durumu Connections arka uçundan okunur.",
  "provider.unavailable": "Kullanılamıyor",
  "settings.close": "Ayarları kapat",
  "settings.sectionUnavailable": "Ayar bölümü kullanılamıyor",
  "settings.sectionUnavailableDetail": "“{section}” paneli yüklenemedi. Ayarları kapatıp yeniden açın veya Tanılama’dan maskelenmiş rapor dışa aktarın.",
  "settings.sectionUnavailableGeneric": "Ayarları kapatıp yeniden açın. Sorun sürerse Tanılama’dan maskelenmiş rapor dışa aktarın.",
  "settings.title": "Ayarlar",
  "shell.desktopTitle": "Picom Masaüstü",
  "storage.cacheLabel": "Önbellek",
  "storage.clearCache": "Önbelleği temizle",
  "storage.clearMedia": "Medya önbelleğini temizle",
  "storage.cleared": "Önbellek temizlendi.",
  "storage.confirmClearCache": "Uygulama önbelleği temizlensin mi? Oturum ve hesap verisi korunur.",
  "storage.confirmClearMedia": "Medya önbelleği temizlensin mi? Oturumunuz korunur.",
  "storage.confirmResetLocal": "Yerel görünüm/bildirim ayarları sıfırlansın mı? Oturum korunur.",
  "storage.description": "Önbellek boyutları ana süreçte ölçülür. Oturumlar burada asla temizlenmez.",
  "storage.logsLabel": "Günlükler",
  "storage.openDownloads": "İndirmeleri aç",
  "storage.openLogs": "Günlük klasörünü aç",
  "storage.recalculate": "Yeniden hesapla",
  "storage.resetDone": "Yerel ayarlar sıfırlandı.",
  "storage.resetLocal": "Yerel ayarları sıfırla",
  "storage.summary": "Depolama özeti",
  "storage.tempLabel": "Geçici",
  "storage.totalUserData": "Toplam userData",
  "theme.dark": "Koyu tema",
  "theme.darkHint": "Ayrılmış yüzeylerle kömür renk kabuk.",
  "theme.light": "Açık tema",
  "theme.lightHint": "Temiz beyaz yüzeylerle yumuşak kabuk.",
  "theme.system": "Sistem teması",
  "theme.systemHint": "Windows, Linux veya macOS görünümünü izler.",
  "toast.accessibilitySaved": "Erişilebilirlik ayarı yerel olarak kaydedildi.",
  "toast.analyticsDisabled": "Anonim tanılama kapatıldı ve yerel kuyruk temizlendi.",
  "toast.analyticsEnabled": "Anonim tanılama yerel olarak etkinleştirildi.",
  "toast.appearanceSaved": "Görünüm tercihi kaydedildi.",
  "toast.autoActivityDisabled": "Otomatik etkinlik durumu kapatıldı.",
  "toast.autoActivityEnabled": "Otomatik etkinlik durumu açıldı. Algılanan oyunlar ve medya durum metninizde görünür.",
  "toast.closeToTrayDisabled": "Kapatınca tepsiye küçültme kapatıldı.",
  "toast.closeToTrayEnabled": "Kapatınca tepsiye küçültme açıldı.",
  "toast.closeToTrayFailed": "Kapatınca tepsiye küçültme güncellenemedi.",
  "toast.companionHomeRequested": "Companion ana ekranı istendi.",
  "toast.companionSaveFailed": "Companion ayarları kaydedilemedi.",
  "toast.companionSaved": "Companion ayarları kaydedildi.",
  "toast.crashQueueStatus": "Yerel olarak {count} maskelenmiş çökme kaydı kuyrukta.",
  "toast.crashReportingDisabled": "Tanılama raporları kapatıldı ve yerel kuyruk temizlendi.",
  "toast.crashReportingEnabled": "Tanılama raporları yerel olarak etkinleştirildi.",
  "toast.crashTestCaptured": "Maskelenmiş test hatası yerel olarak kaydedildi.",
  "toast.crashTestEnableFirst": "Test hatası yakalamadan önce tanılama raporlarını etkinleştirin.",
  "toast.dataExportDownloaded": "Veri dışa aktarımı indirildi: {fileName}.",
  "toast.deletionCanceled": "Hesap silme talebi iptal edildi.",
  "toast.diagnosticsExportCanceled": "Tanılama dışa aktarımı iptal edildi.",
  "toast.diagnosticsExported": "Tanılama {method} ile dışa aktarıldı.",
  "toast.dmPrivacyFailed": "Doğrudan mesaj gizliliği senkronize edilemedi.",
  "toast.dmPrivacyUpdated": "Doğrudan mesaj gizliliği güncellendi.",
  "toast.feedbackCopied": "Maskelenmiş geri bildirim raporu kopyalandı. Rapor gönderilmedi.",
  "toast.firstLaunchReset": "İlk açılış kurulumu sıfırlandı. Tekrar denemek için Picom’u yeniden başlatın; hesap ve yerel veri korundu.",
  "toast.friendRequestPrivacyFailed": "Arkadaşlık isteği gizliliği kaydedilemedi; önceki ayar geri yüklendi.",
  "toast.friendRequestPrivacyUpdated": "Arkadaşlık isteği gizliliği güncellendi.",
  "toast.gamingOverlayRequested": "Oyun katmanı istendi.",
  "toast.inactivityLockDisabled": "Hareketsizlik kilidi tercihi kapatıldı.",
  "toast.inactivityLockEnabled": "Hareketsizlik kilidi tercihi yerel olarak açıldı.",
  "toast.launchOnStartupDisabled": "Başlangıçta açma kapatıldı.",
  "toast.launchOnStartupEnabled": "Oturum açtığınızda Picom başlayacak.",
  "toast.launchOnStartupUnavailable": "Bu derleme veya platformda başlangıçta açma kullanılamıyor.",
  "toast.layoutReset": "Yerel düzen durumu sıfırlandı. Varsayılanlar için ilgili görünümü yeniden açın.",
  "toast.localSettingsReset": "Yerel ayarlar sıfırlandı. Tüm varsayılanlar için Picom’u yeniden başlatın.",
  "toast.noEmail": "Bu hesap için e-posta adresi yok.",
  "toast.notificationPermissionEnabled": "Masaüstü bildirim izni etkinleştirildi.",
  "toast.notificationPermissionUnavailable": "Bildirim izni kullanılamıyor.",
  "toast.notificationPrefSaved": "Bildirim tercihi kaydedildi.",
  "toast.notificationUnavailable": "Bildirim kullanılamıyor.",
  "toast.passwordMismatch": "Yeni parolalar eşleşmiyor.",
  "toast.privacySaved": "Gizlilik ve güvenlik ayarı yerel olarak kaydedildi.",
  "toast.profileDiscarded": "Kaydedilmemiş profil değişiklikleri atıldı.",
  "toast.profilePrivacyFailed": "Profil gizliliği kaydedilemedi; önceki ayar geri yüklendi.",
  "toast.profilePrivacyUpdated": "Profil gizliliği güncellendi.",
  "toast.profileSaved": "Profil değişiklikleri kaydedildi.",
  "toast.reportProblemHint": "Sorun bildirmek için Beta desteğini açın.",
  "toast.startMinimizedRequiresStartup": "Küçültülmüş başlangıç, desteklenen oturum açılışını gerektirir.",
  "toast.startMinimizedSaved": "Küçültülmüş başlangıç tercihi kaydedildi.",
  "toast.systemStatusFallback": "Harici durum sayfası açılamadı; uygulama içi durum gösteriliyor.",
  "toast.systemStatusOpened": "Sistem durumu açıldı: {domain}.",
  "toast.testNotificationSent": "Test bildirimi gönderildi.",
  "toast.traySimulated": "Tepsi ayarları eylemi simüle edildi.",
  "toast.unsafeAccountLink": "Picom güvensiz bir hesap bağlantısını engelledi.",
  "toast.userUnblockFailed": "{name} engeli kaldırılamadı.",
  "toast.userUnblocked": "{name} engeli kaldırıldı.",
  "update.aboutBuild": "Hakkında / derleme meta verisi",
  "update.autoUpdateEnabled": "Otomatik güncelleme açık",
  "update.availableSuffix": " · kullanılabilir {version}",
  "update.browserPreviewAria": "Tarayıcı güncelleme önizleme uyarısı",
  "update.browserPreviewBody": "Yerel güncelleme kurulumu paketlenmiş Picom masaüstü derlemesi gerektirir. Bu panel yine de kontrol simülasyonu ve durum kurtarmayı destekler.",
  "update.browserPreviewTitle": "Tarayıcı önizleme modu",
  "update.changelog": "Değişiklik günlüğü",
  "update.changelogHint": "Kanal notları için genel değişiklik günlüğünü açın. Uygulama içi kurulum imzalı masaüstü uç noktası gerektirir.",
  "update.changelogStrong": "Bu derlemede nelerin geldiğini inceleyin",
  "update.channel": "Kanal",
  "update.channelSummaryAria": "Güncelleme kanalı özeti",
  "update.checkFailed": "Güncelleme denetimi beklenmedik şekilde başarısız oldu. Paket kurulmadı.",
  "update.checkForUpdates": "Güncellemeleri denetle",
  "update.checking": "Güncellemeler denetleniyor…",
  "update.clearError": "Hatayı temizle",
  "update.connected": "Bağlı",
  "update.currentVersion": "Geçerli sürüm",
  "update.description": "Picom masaüstü güncellemelerini denetleyin, kanal meta verisini inceleyin ve imzalı sürüm hazır olduğunda kurun.",
  "update.desktopUpdater": "Masaüstü güncelleyici",
  "update.downloadProgress": "İndirme ilerlemesi: %{percent}",
  "update.downloadUpdate": "Güncellemeyi indir",
  "update.installedSummary": "{channel} kanalında {version} kurulu{available}.",
  "update.lastChecked": "Son denetleme {when}",
  "update.listenersFailed": "Güncelleme dinleyicileri bağlanamadı. Bu önizlemede yerel denetimler çalışır.",
  "update.manualCheckHint": "İmzalı uç nokta yapılandırılana kadar el ile denetleme",
  "update.nativeBridgeHint": "Paketlenmiş masaüstü derlemeleri güncelleyici köprüsünü sunar.",
  "update.nativeUpdater": "Yerel güncelleyici",
  "update.openChangelog": "Değişiklik günlüğünü aç",
  "update.previewOnly": "Yalnızca önizleme",
  "update.releaseNotesTitle": "Sürüm notları",
  "update.restartInstall": "Yeniden başlat ve kur",
  "update.retry": "Yeniden dene",
  "update.retryDownload": "İndirmeyi yeniden dene",
  "update.sectionTitle": "Masaüstü güncellemeleri",
  "update.statusCardAria": "Masaüstü güncelleme durumu",
  "update.statusLabel": "Güncelleme durumu",
  "update.statusLoadFailed": "Güncelleme durumu yüklenemedi. Bu panelden yeniden deneyin.",
  "voice.allowMicrophone": "Mikrofona izin ver ve cihazları yükle",
  "voice.autoGain": "Otomatik kazanç denetimi",
  "voice.autoGainHintSupported": "Desteklenen yakalama cihazlarının mikrofon kazancını normalleştirmesine izin ver.",
  "voice.cameraLabel": "Kamera",
  "voice.cameraNotRequested": "Picom Full MVP tarafından istenmedi",
  "voice.cameraPolicyAria": "Kamera ilkesi",
  "voice.cameraPolicyHint": "Ses odaları ve ekran paylaşımı kamera yakalamayı etkinleştirmez. Picom bu ayar sayfasından kamera izni istemez.",
  "voice.cameraTitle": "Kamera ve ekran paylaşımı",
  "voice.checkingDevices": "Cihazlar denetleniyor…",
  "voice.echoCancellation": "Yankı giderme",
  "voice.echoHintSupported": "Ses yakalama sırasında yerel hoparlör yankısını azalt.",
  "voice.inputLabel": "Mikrofon girişi",
  "voice.inputLevelAria": "Mikrofon giriş seviyesi",
  "voice.listening": "Yerel dinleniyor",
  "voice.microphoneTitle": "Mikrofon",
  "voice.noMicrophones": "Mikrofon yok",
  "voice.noiseHintSupported": "Tarayıcının desteklediği gürültü bastırma kısıtını kullan.",
  "voice.noiseSuppression": "Gürültü bastırma",
  "voice.notSupportedRuntime": "Bu çalışma zamanı tarafından desteklenmiyor.",
  "voice.outputRoutingNote": "Seçilen cihazlar desteklendiğinde etkin LiveKit sesine uygulanır. Radyo ve Podcast oynatması Chromium çıkış yönlendirmesiyle aynı hoparlörü kullanır; güvenli sistem varsayılanına düşer.",
  "voice.outputTitle": "Çıkış ve oynatma",
  "voice.percent": "%{value}",
  "voice.permissionAria": "Mikrofon izin durumu",
  "voice.permissionDenied": "Reddedildi",
  "voice.permissionGranted": "Verildi",
  "voice.permissionLabel": "Mikrofon izni",
  "voice.permissionNotRequested": "İstenmedi",
  "voice.permissionStartupHint": "Picom başlangıçta asla mikrofon veya kamera yakalamayı istemez. İzin yalnızca mikrofonu etkinleştirmeyi seçtiğinizde istenir.",
  "voice.playingTestTone": "Test tonu çalınıyor…",
  "voice.processingTitle": "Giriş işleme",
  "voice.radioVolume": "Radyo ve Podcast sesi: %{percent}",
  "voice.radioVolumeAria": "Varsayılan Radyo ve Podcast sesi",
  "voice.refreshDevices": "Cihazları yenile",
  "voice.screenShareAria": "Ekran paylaşımı rehberi",
  "voice.screenShareHint": "Windows ve Linux, Picom doğrulanmış masaüstü kaynak seçicisini kullanır. macOS Sistem Ayarları’nda Ekran Kaydı izni gerektirebilir. Ayarlardan ekran yakalama başlamaz.",
  "voice.screenShareLabel": "Ekran paylaşımı",
  "voice.screenShareStrong": "Etkin bir ses odasından kaynak seçin",
  "voice.sensitivity": "Giriş duyarlılığı: %{percent}",
  "voice.sensitivityAria": "Mikrofon giriş duyarlılığı",
  "voice.speakerOutput": "Hoparlör çıkışı",
  "voice.startTest": "Mikrofonu test et",
  "voice.stopTest": "Mikrofon testini durdur",
  "voice.stopped": "Durduruldu",
  "voice.systemDefaultOutput": "Sistem varsayılan çıkışı",
  "voice.testAria": "Mikrofon giriş testi",
  "voice.testPrivacyHint": "Ölçer bellekte işlenir. Picom test sesini kaydetmez, yüklemez veya saklamaz.",
  "voice.testSpeaker": "Hoparlör çıkışını test et",
  "voice.testTitle": "Mikrofon testi",
  "voice.unsupported": "Bu çalışma zamanında cihaz seçimi kullanılamıyor. Picom sistem varsayılanlarını kullanır.",
  "voice.useSystemDefaults": "Sistem varsayılanlarını kullan",
  "windows.closeToTray": "Kapatınca tepsiye küçült",
  "windows.closeToTrayHint": "Kapatma uygulamayı tepsiye gönderir; çıkmak için tepsi menüsünden Çıkış kullanın.",
  "windows.description": "Windows başlangıcı, tepsi ve pencere davranışı ana süreç üzerinden denetlenir.",
  "windows.launchHintPackaged": "Windows/macOS’ta paketlenmiş uygulama gerekir.",
  "windows.launchHintSignIn": "Oturum açtığınızda Picom’u başlatır.",
  "windows.launchOnStartup": "Windows başladığında aç",
  "windows.rememberBounds": "Pencere konumunu hatırla",
  "windows.rememberBoundsHint": "Boyut ve konum userData’da saklanır.",
  "windows.startMinimized": "Küçültülmüş başlat",
  "windows.startMinimizedHint": "Sonraki açılış görev çubuğunda küçültülmüş başlar.",
  "windows.startupUpdated": "Başlangıç ayarı güncellendi.",
};
