/** Turkish strings — part A (accessibility → email). */
export default {
  "accessibility.description": "Kontrast, hareket, metin ölçeği ve odak görünürlüğü için yerel masaüstü tercihleri.",
  "accessibility.focusRing": "Belirgin odak halkası",
  "accessibility.focusRingHint": "Klavye odak göstergelerini daha görünür yapar.",
  "accessibility.highContrast": "Yüksek kontrast modu",
  "accessibility.highContrastHint": "Picom tasarım belirteçleriyle metin, kenarlık ve odak halkalarını güçlendirir.",
  "accessibility.largerText": "Daha büyük metin",
  "accessibility.largerTextHint": "Masaüstü düzenini değiştirmeden metin ölçeğini artırır.",
  "accessibility.reducedMotion": "Azaltılmış hareket",
  "accessibility.reducedMotionHint": "Gereksiz geçişleri, animasyonları ve yumuşak kaydırmayı azaltır.",
  "accessibility.title": "Erişilebilirlik görüntü seçenekleri",
  "account.centerHelp": "Güvenlik akışları sistem tarayıcınızda https://account.picom.gg adresinde açılır. Masaüstü parola veya silme formlarını barındırmaz.",
  "account.centerTitle": "Hesap Merkezi",
  "account.connections": "Bağlı hesaplar",
  "account.delete": "Hesabı sil",
  "account.downloadData": "Verilerimi indir",
  "account.editProfile": "Profili düzenle",
  "account.emailPassword": "E-posta ve parola",
  "account.emailPending": "E-posta doğrulaması bekleniyor",
  "account.emailVerified": "Doğrulandı · {when}",
  "account.logout": "Çıkış yap",
  "account.memberSince": "Üyelik tarihi",
  "account.openCenter": "Hesap Merkezi’ni aç",
  "account.plan": "Plan",
  "account.planFree": "Ücretsiz",
  "account.providers": "Bağlı hesaplar",
  "account.refreshIdentity": "Kimliği yenile",
  "account.refreshing": "Yenileniyor…",
  "account.security": "Güvenlik / MFA",
  "account.sessions": "Aktif oturumlar",
  "account.status": "Durum",
  "account.status.online": "çevrimiçi",
  "account.summaryDescription": "Masaüstü yalnızca hesap özeti gösterir. Parola, e-posta, MFA, oturumlar ve hesap silme Hesap Merkezi’nde yönetilir.",
  "appearance.accessibilityPanelAria": "Erişilebilirlik görüntü seçenekleri",
  "appearance.dateStyle": "Tarih biçimi",
  "appearance.dateStyleHint": "Sistem, sayısal veya açıklayıcı tarih seçin.",
  "appearance.density": "Masaüstü yoğunluğu",
  "appearance.densityHint": "Dört sütunlu düzeni değiştirmeden rahat veya kompakt aralık seçin.",
  "appearance.description": "Cihaza özel görsel, dil, tarih ve erişilebilirlik tercihleri.",
  "appearance.language": "Dil",
  "appearance.languageDatePanelAria": "Dil, tarih ve masaüstü yoğunluğu",
  "appearance.languageHint": "Picom arayüz metinlerine uygulanır; kullanıcı içeriği asla çevrilmez.",
  "appearance.option.comfortable": "Rahat",
  "appearance.option.compact": "Kompakt",
  "appearance.option.descriptive": "Açıklayıcı",
  "appearance.option.hour": "saat",
  "appearance.option.langEn": "English",
  "appearance.option.langTr": "Türkçe",
  "appearance.option.numeric": "Sayısal",
  "appearance.option.system": "Sistem",
  "appearance.themePanelAria": "Tema seçimi",
  "appearance.timeFormat": "Saat biçimi",
  "appearance.timeFormatHint": "Sistem, 12 saat veya 24 saat seçin.",
  "appearance.title": "Görünüm",
  "common.cancel": "İptal",
  "common.clear": "Temizle",
  "common.copy": "Kopyala",
  "common.disabled": "Kapalı",
  "common.enabled": "Açık",
  "common.export": "Dışa aktar",
  "common.notAvailable": "Kullanılamıyor",
  "common.openAccount": "Hesabı aç",
  "common.openDiagnostics": "Tanılamayı aç",
  "common.refresh": "Yenile",
  "common.remove": "Kaldır",
  "common.reset": "Sıfırla",
  "common.rotate": "Döndür",
  "common.save": "Kaydet",
  "common.unblock": "Engeli kaldır",
  "common.unmute": "Sessizliği kaldır",
  "confirm.clearLogs": "Bu Picom oturumundaki son maskeleme günlükleri temizlensin mi? Geri alınamaz.",
  "confirm.resetFirstLaunch": "Geliştirme/destek testi için ilk açılış kurulumu sıfırlansın mı? Hesap ve yerel içerik korunur.",
  "confirm.resetLayout": "Bu cihazda Picom akış ve topluluk gezinme düzeni sıfırlansın mı? Mesajlar, taslaklar, hesaplar ve sunucu verisi korunur.",
  "confirm.resetLocalSettings": "Yerel Picom ayarları güvenli varsayılanlara dönsün mü? Oturum, mesajlar, taslaklar ve sunucu verisi silinmez.",
  "confirm.safeModeRestart": "Picom Güvenli Mod’da yeniden başlatılsın mı? Gerçek zamanlı, ses, bildirimler, tepsi, güncellemeler ve diğer isteğe bağlı hizmetler duraklatılır.",
  "diagnostics.background": "arka planda",
  "diagnostics.browserFallback": "Tarayıcı yedek modu",
  "diagnostics.copied": "Maskelenmiş tanılama kopyalandı.",
  "diagnostics.copy": "Tanılamayı kopyala",
  "diagnostics.export": "Tanılamayı dışa aktar",
  "diagnostics.exportCanceled": "Tanılama dışa aktarımı iptal edildi.",
  "diagnostics.exportedVia": "Tanılama {method} ile dışa aktarıldı.",
  "diagnostics.focused": "odakta",
  "diagnostics.metric.auth": "Kimlik doğrulama",
  "diagnostics.metric.build": "Derleme",
  "diagnostics.metric.currentView": "Geçerli görünüm",
  "diagnostics.metric.dataSource": "Veri kaynağı",
  "diagnostics.metric.electron": "Electron",
  "diagnostics.metric.environment": "Ortam",
  "diagnostics.metric.lastApiError": "Son API hatası",
  "diagnostics.metric.livekit": "LiveKit",
  "diagnostics.metric.platform": "Platform",
  "diagnostics.metric.realtime": "Gerçek zamanlı",
  "diagnostics.metric.recentErrors": "Son hatalar",
  "diagnostics.metric.supabase": "Supabase",
  "diagnostics.metric.supabaseHost": "Supabase sunucusu",
  "diagnostics.metric.version": "Sürüm",
  "diagnostics.metric.voice": "Ses",
  "diagnostics.metric.window": "Pencere",
  "diagnostics.none": "Yok",
  "diagnostics.notConfigured": "Yapılandırılmadı",
  "diagnostics.privacyNote": "Gizli anahtarlar, parolalar, belirteçler, çerezler, özel anahtarlar ve yetkilendirme başlıkları hariç tutulur.",
  "diagnostics.snapshotAria": "Tanılama anlık görüntüsü",
  "diagnostics.snapshotTitle": "Tanılama anlık görüntüsü",
  "email.loading": "E-posta tercihleri yükleniyor…",
  "email.row.community_updates.detail": "Davetler, sahiplik değişiklikleri ve önemli topluluk duyuruları.",
  "email.row.community_updates.title": "Topluluk güncellemeleri",
  "email.row.marketing_advertising.detail": "İsteğe bağlı teklifler ve kampanyalar. Varsayılan olarak kapalı.",
  "email.row.marketing_advertising.title": "Pazarlama",
  "email.row.optional_digest.detail": "Kaçırmış olabileceğiniz etkinliğin kısa özeti.",
  "email.row.optional_digest.title": "İsteğe bağlı özet",
  "email.row.product_announcements.detail": "Önemli Picom ürün haberleri.",
  "email.row.product_announcements.title": "Ürün duyuruları",
  "email.row.radio_podcast_updates.detail": "Takip ettiğiniz ses içeriği güncellemeleri.",
  "email.row.radio_podcast_updates.title": "Radyo ve podcast güncellemeleri",
  "email.row.required_account_security.detail": "Zorunlu giriş, kurtarma ve hesap koruma mesajları.",
  "email.row.required_account_security.title": "Hesap ve güvenlik",
  "email.row.support_updates.detail": "Gönderdiğiniz talepler için yanıtlar ve durum değişiklikleri.",
  "email.row.support_updates.title": "Destek güncellemeleri",
  "email.saved": "E-posta tercihleri kaydedildi.",
  "email.subtitle": "Zorunlu güvenlik postası açıkken isteğe bağlı e-postayı yönetin.",
  "email.title": "E-posta tercihleri",
};
