/** Turkish strings — part B (error → profileMedia). */
export default {
  "error.cacheClearIpc": "Önbellek temizleme IPC kullanılamıyor.",
  "error.ipcUnavailable": "Yerel ayar IPC kullanılamıyor.",
  "error.startupPackagedOnly": "Başlangıç ayarı paketlenmiş Electron gerektirir.",
  "feedback.openSupport": "Desteği aç",
  "feedback.prepareReport": "Rapor hazırla",
  "feedback.supportBody": "Yapılandırılmış maskelenmiş rapor hazırlayın veya yapılandırılmış Picom destek portalını açın.",
  "feedback.supportOpened": "Destek Merkezi tarayıcınızda açıldı.",
  "feedback.supportTitle": "Destek ve sorun bildirimi",
  "legal.acceptanceUnavailable": "Kabul durumu kullanılamıyor",
  "legal.checkingAcceptance": "Kabul kontrol ediliyor…",
  "legal.currentAccepted": "Geçerli sürüm kabul edildi",
  "legal.description": "Bu derlemeye bağlı Picom yasal taslaklarını inceleyin. Metinler kayıt veya yeniden kabul sürümüyle eşleşir; profesyonel hukuk incelemesi gerekir.",
  "legal.documentsAria": "Yasal belgeler",
  "legal.documentsTitle": "Belgeler",
  "legal.footer": "Picom {version} · {channel} kanalı · yasal {legalVersion}",
  "legal.loadFailed": "Yasal kabul durumu yüklenemedi.",
  "legal.openDocument": "{title} belgesini aç",
  "legal.packageAcceptance": "Geçerli paket sürümü {version}. Kabul, mümkün olduğunda Picom hesabınızla saklanır.",
  "legal.professionalReview": "Profesyonel inceleme gerekli",
  "legal.reacceptRequired": "Yeniden kabul gerekebilir",
  "legal.recordedAcceptance": "{when}{source} kaydedildi. Koşullar {terms} · gizlilik {privacy}.",
  "legal.refreshAcceptance": "Kabulü yenile",
  "legal.refreshingAcceptance": "Yenileniyor…",
  "legal.signInToReview": "Kayıtlı yasal kabulü görmek için oturum açın.",
  "legal.versionHelp": "Aşağıdaki koşul ve gizlilik bağlantıları kayıt veya yeniden kabul sırasındaki sürümle eşleşir. Taslaklar nihai hukuki tavsiye değildir.",
  "legal.versionSectionAria": "Yasal sürüm ve kabul",
  "legal.yourAcceptance": "Kabulünüz",
  "logs.allLevels": "Tüm seviyeler",
  "logs.allSources": "Tüm kaynaklar",
  "logs.cleared": "Günlükler temizlendi.",
  "logs.copyFiltered": "Filtreleneni kopyala",
  "logs.copySelected": "Seçileni kopyala",
  "logs.empty": "Bu filtrelerle eşleşen günlük yok.",
  "logs.exportCanceled": "Günlük dışa aktarımı iptal edildi.",
  "logs.exported": "Maskelenmiş günlükler dışa aktarıldı.",
  "logs.filterLevelAria": "Günlük seviyesine göre filtrele",
  "logs.filterSourceAria": "Günlük kaynağına göre filtrele",
  "logs.filteredCopied": "{count} maskelenmiş günlük girişi kopyalandı.",
  "logs.hint": "Maskelenmiş ayrıntı için bir satır seçin, ardından kopyalayın veya dışa aktarın.",
  "logs.level.debug": "Hata ayıklama",
  "logs.level.error": "Hata",
  "logs.level.info": "Bilgi",
  "logs.level.warn": "Uyarı",
  "logs.listAria": "Filtrelenmiş maskelenmiş günlükler",
  "logs.noContext": "Bu girişte ek maskelenmiş bağlam yok.",
  "logs.searchAria": "Maskelenmiş günlüklerde ara",
  "logs.searchPlaceholder": "Günlüklerde ara",
  "logs.sectionAria": "Maskelenmiş yerel günlükler",
  "logs.selectedCopied": "Seçilen günlük kopyalandı.",
  "logs.title": "Maskelenmiş günlükler",
  "nav.back": "Geri",
  "nav.group.account": "Hesap",
  "nav.group.media": "Medya",
  "nav.group.more": "Diğer",
  "nav.group.preferences": "Tercihler",
  "nav.group.system": "Sistem",
  "nav.hideMenu": "Menüyü gizle",
  "nav.searchEmpty": "“{query}” için ayar sonucu yok.",
  "nav.searchPlaceholder": "Ayarlarda ara…",
  "nav.section.account": "Hesap",
  "nav.section.adminOperations": "Yönetici işlemleri",
  "nav.section.advanced": "Gelişmiş",
  "nav.section.appearance": "Görünüm",
  "nav.section.companion": "Companion",
  "nav.section.diagnostics": "Tanılama",
  "nav.section.keyboardShortcuts": "Klavye kısayolları",
  "nav.section.legal": "Yasal",
  "nav.section.notifications": "Bildirimler",
  "nav.section.privacySafety": "Gizlilik ve güvenlik",
  "nav.section.profile": "Profil",
  "nav.section.storage": "Depolama",
  "nav.section.update": "Güncelleme",
  "nav.section.voiceVideo": "Ses ve video",
  "nav.section.windowsStartup": "Windows ve başlangıç",
  "nav.showMenu": "Menüyü göster",
  "notifications.accountGroup": "Hesap tercihleri",
  "notifications.deviceGroup": "Bu cihaz",
  "notifications.dnd": "Rahatsız etme",
  "notifications.enableAll": "Bildirimleri etkinleştir",
  "notifications.nativeDesktop": "Windows yerel bildirimleri",
  "notifications.permissionDenied": "Windows bildirim izni reddedildi. Açmadan önce sistem ayarlarından izin verin.",
  "notifications.pref.communityAnnouncements.description": "Erişebildiğiniz topluluklardaki resmi duyurular için bildir.",
  "notifications.pref.communityAnnouncements.label": "Topluluk duyuruları",
  "notifications.pref.directMessages.description": "Sohbet zaten görünür değilken özel mesajlar için bildir.",
  "notifications.pref.directMessages.label": "Doğrudan mesajlar",
  "notifications.pref.eventReminders.description": "Katılıyor veya ilgileniyor işaretlediğiniz etkinliklerden önce bildir.",
  "notifications.pref.eventReminders.label": "Etkinlik hatırlatıcıları",
  "notifications.pref.friendAcceptances.description": "Gönderdiğiniz arkadaşlık isteği kabul edildiğinde bildir.",
  "notifications.pref.friendAcceptances.label": "Arkadaşlık kabul bildirimleri",
  "notifications.pref.friendRequests.description": "Size arkadaşlık isteği geldiğinde bildir.",
  "notifications.pref.friendRequests.label": "Arkadaşlık istekleri",
  "notifications.pref.mentions.description": "Görünür bir topluluk kanalında sizden bahsedildiğinde bildir.",
  "notifications.pref.mentions.label": "Bahsetmeler",
  "notifications.pref.podcastReleases.description": "Takip ettiğiniz Podcast topluluklarında yeni bölümler için bildir.",
  "notifications.pref.podcastReleases.label": "Podcast yayınları",
  "notifications.pref.radioLive.description": "Takip edilen veya hatırlatılan Radyo yayını canlıya geçtiğinde bildir.",
  "notifications.pref.radioLive.label": "Radyo canlı uyarıları",
  "notifications.pref.radioReminders.description": "Kaydedilmiş Radyo program hatırlatıcıları ve değişiklikleri için bildir.",
  "notifications.pref.radioReminders.label": "Radyo hatırlatıcıları",
  "notifications.pref.reactions.description": "Mesajlarınıza tepki verildiğinde bildir.",
  "notifications.pref.reactions.label": "Tepkiler",
  "notifications.pref.replies.description": "Mesajlarınıza yanıt verildiğinde bildir.",
  "notifications.pref.replies.label": "Yanıtlar",
  "notifications.quietHours": "Sessiz saatler",
  "notifications.securityLocked": "Güvenlik uyarıları hesap güvenliği için açık kalır ve buradan kapatılamaz.",
  "notifications.sound": "Bildirim sesi",
  "presence.aria": "Durum",
  "presence.busy": "Meşgul",
  "presence.idle": "Boşta",
  "presence.offline": "Çevrimdışı",
  "presence.online": "Çevrimiçi",
  "profileMedia.actionsAria": "Profil görseli işlemleri",
  "profileMedia.addCover": "Kapak ekle",
  "profileMedia.adjustKicker": "AYARLA",
  "profileMedia.aria": "Profil görselleri",
  "profileMedia.cancelUpload": "Yüklemeyi iptal et",
  "profileMedia.changeCover": "Kapak fotoğrafını değiştir",
  "profileMedia.changeCoverShort": "Kapağı değiştir",
  "profileMedia.changePhoto": "Profil fotoğrafını değiştir",
  "profileMedia.changePhotoShort": "Fotoğrafı değiştir",
  "profileMedia.closeEditor": "Görsel düzenleyiciyi kapat",
  "profileMedia.coverPreview": "{name} kapak önizlemesi",
  "profileMedia.cropPreviewAlt": "Kırpma önizlemesi",
  "profileMedia.dropHint": "Kapak veya fotoğrafa herhangi bir görsel bırakın veya yapıştırın. Picom görseli doğrular, kırpar ve yükler.",
  "profileMedia.dropImageOnly": "Bir görsel dosyası bırakın.",
  "profileMedia.formatHint": "Her görsel biçimi · otomatik kırpılır",
  "profileMedia.horizontal": "Yatay",
  "profileMedia.kind.avatar": "Profil fotoğrafı",
  "profileMedia.kind.cover": "Kapak fotoğrafı",
  "profileMedia.removeConfirmBody": "Picom her yerde baş harflere veya varsayılan kapağa döner.",
  "profileMedia.removeConfirmTitle": "{kind} kaldırılsın mı?",
  "profileMedia.removeCover": "Kapağı kaldır",
  "profileMedia.removePhoto": "Fotoğrafı kaldır",
  "profileMedia.removed": "{kind} kaldırıldı.",
  "profileMedia.removing": "{kind} kaldırılıyor…",
  "profileMedia.stage.preparing": "Hazırlanıyor",
  "profileMedia.updated": "{kind} güncellendi.",
  "profileMedia.uploadCover": "Kapak yükle",
  "profileMedia.uploadPhoto": "Fotoğraf yükle",
  "profileMedia.uploading": "Fotoğrafınız yükleniyor…",
  "profileMedia.vertical": "Dikey",
  "profileMedia.zoom": "Yakınlaştır",
};
