export type SetupLocale = "en" | "tr";

export const firstLaunchCopy = {
  en: {
    setupLabel: "Picom first launch setup",
    desktopSetup: "Desktop setup",
    languageLabel: "Setup language",
    steps: { welcome: "Welcome", theme: "Appearance", permissions: "Permissions", voice: "Voice and sharing", complete: "Ready" },
    currentStep: "Current step",
    completedStep: "Complete",
    upcomingStep: "Upcoming",
    ready: "ready",
    welcome: { eyebrow: "Welcome to Picom", title: "Your desktop community workspace", body: "Set a comfortable theme and review how Picom uses desktop permissions. This takes less than a minute." },
    theme: { eyebrow: "Appearance", title: "Choose your starting theme", body: "The selection applies immediately and can be changed later in Settings.", light: "Light", lightHint: "Soft cool surfaces", dark: "Dark", darkHint: "Calm charcoal surfaces" },
    permissions: {
      eyebrow: "Your control",
      title: "Permissions are requested only when needed",
      body: "Setup explains permissions but never opens a system prompt. You can continue now and decide separately when each feature is used.",
      notifications: "Notifications",
      notificationsBody: "Requested later from notification settings or after a relevant in-app prompt, never at startup.",
      microphone: "Microphone",
      microphoneBody: "Requested only when you join voice and choose to use your microphone.",
      screen: "Screen sharing",
      screenBody: "The source picker and system permission appear only after you start screen sharing.",
      guideTitle: "Platform permission guide",
      guideHint: "Picom does not open these settings during setup.",
      windowsBody: "Review microphone access under Privacy & security. Screen capture source selection appears only when sharing.",
      macBody: "Microphone and Screen & System Audio Recording access are managed in the Privacy & Security area of System Settings. Restarting Picom may be required after a change.",
      linuxBody: "Desktop portals and audio permissions vary by distribution, Wayland/X11 session, and package format. Grant only the source or device you intend to use.",
    },
    voice: {
      eyebrow: "Voice and sharing",
      title: "Nothing starts without your action",
      body: "Joining a voice room, selecting a microphone, and choosing a screen or window are separate explicit actions.",
      rooms: "Voice rooms",
      roomsBody: "Join and leave from a channel. Mute and deafen remain under your control.",
      device: "Device access",
      deviceBody: "Picom waits until a voice action before requesting microphone access.",
      source: "Screen source",
      sourceBody: "Picom never captures the desktop automatically during startup or setup.",
      note: "You can review platform permission guidance from Settings at any time.",
    },
    finish: { eyebrow: "Setup complete", title: "Picom is ready", body: "Continue to sign in or create an account. Account onboarding will stay separate and guide your profile and communities." },
    actions: { back: "Back", later: "Set up later", viewGuide: "View permission guide", hideGuide: "Hide permission guide", continue: "Continue", continueToPicom: "Continue to Picom" },
  },
  tr: {
    setupLabel: "Picom ilk açılış kurulumu",
    desktopSetup: "Masaüstü kurulumu",
    languageLabel: "Kurulum dili",
    steps: { welcome: "Hoş geldiniz", theme: "Görünüm", permissions: "İzinler", voice: "Ses ve paylaşım", complete: "Hazır" },
    currentStep: "Geçerli adım",
    completedStep: "Tamamlandı",
    upcomingStep: "Sırada",
    ready: "hazır",
    welcome: { eyebrow: "Picom'a hoş geldiniz", title: "Masaüstü topluluk çalışma alanınız", body: "Rahat bir tema seçin ve Picom'un masaüstü izinlerini nasıl kullandığını inceleyin. Bu işlem bir dakikadan kısa sürer." },
    theme: { eyebrow: "Görünüm", title: "Başlangıç temanızı seçin", body: "Seçim hemen uygulanır ve daha sonra Ayarlar bölümünden değiştirilebilir.", light: "Açık", lightHint: "Yumuşak ve serin yüzeyler", dark: "Koyu", darkHint: "Sakin kömür tonları" },
    permissions: {
      eyebrow: "Kontrol sizde",
      title: "İzinler yalnızca gerektiğinde istenir",
      body: "Kurulum izinleri açıklar ancak sistem istemi açmaz. Şimdi devam edip her özelliği kullanırken ayrı karar verebilirsiniz.",
      notifications: "Bildirimler",
      notificationsBody: "Başlangıçta değil, daha sonra bildirim ayarlarından veya uygun bir uygulama içi istemden talep edilir.",
      microphone: "Mikrofon",
      microphoneBody: "Yalnızca sesli odaya katılıp mikrofonunuzu kullanmayı seçtiğinizde talep edilir.",
      screen: "Ekran paylaşımı",
      screenBody: "Kaynak seçici ve sistem izni yalnızca ekran paylaşımını başlattığınızda görünür.",
      guideTitle: "Platform izin rehberi",
      guideHint: "Picom kurulum sırasında bu ayarları açmaz.",
      windowsBody: "Mikrofon erişimini Gizlilik ve güvenlik bölümünden inceleyin. Ekran kaynağı seçimi yalnızca paylaşım sırasında görünür.",
      macBody: "Mikrofon ile Ekran ve Sistem Sesi Kaydı erişimi Sistem Ayarları içindeki Gizlilik ve Güvenlik bölümünden yönetilir. Değişiklikten sonra Picom'u yeniden başlatmak gerekebilir.",
      linuxBody: "Masaüstü portalları ve ses izinleri dağıtıma, Wayland/X11 oturumuna ve paket biçimine göre değişir. Yalnızca kullanacağınız kaynak veya aygıta izin verin.",
    },
    voice: {
      eyebrow: "Ses ve paylaşım",
      title: "Siz başlatmadan hiçbir şey çalışmaz",
      body: "Sesli odaya katılmak, mikrofon seçmek ve ekran ya da pencere seçmek birbirinden ayrı, açık işlemlerdir.",
      rooms: "Sesli odalar",
      roomsBody: "Bir kanaldan katılın ve ayrılın. Sessize alma ve sağırlaştırma kontrolü sizde kalır.",
      device: "Aygıt erişimi",
      deviceBody: "Picom, mikrofon erişimi istemeden önce bir ses işlemi yapmanızı bekler.",
      source: "Ekran kaynağı",
      sourceBody: "Picom başlangıçta veya kurulum sırasında masaüstünü otomatik olarak yakalamaz.",
      note: "Platform izin rehberini istediğiniz zaman Ayarlar bölümünden inceleyebilirsiniz.",
    },
    finish: { eyebrow: "Kurulum tamamlandı", title: "Picom hazır", body: "Oturum açmak veya hesap oluşturmak için devam edin. Hesap tanıtımı ayrı kalacak ve profiliniz ile topluluklarınız için yol gösterecektir." },
    actions: { back: "Geri", later: "Daha sonra ayarla", viewGuide: "İzin rehberini görüntüle", hideGuide: "İzin rehberini gizle", continue: "Devam", continueToPicom: "Picom'a devam et" },
  },
} as const;
