import type { Json } from "../supabase/database.types";
import type { FeedCursor,FeedItem,FeedMediaSummary,FeedMode,FeedPage,FeedQuery,FeedReactionSummary,FeedServiceResult,FeedSourceMetadata } from "../../types/feed";
import { createFeedSourceReference } from "./feedSourceClassification";
import { dataSourceService } from "../dataSourceService";
import { loggingService } from "../loggingService";
import { feedRepository,type FeedMetadataRow,type FeedProfileRow,type RankedFeedRow } from "./feedRepository";

type JsonRecord=Record<string,Json|undefined>;
const mockRead=new Set<string>();const mockSaved=new Set<string>();const mockHidden=new Set<string>();
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function record(value:Json|undefined):JsonRecord{return value&&typeof value==="object"&&!Array.isArray(value)?value as JsonRecord:{};}
function text(value:Json|undefined):string|undefined{return typeof value==="string"&&value.length?value:undefined;}
function numberValue(value:Json|undefined):number|undefined{return typeof value==="number"&&Number.isFinite(value)?value:undefined;}
function emptyState(query:FeedQuery):FeedPage["emptyState"]{return query.unreadOnly||query.savedOnly||query.sourceTypes?.length?"filtered_empty":query.mode==="friends"?"no_friend_items":"no_items";}

function sourceMetadata(row:RankedFeedRow,payload:JsonRecord):FeedSourceMetadata{
  if(row.source_type==="text_message")return {type:"text_message",contentKind:row.content_kind??"text_only"};
  if(row.source_type==="radio_session")return {type:"radio_session",status:(text(payload.status)==="live"||text(payload.status)==="ended"?text(payload.status):"scheduled") as "scheduled"|"live"|"ended",hostId:text(payload.host_id)??row.author_id,durationSeconds:numberValue(payload.duration_seconds),listenerCount:numberValue(payload.listener_count)??0,coverUrl:text(payload.cover_url)};
  if(row.source_type==="radio_comment")return {type:"radio_comment",radioSessionId:row.parent_source_id??row.source_id,hostId:text(payload.host_id)};
  if(row.source_type==="podcast_episode")return {type:"podcast_episode",authorId:text(payload.author_id)??row.author_id,durationSeconds:numberValue(payload.duration_seconds),coverUrl:text(payload.cover_url)};
  return {type:"podcast_comment",podcastEpisodeId:row.parent_source_id??row.source_id,authorId:text(payload.author_id)};
}
function media(payload:JsonRecord):readonly FeedMediaSummary[]{const values=Array.isArray(payload.attachments)?payload.attachments:[];return values.flatMap(value=>{const item=record(value);const url=text(item.url);const mime=text(item.mime_type);const id=text(item.id);if(!url||!mime||!id)return[];return[{id,type:mime.startsWith("video/")?"video":"image",url,thumbnailUrl:text(item.thumbnail_url),fileName:text(item.file_name),width:numberValue(item.width),height:numberValue(item.height)}];});}
function reactions(value:Json):readonly FeedReactionSummary[]{return(Array.isArray(value)?value:[]).flatMap(entry=>{const item=record(entry);const emoji=text(item.emoji);if(!emoji)return[];return[{emoji,count:numberValue(item.count)??0,reactedByCurrentUser:item.reacted_by_current_user===true}];});}
function toItem(row:RankedFeedRow,metadata:FeedMetadataRow|undefined,profiles:Map<string,FeedProfileRow>,verifications:Map<string,"verified_user"|"picom_staff"|"verified_bot">):FeedItem{
  const payload=record(metadata?.source_payload);const commenterIds=metadata?.commenter_ids??[];
  return {id:row.feed_item_id,source:createFeedSourceReference({type:row.source_type,id:row.source_id,parentId:row.parent_source_id??undefined,communityId:row.community_id??undefined,channelId:row.channel_id??undefined}),
    sourceMetadata:sourceMetadata(row,payload),author:{id:row.author_id,displayName:row.author_display_name,username:row.author_username,avatarUrl:row.author_avatar_url??undefined,verificationType:verifications.get(row.author_id)},
    community:row.community_id&&row.community_name?{id:row.community_id,name:row.community_name,iconUrl:row.community_icon_url??undefined}:undefined,
    title:text(payload.title),bodyPreview:text(payload.body),media:media(payload),reactions:metadata?reactions(metadata.reaction_summary):[],
    commenters:commenterIds.flatMap(id=>{const profile=profiles.get(id);return profile?[{id,displayName:profile.display_name,username:profile.username,avatarUrl:profile.avatar_url??undefined}]:[];}),commentCount:metadata?.comment_count??0,
    commentPreviews:(Array.isArray(metadata?.comment_previews)?metadata.comment_previews:[]).flatMap(value=>{const preview=record(value);const id=text(preview.id);const authorId=text(preview.author_id);const body=text(preview.body);const createdAt=text(preview.created_at);if(!id||!authorId||!body||!createdAt)return[];const profile=profiles.get(authorId);return[{id,authorId,author:profile?{id:authorId,displayName:profile.display_name,username:profile.username,avatarUrl:profile.avatar_url??undefined}:undefined,body,createdAt}];}),
    createdAt:row.source_created_at,updatedAt:row.source_updated_at,engagement:{uniqueExternalReactors:row.unique_external_reactors,uniqueExternalCommenters:row.unique_external_commenters,additionalReplyCount:row.additional_reply_count,uniqueExternalSavers:row.unique_external_savers,uniqueExternalViewers:row.unique_external_viewers,externalSupporterCount:row.external_supporter_count,listenerCount:numberValue(payload.listener_count)},
    userState:{isDirectMention:row.is_direct_mention,isUnread:row.is_unread,isSaved:row.is_saved,isFriendAuthored:row.is_friend_author,isFriendEngaged:row.is_friend_engaged,isRecentCommunity:false,isHidden:false},
    score:{version:row.score_version,base:row.base_score,raw:row.raw_score,relevance:row.relevance_score,freshness:row.freshness_decay,final:row.final_score,groupPriority:row.group_priority},sourceStatus:metadata?"ready":"access_lost"};
}
async function mockPage(query:FeedQuery):Promise<FeedPage>{const {mockFeedV1Items}=await import("../../data/mockFeedV1");let items=mockFeedV1Items.filter(item=>!mockHidden.has(item.id));if(query.mode==="friends")items=items.filter(item=>item.userState.isFriendAuthored||item.userState.isFriendEngaged);if(query.sourceTypes?.length)items=items.filter(item=>query.sourceTypes?.includes(item.source.type));if(query.unreadOnly)items=items.filter(item=>!mockRead.has(item.id)&&item.userState.isUnread);if(query.savedOnly)items=items.filter(item=>mockSaved.has(item.id)||item.userState.isSaved);const start=query.cursor?Math.max(0,items.findIndex(item=>item.id===query.cursor?.feedItemId)+1):0;const limit=Math.min(Math.max(query.limit??20,1),40);const page=items.slice(start,start+limit).map(item=>({...item,userState:{...item.userState,isUnread:!mockRead.has(item.id)&&item.userState.isUnread,isSaved:mockSaved.has(item.id)||item.userState.isSaved}}));const last=page[page.length-1];const asOf=query.cursor?.asOf??"2026-07-12T12:00:00.000Z";return {items:page,nextCursor:last&&start+page.length<items.length?{groupPriority:last.score.groupPriority,finalScore:last.score.final,createdAt:last.createdAt,feedItemId:last.id,asOf}:null,asOf,emptyState:page.length?null:emptyState(query)};}

async function productionPage(query:FeedQuery):Promise<FeedServiceResult<FeedPage>>{const limit=Math.min(Math.max(query.limit??20,1),40);let result:Awaited<ReturnType<typeof feedRepository.listPage>>|null=null;for(let attempt=0;attempt<2;attempt+=1){result=await feedRepository.listPage(query,limit+1);if(result.ok||!result.error.retryable)break;if(attempt===0)await wait(150);}if(!result||!result.ok)return result??{ok:false,error:{code:"FEED_REQUEST_FAILED",message:"Picom could not load the Feed.",retryable:true}};const hasNext=result.data.rows.length>limit;const rows=result.data.rows.slice(0,limit);const metadata=new Map(result.data.metadata.map(item=>[item.feed_item_id,item]));const profiles=new Map(result.data.profiles.map(item=>[item.id,item]));const verifications=new Map(result.data.verifications.map(item=>[item.user_id,item.verification_type]));const items=rows.map(row=>toItem(row,metadata.get(row.feed_item_id),profiles,verifications));const last=items[items.length-1];const asOf=rows[0]?.ranking_as_of??query.cursor?.asOf??new Date().toISOString();const nextCursor:FeedCursor|null=hasNext&&last?{groupPriority:last.score.groupPriority,finalScore:last.score.final,createdAt:last.createdAt,feedItemId:last.id,asOf}:null;return {ok:true,data:{items,nextCursor,asOf,emptyState:items.length?null:emptyState(query)}};}

export const feedService={
  async listPage(query:FeedQuery):Promise<FeedServiceResult<FeedPage>>{const started=performance.now();if(dataSourceService.getStatus().isMock){const data=await mockPage(query);loggingService.logInfo("Feed page loaded",{mode:query.mode,itemCount:data.items.length,durationMs:Math.round(performance.now()-started),source:"mock"},"feed");return {ok:true,data};}const result=await productionPage(query);const metadata={mode:query.mode,itemCount:result.ok?result.data.items.length:0,durationMs:Math.round(performance.now()-started),source:"supabase",code:result.ok?"OK":result.error.code};result.ok?loggingService.logInfo("Feed page loaded",metadata,"feed"):loggingService.logWarn("Feed page failed",metadata,"feed");return result;},
  initialPage(query:Omit<FeedQuery,"cursor">):Promise<FeedServiceResult<FeedPage>>{return this.listPage({...query,cursor:null});},
  nextPage(query:FeedQuery):Promise<FeedServiceResult<FeedPage>>{return this.listPage(query);},
  refresh(query:Omit<FeedQuery,"cursor">):Promise<FeedServiceResult<FeedPage>>{return this.listPage({...query,cursor:null});},
  async setUserState(feedItemId:string,action:"read"|"save"|"unsave"|"hide"|"seen"|"opened"):Promise<FeedServiceResult<boolean>>{if(dataSourceService.getStatus().isMock){if(action==="read"||action==="opened")mockRead.add(feedItemId);if(action==="save")mockSaved.add(feedItemId);if(action==="unsave")mockSaved.delete(feedItemId);if(action==="hide")mockHidden.add(feedItemId);return {ok:true,data:true};}const result=await feedRepository.setUserState(feedItemId,action);return result.ok?{ok:true,data:true}:result;},
  async openSource(item:FeedItem):Promise<FeedServiceResult<FeedItem["source"]["deepLink"]>>{const state=await this.setUserState(item.id,"opened");return state.ok?{ok:true,data:item.source.deepLink}:state;},
  async recordImpressions(sessionId:string,items:readonly FeedItem[],mode:FeedMode,asOf:string):Promise<FeedServiceResult<number>>{if(dataSourceService.getStatus().isMock)return {ok:true,data:items.length};return feedRepository.recordImpressions(sessionId,items.map(item=>item.id),mode,asOf);},
};
