alter table public.profiles add column if not exists accepted_terms_version text, add column if not exists terms_accepted_at timestamptz, add column if not exists accepted_privacy_version text, add column if not exists privacy_accepted_at timestamptz;
create table if not exists public.legal_policy_versions (policy_key text primary key check (policy_key in ('terms','privacy')), current_version text not null, effective_at timestamptz not null, requires_reaccept boolean not null default true, updated_at timestamptz not null default now());
insert into public.legal_policy_versions(policy_key,current_version,effective_at,requires_reaccept) values ('terms','beta-2026-07-10.1','2026-07-10T00:00:00Z',true),('privacy','beta-2026-07-10.1','2026-07-10T00:00:00Z',true) on conflict(policy_key) do update set current_version=excluded.current_version,effective_at=excluded.effective_at,requires_reaccept=excluded.requires_reaccept,updated_at=now();
create table if not exists public.legal_acceptance_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete restrict, terms_version text not null, privacy_version text not null, accepted_at timestamptz not null default now(), source text not null check(source in ('registration','reaccept')));
comment on table public.legal_acceptance_events is 'Append-only policy acceptance evidence. Do not store IP addresses, auth tokens, passwords, or content.';
create index if not exists idx_legal_acceptance_events_user_accepted on public.legal_acceptance_events(user_id,accepted_at desc);
alter table public.legal_policy_versions enable row level security; alter table public.legal_acceptance_events enable row level security;
grant select on public.legal_policy_versions to anon,authenticated; grant select on public.legal_acceptance_events to authenticated; revoke insert,update,delete on public.legal_policy_versions from anon,authenticated; revoke insert,update,delete on public.legal_acceptance_events from anon,authenticated;
create policy "legal_policy_versions_read" on public.legal_policy_versions for select to anon,authenticated using(true);
create policy "legal_acceptance_events_own_read" on public.legal_acceptance_events for select to authenticated using(user_id=auth.uid());

create or replace function public.protect_profile_legal_acceptance() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin if current_setting('picom.legal_acceptance_write',true)<>'allowed' and (new.accepted_terms_version is distinct from old.accepted_terms_version or new.terms_accepted_at is distinct from old.terms_accepted_at or new.accepted_privacy_version is distinct from old.accepted_privacy_version or new.privacy_accepted_at is distinct from old.privacy_accepted_at) then raise exception 'LEGAL_ACCEPTANCE_FIELDS_PROTECTED' using errcode='42501'; end if; return new; end; $$;
drop trigger if exists protect_profile_legal_acceptance_update on public.profiles; create trigger protect_profile_legal_acceptance_update before update on public.profiles for each row execute function public.protect_profile_legal_acceptance();

create or replace function public.sync_new_auth_user_legal_acceptance() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ declare terms_version text; privacy_version text; acceptance_time timestamptz:=now(); begin select current_version into terms_version from public.legal_policy_versions where policy_key='terms'; select current_version into privacy_version from public.legal_policy_versions where policy_key='privacy'; if new.raw_user_meta_data->>'accepted_terms_version'=terms_version and new.raw_user_meta_data->>'accepted_privacy_version'=privacy_version then perform set_config('picom.legal_acceptance_write','allowed',true); update public.profiles set accepted_terms_version=terms_version,terms_accepted_at=acceptance_time,accepted_privacy_version=privacy_version,privacy_accepted_at=acceptance_time,updated_at=now() where id=new.id; insert into public.legal_acceptance_events(user_id,terms_version,privacy_version,accepted_at,source) values(new.id,terms_version,privacy_version,acceptance_time,'registration'); end if; return new; end; $$;
drop trigger if exists on_auth_user_legal_acceptance on auth.users; create trigger on_auth_user_legal_acceptance after insert on auth.users for each row execute function public.sync_new_auth_user_legal_acceptance();

create or replace function public.accept_current_legal_terms() returns table(terms_version text,privacy_version text,accepted_at timestamptz) language plpgsql security definer set search_path=public,pg_temp as $$ declare current_user_id uuid:=auth.uid(); current_terms text; current_privacy text; acceptance_time timestamptz:=now(); begin if current_user_id is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if; select current_version into current_terms from public.legal_policy_versions where policy_key='terms'; select current_version into current_privacy from public.legal_policy_versions where policy_key='privacy'; if current_terms is null or current_privacy is null then raise exception 'LEGAL_VERSION_NOT_CONFIGURED'; end if; perform set_config('picom.legal_acceptance_write','allowed',true); update public.profiles set accepted_terms_version=current_terms,terms_accepted_at=acceptance_time,accepted_privacy_version=current_privacy,privacy_accepted_at=acceptance_time,updated_at=now() where id=current_user_id; insert into public.legal_acceptance_events(user_id,terms_version,privacy_version,accepted_at,source) values(current_user_id,current_terms,current_privacy,acceptance_time,'reaccept'); return query select current_terms,current_privacy,acceptance_time; end; $$;
grant execute on function public.accept_current_legal_terms() to authenticated;
