-- Task 497: multi-role member moderation, reversible restrictions, controlled reports, and audit evidence.
begin;
create or replace function public.moderation_actor_level(target_community_id uuid,target_user_id uuid) returns integer language sql stable security definer set search_path=public as $$
  select case when exists(select 1 from public.communities where id=target_community_id and owner_id=target_user_id) then 101 else coalesce(max(role.level),0) end from public.roles role where role.community_id=target_community_id and role.id in (select member.role_id from public.community_members member where member.community_id=target_community_id and member.user_id=target_user_id union select assignment.role_id from public.community_member_roles assignment join public.community_members assigned_member on assigned_member.id=assignment.member_id where assignment.community_id=target_community_id and assigned_member.user_id=target_user_id);
$$;
create or replace function public.moderate_community_member(target_community_id uuid,target_user_id uuid,moderation_action text,moderation_reason text,timeout_minutes integer default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare community_owner uuid; actor_level integer; target_level integer; timeout_until timestamptz;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; if moderation_action not in ('kick','ban','timeout','unban','untimeout') then raise exception 'VALIDATION_ERROR'; end if; if char_length(btrim(moderation_reason)) not between 3 and 500 then raise exception 'VALIDATION_ERROR'; end if;
  select owner_id into community_owner from public.communities where id=target_community_id; if community_owner is null then raise exception 'COMMUNITY_NOT_FOUND'; end if; if target_user_id=auth.uid() then raise exception 'PERMISSION_DENIED'; end if;
  actor_level:=public.moderation_actor_level(target_community_id,auth.uid()); if auth.uid()<>community_owner and not public.has_community_permission(target_community_id,'manageMembers') then raise exception 'PERMISSION_DENIED'; end if;
  if moderation_action='unban' then if actor_level<80 then raise exception 'PERMISSION_DENIED'; end if; update public.community_bans set revoked_at=now() where community_id=target_community_id and user_id=target_user_id and revoked_at is null; if not found then raise exception 'ACTIVE_BAN_NOT_FOUND'; end if;
  else target_level:=public.moderation_actor_level(target_community_id,target_user_id); if target_user_id=community_owner or target_level>=101 then raise exception 'OWNER_PROTECTED'; end if; if target_level=0 then raise exception 'MEMBER_NOT_FOUND'; end if; if actor_level<=target_level then raise exception 'ROLE_HIERARCHY_DENIED'; end if;
    if moderation_action='timeout' then if timeout_minutes is null or timeout_minutes<1 or timeout_minutes>10080 then raise exception 'VALIDATION_ERROR'; end if; timeout_until:=now()+make_interval(mins=>timeout_minutes); insert into public.community_member_timeouts(community_id,user_id,timed_out_by,reason,expires_at) values(target_community_id,target_user_id,auth.uid(),btrim(moderation_reason),timeout_until) on conflict(community_id,user_id) do update set timed_out_by=excluded.timed_out_by,reason=excluded.reason,expires_at=excluded.expires_at,created_at=now();
    elsif moderation_action='untimeout' then delete from public.community_member_timeouts where community_id=target_community_id and user_id=target_user_id; if not found then raise exception 'ACTIVE_TIMEOUT_NOT_FOUND'; end if;
    elsif moderation_action='ban' then insert into public.community_bans(community_id,user_id,banned_by,reason,revoked_at) values(target_community_id,target_user_id,auth.uid(),btrim(moderation_reason),null) on conflict(community_id,user_id) do update set banned_by=excluded.banned_by,reason=excluded.reason,revoked_at=null,created_at=now(); delete from public.community_members where community_id=target_community_id and user_id=target_user_id;
    else delete from public.community_members where community_id=target_community_id and user_id=target_user_id; end if;
  end if;
  insert into public.moderation_action_records(community_id,affected_user_id,actor_id,action_type,target_id,reason_code,appealable,appealable_until) values(target_community_id,target_user_id,auth.uid(),moderation_action,target_user_id,left(regexp_replace(lower(btrim(moderation_reason)),'[^a-z0-9_-]+','-','g'),80),moderation_action in ('kick','ban','timeout'),case when moderation_action in ('kick','ban','timeout') then now()+interval '30 days' else now() end);
  insert into public.audit_log(community_id,actor_id,action_type,target_type,target_id,reason) values(target_community_id,auth.uid(),'moderation_action','member',target_user_id,public.redact_audit_reason(moderation_action||': '||btrim(moderation_reason)));
  return jsonb_build_object('action',moderation_action,'targetUserId',target_user_id,'timeoutUntil',timeout_until);
end $$;
create or replace function public.list_community_moderation_states(target_community_id uuid) returns table(record_type text,user_id uuid,display_name text,reason text,actor_id uuid,expires_at timestamptz,created_at timestamptz) language plpgsql stable security definer set search_path=public as $$
begin if not (public.is_community_owner(target_community_id) or public.has_community_permission(target_community_id,'manageMembers')) then raise exception 'PERMISSION_DENIED'; end if; return query select 'ban',ban.user_id,coalesce(profile.display_name,profile.username,'Former member'),ban.reason,ban.banned_by,null::timestamptz,ban.created_at from public.community_bans ban join public.profiles profile on profile.id=ban.user_id where ban.community_id=target_community_id and ban.revoked_at is null union all select 'timeout',item.user_id,coalesce(profile.display_name,profile.username,'Member'),item.reason,item.timed_out_by,item.expires_at,item.created_at from public.community_member_timeouts item join public.profiles profile on profile.id=item.user_id where item.community_id=target_community_id and item.expires_at>now() order by created_at desc; end $$;
create or replace function public.list_community_report_queue(target_community_id uuid) returns setof public.reports language plpgsql stable security definer set search_path=public as $$ begin if not (public.is_community_owner(target_community_id) or public.has_community_permission(target_community_id,'moderateMessages')) then raise exception 'PERMISSION_DENIED'; end if; return query select * from public.reports where community_id=target_community_id and conversation_id is null order by created_at desc limit 100; end $$;
create or replace function public.review_community_report(target_report_id uuid,next_status text,review_reason text) returns setof public.reports language plpgsql security definer set search_path=public as $$
declare current_report public.reports%rowtype; begin select * into current_report from public.reports where id=target_report_id for update; if not found then raise exception 'REPORT_NOT_FOUND'; end if; if current_report.community_id is null or current_report.conversation_id is not null then raise exception 'PRIVATE_REPORT_SCOPE_DENIED' using errcode='42501'; end if; if not (public.is_community_owner(current_report.community_id) or public.has_community_permission(current_report.community_id,'moderateMessages')) then raise exception 'PERMISSION_DENIED' using errcode='42501'; end if; if char_length(btrim(review_reason)) not between 3 and 500 then raise exception 'REVIEW_REASON_INVALID'; end if; if not ((current_report.status='open' and next_status in ('reviewed','dismissed','action_taken')) or (current_report.status='reviewed' and next_status in ('dismissed','action_taken'))) then raise exception 'REPORT_TRANSITION_INVALID'; end if; update public.reports set status=next_status,reviewed_by=auth.uid(),reviewed_at=now(),updated_at=now() where id=target_report_id returning * into current_report; insert into public.audit_log(community_id,actor_id,action_type,target_type,target_id,reason) values(current_report.community_id,auth.uid(),'moderation_action','report',current_report.id,public.redact_audit_reason(next_status||': '||btrim(review_reason))); return next current_report; end $$;
revoke all on function public.moderation_actor_level(uuid,uuid),public.moderate_community_member(uuid,uuid,text,text,integer),public.list_community_moderation_states(uuid),public.list_community_report_queue(uuid),public.review_community_report(uuid,text,text) from public,anon;
grant execute on function public.moderate_community_member(uuid,uuid,text,text,integer),public.list_community_moderation_states(uuid),public.list_community_report_queue(uuid),public.review_community_report(uuid,text,text) to authenticated;
comment on function public.list_community_report_queue(uuid) is 'Community moderator queue excludes direct-conversation reports and unrelated private content.';
commit;
