alter table public.channels drop constraint if exists channels_type_check;
alter table public.channels add constraint channels_type_check check(type in ('text','voice','forum','announcement'));
create or replace function public.can_send_message_to_channel(target_channel_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.channels channel where channel.id=target_channel_id and public.can_view_channel(channel.id) and (channel.type='text' or (channel.type='announcement' and exists(select 1 from public.community_members member join public.roles role on role.id=member.role_id where member.community_id=channel.community_id and member.user_id=auth.uid() and (role.level>=80 or coalesce((role.permissions->>'sendAnnouncements')::boolean,false)))))); $$;
grant execute on function public.can_send_message_to_channel(uuid) to authenticated;
create table if not exists public.forum_posts (id uuid primary key default gen_random_uuid(), channel_id uuid not null references public.channels(id) on delete cascade, title text not null check(char_length(title) between 1 and 180), author_id uuid not null references public.profiles(id) on delete restrict, tags text[] not null default '{}', status text not null default 'open' check(status in ('open','resolved')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_forum_posts_channel_updated on public.forum_posts(channel_id,updated_at desc); alter table public.forum_posts enable row level security; grant select,insert,update on public.forum_posts to authenticated;
create policy "forum_posts_visible_select" on public.forum_posts for select to authenticated using(public.can_view_channel(channel_id));
create policy "forum_posts_member_insert" on public.forum_posts for insert to authenticated with check(author_id=auth.uid() and exists(select 1 from public.channels channel join public.community_members member on member.community_id=channel.community_id where channel.id=channel_id and channel.type='forum' and member.user_id=auth.uid()));
create policy "forum_posts_author_update" on public.forum_posts for update to authenticated using(author_id=auth.uid() or exists(select 1 from public.channels channel where channel.id=channel_id and public.can_moderate_community_reports(channel.community_id))) with check(author_id=auth.uid() or exists(select 1 from public.channels channel where channel.id=channel_id and public.can_moderate_community_reports(channel.community_id)));
