create table if not exists public.polls (id uuid primary key default gen_random_uuid(), message_id uuid not null unique references public.messages(id) on delete cascade, question text not null check(char_length(question) between 1 and 240), allow_multiple boolean not null default false, closes_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.poll_options (id uuid primary key default gen_random_uuid(), poll_id uuid not null references public.polls(id) on delete cascade, text text not null check(char_length(text) between 1 and 100), position integer not null check(position between 0 and 9), unique(poll_id,position));
create table if not exists public.poll_votes (id uuid primary key default gen_random_uuid(), poll_id uuid not null references public.polls(id) on delete cascade, option_id uuid not null references public.poll_options(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), unique(poll_id,option_id,user_id));
create index if not exists idx_poll_votes_poll_option on public.poll_votes(poll_id,option_id);
alter table public.polls enable row level security;
alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;
grant select,insert on public.polls to authenticated;
grant select,insert on public.poll_options to authenticated;
grant select,insert,delete on public.poll_votes to authenticated;
create or replace function public.can_view_poll(target_poll_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.polls poll join public.messages message on message.id=poll.message_id join public.channels channel on channel.id=message.channel_id join public.communities community on community.id=channel.community_id where poll.id=target_poll_id and ((community.visibility='public' and community.public_read_enabled and not channel.is_private and channel.public_read_enabled) or exists(select 1 from public.community_members member where member.community_id=community.id and member.user_id=auth.uid()))); $$;
grant execute on function public.can_view_poll(uuid) to authenticated;
create policy "polls_visible_select" on public.polls for select to authenticated using(public.can_view_poll(id));
create policy "polls_author_insert" on public.polls for insert to authenticated with check(exists(select 1 from public.messages message where message.id=message_id and message.author_id=auth.uid()));
create policy "poll_options_visible_select" on public.poll_options for select to authenticated using(public.can_view_poll(poll_id));
create policy "poll_options_author_insert" on public.poll_options for insert to authenticated with check(exists(select 1 from public.polls poll join public.messages message on message.id=poll.message_id where poll.id=poll_id and message.author_id=auth.uid()));
create policy "poll_votes_visible_select" on public.poll_votes for select to authenticated using(public.can_view_poll(poll_id));
create policy "poll_votes_self_insert" on public.poll_votes for insert to authenticated with check(user_id=auth.uid() and public.can_view_poll(poll_id) and exists(select 1 from public.poll_options option where option.id=option_id and option.poll_id=poll_id));
create policy "poll_votes_self_delete" on public.poll_votes for delete to authenticated using(user_id=auth.uid());
alter publication supabase_realtime add table public.poll_votes;
