-- App-admin-only operational metadata, cursor pagination, and append-only action audit.
create table if not exists public.admin_operations_audit (id bigint generated always as identity primary key, actor_id uuid not null references public.profiles(id) on delete restrict, action_type text not null check (char_length(action_type) between 1 and 80), target_type text not null check (char_length(target_type) between 1 and 40), target_id text check (target_id is null or char_length(target_id) <= 160), created_at timestamptz not null default now());
create index if not exists idx_admin_operations_audit_created on public.admin_operations_audit(created_at desc,id desc);
alter table public.admin_operations_audit enable row level security;
revoke all on public.admin_operations_audit from public,anon,authenticated;
comment on table public.admin_operations_audit is 'Append-only app-admin action metadata. Never store credentials, raw tokens, content, headers, IPs, or request payloads.';
create or replace function public.get_admin_system_status_v2() returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not public.is_app_admin() then raise exception 'APP_ADMIN_REQUIRED' using errcode='42501'; end if; return jsonb_build_object('database','operational','users',(select count(*) from public.profiles),'communities',(select count(*) from public.communities),'open_reports',(select count(*) from public.reports where status='open'),'abuse_events_24h',(select count(*) from public.abuse_events where created_at>=now()-interval '24 hours'),'admin_audit_events_24h',(select count(*) from public.admin_operations_audit where created_at>=now()-interval '24 hours'),'checked_at',now());end$$;
create or replace function public.list_admin_operations_v2(section_name text,page_cursor_created_at timestamptz default null,page_cursor_id text default null,page_limit integer default 25) returns jsonb language plpgsql stable security definer set search_path=public as $$declare safe_limit integer:=least(greatest(coalesce(page_limit,25),1),50);result jsonb;begin if not public.is_app_admin() then raise exception 'APP_ADMIN_REQUIRED' using errcode='42501';end if;
if section_name='users' then with candidates as(select profile.id::text id,profile.display_name label,'@'||profile.username detail,profile.status,profile.created_at from public.profiles profile where page_cursor_created_at is null or(profile.created_at,profile.id::text)<(page_cursor_created_at,coalesce(page_cursor_id,'')) order by profile.created_at desc,profile.id desc limit safe_limit+1),page as(select * from candidates limit safe_limit)select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(page)order by created_at desc,id desc)from page),'[]'::jsonb),'has_more',(select count(*)>safe_limit from candidates),'next_cursor',(select jsonb_build_object('created_at',created_at,'id',id)from page order by created_at asc,id asc limit 1))into result;
elsif section_name='communities' then with candidates as(select community.id::text id,community.name label,(select count(*)::text||' members' from public.community_members member where member.community_id=community.id)detail,community.visibility status,community.created_at from public.communities community where page_cursor_created_at is null or(community.created_at,community.id::text)<(page_cursor_created_at,coalesce(page_cursor_id,''))order by community.created_at desc,community.id desc limit safe_limit+1),page as(select * from candidates limit safe_limit)select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(page)order by created_at desc,id desc)from page),'[]'::jsonb),'has_more',(select count(*)>safe_limit from candidates),'next_cursor',(select jsonb_build_object('created_at',created_at,'id',id)from page order by created_at asc,id asc limit 1))into result;
elsif section_name='reports' then with candidates as(select report.id::text id,report.target_type||' report' label,'Content withheld from operations list'detail,report.status,report.created_at from public.reports report where page_cursor_created_at is null or(report.created_at,report.id::text)<(page_cursor_created_at,coalesce(page_cursor_id,''))order by report.created_at desc,report.id desc limit safe_limit+1),page as(select * from candidates limit safe_limit)select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(page)order by created_at desc,id desc)from page),'[]'::jsonb),'has_more',(select count(*)>safe_limit from candidates),'next_cursor',(select jsonb_build_object('created_at',created_at,'id',id)from page order by created_at asc,id asc limit 1))into result;
elsif section_name='abuse_events' then with candidates as(select event.id::text id,replace(event.event_type,'_',' ')label,event.reason_code detail,event.severity status,event.created_at from public.abuse_events event where page_cursor_created_at is null or(event.created_at,event.id)<(page_cursor_created_at,coalesce(nullif(page_cursor_id,''),'0')::bigint)order by event.created_at desc,event.id desc limit safe_limit+1),page as(select * from candidates limit safe_limit)select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(page)order by created_at desc,id desc)from page),'[]'::jsonb),'has_more',(select count(*)>safe_limit from candidates),'next_cursor',(select jsonb_build_object('created_at',created_at,'id',id)from page order by created_at asc,id asc limit 1))into result;else raise exception 'ADMIN_SECTION_INVALID' using errcode='22023';end if;return result;end$$;
create or replace function public.append_admin_operations_audit(admin_action_type text,admin_target_type text,admin_target_id text default null)returns bigint language plpgsql security definer set search_path=public as $$declare new_id bigint;begin if not public.is_app_admin() then raise exception 'APP_ADMIN_REQUIRED' using errcode='42501';end if;if char_length(trim(admin_action_type))not between 1 and 80 or char_length(trim(admin_target_type))not between 1 and 40 then raise exception 'ADMIN_AUDIT_INVALID' using errcode='22023';end if;insert into public.admin_operations_audit(actor_id,action_type,target_type,target_id)values(auth.uid(),trim(admin_action_type),trim(admin_target_type),nullif(left(trim(coalesce(admin_target_id,'')),160),''))returning id into new_id;return new_id;end$$;
revoke all on function public.get_admin_system_status_v2(),public.list_admin_operations_v2(text,timestamptz,text,integer),public.append_admin_operations_audit(text,text,text)from public,anon;
grant execute on function public.get_admin_system_status_v2(),public.list_admin_operations_v2(text,timestamptz,text,integer),public.append_admin_operations_audit(text,text,text)to authenticated;
