/**
 * Live Now UI catalog — canonical 10 locales (aligned with UiLanguage).
 * Every locale must define all keys; validated by live-now-i18n-parity.test.mjs.
 * No runtime machine translation / hardcoded fallback copy in components.
 */

import type { UiLanguage } from "./uiLanguages.ts";
import { SUPPORTED_UI_LANGUAGES, normalizeUiLanguage } from "./uiLanguages.ts";

export type LiveNowLocale = UiLanguage;

export const LIVE_NOW_LOCALE_CODES = SUPPORTED_UI_LANGUAGES;

export type LiveNowI18nKey =
  | "live.now.title"
  | "live.now.subtitle"
  | "live.now.count"
  | "live.now.searchPlaceholder"
  | "live.now.searchAria"
  | "live.now.clearSearch"
  | "live.now.filter.category"
  | "live.now.filter.language"
  | "live.now.filter.following"
  | "live.now.filter.newest"
  | "live.now.filter.viewers"
  | "live.now.filter.all"
  | "live.now.featured"
  | "live.now.followingLive"
  | "live.now.allLive"
  | "live.now.upcoming"
  | "live.now.categories"
  | "live.now.loadMore"
  | "live.now.refresh"
  | "live.now.refreshing"
  | "live.now.loading"
  | "live.now.empty.title"
  | "live.now.empty.body"
  | "live.now.empty.ctaDiscover"
  | "live.now.empty.filteredTitle"
  | "live.now.empty.filteredBody"
  | "live.now.empty.clearFilters"
  | "live.now.error.title"
  | "live.now.error.body"
  | "live.now.error.retry"
  | "live.now.forbidden.title"
  | "live.now.forbidden.body"
  | "live.now.connection.connected"
  | "live.now.connection.reconnecting"
  | "live.now.connection.disconnected"
  | "live.now.connection.stale"
  | "live.now.cta.requirements"
  | "live.now.cta.apply"
  | "live.now.cta.completeApplication"
  | "live.now.cta.underReview"
  | "live.now.cta.completeInfo"
  | "live.now.cta.dashboard"
  | "live.now.cta.goLive"
  | "live.now.cta.viewDecision"
  | "live.now.cta.suspended"
  | "live.now.cta.revoked"
  | "live.now.badge.creator"
  | "live.now.badge.publisher"
  | "live.now.card.live"
  | "live.now.card.follow"
  | "live.now.card.following"
  | "live.now.card.notify"
  | "live.now.card.notifyAllLive"
  | "live.now.card.notifyScheduledOnly"
  | "live.now.card.notifyImportantOnly"
  | "live.now.card.notifyOff"
  | "live.now.card.report"
  | "live.now.card.watch"
  | "live.now.card.ageWarning"
  | "live.now.schedule.remind"
  | "live.now.schedule.remindOn"
  | "live.now.schedule.remindOff"
  | "live.now.schedule.starts"
  | "live.now.section.secondaryUpcoming"
  | "live.now.section.secondaryCategories";

type Catalog = Record<LiveNowI18nKey, string>;

const en: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Public live streams from approved Creator and Publisher accounts.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Search stream, broadcaster, category, or tag",
  "live.now.searchAria": "Search live streams",
  "live.now.clearSearch": "Clear search",
  "live.now.filter.category": "Category",
  "live.now.filter.language": "Language",
  "live.now.filter.following": "Following",
  "live.now.filter.newest": "Just started",
  "live.now.filter.viewers": "Most watched",
  "live.now.filter.all": "All",
  "live.now.featured": "Featured Live",
  "live.now.followingLive": "Following live",
  "live.now.allLive": "All live streams",
  "live.now.upcoming": "Upcoming streams",
  "live.now.categories": "Categories",
  "live.now.loadMore": "Load more",
  "live.now.refresh": "Refresh",
  "live.now.refreshing": "Refreshing…",
  "live.now.loading": "Loading live streams…",
  "live.now.empty.title": "No live streams right now",
  "live.now.empty.body": "Streams from approved Creator and Publisher accounts will appear here when they go live.",
  "live.now.empty.ctaDiscover": "Discover publishers",
  "live.now.empty.filteredTitle": "No live streams match your filters",
  "live.now.empty.filteredBody": "Try a different search, category, or language.",
  "live.now.empty.clearFilters": "Clear filters",
  "live.now.error.title": "Could not load Live Now",
  "live.now.error.body": "Picom could not load live streams. Try again.",
  "live.now.error.retry": "Try again",
  "live.now.forbidden.title": "Access denied",
  "live.now.forbidden.body": "You do not have permission to view Live Now.",
  "live.now.connection.connected": "Connected",
  "live.now.connection.reconnecting": "Reconnecting",
  "live.now.connection.disconnected": "Disconnected",
  "live.now.connection.stale": "Stale",
  "live.now.cta.requirements": "Application requirements",
  "live.now.cta.apply": "Creator/Publisher application",
  "live.now.cta.completeApplication": "Complete application",
  "live.now.cta.underReview": "Application under review",
  "live.now.cta.completeInfo": "Complete missing information",
  "live.now.cta.dashboard": "Publisher dashboard",
  "live.now.cta.goLive": "Go live",
  "live.now.cta.viewDecision": "View application result",
  "live.now.cta.suspended": "Your publisher account is suspended. Go Live is unavailable.",
  "live.now.cta.revoked": "Your publisher badge was revoked. Go Live is unavailable.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Follow",
  "live.now.card.following": "Following",
  "live.now.card.notify": "Notifications",
  "live.now.card.notifyAllLive": "All live streams",
  "live.now.card.notifyScheduledOnly": "Scheduled only",
  "live.now.card.notifyImportantOnly": "Important only",
  "live.now.card.notifyOff": "Off",
  "live.now.card.report": "Report",
  "live.now.card.watch": "Watch",
  "live.now.card.ageWarning": "Age-restricted content",
  "live.now.schedule.remind": "Remind me",
  "live.now.schedule.remindOn": "Reminders on",
  "live.now.schedule.remindOff": "Reminders off",
  "live.now.schedule.starts": "Starts {{time}}",
  "live.now.section.secondaryUpcoming": "Upcoming",
  "live.now.section.secondaryCategories": "Popular categories",
};

const tr: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Onaylı Creator ve Publisher hesaplarının herkese açık canlı yayınları.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Yayın, yayıncı, kategori veya etiket ara",
  "live.now.searchAria": "Canlı yayınlarda ara",
  "live.now.clearSearch": "Aramayı temizle",
  "live.now.filter.category": "Kategori",
  "live.now.filter.language": "Dil",
  "live.now.filter.following": "Takip edilenler",
  "live.now.filter.newest": "Yeni başlayanlar",
  "live.now.filter.viewers": "En çok izlenenler",
  "live.now.filter.all": "Tümü",
  "live.now.featured": "Öne çıkan yayın",
  "live.now.followingLive": "Takip ettiklerin canlı",
  "live.now.allLive": "Tüm canlı yayınlar",
  "live.now.upcoming": "Yaklaşan yayınlar",
  "live.now.categories": "Kategoriler",
  "live.now.loadMore": "Daha fazla yükle",
  "live.now.refresh": "Yenile",
  "live.now.refreshing": "Yenileniyor…",
  "live.now.loading": "Canlı yayınlar yükleniyor…",
  "live.now.empty.title": "Şu anda canlı yayın yok",
  "live.now.empty.body": "Onaylı Creator ve Publisher hesaplarının yayınları başladığında burada görünecek.",
  "live.now.empty.ctaDiscover": "Yayıncıları keşfet",
  "live.now.empty.filteredTitle": "Filtrelere uygun canlı yayın yok",
  "live.now.empty.filteredBody": "Farklı bir arama, kategori veya dil deneyin.",
  "live.now.empty.clearFilters": "Filtreleri temizle",
  "live.now.error.title": "Live Now yüklenemedi",
  "live.now.error.body": "Picom canlı yayınları yükleyemedi. Tekrar deneyin.",
  "live.now.error.retry": "Tekrar dene",
  "live.now.forbidden.title": "Erişim reddedildi",
  "live.now.forbidden.body": "Live Now’u görüntüleme yetkiniz yok.",
  "live.now.connection.connected": "Bağlı",
  "live.now.connection.reconnecting": "Yeniden bağlanıyor",
  "live.now.connection.disconnected": "Bağlantı yok",
  "live.now.connection.stale": "Eski",
  "live.now.cta.requirements": "Başvuru koşulları",
  "live.now.cta.apply": "Creator/Publisher Başvurusu",
  "live.now.cta.completeApplication": "Başvuruyu tamamla",
  "live.now.cta.underReview": "Başvuru inceleniyor",
  "live.now.cta.completeInfo": "Eksik bilgileri tamamla",
  "live.now.cta.dashboard": "Yayıncı paneli",
  "live.now.cta.goLive": "Yayın başlat",
  "live.now.cta.viewDecision": "Başvuru sonucunu görüntüle",
  "live.now.cta.suspended": "Yayıncı hesabınız askıya alındı. Yayın başlatılamaz.",
  "live.now.cta.revoked": "Yayıncı rozetiniz iptal edildi. Yayın başlatılamaz.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "CANLI",
  "live.now.card.follow": "Takip et",
  "live.now.card.following": "Takip ediliyor",
  "live.now.card.notify": "Bildirimler",
  "live.now.card.notifyAllLive": "Tüm canlı yayınlar",
  "live.now.card.notifyScheduledOnly": "Yalnızca planlananlar",
  "live.now.card.notifyImportantOnly": "Yalnızca önemliler",
  "live.now.card.notifyOff": "Kapalı",
  "live.now.card.report": "Bildir",
  "live.now.card.watch": "İzle",
  "live.now.card.ageWarning": "Yaş kısıtlı içerik",
  "live.now.schedule.remind": "Hatırlat",
  "live.now.schedule.remindOn": "Hatırlatıcılar açık",
  "live.now.schedule.remindOff": "Hatırlatıcılar kapalı",
  "live.now.schedule.starts": "{{time}} başlar",
  "live.now.section.secondaryUpcoming": "Yaklaşan",
  "live.now.section.secondaryCategories": "Popüler kategoriler",
};

const de: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Öffentliche Live-Streams von genehmigten Creator- und Publisher-Konten.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Stream, Sender, Kategorie oder Tag suchen",
  "live.now.searchAria": "Live-Streams durchsuchen",
  "live.now.clearSearch": "Suche löschen",
  "live.now.filter.category": "Kategorie",
  "live.now.filter.language": "Sprache",
  "live.now.filter.following": "Abonniert",
  "live.now.filter.newest": "Gerade gestartet",
  "live.now.filter.viewers": "Meistgesehen",
  "live.now.filter.all": "Alle",
  "live.now.featured": "Empfohlener Live-Stream",
  "live.now.followingLive": "Abonnierte senden live",
  "live.now.allLive": "Alle Live-Streams",
  "live.now.upcoming": "Kommende Streams",
  "live.now.categories": "Kategorien",
  "live.now.loadMore": "Mehr laden",
  "live.now.refresh": "Aktualisieren",
  "live.now.refreshing": "Wird aktualisiert…",
  "live.now.loading": "Live-Streams werden geladen…",
  "live.now.empty.title": "Derzeit keine Live-Streams",
  "live.now.empty.body": "Streams von genehmigten Creator- und Publisher-Konten erscheinen hier, sobald sie live gehen.",
  "live.now.empty.ctaDiscover": "Publisher entdecken",
  "live.now.empty.filteredTitle": "Keine Live-Streams passen zu deinen Filtern",
  "live.now.empty.filteredBody": "Probiere eine andere Suche, Kategorie oder Sprache.",
  "live.now.empty.clearFilters": "Filter zurücksetzen",
  "live.now.error.title": "Live Now konnte nicht geladen werden",
  "live.now.error.body": "Picom konnte die Live-Streams nicht laden. Versuche es erneut.",
  "live.now.error.retry": "Erneut versuchen",
  "live.now.forbidden.title": "Zugriff verweigert",
  "live.now.forbidden.body": "Du hast keine Berechtigung, Live Now anzuzeigen.",
  "live.now.connection.connected": "Verbunden",
  "live.now.connection.reconnecting": "Verbindung wird wiederhergestellt",
  "live.now.connection.disconnected": "Getrennt",
  "live.now.connection.stale": "Veraltet",
  "live.now.cta.requirements": "Voraussetzungen für die Bewerbung",
  "live.now.cta.apply": "Creator-/Publisher-Bewerbung",
  "live.now.cta.completeApplication": "Bewerbung abschließen",
  "live.now.cta.underReview": "Bewerbung wird geprüft",
  "live.now.cta.completeInfo": "Fehlende Angaben ergänzen",
  "live.now.cta.dashboard": "Publisher-Dashboard",
  "live.now.cta.goLive": "Live gehen",
  "live.now.cta.viewDecision": "Ergebnis der Bewerbung anzeigen",
  "live.now.cta.suspended": "Dein Publisher-Konto ist gesperrt. Live gehen ist nicht verfügbar.",
  "live.now.cta.revoked": "Dein Publisher-Abzeichen wurde entzogen. Live gehen ist nicht verfügbar.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Folgen",
  "live.now.card.following": "Abonniert",
  "live.now.card.notify": "Benachrichtigungen",
  "live.now.card.notifyAllLive": "Alle Live-Streams",
  "live.now.card.notifyScheduledOnly": "Nur geplante",
  "live.now.card.notifyImportantOnly": "Nur wichtige",
  "live.now.card.notifyOff": "Aus",
  "live.now.card.report": "Melden",
  "live.now.card.watch": "Ansehen",
  "live.now.card.ageWarning": "Altersbeschränkter Inhalt",
  "live.now.schedule.remind": "Erinnern",
  "live.now.schedule.remindOn": "Erinnerungen an",
  "live.now.schedule.remindOff": "Erinnerungen aus",
  "live.now.schedule.starts": "Beginnt um {{time}}",
  "live.now.section.secondaryUpcoming": "Demnächst",
  "live.now.section.secondaryCategories": "Beliebte Kategorien",
};

const fr: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Diffusions en direct publiques des comptes Creator et Publisher approuvés.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Rechercher un stream, un diffuseur, une catégorie ou un tag",
  "live.now.searchAria": "Rechercher des streams en direct",
  "live.now.clearSearch": "Effacer la recherche",
  "live.now.filter.category": "Catégorie",
  "live.now.filter.language": "Langue",
  "live.now.filter.following": "Abonnements",
  "live.now.filter.newest": "Vient de commencer",
  "live.now.filter.viewers": "Les plus regardés",
  "live.now.filter.all": "Tout",
  "live.now.featured": "En direct à la une",
  "live.now.followingLive": "Abonnements en direct",
  "live.now.allLive": "Tous les streams en direct",
  "live.now.upcoming": "Streams à venir",
  "live.now.categories": "Catégories",
  "live.now.loadMore": "Charger plus",
  "live.now.refresh": "Actualiser",
  "live.now.refreshing": "Actualisation…",
  "live.now.loading": "Chargement des streams en direct…",
  "live.now.empty.title": "Aucun stream en direct pour le moment",
  "live.now.empty.body": "Les streams des comptes Creator et Publisher approuvés s’afficheront ici lorsqu’ils seront en direct.",
  "live.now.empty.ctaDiscover": "Découvrir les publishers",
  "live.now.empty.filteredTitle": "Aucun stream ne correspond à vos filtres",
  "live.now.empty.filteredBody": "Essayez une autre recherche, catégorie ou langue.",
  "live.now.empty.clearFilters": "Effacer les filtres",
  "live.now.error.title": "Impossible de charger Live Now",
  "live.now.error.body": "Picom n’a pas pu charger les streams en direct. Réessayez.",
  "live.now.error.retry": "Réessayer",
  "live.now.forbidden.title": "Accès refusé",
  "live.now.forbidden.body": "Vous n’avez pas l’autorisation d’afficher Live Now.",
  "live.now.connection.connected": "Connecté",
  "live.now.connection.reconnecting": "Reconnexion",
  "live.now.connection.disconnected": "Déconnecté",
  "live.now.connection.stale": "Obsolète",
  "live.now.cta.requirements": "Conditions de candidature",
  "live.now.cta.apply": "Candidature Creator/Publisher",
  "live.now.cta.completeApplication": "Finaliser la candidature",
  "live.now.cta.underReview": "Candidature en cours d’examen",
  "live.now.cta.completeInfo": "Compléter les informations manquantes",
  "live.now.cta.dashboard": "Tableau de bord Publisher",
  "live.now.cta.goLive": "Passer en direct",
  "live.now.cta.viewDecision": "Voir le résultat de la candidature",
  "live.now.cta.suspended": "Votre compte Publisher est suspendu. Passer en direct n’est pas disponible.",
  "live.now.cta.revoked": "Votre badge Publisher a été révoqué. Passer en direct n’est pas disponible.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Suivre",
  "live.now.card.following": "Abonné",
  "live.now.card.notify": "Notifications",
  "live.now.card.notifyAllLive": "Tous les streams en direct",
  "live.now.card.notifyScheduledOnly": "Planifiés uniquement",
  "live.now.card.notifyImportantOnly": "Importants uniquement",
  "live.now.card.notifyOff": "Désactivé",
  "live.now.card.report": "Signaler",
  "live.now.card.watch": "Regarder",
  "live.now.card.ageWarning": "Contenu réservé à un public averti",
  "live.now.schedule.remind": "Me rappeler",
  "live.now.schedule.remindOn": "Rappels activés",
  "live.now.schedule.remindOff": "Rappels désactivés",
  "live.now.schedule.starts": "Commence à {{time}}",
  "live.now.section.secondaryUpcoming": "À venir",
  "live.now.section.secondaryCategories": "Catégories populaires",
};

const es: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Transmisiones en directo públicas de cuentas Creator y Publisher aprobadas.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Buscar stream, emisor, categoría o etiqueta",
  "live.now.searchAria": "Buscar transmisiones en directo",
  "live.now.clearSearch": "Borrar búsqueda",
  "live.now.filter.category": "Categoría",
  "live.now.filter.language": "Idioma",
  "live.now.filter.following": "Siguiendo",
  "live.now.filter.newest": "Recién iniciadas",
  "live.now.filter.viewers": "Más vistas",
  "live.now.filter.all": "Todas",
  "live.now.featured": "Directo destacado",
  "live.now.followingLive": "Siguiendo en directo",
  "live.now.allLive": "Todas las transmisiones en directo",
  "live.now.upcoming": "Próximas transmisiones",
  "live.now.categories": "Categorías",
  "live.now.loadMore": "Cargar más",
  "live.now.refresh": "Actualizar",
  "live.now.refreshing": "Actualizando…",
  "live.now.loading": "Cargando transmisiones en directo…",
  "live.now.empty.title": "No hay transmisiones en directo ahora",
  "live.now.empty.body": "Las transmisiones de cuentas Creator y Publisher aprobadas aparecerán aquí cuando estén en directo.",
  "live.now.empty.ctaDiscover": "Descubrir publishers",
  "live.now.empty.filteredTitle": "Ninguna transmisión coincide con tus filtros",
  "live.now.empty.filteredBody": "Prueba otra búsqueda, categoría o idioma.",
  "live.now.empty.clearFilters": "Quitar filtros",
  "live.now.error.title": "No se pudo cargar Live Now",
  "live.now.error.body": "Picom no pudo cargar las transmisiones en directo. Inténtalo de nuevo.",
  "live.now.error.retry": "Reintentar",
  "live.now.forbidden.title": "Acceso denegado",
  "live.now.forbidden.body": "No tienes permiso para ver Live Now.",
  "live.now.connection.connected": "Conectado",
  "live.now.connection.reconnecting": "Reconectando",
  "live.now.connection.disconnected": "Desconectado",
  "live.now.connection.stale": "Desactualizado",
  "live.now.cta.requirements": "Requisitos de la solicitud",
  "live.now.cta.apply": "Solicitud Creator/Publisher",
  "live.now.cta.completeApplication": "Completar solicitud",
  "live.now.cta.underReview": "Solicitud en revisión",
  "live.now.cta.completeInfo": "Completar información pendiente",
  "live.now.cta.dashboard": "Panel de Publisher",
  "live.now.cta.goLive": "Transmitir en directo",
  "live.now.cta.viewDecision": "Ver resultado de la solicitud",
  "live.now.cta.suspended": "Tu cuenta Publisher está suspendida. Transmitir en directo no está disponible.",
  "live.now.cta.revoked": "Se revocó tu insignia de Publisher. Transmitir en directo no está disponible.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Seguir",
  "live.now.card.following": "Siguiendo",
  "live.now.card.notify": "Notificaciones",
  "live.now.card.notifyAllLive": "Todas las transmisiones en directo",
  "live.now.card.notifyScheduledOnly": "Solo programadas",
  "live.now.card.notifyImportantOnly": "Solo importantes",
  "live.now.card.notifyOff": "Desactivado",
  "live.now.card.report": "Denunciar",
  "live.now.card.watch": "Ver",
  "live.now.card.ageWarning": "Contenido con restricción de edad",
  "live.now.schedule.remind": "Recordarme",
  "live.now.schedule.remindOn": "Recordatorios activados",
  "live.now.schedule.remindOff": "Recordatorios desactivados",
  "live.now.schedule.starts": "Empieza a las {{time}}",
  "live.now.section.secondaryUpcoming": "Próximamente",
  "live.now.section.secondaryCategories": "Categorías populares",
};

const it: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Dirette pubbliche da account Creator e Publisher approvati.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Cerca stream, broadcaster, categoria o tag",
  "live.now.searchAria": "Cerca dirette",
  "live.now.clearSearch": "Cancella ricerca",
  "live.now.filter.category": "Categoria",
  "live.now.filter.language": "Lingua",
  "live.now.filter.following": "Seguiti",
  "live.now.filter.newest": "Appena iniziati",
  "live.now.filter.viewers": "I più visti",
  "live.now.filter.all": "Tutti",
  "live.now.featured": "In evidenza",
  "live.now.followingLive": "Seguiti in diretta",
  "live.now.allLive": "Tutte le dirette",
  "live.now.upcoming": "Prossime dirette",
  "live.now.categories": "Categorie",
  "live.now.loadMore": "Carica altri",
  "live.now.refresh": "Aggiorna",
  "live.now.refreshing": "Aggiornamento…",
  "live.now.loading": "Caricamento dirette…",
  "live.now.empty.title": "Nessuna diretta al momento",
  "live.now.empty.body": "Le dirette degli account Creator e Publisher approvati appariranno qui quando andranno live.",
  "live.now.empty.ctaDiscover": "Scopri i publisher",
  "live.now.empty.filteredTitle": "Nessuna diretta corrisponde ai filtri",
  "live.now.empty.filteredBody": "Prova un’altra ricerca, categoria o lingua.",
  "live.now.empty.clearFilters": "Cancella filtri",
  "live.now.error.title": "Impossibile caricare Live Now",
  "live.now.error.body": "Picom non ha potuto caricare le dirette. Riprova.",
  "live.now.error.retry": "Riprova",
  "live.now.forbidden.title": "Accesso negato",
  "live.now.forbidden.body": "Non hai l’autorizzazione per visualizzare Live Now.",
  "live.now.connection.connected": "Connesso",
  "live.now.connection.reconnecting": "Riconnessione",
  "live.now.connection.disconnected": "Disconnesso",
  "live.now.connection.stale": "Non aggiornato",
  "live.now.cta.requirements": "Requisiti di candidatura",
  "live.now.cta.apply": "Candidatura Creator/Publisher",
  "live.now.cta.completeApplication": "Completa candidatura",
  "live.now.cta.underReview": "Candidatura in revisione",
  "live.now.cta.completeInfo": "Completa le informazioni mancanti",
  "live.now.cta.dashboard": "Dashboard Publisher",
  "live.now.cta.goLive": "Vai in diretta",
  "live.now.cta.viewDecision": "Vedi esito candidatura",
  "live.now.cta.suspended": "Il tuo account Publisher è sospeso. Vai in diretta non è disponibile.",
  "live.now.cta.revoked": "Il tuo badge Publisher è stato revocato. Vai in diretta non è disponibile.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Segui",
  "live.now.card.following": "Segui già",
  "live.now.card.notify": "Notifiche",
  "live.now.card.notifyAllLive": "Tutte le dirette",
  "live.now.card.notifyScheduledOnly": "Solo programmate",
  "live.now.card.notifyImportantOnly": "Solo importanti",
  "live.now.card.notifyOff": "Disattivato",
  "live.now.card.report": "Segnala",
  "live.now.card.watch": "Guarda",
  "live.now.card.ageWarning": "Contenuto con limiti di età",
  "live.now.schedule.remind": "Ricordamelo",
  "live.now.schedule.remindOn": "Promemoria attivi",
  "live.now.schedule.remindOff": "Promemoria disattivi",
  "live.now.schedule.starts": "Inizia alle {{time}}",
  "live.now.section.secondaryUpcoming": "In arrivo",
  "live.now.section.secondaryCategories": "Categorie popolari",
};

const pt: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Transmissões ao vivo públicas de contas Creator e Publisher aprovadas.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Pesquisar stream, emissor, categoria ou tag",
  "live.now.searchAria": "Pesquisar transmissões ao vivo",
  "live.now.clearSearch": "Limpar pesquisa",
  "live.now.filter.category": "Categoria",
  "live.now.filter.language": "Idioma",
  "live.now.filter.following": "A seguir",
  "live.now.filter.newest": "Começaram agora",
  "live.now.filter.viewers": "Mais vistos",
  "live.now.filter.all": "Todos",
  "live.now.featured": "Em destaque",
  "live.now.followingLive": "A seguir ao vivo",
  "live.now.allLive": "Todas as transmissões ao vivo",
  "live.now.upcoming": "Próximas transmissões",
  "live.now.categories": "Categorias",
  "live.now.loadMore": "Carregar mais",
  "live.now.refresh": "Atualizar",
  "live.now.refreshing": "A atualizar…",
  "live.now.loading": "A carregar transmissões ao vivo…",
  "live.now.empty.title": "Sem transmissões ao vivo agora",
  "live.now.empty.body": "Transmissões de contas Creator e Publisher aprovadas aparecerão aqui quando estiverem ao vivo.",
  "live.now.empty.ctaDiscover": "Descobrir publishers",
  "live.now.empty.filteredTitle": "Nenhuma transmissão corresponde aos filtros",
  "live.now.empty.filteredBody": "Tente outra pesquisa, categoria ou idioma.",
  "live.now.empty.clearFilters": "Limpar filtros",
  "live.now.error.title": "Não foi possível carregar Live Now",
  "live.now.error.body": "O Picom não conseguiu carregar as transmissões ao vivo. Tente novamente.",
  "live.now.error.retry": "Tentar novamente",
  "live.now.forbidden.title": "Acesso negado",
  "live.now.forbidden.body": "Não tem permissão para ver Live Now.",
  "live.now.connection.connected": "Ligado",
  "live.now.connection.reconnecting": "A reconectar",
  "live.now.connection.disconnected": "Desligado",
  "live.now.connection.stale": "Desatualizado",
  "live.now.cta.requirements": "Requisitos de candidatura",
  "live.now.cta.apply": "Candidatura Creator/Publisher",
  "live.now.cta.completeApplication": "Concluir candidatura",
  "live.now.cta.underReview": "Candidatura em análise",
  "live.now.cta.completeInfo": "Completar informação em falta",
  "live.now.cta.dashboard": "Painel Publisher",
  "live.now.cta.goLive": "Iniciar transmissão",
  "live.now.cta.viewDecision": "Ver resultado da candidatura",
  "live.now.cta.suspended": "A sua conta Publisher está suspensa. Iniciar transmissão não está disponível.",
  "live.now.cta.revoked": "O seu distintivo Publisher foi revogado. Iniciar transmissão não está disponível.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Seguir",
  "live.now.card.following": "A seguir",
  "live.now.card.notify": "Notificações",
  "live.now.card.notifyAllLive": "Todas as transmissões ao vivo",
  "live.now.card.notifyScheduledOnly": "Apenas agendadas",
  "live.now.card.notifyImportantOnly": "Apenas importantes",
  "live.now.card.notifyOff": "Desligado",
  "live.now.card.report": "Denunciar",
  "live.now.card.watch": "Ver",
  "live.now.card.ageWarning": "Conteúdo com restrição de idade",
  "live.now.schedule.remind": "Lembrar-me",
  "live.now.schedule.remindOn": "Lembretes ativos",
  "live.now.schedule.remindOff": "Lembretes desativados",
  "live.now.schedule.starts": "Começa às {{time}}",
  "live.now.section.secondaryUpcoming": "Em breve",
  "live.now.section.secondaryCategories": "Categorias populares",
};

const ru: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "Публичные прямые эфиры одобренных аккаунтов Creator и Publisher.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "Поиск трансляции, ведущего, категории или тега",
  "live.now.searchAria": "Поиск прямых эфиров",
  "live.now.clearSearch": "Очистить поиск",
  "live.now.filter.category": "Категория",
  "live.now.filter.language": "Язык",
  "live.now.filter.following": "Подписки",
  "live.now.filter.newest": "Только начались",
  "live.now.filter.viewers": "Самые популярные",
  "live.now.filter.all": "Все",
  "live.now.featured": "Рекомендуемый эфир",
  "live.now.followingLive": "Подписки в эфире",
  "live.now.allLive": "Все прямые эфиры",
  "live.now.upcoming": "Предстоящие трансляции",
  "live.now.categories": "Категории",
  "live.now.loadMore": "Загрузить ещё",
  "live.now.refresh": "Обновить",
  "live.now.refreshing": "Обновление…",
  "live.now.loading": "Загрузка прямых эфиров…",
  "live.now.empty.title": "Сейчас нет прямых эфиров",
  "live.now.empty.body": "Эфиры одобренных аккаунтов Creator и Publisher появятся здесь, когда они выйдут в эфир.",
  "live.now.empty.ctaDiscover": "Найти издателей",
  "live.now.empty.filteredTitle": "Нет эфиров по вашим фильтрам",
  "live.now.empty.filteredBody": "Попробуйте другой запрос, категорию или язык.",
  "live.now.empty.clearFilters": "Сбросить фильтры",
  "live.now.error.title": "Не удалось загрузить Live Now",
  "live.now.error.body": "Picom не смог загрузить прямые эфиры. Попробуйте снова.",
  "live.now.error.retry": "Повторить",
  "live.now.forbidden.title": "Доступ запрещён",
  "live.now.forbidden.body": "У вас нет прав на просмотр Live Now.",
  "live.now.connection.connected": "Подключено",
  "live.now.connection.reconnecting": "Переподключение",
  "live.now.connection.disconnected": "Отключено",
  "live.now.connection.stale": "Устарело",
  "live.now.cta.requirements": "Требования к заявке",
  "live.now.cta.apply": "Заявка Creator/Publisher",
  "live.now.cta.completeApplication": "Завершить заявку",
  "live.now.cta.underReview": "Заявка на рассмотрении",
  "live.now.cta.completeInfo": "Заполнить недостающие данные",
  "live.now.cta.dashboard": "Панель Publisher",
  "live.now.cta.goLive": "Начать эфир",
  "live.now.cta.viewDecision": "Результат заявки",
  "live.now.cta.suspended": "Ваш аккаунт Publisher заблокирован. Начать эфир недоступно.",
  "live.now.cta.revoked": "Значок Publisher отозван. Начать эфир недоступно.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "Подписаться",
  "live.now.card.following": "Вы подписаны",
  "live.now.card.notify": "Уведомления",
  "live.now.card.notifyAllLive": "Все прямые эфиры",
  "live.now.card.notifyScheduledOnly": "Только по расписанию",
  "live.now.card.notifyImportantOnly": "Только важные",
  "live.now.card.notifyOff": "Выключено",
  "live.now.card.report": "Пожаловаться",
  "live.now.card.watch": "Смотреть",
  "live.now.card.ageWarning": "Контент с возрастным ограничением",
  "live.now.schedule.remind": "Напомнить",
  "live.now.schedule.remindOn": "Напоминания включены",
  "live.now.schedule.remindOff": "Напоминания выключены",
  "live.now.schedule.starts": "Начало в {{time}}",
  "live.now.section.secondaryUpcoming": "Скоро",
  "live.now.section.secondaryCategories": "Популярные категории",
};

const ar: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "بثوث مباشرة عامة من حسابات Creator وPublisher المعتمدة.",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "ابحث عن بث أو مذيع أو فئة أو وسم",
  "live.now.searchAria": "البحث في البثوث المباشرة",
  "live.now.clearSearch": "مسح البحث",
  "live.now.filter.category": "الفئة",
  "live.now.filter.language": "اللغة",
  "live.now.filter.following": "المتابَعون",
  "live.now.filter.newest": "بدأ للتو",
  "live.now.filter.viewers": "الأكثر مشاهدة",
  "live.now.filter.all": "الكل",
  "live.now.featured": "بث مميز",
  "live.now.followingLive": "المتابَعون مباشر",
  "live.now.allLive": "كل البثوث المباشرة",
  "live.now.upcoming": "بثوث قادمة",
  "live.now.categories": "الفئات",
  "live.now.loadMore": "تحميل المزيد",
  "live.now.refresh": "تحديث",
  "live.now.refreshing": "جارٍ التحديث…",
  "live.now.loading": "جارٍ تحميل البثوث المباشرة…",
  "live.now.empty.title": "لا توجد بثوث مباشرة الآن",
  "live.now.empty.body": "ستظهر بثوث حسابات Creator وPublisher المعتمدة هنا عند بدء البث.",
  "live.now.empty.ctaDiscover": "اكتشف ناشرين",
  "live.now.empty.filteredTitle": "لا توجد بثوث تطابق عوامل التصفية",
  "live.now.empty.filteredBody": "جرّب بحثًا أو فئة أو لغة مختلفة.",
  "live.now.empty.clearFilters": "مسح عوامل التصفية",
  "live.now.error.title": "تعذّر تحميل Live Now",
  "live.now.error.body": "تعذّر على Picom تحميل البثوث المباشرة. حاول مرة أخرى.",
  "live.now.error.retry": "إعادة المحاولة",
  "live.now.forbidden.title": "تم رفض الوصول",
  "live.now.forbidden.body": "ليس لديك إذن لعرض Live Now.",
  "live.now.connection.connected": "متصل",
  "live.now.connection.reconnecting": "إعادة الاتصال",
  "live.now.connection.disconnected": "غير متصل",
  "live.now.connection.stale": "قديم",
  "live.now.cta.requirements": "متطلبات التقديم",
  "live.now.cta.apply": "تقديم Creator/Publisher",
  "live.now.cta.completeApplication": "إكمال التقديم",
  "live.now.cta.underReview": "التقديم قيد المراجعة",
  "live.now.cta.completeInfo": "إكمال المعلومات الناقصة",
  "live.now.cta.dashboard": "لوحة Publisher",
  "live.now.cta.goLive": "بدء البث",
  "live.now.cta.viewDecision": "عرض نتيجة التقديم",
  "live.now.cta.suspended": "حساب Publisher موقوف. بدء البث غير متاح.",
  "live.now.cta.revoked": "تم سحب شارة Publisher. بدء البث غير متاح.",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "متابعة",
  "live.now.card.following": "تتابع",
  "live.now.card.notify": "الإشعارات",
  "live.now.card.notifyAllLive": "كل البثوث المباشرة",
  "live.now.card.notifyScheduledOnly": "المجدولة فقط",
  "live.now.card.notifyImportantOnly": "المهم فقط",
  "live.now.card.notifyOff": "إيقاف",
  "live.now.card.report": "إبلاغ",
  "live.now.card.watch": "مشاهدة",
  "live.now.card.ageWarning": "محتوى مقيد بالعمر",
  "live.now.schedule.remind": "ذكّرني",
  "live.now.schedule.remindOn": "التذكيرات مفعّلة",
  "live.now.schedule.remindOff": "التذكيرات متوقفة",
  "live.now.schedule.starts": "يبدأ {{time}}",
  "live.now.section.secondaryUpcoming": "قريبًا",
  "live.now.section.secondaryCategories": "فئات شائعة",
};

const ja: Catalog = {
  "live.now.title": "Live Now",
  "live.now.subtitle": "承認済みの Creator および Publisher アカウントによる公開ライブ配信。",
  "live.now.count": "Live Now · {{count}}",
  "live.now.searchPlaceholder": "配信、配信者、カテゴリ、タグを検索",
  "live.now.searchAria": "ライブ配信を検索",
  "live.now.clearSearch": "検索をクリア",
  "live.now.filter.category": "カテゴリ",
  "live.now.filter.language": "言語",
  "live.now.filter.following": "フォロー中",
  "live.now.filter.newest": "開始したばかり",
  "live.now.filter.viewers": "視聴数が多い",
  "live.now.filter.all": "すべて",
  "live.now.featured": "注目のライブ",
  "live.now.followingLive": "フォロー中のライブ",
  "live.now.allLive": "すべてのライブ配信",
  "live.now.upcoming": "予定の配信",
  "live.now.categories": "カテゴリ",
  "live.now.loadMore": "さらに読み込む",
  "live.now.refresh": "更新",
  "live.now.refreshing": "更新中…",
  "live.now.loading": "ライブ配信を読み込み中…",
  "live.now.empty.title": "現在ライブ配信はありません",
  "live.now.empty.body": "承認済みの Creator および Publisher アカウントが配信を開始すると、ここに表示されます。",
  "live.now.empty.ctaDiscover": "Publisher を探す",
  "live.now.empty.filteredTitle": "条件に合うライブ配信がありません",
  "live.now.empty.filteredBody": "別の検索、カテゴリ、または言語をお試しください。",
  "live.now.empty.clearFilters": "フィルターをクリア",
  "live.now.error.title": "Live Now を読み込めませんでした",
  "live.now.error.body": "Picom でライブ配信を読み込めませんでした。もう一度お試しください。",
  "live.now.error.retry": "再試行",
  "live.now.forbidden.title": "アクセスが拒否されました",
  "live.now.forbidden.body": "Live Now を表示する権限がありません。",
  "live.now.connection.connected": "接続済み",
  "live.now.connection.reconnecting": "再接続中",
  "live.now.connection.disconnected": "切断",
  "live.now.connection.stale": "古い",
  "live.now.cta.requirements": "申請要件",
  "live.now.cta.apply": "Creator/Publisher 申請",
  "live.now.cta.completeApplication": "申請を完了",
  "live.now.cta.underReview": "申請審査中",
  "live.now.cta.completeInfo": "不足情報を入力",
  "live.now.cta.dashboard": "Publisher ダッシュボード",
  "live.now.cta.goLive": "配信を開始",
  "live.now.cta.viewDecision": "申請結果を見る",
  "live.now.cta.suspended": "Publisher アカウントは停止中です。配信を開始できません。",
  "live.now.cta.revoked": "Publisher バッジが取り消されました。配信を開始できません。",
  "live.now.badge.creator": "Creator",
  "live.now.badge.publisher": "Publisher",
  "live.now.card.live": "LIVE",
  "live.now.card.follow": "フォロー",
  "live.now.card.following": "フォロー中",
  "live.now.card.notify": "通知",
  "live.now.card.notifyAllLive": "すべてのライブ配信",
  "live.now.card.notifyScheduledOnly": "予定のみ",
  "live.now.card.notifyImportantOnly": "重要のみ",
  "live.now.card.notifyOff": "オフ",
  "live.now.card.report": "報告",
  "live.now.card.watch": "視聴",
  "live.now.card.ageWarning": "年齢制限コンテンツ",
  "live.now.schedule.remind": "リマインダー",
  "live.now.schedule.remindOn": "リマインダー ON",
  "live.now.schedule.remindOff": "リマインダー OFF",
  "live.now.schedule.starts": "{{time}} 開始",
  "live.now.section.secondaryUpcoming": "近日",
  "live.now.section.secondaryCategories": "人気カテゴリ",
};

export const LIVE_NOW_LOCALES: Readonly<Record<LiveNowLocale, Catalog>> = {
  en,
  tr,
  de,
  fr,
  es,
  it,
  pt,
  ru,
  ar,
  ja,
};

export const LIVE_NOW_I18N_KEYS = Object.keys(en) as LiveNowI18nKey[];

export function translateLiveNow(
  key: LiveNowI18nKey,
  language: LiveNowLocale | string,
  vars?: Readonly<Record<string, string>>,
): string {
  const locale = normalizeUiLanguage(language);
  const template = LIVE_NOW_LOCALES[locale][key];
  if (template === undefined || template.trim().length === 0) {
    throw new Error(`Missing Live Now i18n key "${key}" for locale "${locale}"`);
  }
  if (!vars) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (_, name: string) => vars[name] ?? "");
}
