/**
 * Publisher / Creator program UI catalogs — canonical 10 UiLanguage locales.
 * Every locale is fully authored (no spread-from-English partial overrides, no
 * placeholder aliasing) and validated by assertPublisherProgramLocaleParity().
 */
import type { UiLanguage } from "./uiLanguages.ts";
import { SUPPORTED_UI_LANGUAGES, normalizeUiLanguage, getUiLanguageBcp47 } from "./uiLanguages.ts";

export type PublisherProgramI18nKey =
  | "apply.aria"
  | "apply.eyebrow"
  | "apply.ready"
  | "apply.belowThreshold"
  | "apply.title"
  | "apply.lede"
  | "apply.refresh"
  | "apply.refreshAria"
  | "apply.dashboard"
  | "apply.close"
  | "apply.loading"
  | "apply.snapshotTitle"
  | "apply.lastCheck"
  | "apply.followers"
  | "apply.largestCommunity"
  | "apply.countedCommunity"
  | "apply.noCommunity"
  | "apply.accountGate"
  | "apply.liveBan"
  | "apply.accountInactive"
  | "apply.accountOk"
  | "apply.pathsTitle"
  | "apply.pathsBody"
  | "apply.followerPath"
  | "apply.followerDetail"
  | "apply.or"
  | "apply.communityPath"
  | "apply.communityDetailNamed"
  | "apply.communityDetailDefault"
  | "apply.applicationsTitle"
  | "apply.formTitle"
  | "apply.formLede"
  | "apply.typeLabel"
  | "apply.typeCreator"
  | "apply.typePublisher"
  | "apply.displayName"
  | "apply.displayPlaceholder"
  | "apply.bio"
  | "apply.bioPlaceholder"
  | "apply.company"
  | "apply.submit"
  | "apply.submitting"
  | "apply.nextTitle"
  | "apply.growFollowersTitle"
  | "apply.growFollowersBody"
  | "apply.growCommunityTitle"
  | "apply.growCommunityBodyNamed"
  | "apply.growCommunityBodyDefault"
  | "apply.asideLabel"
  | "apply.afterKicker"
  | "apply.afterTitle"
  | "apply.afterBadge"
  | "apply.afterDiscovery"
  | "apply.afterGate"
  | "apply.afterSafety"
  | "apply.processKicker"
  | "apply.processTitle"
  | "apply.processStep1"
  | "apply.processStep2"
  | "apply.processStep3"
  | "apply.processStep4"
  | "apply.rulesKicker"
  | "apply.rulesTitle"
  | "apply.rulesFollowers"
  | "apply.rulesCommunity"
  | "apply.rulesOwner"
  | "apply.rulesNoMerge"
  | "apply.elig.notEligible"
  | "apply.elig.both"
  | "apply.elig.followers"
  | "apply.elig.community"
  | "apply.elig.ok"
  | "apply.closer.tie"
  | "apply.closer.followers"
  | "apply.closer.community"
  | "apply.track.met"
  | "apply.track.open"
  | "apply.track.remaining"
  | "apply.track.progressAria"
  | "dash.aria"
  | "dash.title"
  | "dash.gatedBody"
  | "dash.noBroadcast"
  | "dash.viewApplication"
  | "dash.eyebrow"
  | "dash.fallbackName"
  | "dash.badgeActive"
  | "dash.badgeLoading"
  | "dash.goLive"
  | "dash.close"
  | "dash.tabsAria"
  | "dash.tab.overview"
  | "dash.tab.streams"
  | "dash.tab.create"
  | "dash.tab.schedule"
  | "dash.tab.settings"
  | "dash.overviewTitle"
  | "dash.overviewBody"
  | "dash.overviewBilling"
  | "dash.scheduleTitle"
  | "dash.scheduleEmpty"
  | "dash.planTitle"
  | "dash.planName"
  | "dash.planStart"
  | "dash.planSubmit"
  | "dash.settingsTitle"
  | "dash.accountKind"
  | "dash.profileStatus"
  | "dash.applicationHistory"
  | "review.eyebrow"
  | "review.title"
  | "review.lede"
  | "review.status"
  | "review.eligibility"
  | "review.reason"
  | "review.refresh"
  | "review.filter.all"
  | "review.filter.follower"
  | "review.filter.community"
  | "review.filter.both"
  | "review.filter.below"
  | "review.filter.fraud"
  | "review.paths"
  | "review.followers"
  | "review.members"
  | "review.community"
  | "review.owner"
  | "review.notOwner"
  | "review.risk"
  | "review.riskDrop"
  | "review.approve"
  | "review.underReview"
  | "review.reject"
  | "review.suspend"
  | "review.liveBan"
  | "review.empty"
  | "review.defaultReason"
  | "review.banReason";

type Catalog = Record<PublisherProgramI18nKey, string>;

const en: Catalog = {
  "apply.aria": "Creator Publisher application",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Ready to apply",
  "apply.belowThreshold": "Below threshold",
  "apply.title": "Creator / Publisher application",
  "apply.lede":
    "Public Live Now streaming requires Creator or Publisher approval. Eligibility is calculated on the server; counters here are informational and are not the authorization source.",
  "apply.refresh": "Refresh",
  "apply.refreshAria": "Refresh eligibility",
  "apply.dashboard": "Dashboard",
  "apply.close": "Close",
  "apply.loading": "Checking eligibility…",
  "apply.snapshotTitle": "Live eligibility snapshot",
  "apply.lastCheck": "Last check · {time}",
  "apply.followers": "Active followers",
  "apply.largestCommunity": "Largest owned community",
  "apply.countedCommunity": "Counted community",
  "apply.noCommunity": "No countable community yet",
  "apply.accountGate": "Account / live gate",
  "apply.liveBan": "Active live ban — application or streaming blocked",
  "apply.accountInactive": "Account is not active",
  "apply.accountOk": "Account looks eligible",
  "apply.pathsTitle": "Application paths",
  "apply.pathsBody":
    "One path is enough. Member counts are not merged across communities; only the largest active community you own is counted.",
  "apply.followerPath": "Follower path",
  "apply.followerDetail": "Active Picom follower threshold · server count",
  "apply.or": "OR",
  "apply.communityPath": "Community founder path",
  "apply.communityDetailNamed": "{name} · active members (owner)",
  "apply.communityDetailDefault": "Largest owned community · active members (owner)",
  "apply.applicationsTitle": "Your applications",
  "apply.formTitle": "Application form",
  "apply.formLede":
    "After approval, your Live Now identity is matched to this information. Reviewers see the text you submit.",
  "apply.typeLabel": "Application type",
  "apply.typeCreator": "Creator (individual)",
  "apply.typePublisher": "Publisher (organization)",
  "apply.displayName": "Publisher display name",
  "apply.displayPlaceholder": "Visible stream name",
  "apply.bio": "Short bio",
  "apply.bioPlaceholder": "Briefly tell viewers who you are and what you stream",
  "apply.company": "Company / organization name",
  "apply.submit": "Submit application",
  "apply.submitting": "Submitting…",
  "apply.nextTitle": "How to progress",
  "apply.growFollowersTitle": "Grow the follower path",
  "apply.growFollowersBody":
    "{count} more active followers needed for the threshold. Passive or deleted accounts do not count; the server applies active profile rules.",
  "apply.growCommunityTitle": "Grow the community path",
  "apply.growCommunityBodyNamed":
    "“{name}” needs {count} more active members. Even as founder, membership and an active profile are required; communities are not merged.",
  "apply.growCommunityBodyDefault":
    "Your largest owned community needs {count} more active members. Even as founder, membership and an active profile are required; communities are not merged.",
  "apply.asideLabel": "Program summary",
  "apply.afterKicker": "After approval",
  "apply.afterTitle": "What unlocks?",
  "apply.afterBadge": "Creator / Publisher badge and publisher profile",
  "apply.afterDiscovery": "Public discovery visibility on Picom Live Now",
  "apply.afterGate": "Go Live gate (active badge + approved application)",
  "apply.afterSafety": "Continued streaming subject to review and safety rules",
  "apply.processKicker": "Process",
  "apply.processTitle": "Application flow",
  "apply.processStep1": "Complete one of the thresholds",
  "apply.processStep2": "Submit the application form",
  "apply.processStep3": "Review: eligibility risk and content policy checks",
  "apply.processStep4": "Approval → badge; rejection / more info appears here",
  "apply.rulesKicker": "Counting rules",
  "apply.rulesTitle": "What counts?",
  "apply.rulesFollowers": "Followers: {count} active followers",
  "apply.rulesCommunity": "Community: {count} active members in a community you own",
  "apply.rulesOwner": "Owner source: communities.owner_id",
  "apply.rulesNoMerge": "No member merging · progress bars are not authorization",
  "apply.elig.notEligible":
    "You do not meet application requirements yet. Complete one of the paths below to unlock the form.",
  "apply.elig.both": "You meet both application criteria. You can submit your application.",
  "apply.elig.followers": "You met the follower criterion. You can apply as Creator / Publisher.",
  "apply.elig.community": "You met the community founder criterion. You can apply as Creator / Publisher.",
  "apply.elig.ok": "Application requirements met.",
  "apply.closer.tie": "Both paths are similarly distant; grow whichever fits you.",
  "apply.closer.followers": "The follower path is numerically closer right now.",
  "apply.closer.community": "Your largest owned community path is closer right now.",
  "apply.track.met": "Met",
  "apply.track.open": "Path open",
  "apply.track.remaining": "Remaining {count}",
  "apply.track.progressAria": "{label} progress",
  "dash.aria": "Publisher Dashboard",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Only approved Creator/Publisher accounts can access this area.",
  "dash.noBroadcast": "Your account does not have broadcast permission yet.",
  "dash.viewApplication": "View application status",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Publisher panel",
  "dash.badgeActive": "Active badge: {type}",
  "dash.badgeLoading": "Loading badge status…",
  "dash.goLive": "Go Live",
  "dash.close": "Close",
  "dash.tabsAria": "Publisher sections",
  "dash.tab.overview": "overview",
  "dash.tab.streams": "streams",
  "dash.tab.create": "create",
  "dash.tab.schedule": "schedule",
  "dash.tab.settings": "settings",
  "dash.overviewTitle": "Overview",
  "dash.overviewBody":
    "Use Go Live to start a stream. Live Now lists only public_discovery streams with an approved badge.",
  "dash.overviewBilling": "Revenue / subscriptions / ads: not configured yet (no billing provider).",
  "dash.scheduleTitle": "Stream schedule",
  "dash.scheduleEmpty": "No scheduled streams.",
  "dash.planTitle": "Schedule a stream",
  "dash.planName": "Title",
  "dash.planStart": "Start",
  "dash.planSubmit": "Add to calendar",
  "dash.settingsTitle": "Account verification",
  "dash.accountKind": "Account kind: {kind}",
  "dash.profileStatus": "Profile status: {status}",
  "dash.applicationHistory": "Application history",
  "review.eyebrow": "Care & Safety",
  "review.title": "Publisher & Creator Review",
  "review.lede":
    "Meeting a threshold is not automatic approval. Snapshot and current counts are reviewed together.",
  "review.status": "Status",
  "review.eligibility": "Eligibility filter",
  "review.reason": "Decision reason",
  "review.refresh": "Refresh",
  "review.filter.all": "all",
  "review.filter.follower": "Follower criterion",
  "review.filter.community": "Community criterion",
  "review.filter.both": "Both criteria",
  "review.filter.below": "Now below threshold",
  "review.filter.fraud": "Fraud review",
  "review.paths": "Eligibility paths",
  "review.followers": "Followers (app → now)",
  "review.members": "Community members (app → now)",
  "review.community": "Qualified community",
  "review.owner": " (owner)",
  "review.notOwner": " (not owner now)",
  "review.risk": "Risk",
  "review.riskDrop": "Risk warning: unusual count drop after application.",
  "review.approve": "Approve",
  "review.underReview": "Under review",
  "review.reject": "Reject",
  "review.suspend": "Suspend",
  "review.liveBan": "Live ban",
  "review.empty": "Queue empty.",
  "review.defaultReason": "Reviewed by Root Panel",
  "review.banReason": "Live ban from review panel",
};

const tr: Catalog = {
  "apply.aria": "Creator Publisher başvurusu",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Başvuruya hazır",
  "apply.belowThreshold": "Eşik altı",
  "apply.title": "Creator / Publisher başvurusu",
  "apply.lede":
    "Picom Live Now’da kamuya açık yayın yapmak için Creator veya Publisher onayı gerekir. Uygunluk sunucu tarafında hesaplanır; bu ekrandaki sayaçlar bilgilendirme içindir, yetki kaynağı değildir.",
  "apply.refresh": "Yenile",
  "apply.refreshAria": "Uygunluğu yenile",
  "apply.dashboard": "Dashboard",
  "apply.close": "Kapat",
  "apply.loading": "Uygunluk kontrol ediliyor…",
  "apply.snapshotTitle": "Canlı uygunluk özeti",
  "apply.lastCheck": "Son kontrol · {time}",
  "apply.followers": "Aktif takipçi",
  "apply.largestCommunity": "En büyük sahip olunan topluluk",
  "apply.countedCommunity": "Sayılan topluluk",
  "apply.noCommunity": "Henüz sayılacak bir topluluk yok",
  "apply.accountGate": "Hesap / yayın engeli",
  "apply.liveBan": "Aktif live ban — başvuru veya yayın engellenir",
  "apply.accountInactive": "Hesap aktif değil",
  "apply.accountOk": "Hesap uygun görünüyor",
  "apply.pathsTitle": "Başvuru yolları",
  "apply.pathsBody":
    "Tek yol yeterli. Üye sayıları farklı topluluklar arasında birleştirilmez; yalnızca owner olduğunuz en büyük aktif topluluk sayılır.",
  "apply.followerPath": "Takipçi yolu",
  "apply.followerDetail": "Aktif Picom takipçi eşiği · sunucu sayımı",
  "apply.or": "VEYA",
  "apply.communityPath": "Topluluk kurucusu yolu",
  "apply.communityDetailNamed": "{name} · aktif üye (owner)",
  "apply.communityDetailDefault": "En büyük sahip olunan topluluk · aktif üye (owner)",
  "apply.applicationsTitle": "Başvurularınız",
  "apply.formTitle": "Başvuru formu",
  "apply.formLede":
    "Onay sonrası Live Now yayın kimliğiniz bu bilgilerle eşlenir. İnceleme ekibi gönderdiğiniz metni görür.",
  "apply.typeLabel": "Başvuru türü",
  "apply.typeCreator": "Creator (bireysel)",
  "apply.typePublisher": "Publisher (kurumsal)",
  "apply.displayName": "Yayıncı adı",
  "apply.displayPlaceholder": "Görünen yayın adı",
  "apply.bio": "Kısa tanıtım",
  "apply.bioPlaceholder": "İzleyicilere kim olduğunuzu ve ne yayınladığınızı kısaca anlatın",
  "apply.company": "Şirket / kurum adı",
  "apply.submit": "Başvuruyu gönder",
  "apply.submitting": "Gönderiliyor…",
  "apply.nextTitle": "Nasıl ilerlersiniz",
  "apply.growFollowersTitle": "Takipçi yolunu büyütmek",
  "apply.growFollowersBody":
    "Aktif takipçi eşiğine {count} kişi kaldı. Pasif veya silinmiş hesaplar sayılmaz; sunucu aktif profil kurallarını uygular.",
  "apply.growCommunityTitle": "Topluluk yolunu büyütmek",
  "apply.growCommunityBodyNamed":
    "“{name}” için {count} aktif üye daha gerekir. Kurucu olsanız bile üyelik satırı ve aktif profil şarttır; topluluklar arası birleştirme yoktur.",
  "apply.growCommunityBodyDefault":
    "Sahip olduğunuz en büyük topluluk için {count} aktif üye daha gerekir. Kurucu olsanız bile üyelik satırı ve aktif profil şarttır; topluluklar arası birleştirme yoktur.",
  "apply.asideLabel": "Program özeti",
  "apply.afterKicker": "Onay sonrası",
  "apply.afterTitle": "Ne açılır?",
  "apply.afterBadge": "Creator / Publisher rozeti ve yayıncı profili",
  "apply.afterDiscovery": "Picom Live Now’da kamuya açık keşif görünürlüğü",
  "apply.afterGate": "Yayın başlatma kapısı (aktif rozet + onaylı başvuru)",
  "apply.afterSafety": "İnceleme ve güvenlik kurallarına bağlı yayın sürdürme",
  "apply.processKicker": "Süreç",
  "apply.processTitle": "Başvuru akışı",
  "apply.processStep1": "Eşiklerden birini tamamlayın",
  "apply.processStep2": "Başvuru formunu gönderin",
  "apply.processStep3": "İnceleme: uygunluk riski ve içerik politikası kontrolü",
  "apply.processStep4": "Onay → rozet; red / ek bilgi istenirse burada görünür",
  "apply.rulesKicker": "Sayım kuralları",
  "apply.rulesTitle": "Ne sayılır?",
  "apply.rulesFollowers": "Takipçi: {count} aktif takipçi",
  "apply.rulesCommunity": "Topluluk: sahip olduğunuz bir toplulukta {count} aktif üye",
  "apply.rulesOwner": "Owner kaynağı: communities.owner_id",
  "apply.rulesNoMerge": "Üye birleştirme yok · progress bar yetki değildir",
  "apply.elig.notEligible":
    "Henüz başvuru koşullarını karşılamıyorsunuz. Aşağıdaki yollardan birini tamamladığınızda form açılır.",
  "apply.elig.both": "Her iki başvuru kriterini de karşılıyorsunuz. Başvurunuzu gönderebilirsiniz.",
  "apply.elig.followers": "Takipçi kriterini karşıladınız. Creator / Publisher başvurusu yapabilirsiniz.",
  "apply.elig.community":
    "Topluluk kurucusu kriterini karşıladınız. Creator / Publisher başvurusu yapabilirsiniz.",
  "apply.elig.ok": "Başvuru koşulları karşılandı.",
  "apply.closer.tie": "İki yol da benzer uzaklıkta; hangisi size uygunsa onu büyütün.",
  "apply.closer.followers": "Şu an takipçi yolu sayısal olarak daha yakın.",
  "apply.closer.community": "Şu an sahip olduğunuz en büyük topluluk yolu daha yakın.",
  "apply.track.met": "Karşılandı",
  "apply.track.open": "Bu yol açık",
  "apply.track.remaining": "Kalan {count}",
  "apply.track.progressAria": "{label} ilerlemesi",
  "dash.aria": "Yayıncı Paneli",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Bu alana yalnızca onaylı Creator/Publisher hesapları erişebilir.",
  "dash.noBroadcast": "Hesabınız henüz yayın yetkisine sahip değil.",
  "dash.viewApplication": "Başvuru durumunu gör",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Yayıncı paneli",
  "dash.badgeActive": "Aktif rozet: {type}",
  "dash.badgeLoading": "Rozet durumu yükleniyor…",
  "dash.goLive": "Yayını başlat",
  "dash.close": "Kapat",
  "dash.tabsAria": "Yayıncı bölümleri",
  "dash.tab.overview": "genel bakış",
  "dash.tab.streams": "yayınlar",
  "dash.tab.create": "oluştur",
  "dash.tab.schedule": "takvim",
  "dash.tab.settings": "ayarlar",
  "dash.overviewTitle": "Genel bakış",
  "dash.overviewBody":
    "Canlı yayın başlatmak için Go Live kullanın. Live Now yalnızca public_discovery + onaylı rozetli yayınları listeler.",
  "dash.overviewBilling": "Gelir / abonelik / reklam: henüz yapılandırılmadı (billing provider yok).",
  "dash.scheduleTitle": "Yayın takvimi",
  "dash.scheduleEmpty": "Planlanmış yayın yok.",
  "dash.planTitle": "Yayın planla",
  "dash.planName": "Başlık",
  "dash.planStart": "Başlangıç",
  "dash.planSubmit": "Takvime ekle",
  "dash.settingsTitle": "Hesap doğrulama",
  "dash.accountKind": "Hesap türü: {kind}",
  "dash.profileStatus": "Profil durumu: {status}",
  "dash.applicationHistory": "Başvuru geçmişi",
  "review.eyebrow": "Care & Safety",
  "review.title": "Publisher & Creator İncelemesi",
  "review.lede":
    "Eşik karşılamak otomatik onay değildir. Snapshot ve güncel sayılar birlikte incelenir.",
  "review.status": "Durum",
  "review.eligibility": "Uygunluk filtresi",
  "review.reason": "Karar gerekçesi",
  "review.refresh": "Yenile",
  "review.filter.all": "tümü",
  "review.filter.follower": "Takipçi kriteriyle",
  "review.filter.community": "Topluluk kriteriyle",
  "review.filter.both": "Her iki kriter",
  "review.filter.below": "Artık eşiğin altında",
  "review.filter.fraud": "Fraud incelemesi",
  "review.paths": "Uygunluk yolları",
  "review.followers": "Takipçi (başvuru → şimdi)",
  "review.members": "Topluluk üyesi (başvuru → şimdi)",
  "review.community": "Uygun topluluk",
  "review.owner": " (owner)",
  "review.notOwner": " (artık owner değil)",
  "review.risk": "Risk",
  "review.riskDrop": "Risk uyarısı: başvuru sonrası olağan dışı sayı düşüşü.",
  "review.approve": "Onayla",
  "review.underReview": "İnceleniyor",
  "review.reject": "Reddet",
  "review.suspend": "Askıya al",
  "review.liveBan": "Live ban",
  "review.empty": "Kuyruk boş.",
  "review.defaultReason": "Root Panel tarafından incelendi",
  "review.banReason": "İnceleme panelinden live ban",
};

const de: Catalog = {
  "apply.aria": "Creator-Publisher-Bewerbung",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Bereit zur Bewerbung",
  "apply.belowThreshold": "Unter dem Schwellenwert",
  "apply.title": "Creator- / Publisher-Bewerbung",
  "apply.lede":
    "Öffentliches Live-Now-Streaming erfordert eine Creator- oder Publisher-Freigabe. Die Berechtigung wird serverseitig berechnet; die hier angezeigten Zähler dienen nur zur Information und sind nicht die Autorisierungsquelle.",
  "apply.refresh": "Aktualisieren",
  "apply.refreshAria": "Berechtigung aktualisieren",
  "apply.dashboard": "Dashboard",
  "apply.close": "Schließen",
  "apply.loading": "Berechtigung wird geprüft…",
  "apply.snapshotTitle": "Übersicht der Live-Berechtigung",
  "apply.lastCheck": "Letzte Prüfung · {time}",
  "apply.followers": "Aktive Follower",
  "apply.largestCommunity": "Größte eigene Community",
  "apply.countedCommunity": "Gezählte Community",
  "apply.noCommunity": "Noch keine zählbare Community",
  "apply.accountGate": "Konto-/Live-Sperre",
  "apply.liveBan": "Aktives Live-Verbot — Bewerbung oder Streaming blockiert",
  "apply.accountInactive": "Konto ist nicht aktiv",
  "apply.accountOk": "Konto scheint berechtigt zu sein",
  "apply.pathsTitle": "Bewerbungswege",
  "apply.pathsBody":
    "Ein Weg genügt. Mitgliederzahlen werden nicht communityübergreifend zusammengeführt; gezählt wird nur die größte aktive Community, die dir gehört.",
  "apply.followerPath": "Follower-Weg",
  "apply.followerDetail": "Schwelle aktiver Picom-Follower · Serverzählung",
  "apply.or": "ODER",
  "apply.communityPath": "Community-Gründer-Weg",
  "apply.communityDetailNamed": "{name} · aktive Mitglieder (Inhaber)",
  "apply.communityDetailDefault": "Größte eigene Community · aktive Mitglieder (Inhaber)",
  "apply.applicationsTitle": "Deine Bewerbungen",
  "apply.formTitle": "Bewerbungsformular",
  "apply.formLede":
    "Nach der Freigabe wird deine Live-Now-Identität mit diesen Angaben verknüpft. Das Prüfteam sieht den eingereichten Text.",
  "apply.typeLabel": "Bewerbungsart",
  "apply.typeCreator": "Creator (Einzelperson)",
  "apply.typePublisher": "Publisher (Organisation)",
  "apply.displayName": "Anzeigename als Publisher",
  "apply.displayPlaceholder": "Sichtbarer Stream-Name",
  "apply.bio": "Kurzbeschreibung",
  "apply.bioPlaceholder": "Erzähle Zuschauern kurz, wer du bist und was du streamst",
  "apply.company": "Firmen-/Organisationsname",
  "apply.submit": "Bewerbung einreichen",
  "apply.submitting": "Wird gesendet…",
  "apply.nextTitle": "So geht es weiter",
  "apply.growFollowersTitle": "Follower-Weg ausbauen",
  "apply.growFollowersBody":
    "{count} weitere aktive Follower werden für den Schwellenwert benötigt. Inaktive oder gelöschte Konten zählen nicht; der Server wendet die Regeln für aktive Profile an.",
  "apply.growCommunityTitle": "Community-Weg ausbauen",
  "apply.growCommunityBodyNamed":
    "„{name}“ benötigt {count} weitere aktive Mitglieder. Auch als Gründer sind Mitgliedschaft und ein aktives Profil erforderlich; Communitys werden nicht zusammengeführt.",
  "apply.growCommunityBodyDefault":
    "Deine größte eigene Community benötigt {count} weitere aktive Mitglieder. Auch als Gründer sind Mitgliedschaft und ein aktives Profil erforderlich; Communitys werden nicht zusammengeführt.",
  "apply.asideLabel": "Programmübersicht",
  "apply.afterKicker": "Nach der Freigabe",
  "apply.afterTitle": "Was wird freigeschaltet?",
  "apply.afterBadge": "Creator-/Publisher-Abzeichen und Publisher-Profil",
  "apply.afterDiscovery": "Öffentliche Sichtbarkeit in der Picom-Live-Now-Entdeckung",
  "apply.afterGate": "Zugang zu „Live gehen“ (aktives Abzeichen + genehmigte Bewerbung)",
  "apply.afterSafety": "Fortgesetztes Streaming vorbehaltlich Überprüfung und Sicherheitsregeln",
  "apply.processKicker": "Ablauf",
  "apply.processTitle": "Bewerbungsprozess",
  "apply.processStep1": "Einen der Schwellenwerte erreichen",
  "apply.processStep2": "Bewerbungsformular einreichen",
  "apply.processStep3": "Prüfung: Berechtigungsrisiko und Inhaltsrichtlinien",
  "apply.processStep4": "Freigabe → Abzeichen; Ablehnung / weitere Infos erscheinen hier",
  "apply.rulesKicker": "Zählregeln",
  "apply.rulesTitle": "Was zählt?",
  "apply.rulesFollowers": "Follower: {count} aktive Follower",
  "apply.rulesCommunity": "Community: {count} aktive Mitglieder in einer Community, die dir gehört",
  "apply.rulesOwner": "Inhaberquelle: communities.owner_id",
  "apply.rulesNoMerge": "Keine Mitgliederzusammenführung · Fortschrittsbalken sind keine Autorisierung",
  "apply.elig.notEligible":
    "Du erfüllst die Bewerbungsvoraussetzungen noch nicht. Schließe einen der unten stehenden Wege ab, um das Formular freizuschalten.",
  "apply.elig.both": "Du erfüllst beide Bewerbungskriterien. Du kannst deine Bewerbung einreichen.",
  "apply.elig.followers": "Du hast das Follower-Kriterium erfüllt. Du kannst dich als Creator / Publisher bewerben.",
  "apply.elig.community": "Du hast das Community-Gründer-Kriterium erfüllt. Du kannst dich als Creator / Publisher bewerben.",
  "apply.elig.ok": "Bewerbungsvoraussetzungen erfüllt.",
  "apply.closer.tie": "Beide Wege sind ähnlich weit entfernt; baue den aus, der besser zu dir passt.",
  "apply.closer.followers": "Der Follower-Weg ist gerade zahlenmäßig näher.",
  "apply.closer.community": "Der Weg über deine größte eigene Community ist gerade näher.",
  "apply.track.met": "Erfüllt",
  "apply.track.open": "Weg offen",
  "apply.track.remaining": "Verbleibend {count}",
  "apply.track.progressAria": "Fortschritt {label}",
  "dash.aria": "Publisher-Dashboard",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Nur freigegebene Creator-/Publisher-Konten haben Zugriff auf diesen Bereich.",
  "dash.noBroadcast": "Dein Konto hat noch keine Sendeberechtigung.",
  "dash.viewApplication": "Bewerbungsstatus ansehen",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Publisher-Bereich",
  "dash.badgeActive": "Aktives Abzeichen: {type}",
  "dash.badgeLoading": "Abzeichenstatus wird geladen…",
  "dash.goLive": "Live gehen",
  "dash.close": "Schließen",
  "dash.tabsAria": "Publisher-Bereiche",
  "dash.tab.overview": "Übersicht",
  "dash.tab.streams": "Streams",
  "dash.tab.create": "Erstellen",
  "dash.tab.schedule": "Zeitplan",
  "dash.tab.settings": "Einstellungen",
  "dash.overviewTitle": "Übersicht",
  "dash.overviewBody":
    "Verwende „Live gehen“, um einen Stream zu starten. Live Now listet nur public_discovery-Streams mit genehmigtem Abzeichen auf.",
  "dash.overviewBilling": "Einnahmen / Abos / Werbung: noch nicht eingerichtet (kein Zahlungsanbieter).",
  "dash.scheduleTitle": "Stream-Zeitplan",
  "dash.scheduleEmpty": "Keine geplanten Streams.",
  "dash.planTitle": "Stream planen",
  "dash.planName": "Titel",
  "dash.planStart": "Start",
  "dash.planSubmit": "Zum Kalender hinzufügen",
  "dash.settingsTitle": "Kontoverifizierung",
  "dash.accountKind": "Kontotyp: {kind}",
  "dash.profileStatus": "Profilstatus: {status}",
  "dash.applicationHistory": "Bewerbungsverlauf",
  "review.eyebrow": "Care & Safety",
  "review.title": "Publisher- & Creator-Überprüfung",
  "review.lede":
    "Das Erreichen eines Schwellenwerts bedeutet keine automatische Freigabe. Snapshot und aktuelle Zahlen werden gemeinsam geprüft.",
  "review.status": "Status",
  "review.eligibility": "Berechtigungsfilter",
  "review.reason": "Entscheidungsgrund",
  "review.refresh": "Aktualisieren",
  "review.filter.all": "alle",
  "review.filter.follower": "Follower-Kriterium",
  "review.filter.community": "Community-Kriterium",
  "review.filter.both": "Beide Kriterien",
  "review.filter.below": "Jetzt unter dem Schwellenwert",
  "review.filter.fraud": "Betrugsprüfung",
  "review.paths": "Berechtigungswege",
  "review.followers": "Follower (Bewerbung → jetzt)",
  "review.members": "Community-Mitglieder (Bewerbung → jetzt)",
  "review.community": "Qualifizierte Community",
  "review.owner": " (Inhaber)",
  "review.notOwner": " (jetzt nicht Inhaber)",
  "review.risk": "Risiko",
  "review.riskDrop": "Risikowarnung: ungewöhnlicher Rückgang der Zahlen nach der Bewerbung.",
  "review.approve": "Genehmigen",
  "review.underReview": "In Prüfung",
  "review.reject": "Ablehnen",
  "review.suspend": "Sperren",
  "review.liveBan": "Live-Verbot",
  "review.empty": "Warteschlange leer.",
  "review.defaultReason": "Vom Root Panel geprüft",
  "review.banReason": "Live-Verbot aus dem Prüfpanel",
};

const fr: Catalog = {
  "apply.aria": "Candidature Creator Publisher",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Prêt à candidater",
  "apply.belowThreshold": "Sous le seuil",
  "apply.title": "Candidature Creator / Publisher",
  "apply.lede":
    "La diffusion publique sur Live Now nécessite une approbation Creator ou Publisher. L'éligibilité est calculée côté serveur ; les compteurs affichés ici sont informatifs et ne constituent pas la source d'autorisation.",
  "apply.refresh": "Actualiser",
  "apply.refreshAria": "Actualiser l'éligibilité",
  "apply.dashboard": "Dashboard",
  "apply.close": "Fermer",
  "apply.loading": "Vérification de l'éligibilité…",
  "apply.snapshotTitle": "Aperçu de l'éligibilité au direct",
  "apply.lastCheck": "Dernière vérification · {time}",
  "apply.followers": "Abonnés actifs",
  "apply.largestCommunity": "Plus grande communauté possédée",
  "apply.countedCommunity": "Communauté comptabilisée",
  "apply.noCommunity": "Aucune communauté comptabilisable pour l'instant",
  "apply.accountGate": "Restriction de compte / de direct",
  "apply.liveBan": "Interdiction de direct active — candidature ou diffusion bloquée",
  "apply.accountInactive": "Le compte n'est pas actif",
  "apply.accountOk": "Le compte semble éligible",
  "apply.pathsTitle": "Voies de candidature",
  "apply.pathsBody":
    "Une seule voie suffit. Les nombres de membres ne sont pas cumulés entre communautés ; seule la plus grande communauté active que tu possèdes est comptabilisée.",
  "apply.followerPath": "Voie des abonnés",
  "apply.followerDetail": "Seuil d'abonnés Picom actifs · comptage serveur",
  "apply.or": "OU",
  "apply.communityPath": "Voie du fondateur de communauté",
  "apply.communityDetailNamed": "{name} · membres actifs (propriétaire)",
  "apply.communityDetailDefault": "Plus grande communauté possédée · membres actifs (propriétaire)",
  "apply.applicationsTitle": "Tes candidatures",
  "apply.formTitle": "Formulaire de candidature",
  "apply.formLede":
    "Après approbation, ton identité Live Now est associée à ces informations. Les évaluateurs voient le texte que tu soumets.",
  "apply.typeLabel": "Type de candidature",
  "apply.typeCreator": "Creator (individuel)",
  "apply.typePublisher": "Publisher (organisation)",
  "apply.displayName": "Nom d'affichage du publisher",
  "apply.displayPlaceholder": "Nom de diffusion visible",
  "apply.bio": "Courte biographie",
  "apply.bioPlaceholder": "Explique brièvement aux spectateurs qui tu es et ce que tu diffuses",
  "apply.company": "Nom de l'entreprise / organisation",
  "apply.submit": "Soumettre la candidature",
  "apply.submitting": "Envoi en cours…",
  "apply.nextTitle": "Comment progresser",
  "apply.growFollowersTitle": "Développer la voie des abonnés",
  "apply.growFollowersBody":
    "{count} abonnés actifs supplémentaires sont nécessaires pour atteindre le seuil. Les comptes inactifs ou supprimés ne comptent pas ; le serveur applique les règles de profil actif.",
  "apply.growCommunityTitle": "Développer la voie communautaire",
  "apply.growCommunityBodyNamed":
    "« {name} » a besoin de {count} membres actifs supplémentaires. Même en tant que fondateur, l'adhésion et un profil actif sont requis ; les communautés ne sont pas fusionnées.",
  "apply.growCommunityBodyDefault":
    "Ta plus grande communauté a besoin de {count} membres actifs supplémentaires. Même en tant que fondateur, l'adhésion et un profil actif sont requis ; les communautés ne sont pas fusionnées.",
  "apply.asideLabel": "Résumé du programme",
  "apply.afterKicker": "Après approbation",
  "apply.afterTitle": "Qu'est-ce qui se débloque ?",
  "apply.afterBadge": "Badge Creator / Publisher et profil publisher",
  "apply.afterDiscovery": "Visibilité publique dans la découverte Picom Live Now",
  "apply.afterGate": "Accès à « Passer en direct » (badge actif + candidature approuvée)",
  "apply.afterSafety": "Diffusion continue soumise aux règles de modération et de sécurité",
  "apply.processKicker": "Processus",
  "apply.processTitle": "Déroulement de la candidature",
  "apply.processStep1": "Atteindre l'un des seuils",
  "apply.processStep2": "Soumettre le formulaire de candidature",
  "apply.processStep3": "Évaluation : risque d'éligibilité et vérifications de la politique de contenu",
  "apply.processStep4": "Approbation → badge ; refus / informations complémentaires apparaissent ici",
  "apply.rulesKicker": "Règles de comptage",
  "apply.rulesTitle": "Qu'est-ce qui compte ?",
  "apply.rulesFollowers": "Abonnés : {count} abonnés actifs",
  "apply.rulesCommunity": "Communauté : {count} membres actifs dans une communauté que tu possèdes",
  "apply.rulesOwner": "Source du propriétaire : communities.owner_id",
  "apply.rulesNoMerge": "Aucune fusion de membres · les barres de progression ne valent pas autorisation",
  "apply.elig.notEligible":
    "Tu ne remplis pas encore les conditions de candidature. Complète l'une des voies ci-dessous pour débloquer le formulaire.",
  "apply.elig.both": "Tu remplis les deux critères de candidature. Tu peux soumettre ta candidature.",
  "apply.elig.followers": "Tu as atteint le critère d'abonnés. Tu peux candidater en tant que Creator / Publisher.",
  "apply.elig.community": "Tu as atteint le critère de fondateur de communauté. Tu peux candidater en tant que Creator / Publisher.",
  "apply.elig.ok": "Conditions de candidature remplies.",
  "apply.closer.tie": "Les deux voies sont à distance similaire ; développe celle qui te convient le mieux.",
  "apply.closer.followers": "La voie des abonnés est actuellement numériquement plus proche.",
  "apply.closer.community": "La voie de ta plus grande communauté est actuellement plus proche.",
  "apply.track.met": "Atteint",
  "apply.track.open": "Voie ouverte",
  "apply.track.remaining": "Restant {count}",
  "apply.track.progressAria": "Progression {label}",
  "dash.aria": "Dashboard Publisher",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Seuls les comptes Creator/Publisher approuvés peuvent accéder à cette zone.",
  "dash.noBroadcast": "Ton compte n'a pas encore l'autorisation de diffuser.",
  "dash.viewApplication": "Voir le statut de la candidature",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Panneau publisher",
  "dash.badgeActive": "Badge actif : {type}",
  "dash.badgeLoading": "Chargement du statut du badge…",
  "dash.goLive": "Passer en direct",
  "dash.close": "Fermer",
  "dash.tabsAria": "Sections publisher",
  "dash.tab.overview": "aperçu",
  "dash.tab.streams": "diffusions",
  "dash.tab.create": "créer",
  "dash.tab.schedule": "calendrier",
  "dash.tab.settings": "paramètres",
  "dash.overviewTitle": "Aperçu",
  "dash.overviewBody":
    "Utilise « Passer en direct » pour démarrer une diffusion. Live Now liste uniquement les diffusions public_discovery avec un badge approuvé.",
  "dash.overviewBilling": "Revenus / abonnements / publicités : pas encore configuré (aucun fournisseur de facturation).",
  "dash.scheduleTitle": "Calendrier de diffusion",
  "dash.scheduleEmpty": "Aucune diffusion planifiée.",
  "dash.planTitle": "Planifier une diffusion",
  "dash.planName": "Titre",
  "dash.planStart": "Début",
  "dash.planSubmit": "Ajouter au calendrier",
  "dash.settingsTitle": "Vérification du compte",
  "dash.accountKind": "Type de compte : {kind}",
  "dash.profileStatus": "Statut du profil : {status}",
  "dash.applicationHistory": "Historique des candidatures",
  "review.eyebrow": "Care & Safety",
  "review.title": "Évaluation Publisher & Creator",
  "review.lede":
    "Atteindre un seuil ne vaut pas approbation automatique. L'aperçu et les chiffres actuels sont examinés ensemble.",
  "review.status": "Statut",
  "review.eligibility": "Filtre d'éligibilité",
  "review.reason": "Motif de décision",
  "review.refresh": "Actualiser",
  "review.filter.all": "tous",
  "review.filter.follower": "Critère abonnés",
  "review.filter.community": "Critère communauté",
  "review.filter.both": "Les deux critères",
  "review.filter.below": "Désormais sous le seuil",
  "review.filter.fraud": "Examen de fraude",
  "review.paths": "Voies d'éligibilité",
  "review.followers": "Abonnés (candidature → maintenant)",
  "review.members": "Membres de la communauté (candidature → maintenant)",
  "review.community": "Communauté qualifiée",
  "review.owner": " (propriétaire)",
  "review.notOwner": " (n'est plus propriétaire)",
  "review.risk": "Risque",
  "review.riskDrop": "Alerte de risque : baisse inhabituelle des chiffres après la candidature.",
  "review.approve": "Approuver",
  "review.underReview": "En cours d'évaluation",
  "review.reject": "Rejeter",
  "review.suspend": "Suspendre",
  "review.liveBan": "Interdiction de direct",
  "review.empty": "File d'attente vide.",
  "review.defaultReason": "Évalué par le Root Panel",
  "review.banReason": "Interdiction de direct depuis le panneau d'évaluation",
};

const es: Catalog = {
  "apply.aria": "Solicitud Creator Publisher",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Listo para solicitar",
  "apply.belowThreshold": "Por debajo del umbral",
  "apply.title": "Solicitud Creator / Publisher",
  "apply.lede":
    "Transmitir públicamente en Live Now requiere la aprobación como Creator o Publisher. La elegibilidad se calcula en el servidor; los contadores aquí son informativos y no son la fuente de autorización.",
  "apply.refresh": "Actualizar",
  "apply.refreshAria": "Actualizar elegibilidad",
  "apply.dashboard": "Dashboard",
  "apply.close": "Cerrar",
  "apply.loading": "Comprobando elegibilidad…",
  "apply.snapshotTitle": "Resumen de elegibilidad para directo",
  "apply.lastCheck": "Última comprobación · {time}",
  "apply.followers": "Seguidores activos",
  "apply.largestCommunity": "Comunidad propia más grande",
  "apply.countedCommunity": "Comunidad contabilizada",
  "apply.noCommunity": "Aún no hay ninguna comunidad contabilizable",
  "apply.accountGate": "Restricción de cuenta / directo",
  "apply.liveBan": "Prohibición de directo activa — solicitud o transmisión bloqueada",
  "apply.accountInactive": "La cuenta no está activa",
  "apply.accountOk": "La cuenta parece elegible",
  "apply.pathsTitle": "Vías de solicitud",
  "apply.pathsBody":
    "Con una vía es suficiente. El número de miembros no se combina entre comunidades; solo se cuenta la comunidad activa más grande que posees.",
  "apply.followerPath": "Vía de seguidores",
  "apply.followerDetail": "Umbral de seguidores activos de Picom · recuento del servidor",
  "apply.or": "O",
  "apply.communityPath": "Vía de fundador de comunidad",
  "apply.communityDetailNamed": "{name} · miembros activos (propietario)",
  "apply.communityDetailDefault": "Comunidad propia más grande · miembros activos (propietario)",
  "apply.applicationsTitle": "Tus solicitudes",
  "apply.formTitle": "Formulario de solicitud",
  "apply.formLede":
    "Tras la aprobación, tu identidad de Live Now se vincula a esta información. El equipo de revisión ve el texto que envías.",
  "apply.typeLabel": "Tipo de solicitud",
  "apply.typeCreator": "Creator (individual)",
  "apply.typePublisher": "Publisher (organización)",
  "apply.displayName": "Nombre visible como publisher",
  "apply.displayPlaceholder": "Nombre de transmisión visible",
  "apply.bio": "Biografía breve",
  "apply.bioPlaceholder": "Cuéntale brevemente a tu audiencia quién eres y qué transmites",
  "apply.company": "Nombre de la empresa / organización",
  "apply.submit": "Enviar solicitud",
  "apply.submitting": "Enviando…",
  "apply.nextTitle": "Cómo avanzar",
  "apply.growFollowersTitle": "Hacer crecer la vía de seguidores",
  "apply.growFollowersBody":
    "Se necesitan {count} seguidores activos más para alcanzar el umbral. Las cuentas inactivas o eliminadas no cuentan; el servidor aplica las reglas de perfil activo.",
  "apply.growCommunityTitle": "Hacer crecer la vía comunitaria",
  "apply.growCommunityBodyNamed":
    "«{name}» necesita {count} miembros activos más. Incluso como fundador, se requieren membresía y un perfil activo; las comunidades no se combinan.",
  "apply.growCommunityBodyDefault":
    "Tu comunidad propia más grande necesita {count} miembros activos más. Incluso como fundador, se requieren membresía y un perfil activo; las comunidades no se combinan.",
  "apply.asideLabel": "Resumen del programa",
  "apply.afterKicker": "Tras la aprobación",
  "apply.afterTitle": "¿Qué se desbloquea?",
  "apply.afterBadge": "Insignia Creator / Publisher y perfil de publisher",
  "apply.afterDiscovery": "Visibilidad pública en el descubrimiento de Picom Live Now",
  "apply.afterGate": "Acceso a «Salir en directo» (insignia activa + solicitud aprobada)",
  "apply.afterSafety": "Transmisión continua sujeta a revisión y normas de seguridad",
  "apply.processKicker": "Proceso",
  "apply.processTitle": "Flujo de solicitud",
  "apply.processStep1": "Completa uno de los umbrales",
  "apply.processStep2": "Envía el formulario de solicitud",
  "apply.processStep3": "Revisión: riesgo de elegibilidad y verificaciones de política de contenido",
  "apply.processStep4": "Aprobación → insignia; el rechazo / la solicitud de más información aparece aquí",
  "apply.rulesKicker": "Reglas de conteo",
  "apply.rulesTitle": "¿Qué cuenta?",
  "apply.rulesFollowers": "Seguidores: {count} seguidores activos",
  "apply.rulesCommunity": "Comunidad: {count} miembros activos en una comunidad que posees",
  "apply.rulesOwner": "Origen del propietario: communities.owner_id",
  "apply.rulesNoMerge": "Sin combinación de miembros · las barras de progreso no son autorización",
  "apply.elig.notEligible":
    "Aún no cumples los requisitos de solicitud. Completa una de las vías siguientes para desbloquear el formulario.",
  "apply.elig.both": "Cumples ambos criterios de solicitud. Puedes enviar tu solicitud.",
  "apply.elig.followers": "Cumpliste el criterio de seguidores. Puedes solicitar como Creator / Publisher.",
  "apply.elig.community": "Cumpliste el criterio de fundador de comunidad. Puedes solicitar como Creator / Publisher.",
  "apply.elig.ok": "Requisitos de solicitud cumplidos.",
  "apply.closer.tie": "Ambas vías están a una distancia similar; avanza en la que mejor se ajuste a ti.",
  "apply.closer.followers": "La vía de seguidores está numéricamente más cerca en este momento.",
  "apply.closer.community": "La vía de tu comunidad propia más grande está más cerca en este momento.",
  "apply.track.met": "Cumplido",
  "apply.track.open": "Vía abierta",
  "apply.track.remaining": "Restante {count}",
  "apply.track.progressAria": "Progreso de {label}",
  "dash.aria": "Panel de Publisher",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Solo las cuentas Creator/Publisher aprobadas pueden acceder a esta área.",
  "dash.noBroadcast": "Tu cuenta aún no tiene permiso de transmisión.",
  "dash.viewApplication": "Ver estado de la solicitud",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Panel de publisher",
  "dash.badgeActive": "Insignia activa: {type}",
  "dash.badgeLoading": "Cargando estado de la insignia…",
  "dash.goLive": "Salir en directo",
  "dash.close": "Cerrar",
  "dash.tabsAria": "Secciones de publisher",
  "dash.tab.overview": "resumen",
  "dash.tab.streams": "transmisiones",
  "dash.tab.create": "crear",
  "dash.tab.schedule": "calendario",
  "dash.tab.settings": "ajustes",
  "dash.overviewTitle": "Resumen",
  "dash.overviewBody":
    "Usa «Salir en directo» para iniciar una transmisión. Live Now solo muestra transmisiones public_discovery con una insignia aprobada.",
  "dash.overviewBilling": "Ingresos / suscripciones / anuncios: aún no configurado (sin proveedor de facturación).",
  "dash.scheduleTitle": "Calendario de transmisiones",
  "dash.scheduleEmpty": "No hay transmisiones programadas.",
  "dash.planTitle": "Programar una transmisión",
  "dash.planName": "Título",
  "dash.planStart": "Inicio",
  "dash.planSubmit": "Añadir al calendario",
  "dash.settingsTitle": "Verificación de cuenta",
  "dash.accountKind": "Tipo de cuenta: {kind}",
  "dash.profileStatus": "Estado del perfil: {status}",
  "dash.applicationHistory": "Historial de solicitudes",
  "review.eyebrow": "Care & Safety",
  "review.title": "Revisión de Publisher y Creator",
  "review.lede":
    "Alcanzar un umbral no supone una aprobación automática. El resumen y los recuentos actuales se revisan juntos.",
  "review.status": "Estado",
  "review.eligibility": "Filtro de elegibilidad",
  "review.reason": "Motivo de la decisión",
  "review.refresh": "Actualizar",
  "review.filter.all": "todos",
  "review.filter.follower": "Criterio de seguidores",
  "review.filter.community": "Criterio de comunidad",
  "review.filter.both": "Ambos criterios",
  "review.filter.below": "Ahora por debajo del umbral",
  "review.filter.fraud": "Revisión de fraude",
  "review.paths": "Vías de elegibilidad",
  "review.followers": "Seguidores (solicitud → ahora)",
  "review.members": "Miembros de la comunidad (solicitud → ahora)",
  "review.community": "Comunidad calificada",
  "review.owner": " (propietario)",
  "review.notOwner": " (ya no es propietario)",
  "review.risk": "Riesgo",
  "review.riskDrop": "Advertencia de riesgo: caída inusual en los recuentos tras la solicitud.",
  "review.approve": "Aprobar",
  "review.underReview": "En revisión",
  "review.reject": "Rechazar",
  "review.suspend": "Suspender",
  "review.liveBan": "Prohibición de directo",
  "review.empty": "Cola vacía.",
  "review.defaultReason": "Revisado por el Root Panel",
  "review.banReason": "Prohibición de directo desde el panel de revisión",
};

const it: Catalog = {
  "apply.aria": "Candidatura Creator Publisher",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Pronto per candidarti",
  "apply.belowThreshold": "Sotto la soglia",
  "apply.title": "Candidatura Creator / Publisher",
  "apply.lede":
    "Lo streaming pubblico su Live Now richiede l'approvazione come Creator o Publisher. L'idoneità viene calcolata sul server; i contatori qui mostrati sono informativi e non costituiscono la fonte di autorizzazione.",
  "apply.refresh": "Aggiorna",
  "apply.refreshAria": "Aggiorna idoneità",
  "apply.dashboard": "Dashboard",
  "apply.close": "Chiudi",
  "apply.loading": "Verifica dell'idoneità in corso…",
  "apply.snapshotTitle": "Riepilogo idoneità live",
  "apply.lastCheck": "Ultimo controllo · {time}",
  "apply.followers": "Follower attivi",
  "apply.largestCommunity": "Community di proprietà più grande",
  "apply.countedCommunity": "Community conteggiata",
  "apply.noCommunity": "Nessuna community conteggiabile per ora",
  "apply.accountGate": "Restrizione account / live",
  "apply.liveBan": "Ban live attivo — candidatura o streaming bloccati",
  "apply.accountInactive": "L'account non è attivo",
  "apply.accountOk": "L'account sembra idoneo",
  "apply.pathsTitle": "Percorsi di candidatura",
  "apply.pathsBody":
    "Un solo percorso è sufficiente. I conteggi dei membri non vengono uniti tra community diverse; viene conteggiata solo la community attiva più grande di cui sei proprietario.",
  "apply.followerPath": "Percorso follower",
  "apply.followerDetail": "Soglia follower Picom attivi · conteggio server",
  "apply.or": "OPPURE",
  "apply.communityPath": "Percorso fondatore di community",
  "apply.communityDetailNamed": "{name} · membri attivi (proprietario)",
  "apply.communityDetailDefault": "Community di proprietà più grande · membri attivi (proprietario)",
  "apply.applicationsTitle": "Le tue candidature",
  "apply.formTitle": "Modulo di candidatura",
  "apply.formLede":
    "Dopo l'approvazione, la tua identità Live Now viene associata a queste informazioni. Il team di revisione visualizza il testo inviato.",
  "apply.typeLabel": "Tipo di candidatura",
  "apply.typeCreator": "Creator (individuale)",
  "apply.typePublisher": "Publisher (organizzazione)",
  "apply.displayName": "Nome visualizzato come publisher",
  "apply.displayPlaceholder": "Nome dello stream visibile",
  "apply.bio": "Breve biografia",
  "apply.bioPlaceholder": "Racconta brevemente agli spettatori chi sei e cosa trasmetti",
  "apply.company": "Nome dell'azienda / organizzazione",
  "apply.submit": "Invia candidatura",
  "apply.submitting": "Invio in corso…",
  "apply.nextTitle": "Come procedere",
  "apply.growFollowersTitle": "Sviluppare il percorso follower",
  "apply.growFollowersBody":
    "Servono altri {count} follower attivi per raggiungere la soglia. Gli account inattivi o eliminati non vengono conteggiati; il server applica le regole del profilo attivo.",
  "apply.growCommunityTitle": "Sviluppare il percorso community",
  "apply.growCommunityBodyNamed":
    "\"{name}\" ha bisogno di altri {count} membri attivi. Anche come fondatore, sono richiesti iscrizione e profilo attivo; le community non vengono unite.",
  "apply.growCommunityBodyDefault":
    "La tua community di proprietà più grande ha bisogno di altri {count} membri attivi. Anche come fondatore, sono richiesti iscrizione e profilo attivo; le community non vengono unite.",
  "apply.asideLabel": "Riepilogo del programma",
  "apply.afterKicker": "Dopo l'approvazione",
  "apply.afterTitle": "Cosa si sblocca?",
  "apply.afterBadge": "Badge Creator / Publisher e profilo publisher",
  "apply.afterDiscovery": "Visibilità pubblica nella sezione scopri di Picom Live Now",
  "apply.afterGate": "Accesso a \"Vai in diretta\" (badge attivo + candidatura approvata)",
  "apply.afterSafety": "Streaming continuativo soggetto a revisione e regole di sicurezza",
  "apply.processKicker": "Processo",
  "apply.processTitle": "Flusso della candidatura",
  "apply.processStep1": "Completa una delle soglie",
  "apply.processStep2": "Invia il modulo di candidatura",
  "apply.processStep3": "Revisione: rischio di idoneità e controlli sulle policy dei contenuti",
  "apply.processStep4": "Approvazione → badge; rifiuto / richiesta di ulteriori informazioni appare qui",
  "apply.rulesKicker": "Regole di conteggio",
  "apply.rulesTitle": "Cosa conta?",
  "apply.rulesFollowers": "Follower: {count} follower attivi",
  "apply.rulesCommunity": "Community: {count} membri attivi in una community di tua proprietà",
  "apply.rulesOwner": "Origine proprietario: communities.owner_id",
  "apply.rulesNoMerge": "Nessuna unione di membri · le barre di avanzamento non equivalgono ad autorizzazione",
  "apply.elig.notEligible":
    "Non soddisfi ancora i requisiti di candidatura. Completa uno dei percorsi qui sotto per sbloccare il modulo.",
  "apply.elig.both": "Soddisfi entrambi i criteri di candidatura. Puoi inviare la tua candidatura.",
  "apply.elig.followers": "Hai soddisfatto il criterio follower. Puoi candidarti come Creator / Publisher.",
  "apply.elig.community": "Hai soddisfatto il criterio fondatore di community. Puoi candidarti come Creator / Publisher.",
  "apply.elig.ok": "Requisiti di candidatura soddisfatti.",
  "apply.closer.tie": "Entrambi i percorsi sono a una distanza simile; sviluppa quello più adatto a te.",
  "apply.closer.followers": "Il percorso follower è al momento numericamente più vicino.",
  "apply.closer.community": "Il percorso della tua community più grande è al momento più vicino.",
  "apply.track.met": "Raggiunto",
  "apply.track.open": "Percorso aperto",
  "apply.track.remaining": "Mancano {count}",
  "apply.track.progressAria": "Avanzamento {label}",
  "dash.aria": "Dashboard Publisher",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Solo gli account Creator/Publisher approvati possono accedere a quest'area.",
  "dash.noBroadcast": "Il tuo account non ha ancora l'autorizzazione a trasmettere.",
  "dash.viewApplication": "Visualizza stato candidatura",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Pannello publisher",
  "dash.badgeActive": "Badge attivo: {type}",
  "dash.badgeLoading": "Caricamento stato badge…",
  "dash.goLive": "Vai in diretta",
  "dash.close": "Chiudi",
  "dash.tabsAria": "Sezioni publisher",
  "dash.tab.overview": "panoramica",
  "dash.tab.streams": "stream",
  "dash.tab.create": "crea",
  "dash.tab.schedule": "calendario",
  "dash.tab.settings": "impostazioni",
  "dash.overviewTitle": "Panoramica",
  "dash.overviewBody":
    "Usa \"Vai in diretta\" per avviare uno stream. Live Now elenca solo gli stream public_discovery con badge approvato.",
  "dash.overviewBilling": "Ricavi / abbonamenti / pubblicità: non ancora configurati (nessun fornitore di fatturazione).",
  "dash.scheduleTitle": "Calendario stream",
  "dash.scheduleEmpty": "Nessuno stream programmato.",
  "dash.planTitle": "Pianifica uno stream",
  "dash.planName": "Titolo",
  "dash.planStart": "Inizio",
  "dash.planSubmit": "Aggiungi al calendario",
  "dash.settingsTitle": "Verifica dell'account",
  "dash.accountKind": "Tipo di account: {kind}",
  "dash.profileStatus": "Stato del profilo: {status}",
  "dash.applicationHistory": "Cronologia candidature",
  "review.eyebrow": "Care & Safety",
  "review.title": "Revisione Publisher e Creator",
  "review.lede":
    "Raggiungere una soglia non equivale ad approvazione automatica. Lo snapshot e i conteggi attuali vengono esaminati insieme.",
  "review.status": "Stato",
  "review.eligibility": "Filtro idoneità",
  "review.reason": "Motivo della decisione",
  "review.refresh": "Aggiorna",
  "review.filter.all": "tutti",
  "review.filter.follower": "Criterio follower",
  "review.filter.community": "Criterio community",
  "review.filter.both": "Entrambi i criteri",
  "review.filter.below": "Ora sotto la soglia",
  "review.filter.fraud": "Revisione frodi",
  "review.paths": "Percorsi di idoneità",
  "review.followers": "Follower (candidatura → ora)",
  "review.members": "Membri della community (candidatura → ora)",
  "review.community": "Community qualificata",
  "review.owner": " (proprietario)",
  "review.notOwner": " (non più proprietario)",
  "review.risk": "Rischio",
  "review.riskDrop": "Avviso di rischio: calo insolito dei conteggi dopo la candidatura.",
  "review.approve": "Approva",
  "review.underReview": "In revisione",
  "review.reject": "Rifiuta",
  "review.suspend": "Sospendi",
  "review.liveBan": "Ban live",
  "review.empty": "Coda vuota.",
  "review.defaultReason": "Revisionato dal Root Panel",
  "review.banReason": "Ban live dal pannello di revisione",
};

const pt: Catalog = {
  "apply.aria": "Candidatura Creator Publisher",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Pronto para se candidatar",
  "apply.belowThreshold": "Abaixo do limite",
  "apply.title": "Candidatura Creator / Publisher",
  "apply.lede":
    "Transmitir publicamente no Live Now exige aprovação como Creator ou Publisher. A elegibilidade é calculada no servidor; os contadores aqui são informativos e não são a fonte de autorização.",
  "apply.refresh": "Atualizar",
  "apply.refreshAria": "Atualizar elegibilidade",
  "apply.dashboard": "Dashboard",
  "apply.close": "Fechar",
  "apply.loading": "Verificando elegibilidade…",
  "apply.snapshotTitle": "Resumo de elegibilidade para transmissão",
  "apply.lastCheck": "Última verificação · {time}",
  "apply.followers": "Seguidores ativos",
  "apply.largestCommunity": "Maior comunidade que você possui",
  "apply.countedCommunity": "Comunidade contabilizada",
  "apply.noCommunity": "Ainda não há comunidade contabilizável",
  "apply.accountGate": "Restrição de conta / transmissão",
  "apply.liveBan": "Banimento de transmissão ativo — candidatura ou transmissão bloqueada",
  "apply.accountInactive": "A conta não está ativa",
  "apply.accountOk": "A conta parece elegível",
  "apply.pathsTitle": "Caminhos de candidatura",
  "apply.pathsBody":
    "Um caminho já é suficiente. As contagens de membros não são somadas entre comunidades; apenas a maior comunidade ativa que você possui é contabilizada.",
  "apply.followerPath": "Caminho de seguidores",
  "apply.followerDetail": "Limite de seguidores ativos do Picom · contagem do servidor",
  "apply.or": "OU",
  "apply.communityPath": "Caminho de fundador de comunidade",
  "apply.communityDetailNamed": "{name} · membros ativos (proprietário)",
  "apply.communityDetailDefault": "Maior comunidade que você possui · membros ativos (proprietário)",
  "apply.applicationsTitle": "Suas candidaturas",
  "apply.formTitle": "Formulário de candidatura",
  "apply.formLede":
    "Após a aprovação, sua identidade no Live Now é associada a essas informações. A equipe de revisão vê o texto que você enviar.",
  "apply.typeLabel": "Tipo de candidatura",
  "apply.typeCreator": "Creator (individual)",
  "apply.typePublisher": "Publisher (organização)",
  "apply.displayName": "Nome de exibição como publisher",
  "apply.displayPlaceholder": "Nome de transmissão visível",
  "apply.bio": "Bio curta",
  "apply.bioPlaceholder": "Conte brevemente ao público quem você é e o que transmite",
  "apply.company": "Nome da empresa / organização",
  "apply.submit": "Enviar candidatura",
  "apply.submitting": "Enviando…",
  "apply.nextTitle": "Como avançar",
  "apply.growFollowersTitle": "Expandir o caminho de seguidores",
  "apply.growFollowersBody":
    "Faltam {count} seguidores ativos para atingir o limite. Contas inativas ou excluídas não contam; o servidor aplica as regras de perfil ativo.",
  "apply.growCommunityTitle": "Expandir o caminho da comunidade",
  "apply.growCommunityBodyNamed":
    "\"{name}\" precisa de mais {count} membros ativos. Mesmo como fundador, associação e perfil ativo são exigidos; comunidades não são combinadas.",
  "apply.growCommunityBodyDefault":
    "Sua maior comunidade precisa de mais {count} membros ativos. Mesmo como fundador, associação e perfil ativo são exigidos; comunidades não são combinadas.",
  "apply.asideLabel": "Resumo do programa",
  "apply.afterKicker": "Após a aprovação",
  "apply.afterTitle": "O que é desbloqueado?",
  "apply.afterBadge": "Selo Creator / Publisher e perfil de publisher",
  "apply.afterDiscovery": "Visibilidade pública na descoberta do Picom Live Now",
  "apply.afterGate": "Acesso a \"Iniciar transmissão\" (selo ativo + candidatura aprovada)",
  "apply.afterSafety": "Transmissão contínua sujeita a revisão e regras de segurança",
  "apply.processKicker": "Processo",
  "apply.processTitle": "Fluxo da candidatura",
  "apply.processStep1": "Complete um dos limites",
  "apply.processStep2": "Envie o formulário de candidatura",
  "apply.processStep3": "Revisão: risco de elegibilidade e verificações de política de conteúdo",
  "apply.processStep4": "Aprovação → selo; rejeição / mais informações aparecem aqui",
  "apply.rulesKicker": "Regras de contagem",
  "apply.rulesTitle": "O que conta?",
  "apply.rulesFollowers": "Seguidores: {count} seguidores ativos",
  "apply.rulesCommunity": "Comunidade: {count} membros ativos em uma comunidade que você possui",
  "apply.rulesOwner": "Origem do proprietário: communities.owner_id",
  "apply.rulesNoMerge": "Sem combinação de membros · barras de progresso não são autorização",
  "apply.elig.notEligible":
    "Você ainda não atende aos requisitos de candidatura. Complete um dos caminhos abaixo para desbloquear o formulário.",
  "apply.elig.both": "Você atende aos dois critérios de candidatura. Você pode enviar sua candidatura.",
  "apply.elig.followers": "Você atendeu ao critério de seguidores. Você pode se candidatar como Creator / Publisher.",
  "apply.elig.community": "Você atendeu ao critério de fundador de comunidade. Você pode se candidatar como Creator / Publisher.",
  "apply.elig.ok": "Requisitos de candidatura atendidos.",
  "apply.closer.tie": "Os dois caminhos estão a uma distância parecida; avance no que fizer mais sentido para você.",
  "apply.closer.followers": "O caminho de seguidores está numericamente mais próximo no momento.",
  "apply.closer.community": "O caminho da sua maior comunidade está mais próximo no momento.",
  "apply.track.met": "Atingido",
  "apply.track.open": "Caminho aberto",
  "apply.track.remaining": "Faltam {count}",
  "apply.track.progressAria": "Progresso de {label}",
  "dash.aria": "Painel do Publisher",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Apenas contas Creator/Publisher aprovadas podem acessar esta área.",
  "dash.noBroadcast": "Sua conta ainda não tem permissão de transmissão.",
  "dash.viewApplication": "Ver status da candidatura",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Painel do publisher",
  "dash.badgeActive": "Selo ativo: {type}",
  "dash.badgeLoading": "Carregando status do selo…",
  "dash.goLive": "Iniciar transmissão",
  "dash.close": "Fechar",
  "dash.tabsAria": "Seções do publisher",
  "dash.tab.overview": "visão geral",
  "dash.tab.streams": "transmissões",
  "dash.tab.create": "criar",
  "dash.tab.schedule": "agenda",
  "dash.tab.settings": "configurações",
  "dash.overviewTitle": "Visão geral",
  "dash.overviewBody":
    "Use \"Iniciar transmissão\" para começar uma transmissão. O Live Now lista apenas transmissões public_discovery com selo aprovado.",
  "dash.overviewBilling": "Receita / assinaturas / anúncios: ainda não configurado (sem provedor de cobrança).",
  "dash.scheduleTitle": "Agenda de transmissões",
  "dash.scheduleEmpty": "Nenhuma transmissão agendada.",
  "dash.planTitle": "Agendar uma transmissão",
  "dash.planName": "Título",
  "dash.planStart": "Início",
  "dash.planSubmit": "Adicionar à agenda",
  "dash.settingsTitle": "Verificação de conta",
  "dash.accountKind": "Tipo de conta: {kind}",
  "dash.profileStatus": "Status do perfil: {status}",
  "dash.applicationHistory": "Histórico de candidaturas",
  "review.eyebrow": "Care & Safety",
  "review.title": "Revisão de Publisher e Creator",
  "review.lede":
    "Atingir um limite não é aprovação automática. O snapshot e os números atuais são revisados em conjunto.",
  "review.status": "Status",
  "review.eligibility": "Filtro de elegibilidade",
  "review.reason": "Motivo da decisão",
  "review.refresh": "Atualizar",
  "review.filter.all": "todos",
  "review.filter.follower": "Critério de seguidores",
  "review.filter.community": "Critério de comunidade",
  "review.filter.both": "Ambos os critérios",
  "review.filter.below": "Agora abaixo do limite",
  "review.filter.fraud": "Revisão de fraude",
  "review.paths": "Caminhos de elegibilidade",
  "review.followers": "Seguidores (candidatura → agora)",
  "review.members": "Membros da comunidade (candidatura → agora)",
  "review.community": "Comunidade qualificada",
  "review.owner": " (proprietário)",
  "review.notOwner": " (não é mais proprietário)",
  "review.risk": "Risco",
  "review.riskDrop": "Alerta de risco: queda incomum nos números após a candidatura.",
  "review.approve": "Aprovar",
  "review.underReview": "Em análise",
  "review.reject": "Rejeitar",
  "review.suspend": "Suspender",
  "review.liveBan": "Banimento de transmissão",
  "review.empty": "Fila vazia.",
  "review.defaultReason": "Revisado pelo Root Panel",
  "review.banReason": "Banimento de transmissão pelo painel de revisão",
};

const nl: Catalog = {
  "apply.aria": "Creator Publisher-aanvraag",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Klaar om te solliciteren",
  "apply.belowThreshold": "Onder de drempel",
  "apply.title": "Creator- / Publisher-aanvraag",
  "apply.lede":
    "Voor openbaar streamen op Live Now is goedkeuring als Creator of Publisher vereist. De geschiktheid wordt server-side berekend; de tellers hier zijn alleen informatief en vormen niet de bron van autorisatie.",
  "apply.refresh": "Vernieuwen",
  "apply.refreshAria": "Geschiktheid vernieuwen",
  "apply.dashboard": "Dashboard",
  "apply.close": "Sluiten",
  "apply.loading": "Geschiktheid controleren…",
  "apply.snapshotTitle": "Overzicht livegeschiktheid",
  "apply.lastCheck": "Laatste controle · {time}",
  "apply.followers": "Actieve volgers",
  "apply.largestCommunity": "Grootste eigen community",
  "apply.countedCommunity": "Meegetelde community",
  "apply.noCommunity": "Nog geen telbare community",
  "apply.accountGate": "Account-/live-blokkade",
  "apply.liveBan": "Actief liveverbod — aanvraag of streamen geblokkeerd",
  "apply.accountInactive": "Account is niet actief",
  "apply.accountOk": "Account lijkt in aanmerking te komen",
  "apply.pathsTitle": "Aanvraagroutes",
  "apply.pathsBody":
    "Eén route is voldoende. Ledenaantallen worden niet samengevoegd tussen communitys; alleen de grootste actieve community die je bezit telt mee.",
  "apply.followerPath": "Volgersroute",
  "apply.followerDetail": "Drempel actieve Picom-volgers · servertelling",
  "apply.or": "OF",
  "apply.communityPath": "Route via community-oprichter",
  "apply.communityDetailNamed": "{name} · actieve leden (eigenaar)",
  "apply.communityDetailDefault": "Grootste eigen community · actieve leden (eigenaar)",
  "apply.applicationsTitle": "Jouw aanvragen",
  "apply.formTitle": "Aanvraagformulier",
  "apply.formLede":
    "Na goedkeuring wordt je Live Now-identiteit gekoppeld aan deze informatie. Beoordelaars zien de tekst die je indient.",
  "apply.typeLabel": "Type aanvraag",
  "apply.typeCreator": "Creator (individueel)",
  "apply.typePublisher": "Publisher (organisatie)",
  "apply.displayName": "Weergavenaam als publisher",
  "apply.displayPlaceholder": "Zichtbare streamnaam",
  "apply.bio": "Korte bio",
  "apply.bioPlaceholder": "Vertel kijkers kort wie je bent en wat je streamt",
  "apply.company": "Naam van bedrijf / organisatie",
  "apply.submit": "Aanvraag indienen",
  "apply.submitting": "Bezig met verzenden…",
  "apply.nextTitle": "Hoe verder",
  "apply.growFollowersTitle": "Volgersroute laten groeien",
  "apply.growFollowersBody":
    "Er zijn nog {count} actieve volgers nodig voor de drempel. Inactieve of verwijderde accounts tellen niet mee; de server hanteert de regels voor een actief profiel.",
  "apply.growCommunityTitle": "Communityroute laten groeien",
  "apply.growCommunityBodyNamed":
    "\"{name}\" heeft nog {count} actieve leden nodig. Ook als oprichter zijn lidmaatschap en een actief profiel vereist; communitys worden niet samengevoegd.",
  "apply.growCommunityBodyDefault":
    "Je grootste eigen community heeft nog {count} actieve leden nodig. Ook als oprichter zijn lidmaatschap en een actief profiel vereist; communitys worden niet samengevoegd.",
  "apply.asideLabel": "Programmaoverzicht",
  "apply.afterKicker": "Na goedkeuring",
  "apply.afterTitle": "Wat wordt ontgrendeld?",
  "apply.afterBadge": "Creator-/Publisher-badge en publisherprofiel",
  "apply.afterDiscovery": "Openbare zichtbaarheid in Picom Live Now-ontdekking",
  "apply.afterGate": "Toegang tot \"Live gaan\" (actieve badge + goedgekeurde aanvraag)",
  "apply.afterSafety": "Voortgezet streamen onder voorbehoud van beoordeling en veiligheidsregels",
  "apply.processKicker": "Proces",
  "apply.processTitle": "Aanvraagverloop",
  "apply.processStep1": "Voltooi een van de drempels",
  "apply.processStep2": "Dien het aanvraagformulier in",
  "apply.processStep3": "Beoordeling: geschiktheidsrisico en controles op contentbeleid",
  "apply.processStep4": "Goedkeuring → badge; afwijzing / verzoek om meer informatie verschijnt hier",
  "apply.rulesKicker": "Telregels",
  "apply.rulesTitle": "Wat telt mee?",
  "apply.rulesFollowers": "Volgers: {count} actieve volgers",
  "apply.rulesCommunity": "Community: {count} actieve leden in een community die je bezit",
  "apply.rulesOwner": "Bron van eigenaarschap: communities.owner_id",
  "apply.rulesNoMerge": "Geen samenvoeging van leden · voortgangsbalken zijn geen autorisatie",
  "apply.elig.notEligible":
    "Je voldoet nog niet aan de aanvraagvereisten. Voltooi een van onderstaande routes om het formulier te ontgrendelen.",
  "apply.elig.both": "Je voldoet aan beide aanvraagcriteria. Je kunt je aanvraag indienen.",
  "apply.elig.followers": "Je voldeed aan het volgerscriterium. Je kunt solliciteren als Creator / Publisher.",
  "apply.elig.community": "Je voldeed aan het criterium community-oprichter. Je kunt solliciteren als Creator / Publisher.",
  "apply.elig.ok": "Aan de aanvraagvereisten voldaan.",
  "apply.closer.tie": "Beide routes liggen even ver weg; ontwikkel de route die het beste bij je past.",
  "apply.closer.followers": "De volgersroute ligt op dit moment cijfermatig dichterbij.",
  "apply.closer.community": "De route via je grootste eigen community ligt op dit moment dichterbij.",
  "apply.track.met": "Behaald",
  "apply.track.open": "Route open",
  "apply.track.remaining": "Nog {count} nodig",
  "apply.track.progressAria": "Voortgang {label}",
  "dash.aria": "Publisher-dashboard",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Alleen goedgekeurde Creator-/Publisher-accounts hebben toegang tot dit gedeelte.",
  "dash.noBroadcast": "Je account heeft nog geen uitzendrechten.",
  "dash.viewApplication": "Aanvraagstatus bekijken",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Publisherpaneel",
  "dash.badgeActive": "Actieve badge: {type}",
  "dash.badgeLoading": "Badgestatus laden…",
  "dash.goLive": "Live gaan",
  "dash.close": "Sluiten",
  "dash.tabsAria": "Publisheronderdelen",
  "dash.tab.overview": "overzicht",
  "dash.tab.streams": "streams",
  "dash.tab.create": "aanmaken",
  "dash.tab.schedule": "planning",
  "dash.tab.settings": "instellingen",
  "dash.overviewTitle": "Overzicht",
  "dash.overviewBody":
    "Gebruik \"Live gaan\" om een stream te starten. Live Now toont alleen public_discovery-streams met een goedgekeurde badge.",
  "dash.overviewBilling": "Inkomsten / abonnementen / advertenties: nog niet geconfigureerd (geen betalingsprovider).",
  "dash.scheduleTitle": "Streamplanning",
  "dash.scheduleEmpty": "Geen geplande streams.",
  "dash.planTitle": "Een stream plannen",
  "dash.planName": "Titel",
  "dash.planStart": "Start",
  "dash.planSubmit": "Toevoegen aan agenda",
  "dash.settingsTitle": "Accountverificatie",
  "dash.accountKind": "Accounttype: {kind}",
  "dash.profileStatus": "Profielstatus: {status}",
  "dash.applicationHistory": "Aanvraaggeschiedenis",
  "review.eyebrow": "Care & Safety",
  "review.title": "Publisher- en Creator-beoordeling",
  "review.lede":
    "Een drempel bereiken is geen automatische goedkeuring. Snapshot en huidige aantallen worden samen beoordeeld.",
  "review.status": "Status",
  "review.eligibility": "Geschiktheidsfilter",
  "review.reason": "Reden van beslissing",
  "review.refresh": "Vernieuwen",
  "review.filter.all": "alle",
  "review.filter.follower": "Volgerscriterium",
  "review.filter.community": "Communitycriterium",
  "review.filter.both": "Beide criteria",
  "review.filter.below": "Nu onder de drempel",
  "review.filter.fraud": "Fraudebeoordeling",
  "review.paths": "Geschiktheidsroutes",
  "review.followers": "Volgers (aanvraag → nu)",
  "review.members": "Communityleden (aanvraag → nu)",
  "review.community": "Gekwalificeerde community",
  "review.owner": " (eigenaar)",
  "review.notOwner": " (nu geen eigenaar)",
  "review.risk": "Risico",
  "review.riskDrop": "Risicowaarschuwing: ongebruikelijke daling in aantallen na aanvraag.",
  "review.approve": "Goedkeuren",
  "review.underReview": "In beoordeling",
  "review.reject": "Afwijzen",
  "review.suspend": "Opschorten",
  "review.liveBan": "Liveverbod",
  "review.empty": "Wachtrij leeg.",
  "review.defaultReason": "Beoordeeld door het Root Panel",
  "review.banReason": "Liveverbod vanuit het beoordelingspaneel",
};

const pl: Catalog = {
  "apply.aria": "Wniosek Creator Publisher",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Gotowe do złożenia wniosku",
  "apply.belowThreshold": "Poniżej progu",
  "apply.title": "Wniosek Creator / Publisher",
  "apply.lede":
    "Publiczne transmisje w Live Now wymagają zatwierdzenia jako Creator lub Publisher. Kwalifikowalność jest obliczana po stronie serwera; liczniki widoczne tutaj mają charakter informacyjny i nie są źródłem autoryzacji.",
  "apply.refresh": "Odśwież",
  "apply.refreshAria": "Odśwież kwalifikowalność",
  "apply.dashboard": "Dashboard",
  "apply.close": "Zamknij",
  "apply.loading": "Sprawdzanie kwalifikowalności…",
  "apply.snapshotTitle": "Podsumowanie kwalifikowalności do transmisji",
  "apply.lastCheck": "Ostatnie sprawdzenie · {time}",
  "apply.followers": "Aktywni obserwujący",
  "apply.largestCommunity": "Największa posiadana społeczność",
  "apply.countedCommunity": "Liczona społeczność",
  "apply.noCommunity": "Brak jeszcze liczonej społeczności",
  "apply.accountGate": "Blokada konta / transmisji",
  "apply.liveBan": "Aktywny zakaz transmisji — wniosek lub transmisja zablokowane",
  "apply.accountInactive": "Konto nie jest aktywne",
  "apply.accountOk": "Konto wygląda na kwalifikujące się",
  "apply.pathsTitle": "Ścieżki wniosku",
  "apply.pathsBody":
    "Wystarczy jedna ścieżka. Liczba członków nie jest sumowana między społecznościami; liczy się tylko największa aktywna społeczność, której jesteś właścicielem.",
  "apply.followerPath": "Ścieżka obserwujących",
  "apply.followerDetail": "Próg aktywnych obserwujących Picom · liczone przez serwer",
  "apply.or": "LUB",
  "apply.communityPath": "Ścieżka założyciela społeczności",
  "apply.communityDetailNamed": "{name} · aktywni członkowie (właściciel)",
  "apply.communityDetailDefault": "Największa posiadana społeczność · aktywni członkowie (właściciel)",
  "apply.applicationsTitle": "Twoje wnioski",
  "apply.formTitle": "Formularz wniosku",
  "apply.formLede":
    "Po zatwierdzeniu Twoja tożsamość Live Now zostanie powiązana z tymi informacjami. Zespół weryfikujący widzi przesłany tekst.",
  "apply.typeLabel": "Rodzaj wniosku",
  "apply.typeCreator": "Creator (indywidualny)",
  "apply.typePublisher": "Publisher (organizacja)",
  "apply.displayName": "Nazwa wyświetlana jako publisher",
  "apply.displayPlaceholder": "Widoczna nazwa transmisji",
  "apply.bio": "Krótki opis",
  "apply.bioPlaceholder": "Krótko opowiedz widzom, kim jesteś i co transmitujesz",
  "apply.company": "Nazwa firmy / organizacji",
  "apply.submit": "Wyślij wniosek",
  "apply.submitting": "Wysyłanie…",
  "apply.nextTitle": "Jak postępować dalej",
  "apply.growFollowersTitle": "Rozwijaj ścieżkę obserwujących",
  "apply.growFollowersBody":
    "Do osiągnięcia progu potrzeba jeszcze {count} aktywnych obserwujących. Nieaktywne lub usunięte konta się nie liczą; serwer stosuje zasady aktywnego profilu.",
  "apply.growCommunityTitle": "Rozwijaj ścieżkę społeczności",
  "apply.growCommunityBodyNamed":
    "„{name}” potrzebuje jeszcze {count} aktywnych członków. Nawet jako założyciel wymagane jest członkostwo i aktywny profil; społeczności nie są łączone.",
  "apply.growCommunityBodyDefault":
    "Twoja największa posiadana społeczność potrzebuje jeszcze {count} aktywnych członków. Nawet jako założyciel wymagane jest członkostwo i aktywny profil; społeczności nie są łączone.",
  "apply.asideLabel": "Podsumowanie programu",
  "apply.afterKicker": "Po zatwierdzeniu",
  "apply.afterTitle": "Co zostaje odblokowane?",
  "apply.afterBadge": "Odznaka Creator / Publisher i profil publishera",
  "apply.afterDiscovery": "Publiczna widoczność w sekcji odkrywania Picom Live Now",
  "apply.afterGate": "Dostęp do „Rozpocznij transmisję” (aktywna odznaka + zatwierdzony wniosek)",
  "apply.afterSafety": "Dalsze transmisje podlegają weryfikacji i zasadom bezpieczeństwa",
  "apply.processKicker": "Proces",
  "apply.processTitle": "Przebieg wniosku",
  "apply.processStep1": "Osiągnij jeden z progów",
  "apply.processStep2": "Wyślij formularz wniosku",
  "apply.processStep3": "Weryfikacja: ryzyko kwalifikowalności i kontrola zgodności z zasadami treści",
  "apply.processStep4": "Zatwierdzenie → odznaka; odrzucenie / prośba o dodatkowe informacje pojawia się tutaj",
  "apply.rulesKicker": "Zasady liczenia",
  "apply.rulesTitle": "Co się liczy?",
  "apply.rulesFollowers": "Obserwujący: {count} aktywnych obserwujących",
  "apply.rulesCommunity": "Społeczność: {count} aktywnych członków w społeczności, której jesteś właścicielem",
  "apply.rulesOwner": "Źródło właściciela: communities.owner_id",
  "apply.rulesNoMerge": "Brak łączenia członków · paski postępu nie są autoryzacją",
  "apply.elig.notEligible":
    "Nie spełniasz jeszcze wymagań wniosku. Ukończ jedną z poniższych ścieżek, aby odblokować formularz.",
  "apply.elig.both": "Spełniasz oba kryteria wniosku. Możesz wysłać swój wniosek.",
  "apply.elig.followers": "Spełniłeś/aś kryterium obserwujących. Możesz złożyć wniosek jako Creator / Publisher.",
  "apply.elig.community": "Spełniłeś/aś kryterium założyciela społeczności. Możesz złożyć wniosek jako Creator / Publisher.",
  "apply.elig.ok": "Wymagania wniosku spełnione.",
  "apply.closer.tie": "Obie ścieżki są w podobnej odległości; rozwijaj tę, która lepiej Ci odpowiada.",
  "apply.closer.followers": "Ścieżka obserwujących jest obecnie liczbowo bliższa.",
  "apply.closer.community": "Ścieżka Twojej największej posiadanej społeczności jest obecnie bliższa.",
  "apply.track.met": "Spełniono",
  "apply.track.open": "Ścieżka otwarta",
  "apply.track.remaining": "Pozostało {count}",
  "apply.track.progressAria": "Postęp {label}",
  "dash.aria": "Panel Publisher",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Tylko zatwierdzone konta Creator/Publisher mają dostęp do tego obszaru.",
  "dash.noBroadcast": "Twoje konto nie ma jeszcze uprawnień do transmisji.",
  "dash.viewApplication": "Zobacz status wniosku",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Panel publishera",
  "dash.badgeActive": "Aktywna odznaka: {type}",
  "dash.badgeLoading": "Wczytywanie statusu odznaki…",
  "dash.goLive": "Rozpocznij transmisję",
  "dash.close": "Zamknij",
  "dash.tabsAria": "Sekcje publishera",
  "dash.tab.overview": "przegląd",
  "dash.tab.streams": "transmisje",
  "dash.tab.create": "utwórz",
  "dash.tab.schedule": "harmonogram",
  "dash.tab.settings": "ustawienia",
  "dash.overviewTitle": "Przegląd",
  "dash.overviewBody":
    "Użyj „Rozpocznij transmisję”, aby rozpocząć stream. Live Now wyświetla tylko transmisje public_discovery z zatwierdzoną odznaką.",
  "dash.overviewBilling": "Przychody / subskrypcje / reklamy: jeszcze nie skonfigurowano (brak dostawcy płatności).",
  "dash.scheduleTitle": "Harmonogram transmisji",
  "dash.scheduleEmpty": "Brak zaplanowanych transmisji.",
  "dash.planTitle": "Zaplanuj transmisję",
  "dash.planName": "Tytuł",
  "dash.planStart": "Start",
  "dash.planSubmit": "Dodaj do kalendarza",
  "dash.settingsTitle": "Weryfikacja konta",
  "dash.accountKind": "Rodzaj konta: {kind}",
  "dash.profileStatus": "Status profilu: {status}",
  "dash.applicationHistory": "Historia wniosków",
  "review.eyebrow": "Care & Safety",
  "review.title": "Weryfikacja Publisher i Creator",
  "review.lede":
    "Osiągnięcie progu nie oznacza automatycznego zatwierdzenia. Migawka i aktualne liczby są sprawdzane razem.",
  "review.status": "Status",
  "review.eligibility": "Filtr kwalifikowalności",
  "review.reason": "Powód decyzji",
  "review.refresh": "Odśwież",
  "review.filter.all": "wszystkie",
  "review.filter.follower": "Kryterium obserwujących",
  "review.filter.community": "Kryterium społeczności",
  "review.filter.both": "Oba kryteria",
  "review.filter.below": "Obecnie poniżej progu",
  "review.filter.fraud": "Weryfikacja pod kątem nadużyć",
  "review.paths": "Ścieżki kwalifikowalności",
  "review.followers": "Obserwujący (wniosek → teraz)",
  "review.members": "Członkowie społeczności (wniosek → teraz)",
  "review.community": "Kwalifikująca się społeczność",
  "review.owner": " (właściciel)",
  "review.notOwner": " (obecnie nie jest właścicielem)",
  "review.risk": "Ryzyko",
  "review.riskDrop": "Ostrzeżenie o ryzyku: nietypowy spadek liczby po złożeniu wniosku.",
  "review.approve": "Zatwierdź",
  "review.underReview": "W trakcie weryfikacji",
  "review.reject": "Odrzuć",
  "review.suspend": "Zawieś",
  "review.liveBan": "Zakaz transmisji",
  "review.empty": "Kolejka pusta.",
  "review.defaultReason": "Zweryfikowano przez Root Panel",
  "review.banReason": "Zakaz transmisji z panelu weryfikacji",
};

const ru: Catalog = {
  "apply.aria": "Заявка Creator Publisher",
  "apply.eyebrow": "Publisher Program",
  "apply.ready": "Готово к подаче заявки",
  "apply.belowThreshold": "Ниже порога",
  "apply.title": "Заявка Creator / Publisher",
  "apply.lede":
    "Для публичных трансляций в Live Now требуется одобрение статуса Creator или Publisher. Соответствие критериям рассчитывается на сервере; счётчики здесь носят информационный характер и не являются источником авторизации.",
  "apply.refresh": "Обновить",
  "apply.refreshAria": "Обновить статус соответствия",
  "apply.dashboard": "Dashboard",
  "apply.close": "Закрыть",
  "apply.loading": "Проверка соответствия критериям…",
  "apply.snapshotTitle": "Сводка по соответствию для трансляций",
  "apply.lastCheck": "Последняя проверка · {time}",
  "apply.followers": "Активные подписчики",
  "apply.largestCommunity": "Крупнейшее собственное сообщество",
  "apply.countedCommunity": "Учитываемое сообщество",
  "apply.noCommunity": "Пока нет учитываемого сообщества",
  "apply.accountGate": "Ограничение аккаунта / трансляций",
  "apply.liveBan": "Активный запрет на трансляции — заявка или трансляция заблокированы",
  "apply.accountInactive": "Аккаунт неактивен",
  "apply.accountOk": "Аккаунт выглядит соответствующим критериям",
  "apply.pathsTitle": "Пути подачи заявки",
  "apply.pathsBody":
    "Достаточно одного пути. Количество участников не суммируется между сообществами; учитывается только самое крупное активное сообщество, которым вы владеете.",
  "apply.followerPath": "Путь через подписчиков",
  "apply.followerDetail": "Порог активных подписчиков Picom · подсчёт сервером",
  "apply.or": "ИЛИ",
  "apply.communityPath": "Путь основателя сообщества",
  "apply.communityDetailNamed": "{name} · активные участники (владелец)",
  "apply.communityDetailDefault": "Крупнейшее собственное сообщество · активные участники (владелец)",
  "apply.applicationsTitle": "Ваши заявки",
  "apply.formTitle": "Форма заявки",
  "apply.formLede":
    "После одобрения ваша личность в Live Now будет связана с этой информацией. Модераторы видят отправленный вами текст.",
  "apply.typeLabel": "Тип заявки",
  "apply.typeCreator": "Creator (физическое лицо)",
  "apply.typePublisher": "Publisher (организация)",
  "apply.displayName": "Отображаемое имя publisher",
  "apply.displayPlaceholder": "Видимое имя трансляции",
  "apply.bio": "Краткое описание",
  "apply.bioPlaceholder": "Кратко расскажите зрителям, кто вы и что транслируете",
  "apply.company": "Название компании / организации",
  "apply.submit": "Отправить заявку",
  "apply.submitting": "Отправка…",
  "apply.nextTitle": "Как продвигаться дальше",
  "apply.growFollowersTitle": "Развивать путь через подписчиков",
  "apply.growFollowersBody":
    "До порога не хватает {count} активных подписчиков. Неактивные или удалённые аккаунты не учитываются; сервер применяет правила активного профиля.",
  "apply.growCommunityTitle": "Развивать путь через сообщество",
  "apply.growCommunityBodyNamed":
    "«{name}» нужно ещё {count} активных участников. Даже будучи основателем, необходимы членство и активный профиль; сообщества не объединяются.",
  "apply.growCommunityBodyDefault":
    "Вашему крупнейшему собственному сообществу нужно ещё {count} активных участников. Даже будучи основателем, необходимы членство и активный профиль; сообщества не объединяются.",
  "apply.asideLabel": "Сводка программы",
  "apply.afterKicker": "После одобрения",
  "apply.afterTitle": "Что открывается?",
  "apply.afterBadge": "Значок Creator / Publisher и профиль publisher",
  "apply.afterDiscovery": "Публичная видимость в разделе рекомендаций Picom Live Now",
  "apply.afterGate": "Доступ к запуску трансляции (активный значок + одобренная заявка)",
  "apply.afterSafety": "Продолжение трансляций при условии проверки и соблюдения правил безопасности",
  "apply.processKicker": "Процесс",
  "apply.processTitle": "Порядок рассмотрения заявки",
  "apply.processStep1": "Достигните одного из порогов",
  "apply.processStep2": "Отправьте форму заявки",
  "apply.processStep3": "Проверка: риск соответствия критериям и проверка на соблюдение правил контента",
  "apply.processStep4": "Одобрение → значок; отказ / запрос доп. информации отображается здесь",
  "apply.rulesKicker": "Правила подсчёта",
  "apply.rulesTitle": "Что учитывается?",
  "apply.rulesFollowers": "Подписчики: {count} активных подписчиков",
  "apply.rulesCommunity": "Сообщество: {count} активных участников в сообществе, которым вы владеете",
  "apply.rulesOwner": "Источник владельца: communities.owner_id",
  "apply.rulesNoMerge": "Без объединения участников · индикаторы прогресса не являются авторизацией",
  "apply.elig.notEligible":
    "Вы пока не соответствуете требованиям для подачи заявки. Пройдите один из путей ниже, чтобы разблокировать форму.",
  "apply.elig.both": "Вы соответствуете обоим критериям заявки. Вы можете отправить заявку.",
  "apply.elig.followers": "Вы соответствуете критерию по подписчикам. Вы можете подать заявку как Creator / Publisher.",
  "apply.elig.community": "Вы соответствуете критерию основателя сообщества. Вы можете подать заявку как Creator / Publisher.",
  "apply.elig.ok": "Требования для подачи заявки выполнены.",
  "apply.closer.tie": "Оба пути находятся на схожем расстоянии; развивайте тот, что вам ближе.",
  "apply.closer.followers": "Сейчас путь через подписчиков численно ближе.",
  "apply.closer.community": "Сейчас путь через ваше крупнейшее сообщество ближе.",
  "apply.track.met": "Достигнуто",
  "apply.track.open": "Путь открыт",
  "apply.track.remaining": "Осталось {count}",
  "apply.track.progressAria": "Прогресс {label}",
  "dash.aria": "Панель Publisher",
  "dash.title": "Publisher Dashboard",
  "dash.gatedBody": "Доступ к этому разделу есть только у одобренных аккаунтов Creator/Publisher.",
  "dash.noBroadcast": "У вашего аккаунта пока нет разрешения на трансляцию.",
  "dash.viewApplication": "Посмотреть статус заявки",
  "dash.eyebrow": "Publisher Dashboard",
  "dash.fallbackName": "Панель publisher",
  "dash.badgeActive": "Активный значок: {type}",
  "dash.badgeLoading": "Загрузка статуса значка…",
  "dash.goLive": "Начать трансляцию",
  "dash.close": "Закрыть",
  "dash.tabsAria": "Разделы publisher",
  "dash.tab.overview": "обзор",
  "dash.tab.streams": "трансляции",
  "dash.tab.create": "создать",
  "dash.tab.schedule": "расписание",
  "dash.tab.settings": "настройки",
  "dash.overviewTitle": "Обзор",
  "dash.overviewBody":
    "Используйте кнопку запуска трансляции, чтобы начать стрим. Live Now показывает только трансляции public_discovery с одобренным значком.",
  "dash.overviewBilling": "Доход / подписки / реклама: пока не настроено (нет платёжного провайдера).",
  "dash.scheduleTitle": "Расписание трансляций",
  "dash.scheduleEmpty": "Запланированных трансляций нет.",
  "dash.planTitle": "Запланировать трансляцию",
  "dash.planName": "Название",
  "dash.planStart": "Начало",
  "dash.planSubmit": "Добавить в календарь",
  "dash.settingsTitle": "Верификация аккаунта",
  "dash.accountKind": "Тип аккаунта: {kind}",
  "dash.profileStatus": "Статус профиля: {status}",
  "dash.applicationHistory": "История заявок",
  "review.eyebrow": "Care & Safety",
  "review.title": "Проверка Publisher и Creator",
  "review.lede":
    "Достижение порога не означает автоматическое одобрение. Снимок данных и текущие показатели рассматриваются вместе.",
  "review.status": "Статус",
  "review.eligibility": "Фильтр соответствия",
  "review.reason": "Причина решения",
  "review.refresh": "Обновить",
  "review.filter.all": "все",
  "review.filter.follower": "Критерий подписчиков",
  "review.filter.community": "Критерий сообщества",
  "review.filter.both": "Оба критерия",
  "review.filter.below": "Сейчас ниже порога",
  "review.filter.fraud": "Проверка на мошенничество",
  "review.paths": "Пути соответствия критериям",
  "review.followers": "Подписчики (заявка → сейчас)",
  "review.members": "Участники сообщества (заявка → сейчас)",
  "review.community": "Подходящее сообщество",
  "review.owner": " (владелец)",
  "review.notOwner": " (сейчас не владелец)",
  "review.risk": "Риск",
  "review.riskDrop": "Предупреждение о риске: необычное падение показателей после подачи заявки.",
  "review.approve": "Одобрить",
  "review.underReview": "На рассмотрении",
  "review.reject": "Отклонить",
  "review.suspend": "Приостановить",
  "review.liveBan": "Запрет на трансляции",
  "review.empty": "Очередь пуста.",
  "review.defaultReason": "Проверено Root Panel",
  "review.banReason": "Запрет на трансляции из панели проверки",
};

function pack(base: Catalog): Catalog {
  return { ...base };
}

export const PUBLISHER_PROGRAM_LOCALES: Readonly<Record<UiLanguage, Catalog>> = {
  en: pack(en),
  tr: pack(tr),
  de: pack(de),
  fr: pack(fr),
  es: pack(es),
  it: pack(it),
  pt: pack(pt),
  nl: pack(nl),
  pl: pack(pl),
  ru: pack(ru),
};

export const PUBLISHER_PROGRAM_I18N_KEYS = Object.keys(en) as PublisherProgramI18nKey[];

export function translatePublisherProgram(
  key: PublisherProgramI18nKey,
  language: UiLanguage | string = "en",
  params: Record<string, string | number> = {},
): string {
  const locale = normalizeUiLanguage(language);
  const template = PUBLISHER_PROGRAM_LOCALES[locale][key];
  if (typeof template !== "string" || !template.trim()) {
    throw new Error(`Missing publisher program i18n key ${key} for locale ${locale}`);
  }
  return template.replace(/\{(\w+)\}/g, (_match, name: string) => String(params[name] ?? ""));
}

export function formatPublisherCount(value: number, language: UiLanguage | string = "en"): string {
  return value.toLocaleString(getUiLanguageBcp47(normalizeUiLanguage(language)));
}

export function assertPublisherProgramLocaleParity(): { ok: true } | { ok: false; detail: string } {
  const enKeys = Object.keys(PUBLISHER_PROGRAM_LOCALES.en).sort();
  for (const locale of SUPPORTED_UI_LANGUAGES) {
    const keys = Object.keys(PUBLISHER_PROGRAM_LOCALES[locale]).sort();
    if (keys.length !== enKeys.length || keys.some((k, i) => k !== enKeys[i])) {
      return { ok: false, detail: `${locale} key set mismatch` };
    }
    for (const key of enKeys) {
      const value = PUBLISHER_PROGRAM_LOCALES[locale][key as PublisherProgramI18nKey];
      if (typeof value !== "string" || !value.trim()) {
        return { ok: false, detail: `${locale}.${key} empty` };
      }
    }
  }
  return { ok: true };
}
