export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  emailVerificationPending: "/email-verification-pending",
  /** Opaque soft-verify redeem (email CTA). */
  verifyEmail: "/verify-email",
  verifyEmailCode: "/verify-email/:opaqueCode",
  verifyEmailSuccess: "/verify-email/success",
  verifyEmailExpired: "/verify-email/expired",
  verifyEmailFailed: "/verify-email/failed",
  /** Legacy Supabase Auth confirm bridge (not used in user-facing email CTAs). */
  verifyEmailLegacyConfirm: "/auth/confirm",
  forgotPassword: "/forgot-password",
  /** Opaque reset redeem (email CTA). */
  resetPassword: "/reset-password",
  resetPasswordCode: "/reset-password/:opaqueCode",
  resetPasswordSuccess: "/reset-password/success",
  resetPasswordExpired: "/reset-password/expired",
  /** Legacy Auth recovery bridge. */
  resetPasswordLegacy: "/auth/reset-password",
  confirmEmailChange: "/email-change",
  confirmEmailChangeCode: "/email-change/:opaqueCode",
  confirmEmailChangeLegacy: "/auth/change-email",
  openAppCode: "/open-app/:opaqueCode",
  authCallback: "/auth/callback",
  authError: "/auth/error",
  mfaChallenge: "/mfa",
  support: "/support",
  legalPrivacy: "/legal/privacy",
  legalTerms: "/legal/terms",
  legalCookies: "/legal/cookies",
  accountOverview: "/account/overview",
  profile: "/account/profile",
  profileSetup: "/account/profile/setup",
  profileVerification: "/account/profile/verification",
  emailVerification: "/account/email-verification",
  security: "/security",
  /** Spec / desktop alias for security hub */
  accountSecurity: "/account/security",
  /** Public path used in email CTAs; protected shell. */
  connections: "/connections",
  /** Legacy nested path. */
  connectionsLegacy: "/account/connections",
  passwordChange: "/security/password",
  /** Spec alias */
  accountPassword: "/account/password",
  emailChange: "/security/email",
  /** Spec alias */
  accountEmail: "/account/email",
  mfa: "/security/mfa",
  sessions: "/account/sessions",
  preferences: "/account/preferences",
  notifications: "/account/notifications",
  privacy: "/account/privacy",
  dataExport: "/account/data-export",
  /** Spec alias for data export */
  data: "/account/data",
  deactivate: "/account/deactivate",
  deleteAccount: "/account/delete",
  verified: "/verified",
  verifiedCheckout: "/verified/checkout",
  verifiedStatus: "/verified/status",
  accountBilling: "/account/billing",
  accountVerification: "/account/verification",
  business: "/business",
  businessApply: "/business/apply",
  businessApplication: "/business/applications/:id",
  businessApplicationStatus: "/business/applications/:id/status",
  businessDashboard: "/business/dashboard",
  businessDashboardProfile: "/business/dashboard/profile",
  businessDashboardVerification: "/business/dashboard/verification",
  businessDashboardTeam: "/business/dashboard/team",
  businessDashboardDocuments: "/business/dashboard/documents",
  businessDashboardSettings: "/business/dashboard/settings",
  businessDashboardProducts: "/business/dashboard/products",
  businessDashboardCollections: "/business/dashboard/collections",
  businessDashboardPosts: "/business/dashboard/posts",
  publicBusinessProfileAt: "/business/@:slug",
  publicBusinessProfile: "/business/:slug",
  publicBusinessProductAt: "/business/@:slug/products/:productSlug",
  advertise: "/advertise",
  advertiseCreateAccount: "/advertise/create-account",
  advertiserDashboard: "/advertiser/dashboard",
  advertiserSettings: "/advertiser/dashboard/settings",
  advertiserTeam: "/advertiser/dashboard/team",
  advertiserBilling: "/advertiser/dashboard/billing",
  advertiserVerification: "/advertiser/dashboard/verification",
  advertiserCampaigns: "/advertiser/dashboard/campaigns",
  advertiserCampaignNew: "/advertiser/dashboard/campaigns/new",
  advertiserCreatives: "/advertiser/dashboard/creatives",
  advertiserReports: "/advertiser/dashboard/reports",
  creatorMonetization: "/creator/monetization",
  creatorMonetizationOnboarding: "/creator/monetization/onboarding",
  creatorMonetizationEarnings: "/creator/monetization/earnings",
  creatorMonetizationPayouts: "/creator/monetization/payouts",
  creatorMonetizationTax: "/creator/monetization/tax",
  creatorMonetizationAgreements: "/creator/monetization/agreements",
  publisherMonetization: "/publisher/monetization",
  publisherMonetizationOnboarding: "/publisher/monetization/onboarding",
  publisherMonetizationEarnings: "/publisher/monetization/earnings",
  publisherMonetizationPayouts: "/publisher/monetization/payouts",
  publisherMonetizationTax: "/publisher/monetization/tax",
  publisherMonetizationAgreements: "/publisher/monetization/agreements",
  adsTransparency: "/ads/transparency",
  adsTransparencyDetail: "/ads/transparency/:archiveId",
  adsAdvertiserPublic: "/ads/advertisers/:advertiserId",
} as const;

export type AccountRoutePath = (typeof ROUTES)[keyof typeof ROUTES];

/** Paths allowed for post-auth returnTo redirects (open-redirect protection). */
export const RETURN_TO_ALLOWLIST: readonly string[] = [
  ROUTES.home,
  ROUTES.login,
  ROUTES.register,
  ROUTES.emailVerificationPending,
  ROUTES.verifyEmail,
  ROUTES.verifyEmailSuccess,
  ROUTES.verifyEmailExpired,
  ROUTES.verifyEmailFailed,
  ROUTES.verifyEmailLegacyConfirm,
  ROUTES.forgotPassword,
  ROUTES.resetPassword,
  ROUTES.resetPasswordSuccess,
  ROUTES.resetPasswordExpired,
  ROUTES.resetPasswordLegacy,
  ROUTES.confirmEmailChange,
  ROUTES.confirmEmailChangeLegacy,
  ROUTES.authCallback,
  ROUTES.authError,
  ROUTES.mfaChallenge,
  ROUTES.support,
  ROUTES.legalPrivacy,
  ROUTES.legalTerms,
  ROUTES.legalCookies,
  ROUTES.accountOverview,
  ROUTES.profile,
  ROUTES.profileSetup,
  ROUTES.profileVerification,
  ROUTES.emailVerification,
  ROUTES.security,
  ROUTES.accountSecurity,
  ROUTES.connections,
  ROUTES.connectionsLegacy,
  ROUTES.passwordChange,
  ROUTES.accountPassword,
  ROUTES.emailChange,
  ROUTES.accountEmail,
  ROUTES.mfa,
  ROUTES.sessions,
  ROUTES.preferences,
  ROUTES.notifications,
  ROUTES.privacy,
  ROUTES.dataExport,
  ROUTES.data,
  ROUTES.deactivate,
  ROUTES.deleteAccount,
  ROUTES.verified,
  ROUTES.verifiedCheckout,
  ROUTES.verifiedStatus,
  ROUTES.accountBilling,
  ROUTES.accountVerification,
  ROUTES.business,
  ROUTES.businessApply,
  "/business/applications",
  ROUTES.businessDashboard,
  ROUTES.advertise,
  ROUTES.advertiseCreateAccount,
  ROUTES.advertiserDashboard,
  ROUTES.creatorMonetization,
  ROUTES.publisherMonetization,
  ROUTES.adsTransparency,
];
